#!/usr/bin/env python3
"""Regenerate the Mermaid module dependency graph in README.md."""

from pathlib import Path
import re
import yaml

REPO = Path(__file__).parent
README = REPO / "README.md"
START = "<!-- hierarchy-start -->"
END = "<!-- hierarchy-end -->"


def collect() -> dict[str, list[str]]:
    graph: dict[str, list[str]] = {}
    for core in sorted(REPO.glob("**/*.core")):
        if "build" in core.parts:
            continue
        data = yaml.safe_load(core.read_text())
        module = data["name"].split(":")[2]
        deps: list[str] = []
        rtl_fs = data.get("filesets", {}).get("rtl", {})
        for dep in rtl_fs.get("depend", []):
            d = dep.split(":")[2]
            if d not in deps:
                deps.append(d)
        graph[module] = deps
    return graph


def mermaid(graph: dict[str, list[str]]) -> str:
    lines = [
        "```mermaid",
        "graph TD",
        "    %% auto-generated by hierarchy.py — do not edit",
    ]
    dependents = {d for deps in graph.values() for d in deps}
    for module, deps in sorted(graph.items()):
        if deps:
            for dep in sorted(deps):
                lines.append(f"    {module} --> {dep}")
        elif module not in dependents:
            lines.append(f"    {module}")
    lines.append("```")
    return "\n".join(lines)


def patch_readme(block: str) -> None:
    section = f"## Module dependency graph\n\n{block}\n"
    wrapped = f"{START}\n{section}{END}"
    text = README.read_text()
    if START in text:
        text = re.sub(
            rf"{re.escape(START)}.*?{re.escape(END)}",
            wrapped,
            text,
            flags=re.DOTALL,
        )
    else:
        text = text.rstrip("\n") + f"\n\n{wrapped}\n"
    README.write_text(text)


if __name__ == "__main__":
    patch_readme(mermaid(collect()))
    print("README.md updated.")
