/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=53 (degree 6); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m53 #(parameter integer WMAN = 53, parameter integer D = 6, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 in_valid,
    input  wire       [WSB-1:0] sb_in,
    input  wire      [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                 out_valid,
    output wire       [WSB-1:0] sb_out,
    output wire [2*WMAN+12-2:0] l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    // verilator coverage_off
    generate if (D != 6) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 7;
    localparam integer RW   = 45;
    localparam integer CW   = 68;
    localparam integer ACCW = 70;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WFRAC;  // carry t alongside the sideband to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {68'h0000000000019c23d, 68'hffffffffff09d54f4, 68'h0000000093bb59441, 68'hffffffa3aae26e8ee, 68'h00003d8e13b8737df, 68'hffd1d57135a8fa0c7, 68'h2e2a8eca5705fc2ee};
        rom[  1] = {68'h0000000000018906b, 68'hffffffffff137da35, 68'h000000008f0497fd3, 68'hffffffa5f0525b5e7, 68'h00003c7c813e50e89, 68'hffd24f7aa7e96527c, 68'h2dfca16dde10a2ff0};
        rom[  2] = {68'h00000000000176ef2, 68'hffffffffff1cb350c, 68'h000000008a7d029b9, 68'hffffffa8234658179, 68'h00003b71a32ae1bb2, 68'hffd2c767b2da23613, 68'h2dcf2d0b85a45314d};
        rom[  3] = {68'h00000000000165cd4, 68'hffffffffff257c782, 68'h0000000086226b21e, 68'hffffffaa4476ae3b4, 68'h00003a6d4320f1e1a, 68'hffd33d45888f43ba8, 68'h2da22f8d888add23f};
        rom[  4] = {68'h00000000000155925, 68'hffffffffff2ddedb0, 68'h0000000081f2c1492, 68'hffffffac54932b5dd, 68'h0000396f2cdf5232f, 68'hffd3b120f082afde9, 68'h2d75a6eb1dfb0e626};
        rom[  5] = {68'h00000000000146309, 68'hffffffffff35dfe2b, 68'h000000007dec10b64, 68'hffffffae544394611, 68'h000038772e28134bd, 68'hffd423064bb33736a, 68'h2d49912811123187e};
        rom[  6] = {68'h000000000001379b3, 68'hffffffffff3d84a5f, 68'h000000007a0c7f4f6, 68'hffffffb0442811c4b, 68'h0000378516a90f9b5, 68'hffd493019893625ae, 68'h2d1dec545c544734c};
        rom[  7] = {68'h00000000000129c63, 68'hffffffffff44d1eea, 68'h0000000076524bacb, 68'hffffffb224d99583b, 68'h00003698b7e5b0970, 68'hffd5011e76ca98fd8, 68'h2cf2b68bc90406800};
        rom[  8] = {68'h0000000000011ca66, 68'hffffffffff4bcc3e9, 68'h0000000072bbcba45, 68'hffffffb3f6ea3aec4, 68'h000035b1e521dc655, 68'hffd56d682acafdb74, 68'h2cc7edf592262cf99};
        rom[  9] = {68'h00000000000110313, 68'hffffffffff5277d46, 68'h000000006f476aee2, 68'hffffffb5bae5a0d74, 68'h000034d0734dfa861, 68'hffd5d7e9a13e3ef66, 68'h2c9d90c40b05f68b6};
        rom[ 10] = {68'h000000000001045cf, 68'hffffffffff58d8aff, 68'h000000006bf3a9deb, 68'hffffffb771513e9e3, 68'h000033f438f3ff28b, 68'hffd640ad724b7a8d9, 68'h2c739d344912c3d2b};
        rom[ 11] = {68'h000000000000f9205, 68'hffffffffff5ef2961, 68'h0000000068bf1c36f, 68'hffffffb91aacb4264, 68'h0000331d0e256deed, 68'hffd6a7bde4b831d10, 68'h2c4a118dd0f103128};
        rom[ 12] = {68'h000000000000ee72e, 68'hffffffffff64c914c, 68'h0000000065a868077, 68'hffffffbab77215526, 68'h0000324acc6a45d74, 68'hffd70d24f0e62ead1, 68'h2c20ec22469a5ee5b};
        rom[ 13] = {68'h000000000000e44c7, 68'hffffffffff6a5f866, 68'h0000000062ae44a5f, 68'hffffffbc481631273, 68'h0000317d4eb0c8f79, 68'hffd770ec43b01e895, 68'h2bf82b4d206b084b6};
        rom[ 14] = {68'h000000000000daa58, 68'hffffffffff6fb9150, 68'h000000005fcf79b3d, 68'hffffffbdcd08d4e6e, 68'h000030b4713e13845, 68'hffd7d31d41268df04, 68'h2bcfcd735cfba96c2};
        rom[ 15] = {68'h000000000000d1770, 68'hffffffffff74d8bd7, 68'h000000005d0ade33d, 68'hffffffbf46b50b669, 68'h00002ff0119f76741, 68'hffd833c1072ed7c6a, 68'h2ba7d1033ba92d35c};
        rom[ 16] = {68'h000000000000c8ba5, 68'hffffffffff79c1520, 68'h000000005a5f57af3, 68'hffffffc0b58158d98, 68'h00002f300e9c8ac40, 68'hffd892e07005842ed, 68'h2b803473f7ad0f3f3};
        rom[ 17] = {68'h000000000000c0693, 68'hffffffffff7e757d4, 68'h0000000057cbd967c, 68'hffffffc219cff34a8, 68'h00002e744829f3163, 68'hffd8f08414a57df80, 68'h2b58f64585aa58c70};
        rom[ 18] = {68'h000000000000b87dc, 68'hffffffffff82f7c47, 68'h00000000554f6396e, 68'hffffffc373fef7f85, 68'h00002dbc9f5cc203c, 68'hffd94cb44f15718c4, 68'h2b3215005394cc6de};
        rom[ 19] = {68'h000000000000b0f28, 68'hffffffffff874a898, 68'h0000000052e902b84, 68'hffffffc4c4689dc5d, 68'h00002d08f65e7c165, 68'hffd9a7793c9c95a06, 68'h2b0b8f350ad90bcf1};
        rom[ 20] = {68'h000000000000a9c25, 68'hffffffffff8b700da, 68'h000000005097cee01, 68'hffffffc60b6364ebf, 68'h00002c593061ace95, 68'hffda00dabfe00c5de, 68'h2ae5637c54adb97fc};
        rom[ 21] = {68'h000000000000a2e85, 68'hffffffffff8f6a730, 68'h000000004e5aeb1aa, 68'hffffffc749424417b, 68'h00002bad31970778f, 68'hffda58e082e9fb469, 68'h2abf9076a076c062d};
        rom[ 22] = {68'h0000000000009c5ff, 68'hffffffffff933bbe8, 68'h000000004c3184d67, 68'hffffffc87e54d31bb, 68'h00002b04df230a1ef, 68'hffdaaf91f91b689ac, 68'h2a9a14cbec24ffaff};
        rom[ 23] = {68'h0000000000009624f, 68'hffffffffff96e5d9d, 68'h000000004a1ad356d, 68'hffffffc9aae7735b4, 68'h00002a601f141f31c, 68'hffdb04f66109de7d9, 68'h2a74ef2b8e7da27a2};
        rom[ 24] = {68'h00000000000090332, 68'hffffffffff9a6a94c, 68'h000000004816172ec, 68'hffffffcacf4376111, 68'h000029bed85933a4e, 68'hffdb5914c649c66c8, 68'h2a501e4c033562da3};
        rom[ 25] = {68'h0000000000008a86e, 68'hffffffffff9dcba6e, 68'h00000000462299c42, 68'hffffffcbebaf40914, 68'h00002920f2b8bd6fc, 68'hffdbabf4032662bef, 68'h2a2ba0eab8cce4f33};
        rom[ 26] = {68'h000000000000851c7, 68'hffffffffffa10ab10, 68'h00000000443facd9a, 68'hffffffcd006e6ea72, 68'h0000288656c82bdc5, 68'hffdbfd9ac2483fce5, 68'h2a0775cbe01c35a50};
        rom[ 27] = {68'h0000000000007ff09, 68'hffffffffffa4293e3, 68'h00000000426caa200, 68'hffffffce0dc1f3281, 68'h000027eeede3bc379, 68'hffdc4e0f804aeb024, 68'h29e39bba3d7c4c9dc};
        rom[ 28] = {68'h0000000000007afff, 68'hffffffffffa728c57, 68'h0000000040a8f2cd7, 68'hffffffcf13e836d8f, 68'h0000275aa226adb0b, 68'hffdc9d588d42b343c, 68'h29c01186fb7e3a4e5};
        rom[ 29] = {68'h0000000000007647a, 68'hffffffffffaa0aaa9, 68'h000000003ef3ef3b0, 68'hffffffd0131d35bca, 68'h000026c95e63cf7fc, 68'hffdceb7c0e332c409, 68'h299cd6097f2068ae8};
        rom[ 30] = {68'h00000000000071c4d, 68'hffffffffffacd03f4, 68'h000000003d4d0e87e, 68'hffffffd10b9a9ae43, 68'h0000263b0e1e64b4f, 68'hffdd387ffe772464b, 68'h2979e81f3d730a58b};
        rom[ 31] = {68'h0000000000006d74d, 68'hffffffffffaf7ac44, 68'h000000003bb3c6418, 68'hffffffd1fd97dad62, 68'h000025af9d8359558, 68'hffdd846a311ab473f, 68'h295746ab929d7ee27};
        rom[ 32] = {68'h00000000000069551, 68'hffffffffffb20b6a5, 68'h000000003a2792112, 68'hffffffd2e94a4ca0a, 68'h00002526f962c4aa0, 68'hffddcf40522807397, 68'h2934f0979a3715fc9};
        rom[ 33] = {68'h00000000000065632, 68'hffffffffffb48352e, 68'h0000000038a7f36d7, 68'hffffffd3cee541aaf, 68'h000024a10f29b4de1, 68'hffde1907e7e76fc59, 68'h2912e4d208e635511};
        rom[ 34] = {68'h000000000000619ce, 68'hffffffffffb6e3913, 68'h00000000373471513, 68'hffffffd4ae9a1c56d, 68'h0000241dccdc4046d, 68'hffde61c654135d298, 68'h28f1224f073977c31};
        rom[ 35] = {68'h0000000000005e002, 68'hffffffffffb92d2ae, 68'h0000000035cc97f54, 68'hffffffd5889865838, 68'h0000239d210fd8dce, 68'hffdea980d500b3837, 68'h28cfa8080daee8096};
        rom[ 36] = {68'h0000000000005a8ad, 68'hffffffffffbb6118d, 68'h00000000346ff88f1, 68'hffffffd65d0de1021, 68'h0000231efae5dea4e, 68'hffdef03c86bc0b73c, 68'h28ae74fbc1ddfd0d7};
        rom[ 37] = {68'h000000000000573b1, 68'hffffffffffbd8047d, 68'h00000000331e29122, 68'hffffffd72c26a1092, 68'h000022a34a066df0f, 68'hffdf35fe641c52bc9, 68'h288d882dd4b97c5ab};
        rom[ 38] = {68'h000000000000540f1, 68'hffffffffffbf8b992, 68'h0000000031d6c3f56, 68'hffffffd7f60d18b78, 68'h00002229fe9b66900, 68'hffdf7acb47cb42cb5, 68'h286ce0a6e1dedea63};
        rom[ 39] = {68'h00000000000051052, 68'hffffffffffc183e36, 68'h00000000309967fba, 68'hffffffd8baea2db11, 68'h000021b3094ba9297, 68'hffdfbea7ed441c3f3, 68'h284c7d744fe944568};
        rom[ 40] = {68'h0000000000004e1ba, 68'hffffffffffc369f2d, 68'h000000002f65b7fe9, 68'hffffffd97ae548e3b, 68'h0000213e5b3688286, 68'hffe00198f1c911236, 68'h282c5da831be74545};
        rom[ 41] = {68'h0000000000004b511, 68'hffffffffffc53e8a0, 68'h000000002e3b5abd4, 68'hffffffda3624667ed, 68'h000020cbe5ef69be9, 68'hffe043a2d54fc27d5, 68'h280c805928ccc690c};
        rom[ 42] = {68'h00000000000048a3f, 68'hffffffffffc702626, 68'h000000002d19faacc, 68'hffffffdaeccc25293, 68'h0000205b9b7998a93, 68'hffe084c9fb6531046, 68'h27ece4a248313de3c};
        rom[ 43] = {68'h0000000000004612e, 68'hffffffffffc8b62ca, 68'h000000002c0145cb7, 68'hffffffdb9effd47ec, 68'h00001fed6e4441801, 68'hffe0c512ac097c48d, 68'h27cd89a2f8bd726da};
        rom[ 44] = {68'h000000000000439ca, 68'hffffffffffca5a912, 68'h000000002af0ed768, 68'hffffffdc4ce182e03, 68'h00001f8151269a776, 68'hffe104811483c7431, 68'h27ae6e7eddd546c02};
        rom[ 45] = {68'h000000000000413fe, 68'hffffffffffcbf030a, 68'h0000000029e8a6424, 68'hffffffdcf6920a9e5, 68'h00001f17375c33968, 68'hffe14319482e952dc, 68'h278f925dbb1cb6fef};
        rom[ 46] = {68'h0000000000003efb8, 68'hffffffffffcd77a45, 68'h0000000028e827d35, 68'hffffffdd9c311e87b, 68'h00001eaf14816d836, 68'hffe180df413cedb0d, 68'h2770f46b5aee62143};
        rom[ 47] = {68'h0000000000003cce7, 68'hffffffffffcef17e6, 68'h0000000027ef2cbb6, 68'hffffffde3ddd55e38, 68'h00001e48dc9015181, 68'hffe1bdd6e17893b6c, 68'h275293d77593ba433};
        rom[ 48] = {68'h0000000000003ab78, 68'hffffffffffd05e4a6, 68'h0000000026fd72562, 68'hffffffdedbb437de6, 68'h00001de483dc2211d, 68'hffe1fa03f2f996cd5, 68'h27346fd5993813fda};
        rom[ 49] = {68'h00000000000038b5d, 68'hffffffffffd1be8d8, 68'h000000002612b8a97, 68'hffffffdf75d24672c, 68'h00001d81ff10973ec, 68'hffe2356a28d783a5e, 68'h2716879d129010134};
        rom[ 50] = {68'h00000000000036c86, 68'hffffffffffd312c6f, 68'h00000000252ec2460, 68'hffffffe00c5308d1d, 68'h00001d21432c82a38, 68'hffe2700d1fd475281, 68'h26f8da68d62f21577};
        rom[ 51] = {68'h00000000000034ee5, 68'hffffffffffd45b703, 68'h000000002451542a5, 68'hffffffe09f511554d, 68'h00001cc245801c26a, 68'hffe2a9f05f024491b, 68'h26db67776a852dca3};
        rom[ 52] = {68'h0000000000003326b, 68'hffffffffffd598fd5, 68'h00000000237a35a6c, 68'hffffffe12ee61afbc, 68'h00001c64fbaa0162a, 68'hffe2e3175862144d7, 68'h26be2e0ad27e88602};
        rom[ 53] = {68'h0000000000003170c, 68'hffffffffffd6cbdd3, 68'h0000000022a930434, 68'hffffffe1bb2aea7f8, 68'h00001c095b948d501, 68'hffe31b85697e6e7bb, 68'h26a12d6878c0bad6b};
        rom[ 54] = {68'h0000000000002fcbc, 68'hffffffffffd7f479d, 68'h0000000021de0fa60, 68'hffffffe244377efd7, 68'h00001baf5b734a8a6, 68'hffe3533ddc002d9dd, 68'h268464d91b7eceb32};
        rom[ 55] = {68'h0000000000002e36e, 68'hffffffffffd91338a, 68'h000000002118a17ba, 68'hffffffe2ca2306403, 68'h00001b56f1c07f02b, 68'hffe38a43e63e636a5, 68'h2667d3a8b8dff9c45};
        rom[ 56] = {68'h0000000000002cb17, 68'hffffffffffda287a8, 68'h000000002058b560a, 68'hffffffe34d03e8ac1, 68'h00001b00153ad000d, 68'hffe3c09aabc96f82f, 68'h264b79267bf3c55c9};
        rom[ 57] = {68'h0000000000002b3ad, 68'hffffffffffdb349c3, 68'h000000001f9e1ccb9, 68'hffffffe3ccefd0d27, 68'h00001aaabce2fd62d, 68'hffe3f6453df175985, 68'h262f54a4aa2ef818f};
        rom[ 58] = {68'h00000000000029d25, 68'hffffffffffdc37f66, 68'h000000001ee8aaf8b, 68'hffffffe449fbb2b0c, 68'h00001a56dff9b3179, 68'hffe42b469c4860711, 68'h26136578916cb8890};
        rom[ 59] = {68'h00000000000028776, 68'hffffffffffdd32ddf, 68'h000000001e3834d63, 68'hffffffe4c43bd29fe, 68'h00001a0475fd6fdd6, 68'hffe45fa1b51f9d52d, 68'h25f7aafa766f8b83c};
        rom[ 60] = {68'h00000000000027297, 68'hffffffffffde25a44, 68'h000000001d8c90f1e, 68'hffffffe53bc3cbf68, 68'h000019b376a8805a8, 68'hffe493596601b9683, 68'h25dc248583ddfb7f6};
        rom[ 61] = {68'h00000000000025e7e, 68'hffffffffffdf10970, 68'h000000001ce597672, 68'hffffffe5b0a697637, 68'h00001963d9ef0dafb, 68'hffe4c6707c2808f61, 68'h25c0d177b9b6def82};
        rom[ 62] = {68'h00000000000024b24, 68'hffffffffffdff400c, 68'h000000001c4321ce3, 68'hffffffe622f691022, 68'h0000191597fd3eb02, 68'hffe4f8e9b4ec7e7e9, 68'h25a5b131dd395ae75};
        rom[ 63] = {68'h00000000000023880, 68'hffffffffffe0d028e, 68'h000000001ba50b2c2, 68'hffffffe692c57e2de, 68'h000018c8a9356af49, 68'hffe52ac7be37d64f3, 68'h258ac317693ce3995};
        rom[ 64] = {68'h0000000000002268b, 68'hffffffffffe1a553c, 68'h000000001b0b2fe35, 68'hffffffe700249315c, 68'h0000187d062e5f07f, 68'hffe55c0d36ec396eb, 68'h2570068e7ef5a1e7e};
        rom[ 65] = {68'h0000000000002153e, 68'hffffffffffe273c30, 68'h000000001a756da51, 68'hffffffe76b2478153, 68'h00001832a7b1b0f5f, 68'hffe58cbcaf4c7963f, 68'h25557affd721c5140};
        rom[ 66] = {68'h00000000000020491, 68'hffffffffffe33bb55, 68'h0000000019e3a3639, 68'hffffffe7d3d54ed2d, 68'h000017e986ba248ca, 68'hffe5bcd8a96004e97, 68'h253b1fd6b39c6a3ee};
        rom[ 67] = {68'h0000000000001f47e, 68'hffffffffffe3fd670, 68'h000000001955b144a, 68'hffffffe83a46b729c, 68'h000017a19c721ea91, 68'hffe5ec639953b44a1, 68'h2520f480d152e1e9a};
        rom[ 68] = {68'h0000000000001e4ff, 68'hffffffffffe4b911d, 68'h0000000018cb78951, 68'hffffffe89e87d3de4, 68'h0000175ae23226f07, 68'hffe61b5fe5d78ade1, 68'h2506f86e5a9939f9f};
        rom[ 69] = {68'h0000000000001d60d, 68'hffffffffffe56eed1, 68'h000000001844dbbc9, 68'hffffffe900a74f218, 68'h00001715517f775d2, 68'hffe649cfe87989e66, 68'h24ed2b11d9db0f9d7};
        rom[ 70] = {68'h0000000000001c7a4, 68'hffffffffffe61f2e0, 68'h0000000017c1be321, 68'hffffffe960b35ee5a, 68'h000016d0e40a990f3, 68'hffe677b5edfdafdd8, 68'h24d38be02ca5c80ce};
        rom[ 71] = {68'h0000000000001b9bd, 68'hffffffffffe6ca078, 68'h0000000017420470f, 68'hffffffe9beb9c9053, 68'h0000168d93ae0dd57, 68'hffe6a51436b33e384, 68'h24ba1a50770969b96};
        rom[ 72] = {68'h0000000000001ac53, 68'hffffffffffe76faaa, 68'h0000000016c593ee6, 68'hffffffea1ac7e73f2, 68'h0000164b5a6d05eb1, 68'hffe6d1ecf6c75e82c, 68'h24a0d5dc174d68e08};
        rom[ 73] = {68'h00000000000019f62, 68'hffffffffffe810465, 68'h00000000164c530f8, 68'hffffffea74eaab0a3, 68'h0000160a3272216bf, 68'hffe6fe4256953ec45, 68'h2487bdfe99f6d2ebb};
        rom[ 74] = {68'h000000000000192e4, 68'hffffffffffe8ac07a, 68'h0000000015d6291f7, 68'hffffffeacd2ea1409, 68'h000015ca160e3d073, 68'hffe72a1672f3bc1cd, 68'h246ed235ae1d5b720};
        rom[ 75] = {68'h000000000000186d5, 68'hffffffffffe94319e, 68'h000000001562fe467, 68'hffffffeb239ff5a67, 68'h0000158affb7497ca, 68'hffe7556b5d80b1a61, 68'h245612011a0ce42bd};
        rom[ 76] = {68'h00000000000017b31, 68'hffffffffffe9d5a6c, 68'h0000000014f2bb813, 68'hffffffeb784a764cd, 68'h0000154cea072d774, 68'hffe780431cea00bdd, 68'h243d7ce2b0312ec2a};
        rom[ 77] = {68'h00000000000016ff3, 68'hffffffffffea63d62, 68'h0000000014854a984, 68'hffffffebcb3996d16, 68'h0000150fcfbab15c5, 68'hffe7aa9fad34670b8, 68'h2425125e44497c1f7};
        rom[ 78] = {68'h00000000000016518, 68'hffffffffffeaedce7, 68'h00000000141a96181, 68'hffffffec1c78737ee, 68'h000014d3abb074a9c, 68'hffe7d483000035c32, 68'h240cd1f9a0e1f0c64};
        rom[ 79] = {68'h00000000000015a9b, 68'hffffffffffeb73b4a, 68'h0000000013b289498, 68'hffffffec6c11d44cf, 68'h0000149878e7ec84b, 68'hffe7fdeefccbfce4d, 68'h23f4bb3c7d10a8ea0};
        rom[ 80] = {68'h0000000000001507a, 68'hffffffffffebf5ac3, 68'h00000000134d102a6, 68'hffffffecba102fc2e, 68'h0000145e32806b1bd, 68'hffe826e581353c7c8, 68'h23dccdb0727479485};
        rom[ 81] = {68'h000000000000146af, 68'hffffffffffec73d73, 68'h0000000012ea17667, 68'hffffffed067dadbd8, 68'h00001424d3b82f85f, 68'hffe84f6861372d30c, 68'h23c508e0f3736b81a};
        rom[ 82] = {68'h00000000000013d39, 68'hffffffffffecee567, 68'h0000000012898c50e, 68'hffffffed51642a19b, 68'h000013ec57eb7dc93, 68'hffe877796767b0c4b, 68'h23ad6c5b41b7159e7};
        rom[ 83] = {68'h00000000000013414, 68'hffffffffffed65498, 68'h00000000122b5cdda, 68'hffffffed9acd3744a, 68'h000013b4ba93beb9d, 68'hffe89f1a55327a8d7, 68'h2395f7ae64e4fcc0e};
        rom[ 84] = {68'h00000000000012b3d, 68'hffffffffffedd8cec, 68'h0000000011cf779b9, 68'hffffffede2c220b30, 68'h0000137df746a763f, 68'hffe8c64ce3127f3ca, 68'h237eaa6b219142b53};
        rom[ 85] = {68'h000000000000122b1, 68'hffffffffffee49036, 68'h000000001175cbae4, 68'hffffffee294bed404, 68'h0000134809b567b76, 68'hffe8ed12c0c9bacc4, 68'h23678423f069ed26d};
        rom[ 86] = {68'h00000000000011a6c, 68'hffffffffffeeb6037, 68'h00000000111e48c8a, 68'hffffffee6e7361771, 68'h00001312edabe02d9, 68'hffe9136d95975ac7c, 68'h2350846cf59923c75};
        rom[ 87] = {68'h0000000000001126e, 68'hffffffffffef1fea1, 68'h0000000010c8df27a, 68'hffffffeeb24101c31, 68'h000012de9f0fde27c, 68'hffe9395f006c5aa48, 68'h2339aadbf85cd0a68};
        rom[ 88] = {68'h00000000000010ab2, 68'hffffffffffef86d13, 68'h0000000010757f8cb, 68'hffffffeef4bd148ea, 68'h000012ab19e05ec35, 68'hffe95ee8981e9f571, 68'h2322f7085ad21b6e5};
        rom[ 89] = {68'h00000000000010336, 68'hffffffffffefead20, 68'h0000000010241b393, 68'hffffffef35efa44b4, 68'h000012785a34d7e7a, 68'hffe9840beb9a9ed52, 68'h230c688b11f345206};
        rom[ 90] = {68'h0000000000000fbf9, 68'hfffffffffff04c049, 68'h000000000fd4a3e98, 68'hffffffef75e081675, 68'h000012465c3c87511, 68'hffe9a8ca82139fb94, 68'h22f5fefe9dc676670};
        rom[ 91] = {68'h0000000000000f4f7, 68'hfffffffffff0aa802, 68'h000000000f870bd07, 68'hffffffefb49744314, 68'h000012151c3dc7608, 68'hffe9cd25db329ccb4, 68'h22dfb9ff01bc1e863};
        rom[ 92] = {68'h0000000000000ee2f, 68'hfffffffffff1065b2, 68'h000000000f3b45930, 68'hffffffeff21b4ea89, 68'h000011e496956979b, 68'hffe9f11f6f43d7bee, 68'h22c99929bd3b8c832};
        rom[ 93] = {68'h0000000000000e79e, 68'hfffffffffff15fab2, 68'h000000000ef144443, 68'hfffffff02e73ce3e1, 68'h000011b4c7b615bae, 68'hffea14b8af6326114, 68'h22b39c1dc45c77356};
        rom[ 94] = {68'h0000000000000e143, 68'hfffffffffff1b684f, 68'h000000000ea8fb60f, 68'hfffffff069a7bd839, 68'h00001185ac27afdc5, 68'hffea37f305a70284e, 68'h229dc27b78cc33a8c};
        rom[ 95] = {68'h0000000000000db1c, 68'hfffffffffff20afca, 68'h000000000e625ecc4, 68'hfffffff0a3bde5cc2, 68'h000011574086c1076, 68'hffea5acfd54a6d5da, 68'h22880be4a2dd63878};
        rom[ 96] = {68'h0000000000000d526, 68'hfffffffffff25d257, 68'h000000000e1d62cba, 68'hfffffff0dcbce0bd0, 68'h000011298183e677b, 68'hffea7d507ad5a51af, 68'h227277fc6ac0ef333};
        rom[ 97] = {68'h0000000000000cf5f, 68'hfffffffffff2ad121, 68'h000000000dd9fc036, 68'hfffffff114ab19d04, 68'h000010fc6be344b8c, 68'hffea9f764c45c118f, 68'h225d066751e728c63};
        rom[ 98] = {68'h0000000000000c9c8, 68'hfffffffffff2fad48, 68'h000000000d981f736, 68'hfffffff14b8ecfc98, 68'h000010cffc7bff573, 68'hffeac14299333726f, 68'h2247b6cb2c87fe739};
        rom[ 99] = {68'h0000000000000c45c, 68'hfffffffffff3467e0, 68'h000000000d57c273b, 68'hfffffff1816e161d2, 68'h000010a43037b4db4, 68'hffeae2b6aaf754d08, 68'h223288cf1b512b9f7};
        rom[100] = {68'h0000000000000bf1c, 68'hfffffffffff3901f6, 68'h000000000d18dab19, 68'hfffffff1b64ed64b2, 68'h000010790411fee6f, 68'hffeb03d3c4d0b4c5e, 68'h221d7c1b8539609fd};
        rom[101] = {68'h0000000000000ba05, 68'hfffffffffff3d7c8a, 68'h000000000cdb5e2c3, 68'hfffffff1ea36d12d7, 68'h0000104e7517f650f, 68'hffeb249b2406b8829, 68'h2208905a1177615a6};
        rom[102] = {68'h0000000000000b516, 68'hfffffffffff41d896, 68'h000000000c9f43321, 68'hfffffff21d2ba03a6, 68'h000010248067bb191, 68'hffeb450e000c0e0a9, 68'h21f3c535a19c22f08};
        rom[103] = {68'h0000000000000b04e, 68'hfffffffffff46170a, 68'h000000000c64805e2, 68'hfffffff24f32b6bbe, 68'h00000ffb23300012f, 68'hffeb652d8aa0494b4, 68'h21df1a5a4bcef85b5};
        rom[104] = {68'h0000000000000abab, 68'hfffffffffff4a38ce, 68'h000000000c2b0c950, 68'hfffffff2805162fbe, 68'h00000fd25aaf9a26a, 68'hffeb84faeff0986d9, 68'h21ca8f75552ae5490};
        rom[105] = {68'h0000000000000a72d, 68'hfffffffffff4e3ec1, 68'h000000000bf2df028, 68'hfffffff2b08ccf664, 68'h00000faa243513056, 68'hffeba47756b79a22e, 68'h21b624352c3c35b5a};
        rom[106] = {68'h0000000000000a2d1, 68'hfffffffffff5229bd, 68'h000000000bbbef176, 68'hfffffff2dfea03a0a, 68'h00000f827d1e3f362, 68'hffebc3a3e05c5cb7b, 68'h21a1d849639d7fa59};
        rom[107] = {68'h00000000000009e96, 68'hfffffffffff55fa90, 68'h000000000b8634867, 68'hfffffff30e6de5987, 68'h00000f5b62d7d759e, 68'hffebe281a9108c7c6, 68'h218dab62acb33b142};
        rom[108] = {68'h00000000000009a7c, 68'hfffffffffff59b206, 68'h000000000b51a742e, 68'hfffffff33c1d3a87f, 68'h00000f34d2dd148d6, 68'hffec0111c7edd7d8c, 68'h21799d32d285229bc};
        rom[109] = {68'h00000000000009682, 68'hfffffffffff5d50e1, 68'h000000000b1e3f7d9, 68'hfffffff368fca7f24, 68'h00000f0ecab74fcb4, 68'hffec1f554f128f275, 68'h2165ad6cb4b49594d};
        rom[110] = {68'h000000000000092a5, 68'hfffffffffff60d7dc, 68'h000000000aebf5a34, 68'hfffffff39510b4968, 68'h00000ee947fda435d, 68'hffec3d4d4bbd8641a, 68'h2151dbc4428f3a6d6};
        rom[111] = {68'h00000000000008ee6, 68'hfffffffffff6447ad, 68'h000000000abac25a9, 68'hfffffff3c05dc95b0, 68'h00000ec44854942dc, 68'hffec5afac6693d706, 68'h213e27ee763d25c6a};
        rom[112] = {68'h00000000000008b43, 68'hfffffffffff67a104, 68'h000000000a8a9e81b, 68'hfffffff3eae832309, 68'h00000e9fc96db11ea, 68'hffec785ec2e657437, 68'h212a91a15009d0839};
        rom[113] = {68'h000000000000087bc, 68'hfffffffffff6ae48b, 68'h000000000a5b832d1, 68'hfffffff414b41eedc, 68'h00000e7bc90745e90, 68'hffec957a407560a3a, 68'h21171893d1c72c5c5};
        rom[114] = {68'h0000000000000844f, 68'hfffffffffff6e12e5, 68'h000000000a2d69a51, 68'hfffffff43dc5a4232, 68'h00000e5844ec03d45, 68'hffecb24e39dff044e, 68'h2103bc7dfa4a2bc82};
        rom[115] = {68'h000000000000080fb, 68'hfffffffffff712cb1, 68'h000000000a004b647, 68'hfffffff46620bbe87, 68'h00000e353af2b1f1c, 68'hffeccedba59122700, 68'h20f07d18c100171cb};
        rom[116] = {68'h00000000000007dc0, 68'hfffffffffff743289, 68'h0000000009d42216d, 68'hfffffff48dc946a28, 68'h00000e12a8fddedcc, 68'hffeceb2375ad75f3d, 68'h20dd5a1e119c0da5f};
        rom[117] = {68'h00000000000007a9e, 68'hfffffffffff772500, 68'h0000000009a8e796d, 68'hfffffff4b4c30bc36, 68'h00000df08cfb94c41, 68'hffed0726982a0ee2f, 68'h20ca5348c7dc16347};
        rom[118] = {68'h00000000000007792, 68'hfffffffffff7a04a6, 68'h00000000097e95ecb, 68'hfffffff4db11ba831, 68'h00000dcee4e50fa7c, 68'hffed22e5f6e3639b5, 68'h20b76854ab65272f7};
        rom[119] = {68'h0000000000000749c, 68'hfffffffffff7cd205, 68'h000000000955274cb, 68'hfffffff500b8ea936, 68'h00000dadaebe75bab, 68'hffed3e6277b358714, 68'h20a498fe6bb592a5c};
        rom[120] = {68'h000000000000071bc, 68'hfffffffffff7f8da5, 68'h00000000092c9615d, 68'hfffffff525bc1cccd, 68'h00000d8ce89691d47, 68'hffed599cfc86ce2fe, 68'h2091e5039c2d471be};
        rom[121] = {68'h00000000000006ef2, 68'hfffffffffff823806, 68'h000000000904dcd03, 68'hfffffff54a1ebbd69, 68'h00000d6c90868fe31, 68'hffed74966372a780b, 68'h207f4c22b02b59f8e};
        rom[122] = {68'h00000000000006c3b, 68'hfffffffffff84d1a6, 68'h0000000008ddf62bd, 68'hfffffff56de41cc8b, 68'h00000d4ca4b1bb4b7, 68'hffed8f4f86c849278, 68'h206cce1af7405472d};
        rom[123] = {68'h00000000000006998, 68'hfffffffffff875aff, 68'h0000000008b7dcff6, 68'hfffffff5910f7fc92, 68'h00000d2d23453f290, 68'hffeda9c93d2998e1b, 68'h205a6aac9974bfb85};
        rom[124] = {68'h00000000000006708, 68'hfffffffffff89d486, 68'h0000000008928c471, 68'hfffffff5b3a410a3c, 68'h00000d0e0a77e85c4, 68'hffedc404599c7e955, 68'h2048219893a370d4f};
        rom[125] = {68'h0000000000000648a, 68'hfffffffffff8c3ead, 68'h00000000086dff22e, 68'hfffffff5d5a4e75d3, 68'h00000cef5889e95a7, 68'hffedde01ab9deb61e, 68'h2035f2a0b3e7186a2};
        rom[126] = {68'h0000000000000621e, 68'hfffffffffff8e99e2, 68'h00000000084a30d64, 68'hfffffff5f71508c18, 68'h00000cd10bc49faef, 68'hffedf7c1ff346a03d, 68'h2023dd87961a9dda0};
        rom[127] = {68'h00000000000005fc4, 68'hfffffffffff90e691, 68'h0000000008271cc64, 68'hfffffff617f766ede, 68'h00000cb3227a5b20e, 68'hffee11461d023be14, 68'h2011e210a06bd0e48};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [WSB-1:0]   sb_p   = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .WACC(ACCW), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
