/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=27): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m27 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 50:0] x0,
    input  wire signed [ 50:0] y0,
    input  wire signed [ 50:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 50:0] xn,
    output wire signed [ 50:0] yn,
    output wire signed [ 50:0] zn,
    output wire        [ 51:0] const2pi,   // round(2*pi * 2**XF), CWB = XF + 3 bits (sin/cos small angle)
    output wire        [ 46:0] inv_tau,    // round(2**XF / (2*pi)), XF-2 bits (atan2 turns scaling)
    output wire        [ 50:0] kinv        // round(2**XF / gain), inverse CORDIC-gain (atan2 magnitude)
);
    localparam integer N    = 19;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 51;
    localparam integer WZ   = 51;
    localparam integer XF   = 49;   // x/y fractional scale
    localparam integer ZF   = 48;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 52;
    localparam signed [WX-1:0] KINV = 51'sd341853011479034;   // round(1/gain * 2**XF) (== 2**XF/gain)

    assign const2pi = 52'd3537118876014220;
    assign inv_tau  = 47'd89596267800354;
    assign kinv     = KINV[WX-1:0];

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        51'd170891319,   // atan(2^-18)/2pi
        51'd341782638,   // atan(2^-17)/2pi
        51'd683565276,   // atan(2^-16)/2pi
        51'd1367130551,   // atan(2^-15)/2pi
        51'd2734261099,   // atan(2^-14)/2pi
        51'd5468522177,   // atan(2^-13)/2pi
        51'd10937044192,   // atan(2^-12)/2pi
        51'd21874087080,   // atan(2^-11)/2pi
        51'd43748163730,   // atan(2^-10)/2pi
        51'd87496244017,   // atan(2^-9)/2pi
        51'd174991820497,   // atan(2^-8)/2pi
        51'd349978300884,   // atan(2^-7)/2pi
        51'd699913886760,   // atan(2^-6)/2pi
        51'd1399486241028,   // atan(2^-5)/2pi
        51'd2796246208089,   // atan(2^-4)/2pi
        51'd5570871696862,   // atan(2^-3)/2pi
        51'd10974586953444,   // atan(2^-2)/2pi
        51'd20770547670515,   // atan(2^-1)/2pi
        51'd35184372088832   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
