/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=23 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + 1 (final multiply); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m23_d3 #(parameter integer WMAN = 23, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 6;
    localparam integer D    = 3;
    localparam integer RW   = 16;
    localparam integer CW   = 38;
    localparam integer ACCW = 40;
    localparam integer NSEG = 64;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {38'h3fffff4bdf, 38'h00003d8b42, 38'h3fe8eab92b, 38'h0b8aa3b291};
        rom[1] = {38'h3fffff5487, 38'h00003b6efe, 38'h3fe963b460, 38'h0b73cb42dd};
        rom[2] = {38'h3fffff5ca7, 38'h0000396cb2, 38'h3fe9d890f7, 38'h0b5d69bac4};
        rom[3] = {38'h3fffff6448, 38'h00003782c2, 38'h3fea498143, 38'h0b477b1513};
        rom[4] = {38'h3fffff6b74, 38'h000035afb4, 38'h3feab6b485, 38'h0b31fb7d61};
        rom[5] = {38'h3fffff7234, 38'h000033f229, 38'h3feb205723, 38'h0b1ce74d0f};
        rom[6] = {38'h3fffff788f, 38'h00003248db, 38'h3feb8692dc, 38'h0b083b088f};
        rom[7] = {38'h3fffff7e8c, 38'h000030b29c, 38'h3febe98efe, 38'h0af3f35cd4};
        rom[8] = {38'h3fffff8433, 38'h00002f2e54, 38'h3fec497090, 38'h0ae00d1cfb};
        rom[9] = {38'h3fffff8988, 38'h00002dbafd, 38'h3feca65a7b, 38'h0acc854012};
        rom[10] = {38'h3fffff8e92, 38'h00002c57a5, 38'h3fed006daf, 38'h0ab958df13};
        rom[11] = {38'h3fffff9355, 38'h00002b036a, 38'h3fed57c947, 38'h0aa68532f9};
        rom[12] = {38'h3fffff97d7, 38'h000029bd77, 38'h3fedac8aaa, 38'h0a940792ff};
        rom[13] = {38'h3fffff9c1b, 38'h0000288508, 38'h3fedfecda4, 38'h0a81dd72f6};
        rom[14] = {38'h3fffffa026, 38'h0000275965, 38'h3fee4eac86, 38'h0a700461bd};
        rom[15] = {38'h3fffffa3fb, 38'h00002639e1, 38'h3fee9c403b, 38'h0a5e7a07cd};
        rom[16] = {38'h3fffffa79d, 38'h00002525dc, 38'h3feee7a062, 38'h0a4d3c25e5};
        rom[17] = {38'h3fffffab11, 38'h0000241cbe, 38'h3fef30e360, 38'h0a3c4893c0};
        rom[18] = {38'h3fffffae58, 38'h0000231df9, 38'h3fef781e77, 38'h0a2b9d3eef};
        rom[19] = {38'h3fffffb175, 38'h000022290a, 38'h3fefbd65d5, 38'h0a1b3829b7};
        rom[20] = {38'h3fffffb46c, 38'h0000213d72, 38'h3ff000cca7, 38'h0a0b176a0b};
        rom[21] = {38'h3fffffb73e, 38'h0000205abe, 38'h3ff042652a, 38'h09fb392891};
        rom[22] = {38'h3fffffb9ed, 38'h00001f807e, 38'h3ff08240b4, 38'h09eb9b9fb6};
        rom[23] = {38'h3fffffbc7b, 38'h00001eae4b, 38'h3ff0c06fc9, 38'h09dc3d1ad5};
        rom[24] = {38'h3fffffbeeb, 38'h00001de3c4, 38'h3ff0fd0220, 38'h09cd1bf565};
        rom[25] = {38'h3fffffc13e, 38'h00001d208c, 38'h3ff13806b4, 38'h09be369a34};
        rom[26] = {38'h3fffffc376, 38'h00001c644d, 38'h3ff1718bcf, 38'h09af8b82b4};
        rom[27] = {38'h3fffffc594, 38'h00001baeb5, 38'h3ff1a99f0f, 38'h09a1193646};
        rom[28] = {38'h3fffffc79a, 38'h00001aff76, 38'h3ff1e04d76, 38'h0992de499e};
        rom[29] = {38'h3fffffc988, 38'h00001a5648, 38'h3ff215a36d, 38'h0984d95e23};
        rom[30] = {38'h3fffffcb61, 38'h000019b2e5, 38'h3ff249acd0, 38'h0977092160};
        rom[31] = {38'h3fffffcd25, 38'h000019150d, 38'h3ff27c74f6, 38'h09696c4c76};
        rom[32] = {38'h3fffffced6, 38'h0000187c81, 38'h3ff2ae06b6, 38'h095c01a39f};
        rom[33] = {38'h3fffffd074, 38'h000017e907, 38'h3ff2de6c6e, 38'h094ec7f5ac};
        rom[34] = {38'h3fffffd201, 38'h0000175a68, 38'h3ff30db00b, 38'h0941be1b96};
        rom[35] = {38'h3fffffd37d, 38'h000016d06f, 38'h3ff33bdb0e, 38'h0934e2f80a};
        rom[36] = {38'h3fffffd4ea, 38'h0000164aea, 38'h3ff368f692, 38'h0928357705};
        rom[37] = {38'h3fffffd647, 38'h000015c9aa, 38'h3ff3950b4f, 38'h091bb48d6b};
        rom[38] = {38'h3fffffd796, 38'h0000154c83, 38'h3ff3c021a3, 38'h090f5f38ab};
        rom[39] = {38'h3fffffd8d8, 38'h000014d349, 38'h3ff3ea4194, 38'h0903347e68};
        rom[40] = {38'h3fffffda0d, 38'h0000145dd3, 38'h3ff41372d4, 38'h08f7336c1c};
        rom[41] = {38'h3fffffdb35, 38'h000013ebfd, 38'h3ff43bbcc6, 38'h08eb5b16d0};
        rom[42] = {38'h3fffffdc52, 38'h0000137d9f, 38'h3ff4632683, 38'h08dfaa9ac8};
        rom[43] = {38'h3fffffdd64, 38'h0000131299, 38'h3ff489b6dc, 38'h08d4211b3d};
        rom[44] = {38'h3fffffde6c, 38'h000012aac9, 38'h3ff4af745c, 38'h08c8bdc216};
        rom[45] = {38'h3fffffdf69, 38'h000012460e, 38'h3ff4d46551, 38'h08bd7fbfa7};
        rom[46] = {38'h3fffffe05d, 38'h000011e44b, 38'h3ff4f88fc7, 38'h08b2664a6f};
        rom[47] = {38'h3fffffe147, 38'h0000118564, 38'h3ff51bf991, 38'h08a7709ede};
        rom[48] = {38'h3fffffe229, 38'h000011293c, 38'h3ff53ea84b, 38'h089c9dff1a};
        rom[49] = {38'h3fffffe303, 38'h000010cfb9, 38'h3ff560a15a, 38'h0891edb2cb};
        rom[50] = {38'h3fffffe3d4, 38'h00001078c3, 38'h3ff581e9ef, 38'h08875f06e1};
        rom[51] = {38'h3fffffe49e, 38'h0000102442, 38'h3ff5a2870c, 38'h087cf14d68};
        rom[52] = {38'h3fffffe561, 38'h00000fd21f, 38'h3ff5c27d84, 38'h0872a3dd55};
        rom[53] = {38'h3fffffe61d, 38'h00000f8243, 38'h3ff5e1d1fc, 38'h0868761259};
        rom[54] = {38'h3fffffe6d2, 38'h00000f349b, 38'h3ff60088ef, 38'h085e674cb4};
        rom[55] = {38'h3fffffe781, 38'h00000ee912, 38'h3ff61ea6b1, 38'h085476f110};
        rom[56] = {38'h3fffffe829, 38'h00000e9f95, 38'h3ff63c2f6c, 38'h084aa46854};
        rom[57] = {38'h3fffffe8cc, 38'h00000e5813, 38'h3ff6592727, 38'h0840ef1f7e};
        rom[58] = {38'h3fffffe969, 38'h00000e1278, 38'h3ff67591c5, 38'h0837568784};
        rom[59] = {38'h3fffffea01, 38'h00000dceb6, 38'h3ff6917305, 38'h082dda152b};
        rom[60] = {38'h3fffffea94, 38'h00000d8cbb, 38'h3ff6acce87, 38'h08247940e7};
        rom[61] = {38'h3fffffeb22, 38'h00000d4c79, 38'h3ff6c7a7cc, 38'h081b3386be};
        rom[62] = {38'h3fffffebab, 38'h00000d0de0, 38'h3ff6e20235, 38'h0812086625};
        rom[63] = {38'h3fffffec30, 38'h00000cd0e3, 38'h3ff6fbe108, 38'h0808f761e5};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
