/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=18 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m18 #(parameter integer WMAN = 18, parameter integer D = 2, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 8;
    localparam integer RW   = 10;
    localparam integer CW   = 33;
    localparam integer ACCW = 35;
    localparam integer NSEG = 256;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {33'h000008d77, 33'h1ff8eabfd, 33'h07ffffffa};
        rom[  1] = {33'h000008b19, 33'h1ff8fc6e9, 33'h07f8f3961};
        rom[  2] = {33'h0000088c9, 33'h1ff90dd19, 33'h07f1f8b57};
        rom[  3] = {33'h000008687, 33'h1ff91eea8, 33'h07eb0f12c};
        rom[  4] = {33'h000008453, 33'h1ff92fbb4, 33'h07e43664f};
        rom[  5] = {33'h00000822c, 33'h1ff940458, 33'h07dd6e64b};
        rom[  6] = {33'h000008012, 33'h1ff9508ae, 33'h07d6b6cc4};
        rom[  7] = {33'h000007e04, 33'h1ff9608d0, 33'h07d00f579};
        rom[  8] = {33'h000007c02, 33'h1ff9704d6, 33'h07c977c42};
        rom[  9] = {33'h000007a0c, 33'h1ff97fcd8, 33'h07c2efd0f};
        rom[ 10] = {33'h000007821, 33'h1ff98f0ef, 33'h07bc773e9};
        rom[ 11] = {33'h000007642, 33'h1ff99e130, 33'h07b60dcef};
        rom[ 12] = {33'h00000746c, 33'h1ff9acdb1, 33'h07afb3457};
        rom[ 13] = {33'h0000072a2, 33'h1ff9bb689, 33'h07a96766b};
        rom[ 14] = {33'h0000070e1, 33'h1ff9c9bcb, 33'h07a329f8d};
        rom[ 15] = {33'h000006f2a, 33'h1ff9d7d8c, 33'h079cfac30};
        rom[ 16] = {33'h000006d7d, 33'h1ff9e5be0, 33'h0796d98de};
        rom[ 17] = {33'h000006bd9, 33'h1ff9f36d9, 33'h0790c6232};
        rom[ 18] = {33'h000006a3e, 33'h1ffa00e89, 33'h078ac04db};
        rom[ 19] = {33'h0000068ac, 33'h1ffa0e304, 33'h0784c7d9a};
        rom[ 20] = {33'h000006722, 33'h1ffa1b45a, 33'h077edc941};
        rom[ 21] = {33'h0000065a0, 33'h1ffa2829c, 33'h0778fe4b4};
        rom[ 22] = {33'h000006426, 33'h1ffa34ddb, 33'h07732cce9};
        rom[ 23] = {33'h0000062b5, 33'h1ffa41627, 33'h076d67ee2};
        rom[ 24] = {33'h00000614b, 33'h1ffa4db8f, 33'h0767af7b6};
        rom[ 25] = {33'h000005fe8, 33'h1ffa59e23, 33'h076203488};
        rom[ 26] = {33'h000005e8c, 33'h1ffa65df2, 33'h075c6328c};
        rom[ 27] = {33'h000005d38, 33'h1ffa71b09, 33'h0756cef03};
        rom[ 28] = {33'h000005bea, 33'h1ffa7d577, 33'h07514673c};
        rom[ 29] = {33'h000005aa3, 33'h1ffa88d4a, 33'h074bc9897};
        rom[ 30] = {33'h000005962, 33'h1ffa9428f, 33'h07465807e};
        rom[ 31] = {33'h000005828, 33'h1ffa9f553, 33'h0740f1c69};
        rom[ 32] = {33'h0000056f4, 33'h1ffaaa5a2, 33'h073b969dd};
        rom[ 33] = {33'h0000055c6, 33'h1ffab5389, 33'h07364666d};
        rom[ 34] = {33'h00000549e, 33'h1ffabff14, 33'h073100fb6};
        rom[ 35] = {33'h00000537b, 33'h1ffaca84e, 33'h072bc6362};
        rom[ 36] = {33'h00000525e, 33'h1ffad4f43, 33'h072695f25};
        rom[ 37] = {33'h000005146, 33'h1ffadf3ff, 33'h0721700c1};
        rom[ 38] = {33'h000005034, 33'h1ffae968a, 33'h071c54600};
        rom[ 39] = {33'h000004f27, 33'h1ffaf36f2, 33'h071742cb9};
        rom[ 40] = {33'h000004e1f, 33'h1ffafd53f, 33'h07123b2cb};
        rom[ 41] = {33'h000004d1b, 33'h1ffb0717b, 33'h070d3d623};
        rom[ 42] = {33'h000004c1d, 33'h1ffb10bb1, 33'h0708494b4};
        rom[ 43] = {33'h000004b23, 33'h1ffb1a3ea, 33'h07035ec7d};
        rom[ 44] = {33'h000004a2e, 33'h1ffb23a30, 33'h06fe7db86};
        rom[ 45] = {33'h00000493d, 33'h1ffb2ce8b, 33'h06f9a5fdf};
        rom[ 46] = {33'h000004851, 33'h1ffb36105, 33'h06f4d77a3};
        rom[ 47] = {33'h000004769, 33'h1ffb3f1a6, 33'h06f0120f3};
        rom[ 48] = {33'h000004684, 33'h1ffb48076, 33'h06eb559fd};
        rom[ 49] = {33'h0000045a4, 33'h1ffb50d7f, 33'h06e6a20f3};
        rom[ 50] = {33'h0000044c8, 33'h1ffb598c7, 33'h06e1f7412};
        rom[ 51] = {33'h0000043f0, 33'h1ffb62258, 33'h06dd5519d};
        rom[ 52] = {33'h00000431c, 33'h1ffb6aa38, 33'h06d8bb7e0};
        rom[ 53] = {33'h00000424b, 33'h1ffb7306f, 33'h06d42a52f};
        rom[ 54] = {33'h00000417e, 33'h1ffb7b505, 33'h06cfa17e5};
        rom[ 55] = {33'h0000040b5, 33'h1ffb83800, 33'h06cb20e64};
        rom[ 56] = {33'h000003fee, 33'h1ffb8b969, 33'h06c6a8714};
        rom[ 57] = {33'h000003f2c, 33'h1ffb93945, 33'h06c238068};
        rom[ 58] = {33'h000003e6c, 33'h1ffb9b79c, 33'h06bdcf8d5};
        rom[ 59] = {33'h000003db0, 33'h1ffba3474, 33'h06b96eed9};
        rom[ 60] = {33'h000003cf7, 33'h1ffbaafd4, 33'h06b5160fa};
        rom[ 61] = {33'h000003c41, 33'h1ffbb29c1, 33'h06b0c4dc1};
        rom[ 62] = {33'h000003b8e, 33'h1ffbba243, 33'h06ac7b3bf};
        rom[ 63] = {33'h000003ade, 33'h1ffbc195e, 33'h06a83918c};
        rom[ 64] = {33'h000003a31, 33'h1ffbc8f1a, 33'h06a3fe5c4};
        rom[ 65] = {33'h000003987, 33'h1ffbd037b, 33'h069fcaf0b};
        rom[ 66] = {33'h0000038df, 33'h1ffbd7688, 33'h069b9ec09};
        rom[ 67] = {33'h00000383a, 33'h1ffbde845, 33'h069779b6c};
        rom[ 68] = {33'h000003798, 33'h1ffbe58b9, 33'h06935bbe8};
        rom[ 69] = {33'h0000036f8, 33'h1ffbec7e9, 33'h068f44c36};
        rom[ 70] = {33'h00000365b, 33'h1ffbf35d9, 33'h068b34b14};
        rom[ 71] = {33'h0000035c1, 33'h1ffbfa290, 33'h06872b745};
        rom[ 72] = {33'h000003529, 33'h1ffc00e11, 33'h068328f93};
        rom[ 73] = {33'h000003493, 33'h1ffc07862, 33'h067f2d2c9};
        rom[ 74] = {33'h000003400, 33'h1ffc0e188, 33'h067b37fbc};
        rom[ 75] = {33'h00000336f, 33'h1ffc14987, 33'h067749541};
        rom[ 76] = {33'h0000032e0, 33'h1ffc1b064, 33'h067361234};
        rom[ 77] = {33'h000003253, 33'h1ffc21624, 33'h066f7f575};
        rom[ 78] = {33'h0000031c9, 33'h1ffc27aca, 33'h066ba3de9};
        rom[ 79] = {33'h000003140, 33'h1ffc2de5b, 33'h0667cea78};
        rom[ 80] = {33'h0000030ba, 33'h1ffc340db, 33'h0663ffa11};
        rom[ 81] = {33'h000003036, 33'h1ffc3a24f, 33'h066036ba4};
        rom[ 82] = {33'h000002fb4, 33'h1ffc402bb, 33'h065c73e26};
        rom[ 83] = {33'h000002f33, 33'h1ffc46222, 33'h0658b7092};
        rom[ 84] = {33'h000002eb5, 33'h1ffc4c088, 33'h0655001e4};
        rom[ 85] = {33'h000002e38, 33'h1ffc51df1, 33'h06514f11e};
        rom[ 86] = {33'h000002dbe, 33'h1ffc57a62, 33'h064da3d45};
        rom[ 87] = {33'h000002d45, 33'h1ffc5d5dd, 33'h0649fe563};
        rom[ 88] = {33'h000002cce, 33'h1ffc63067, 33'h06465e882};
        rom[ 89] = {33'h000002c58, 33'h1ffc68a02, 33'h0642c45b4};
        rom[ 90] = {33'h000002be5, 33'h1ffc6e2b3, 33'h063f2fc0c};
        rom[ 91] = {33'h000002b73, 33'h1ffc73a7c, 33'h063ba0aa1};
        rom[ 92] = {33'h000002b02, 33'h1ffc79161, 33'h06381708d};
        rom[ 93] = {33'h000002a94, 33'h1ffc7e766, 33'h063492cee};
        rom[ 94] = {33'h000002a27, 33'h1ffc83c8d, 33'h063113ee6};
        rom[ 95] = {33'h0000029bb, 33'h1ffc890da, 33'h062d9a597};
        rom[ 96] = {33'h000002951, 33'h1ffc8e450, 33'h062a2602a};
        rom[ 97] = {33'h0000028e8, 33'h1ffc936f1, 33'h0626b6dc8};
        rom[ 98] = {33'h000002881, 33'h1ffc988c2, 33'h06234cda0};
        rom[ 99] = {33'h00000281c, 33'h1ffc9d9c4, 33'h061fe7ee1};
        rom[100] = {33'h0000027b7, 33'h1ffca29fb, 33'h061c880bf};
        rom[101] = {33'h000002754, 33'h1ffca796a, 33'h06192d26f};
        rom[102] = {33'h0000026f3, 33'h1ffcac812, 33'h0615d732c};
        rom[103] = {33'h000002693, 33'h1ffcb15f8, 33'h06128622f};
        rom[104] = {33'h000002634, 33'h1ffcb631e, 33'h060f39eb8};
        rom[105] = {33'h0000025d6, 33'h1ffcbaf85, 33'h060bf2808};
        rom[106] = {33'h00000257a, 33'h1ffcbfb32, 33'h0608afd61};
        rom[107] = {33'h00000251f, 33'h1ffcc4626, 33'h060571e0c};
        rom[108] = {33'h0000024c5, 33'h1ffcc9064, 33'h06023894f};
        rom[109] = {33'h00000246d, 33'h1ffccd9ef, 33'h05ff03e76};
        rom[110] = {33'h000002415, 33'h1ffcd22c8, 33'h05fbd3cd0};
        rom[111] = {33'h0000023bf, 33'h1ffcd6af2, 33'h05f8a83ab};
        rom[112] = {33'h00000236a, 33'h1ffcdb270, 33'h05f58125a};
        rom[113] = {33'h000002316, 33'h1ffcdf944, 33'h05f25e832};
        rom[114] = {33'h0000022c3, 33'h1ffce3f6f, 33'h05ef4048a};
        rom[115] = {33'h000002271, 33'h1ffce84f5, 33'h05ec266bb};
        rom[116] = {33'h000002220, 33'h1ffcec9d7, 33'h05e910e1f};
        rom[117] = {33'h0000021d1, 33'h1ffcf0e18, 33'h05e5ffa15};
        rom[118] = {33'h000002182, 33'h1ffcf51b9, 33'h05e2f29fc};
        rom[119] = {33'h000002134, 33'h1ffcf94bd, 33'h05dfe9d36};
        rom[120] = {33'h0000020e8, 33'h1ffcfd726, 33'h05dce5327};
        rom[121] = {33'h00000209c, 33'h1ffd018f6, 33'h05d9e4b33};
        rom[122] = {33'h000002051, 33'h1ffd05a2e, 33'h05d6e84c3};
        rom[123] = {33'h000002008, 33'h1ffd09ad1, 33'h05d3eff41};
        rom[124] = {33'h000001fbf, 33'h1ffd0dae0, 33'h05d0fba18};
        rom[125] = {33'h000001f77, 33'h1ffd11a5d, 33'h05ce0b4b5};
        rom[126] = {33'h000001f30, 33'h1ffd1594b, 33'h05cb1ee88};
        rom[127] = {33'h000001eea, 33'h1ffd197ab, 33'h05c836701};
        rom[128] = {33'h000001ea5, 33'h1ffd1d57e, 33'h05c551d94};
        rom[129] = {33'h000001e60, 33'h1ffd212c7, 33'h05c2711b5};
        rom[130] = {33'h000001e1d, 33'h1ffd24f87, 33'h05bf942db};
        rom[131] = {33'h000001dda, 33'h1ffd28bc0, 33'h05bcbb07e};
        rom[132] = {33'h000001d98, 33'h1ffd2c774, 33'h05b9e5a16};
        rom[133] = {33'h000001d57, 33'h1ffd302a4, 33'h05b713f21};
        rom[134] = {33'h000001d17, 33'h1ffd33d52, 33'h05b445f1a};
        rom[135] = {33'h000001cd7, 33'h1ffd3777f, 33'h05b17b981};
        rom[136] = {33'h000001c98, 33'h1ffd3b12d, 33'h05aeb4dd6};
        rom[137] = {33'h000001c5a, 33'h1ffd3ea5d, 33'h05abf1b99};
        rom[138] = {33'h000001c1d, 33'h1ffd42312, 33'h05a93224f};
        rom[139] = {33'h000001be1, 33'h1ffd45b4c, 33'h05a67617d};
        rom[140] = {33'h000001ba5, 33'h1ffd4930d, 33'h05a3bd8a8};
        rom[141] = {33'h000001b6a, 33'h1ffd4ca56, 33'h05a108758};
        rom[142] = {33'h000001b2f, 33'h1ffd50129, 33'h059e56d17};
        rom[143] = {33'h000001af6, 33'h1ffd53788, 33'h059ba896e};
        rom[144] = {33'h000001abd, 33'h1ffd56d73, 33'h0598fdbeb};
        rom[145] = {33'h000001a84, 33'h1ffd5a2ec, 33'h059656419};
        rom[146] = {33'h000001a4c, 33'h1ffd5d7f4, 33'h0593b2188};
        rom[147] = {33'h000001a15, 33'h1ffd60c8d, 33'h0591113c7};
        rom[148] = {33'h0000019df, 33'h1ffd640b8, 33'h058e73a68};
        rom[149] = {33'h0000019a9, 33'h1ffd67476, 33'h058bd94fd};
        rom[150] = {33'h000001974, 33'h1ffd6a7c8, 33'h05894231b};
        rom[151] = {33'h00000193f, 33'h1ffd6dab0, 33'h0586ae456};
        rom[152] = {33'h00000190c, 33'h1ffd70d2f, 33'h05841d844};
        rom[153] = {33'h0000018d8, 33'h1ffd73f46, 33'h05818fe7d};
        rom[154] = {33'h0000018a5, 33'h1ffd770f6, 33'h057f0569a};
        rom[155] = {33'h000001873, 33'h1ffd7a240, 33'h057c7e034};
        rom[156] = {33'h000001841, 33'h1ffd7d327, 33'h0579f9ae6};
        rom[157] = {33'h000001810, 33'h1ffd803a9, 33'h05777864d};
        rom[158] = {33'h0000017e0, 33'h1ffd833ca, 33'h0574fa206};
        rom[159] = {33'h0000017b0, 33'h1ffd8638a, 33'h05727edaf};
        rom[160] = {33'h000001780, 33'h1ffd892e9, 33'h0570068e7};
        rom[161] = {33'h000001751, 33'h1ffd8c1ea, 33'h056d91350};
        rom[162] = {33'h000001723, 33'h1ffd8f08d, 33'h056b1ec8b};
        rom[163] = {33'h0000016f5, 33'h1ffd91ed3, 33'h0568af439};
        rom[164] = {33'h0000016c8, 33'h1ffd94cbd, 33'h056642a00};
        rom[165] = {33'h00000169b, 33'h1ffd97a4c, 33'h0563d8d84};
        rom[166] = {33'h00000166e, 33'h1ffd9a782, 33'h056171e6a};
        rom[167] = {33'h000001642, 33'h1ffd9d45e, 33'h055f0dc59};
        rom[168] = {33'h000001617, 33'h1ffda00e3, 33'h055cac6f8};
        rom[169] = {33'h0000015ec, 33'h1ffda2d11, 33'h055a4ddf1};
        rom[170] = {33'h0000015c1, 33'h1ffda58e8, 33'h0557f20ed};
        rom[171] = {33'h000001597, 33'h1ffda846b, 33'h055598f96};
        rom[172] = {33'h00000156e, 33'h1ffdaaf9a, 33'h055342997};
        rom[173] = {33'h000001544, 33'h1ffdada75, 33'h0550eee9e};
        rom[174] = {33'h00000151c, 33'h1ffdb04fe, 33'h054e9de57};
        rom[175] = {33'h0000014f3, 33'h1ffdb2f35, 33'h054c4f870};
        rom[176] = {33'h0000014cc, 33'h1ffdb591c, 33'h054a03c98};
        rom[177] = {33'h0000014a4, 33'h1ffdb82b3, 33'h0547baa7f};
        rom[178] = {33'h00000147d, 33'h1ffdbabfb, 33'h0545741d5};
        rom[179] = {33'h000001456, 33'h1ffdbd4f5, 33'h05433024d};
        rom[180] = {33'h000001430, 33'h1ffdbfda2, 33'h0540eeb97};
        rom[181] = {33'h00000140a, 33'h1ffdc2602, 33'h053eafd69};
        rom[182] = {33'h0000013e5, 33'h1ffdc4e16, 33'h053c73774};
        rom[183] = {33'h0000013c0, 33'h1ffdc75e0, 33'h053a3996f};
        rom[184] = {33'h00000139b, 33'h1ffdc9d5f, 33'h05380230e};
        rom[185] = {33'h000001377, 33'h1ffdcc495, 33'h0535cd407};
        rom[186] = {33'h000001353, 33'h1ffdceb83, 33'h05339ac13};
        rom[187] = {33'h00000132f, 33'h1ffdd1228, 33'h05316aae7};
        rom[188] = {33'h00000130c, 33'h1ffdd3887, 33'h052f3d03e};
        rom[189] = {33'h0000012e9, 33'h1ffdd5e9e, 33'h052d11bd0};
        rom[190] = {33'h0000012c7, 33'h1ffdd8471, 33'h052ae8d57};
        rom[191] = {33'h0000012a4, 33'h1ffdda9fe, 33'h0528c248d};
        rom[192] = {33'h000001283, 33'h1ffddcf47, 33'h05269e12f};
        rom[193] = {33'h000001261, 33'h1ffddf44c, 33'h05247c2f7};
        rom[194] = {33'h000001240, 33'h1ffde190e, 33'h05225c9a4};
        rom[195] = {33'h00000121f, 33'h1ffde3d8e, 33'h05203f4f1};
        rom[196] = {33'h0000011ff, 33'h1ffde61cc, 33'h051e2449e};
        rom[197] = {33'h0000011df, 33'h1ffde85ca, 33'h051c0b868};
        rom[198] = {33'h0000011bf, 33'h1ffdea987, 33'h0519f5010};
        rom[199] = {33'h00000119f, 33'h1ffdecd04, 33'h0517e0b55};
        rom[200] = {33'h000001180, 33'h1ffdef042, 33'h0515ce9f7};
        rom[201] = {33'h000001161, 33'h1ffdf1342, 33'h0513bebb9};
        rom[202] = {33'h000001142, 33'h1ffdf3604, 33'h0511b105b};
        rom[203] = {33'h000001124, 33'h1ffdf5889, 33'h050fa57a1};
        rom[204] = {33'h000001106, 33'h1ffdf7ad1, 33'h050d9c14d};
        rom[205] = {33'h0000010e8, 33'h1ffdf9cdd, 33'h050b94d24};
        rom[206] = {33'h0000010cb, 33'h1ffdfbead, 33'h05098fae8};
        rom[207] = {33'h0000010ae, 33'h1ffdfe043, 33'h05078ca60};
        rom[208] = {33'h000001091, 33'h1ffe0019e, 33'h05058bb50};
        rom[209] = {33'h000001074, 33'h1ffe022c0, 33'h05038cd7f};
        rom[210] = {33'h000001058, 33'h1ffe043a8, 33'h0501900b2};
        rom[211] = {33'h00000103c, 33'h1ffe06458, 33'h04ff954b1};
        rom[212] = {33'h000001020, 33'h1ffe084cf, 33'h04fd9c944};
        rom[213] = {33'h000001004, 33'h1ffe0a50f, 33'h04fba5e33};
        rom[214] = {33'h000000fe9, 33'h1ffe0c518, 33'h04f9b1346};
        rom[215] = {33'h000000fce, 33'h1ffe0e4ea, 33'h04f7be846};
        rom[216] = {33'h000000fb3, 33'h1ffe10486, 33'h04f5cdcfd};
        rom[217] = {33'h000000f99, 33'h1ffe123ed, 33'h04f3df136};
        rom[218] = {33'h000000f7f, 33'h1ffe1431e, 33'h04f1f24bb};
        rom[219] = {33'h000000f64, 33'h1ffe1621b, 33'h04f007757};
        rom[220] = {33'h000000f4b, 33'h1ffe180e4, 33'h04ee1e8d6};
        rom[221] = {33'h000000f31, 33'h1ffe19f79, 33'h04ec37905};
        rom[222] = {33'h000000f18, 33'h1ffe1bddc, 33'h04ea527af};
        rom[223] = {33'h000000eff, 33'h1ffe1dc0b, 33'h04e86f4a2};
        rom[224] = {33'h000000ee6, 33'h1ffe1fa09, 33'h04e68dfab};
        rom[225] = {33'h000000ecd, 33'h1ffe217d4, 33'h04e4ae899};
        rom[226] = {33'h000000eb5, 33'h1ffe2356f, 33'h04e2d0f3a};
        rom[227] = {33'h000000e9d, 33'h1ffe252d8, 33'h04e0f535d};
        rom[228] = {33'h000000e85, 33'h1ffe27012, 33'h04df1b4d1};
        rom[229] = {33'h000000e6d, 33'h1ffe28d1b, 33'h04dd43367};
        rom[230] = {33'h000000e55, 33'h1ffe2a9f5, 33'h04db6ceef};
        rom[231] = {33'h000000e3e, 33'h1ffe2c6a0, 33'h04d998738};
        rom[232] = {33'h000000e27, 33'h1ffe2e31c, 33'h04d7c5c15};
        rom[233] = {33'h000000e10, 33'h1ffe2ff6a, 33'h04d5f4d58};
        rom[234] = {33'h000000df9, 33'h1ffe31b8a, 33'h04d425ad1};
        rom[235] = {33'h000000de3, 33'h1ffe3377c, 33'h04d258453};
        rom[236] = {33'h000000dcd, 33'h1ffe35342, 33'h04d08c9b2};
        rom[237] = {33'h000000db6, 33'h1ffe36edb, 33'h04cec2ac0};
        rom[238] = {33'h000000da1, 33'h1ffe38a48, 33'h04ccfa751};
        rom[239] = {33'h000000d8b, 33'h1ffe3a589, 33'h04cb33f39};
        rom[240] = {33'h000000d75, 33'h1ffe3c09f, 33'h04c96f24d};
        rom[241] = {33'h000000d60, 33'h1ffe3db89, 33'h04c7ac060};
        rom[242] = {33'h000000d4b, 33'h1ffe3f649, 33'h04c5ea949};
        rom[243] = {33'h000000d36, 33'h1ffe410df, 33'h04c42acdd};
        rom[244] = {33'h000000d21, 33'h1ffe42b4a, 33'h04c26caf1};
        rom[245] = {33'h000000d0c, 33'h1ffe4458d, 33'h04c0b035c};
        rom[246] = {33'h000000cf8, 33'h1ffe45fa6, 33'h04bef55f5};
        rom[247] = {33'h000000ce4, 33'h1ffe47996, 33'h04bd3c292};
        rom[248] = {33'h000000cd0, 33'h1ffe4935d, 33'h04bb8490b};
        rom[249] = {33'h000000cbc, 33'h1ffe4acfd, 33'h04b9ce937};
        rom[250] = {33'h000000ca8, 33'h1ffe4c674, 33'h04b81a2ef};
        rom[251] = {33'h000000c95, 33'h1ffe4dfc4, 33'h04b66760b};
        rom[252] = {33'h000000c81, 33'h1ffe4f8ed, 33'h04b4b6264};
        rom[253] = {33'h000000c6e, 33'h1ffe511f0, 33'h04b3067d2};
        rom[254] = {33'h000000c5b, 33'h1ffe52acb, 33'h04b15862f};
        rom[255] = {33'h000000c48, 33'h1ffe54381, 33'h04afabd54};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
