/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=36 (degree 4); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m36 #(parameter integer WMAN = 36, parameter integer D = 4, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [SBW-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [SBW-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 4) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer CF   = 48;
    localparam integer RW   = 42;
    localparam integer CW   = 51;
    localparam integer ACCW = 53;
    localparam integer NSEG = 64;
    localparam integer HSBW = SBW;

    (* rom_style = "block", syn_romstyle = "EBR" *)  // The table is large, map it to a block ROM (EBR)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {51'h00000000279c2, 51'h00000038d5e1b, 51'h00003d7f7c103, 51'h002c5c85fdf25, 51'h1000000000001};
        rom[  1] = {51'h00000000280a9, 51'h000000397451d, 51'h00003e2aeb808, 51'h002cd83016283, 51'h102c9a3e77807};
        rom[  2] = {51'h00000000287a2, 51'h0000003a147b9, 51'h00003ed838d7f, 51'h002d5532ea48a, 51'h1059b0d315858};
        rom[  3] = {51'h0000000028eb0, 51'h0000003ab663c, 51'h00003f87694ac, 51'h002dd3923b53b, 51'h10874518759bd};
        rom[  4] = {51'h00000000295d1, 51'h0000003b5a0f6, 51'h00004038821ba, 51'h002e5351d4c07, 51'h10b5586cf9892};
        rom[  5] = {51'h0000000029d06, 51'h0000003bff833, 51'h000040eb889c1, 51'h002ed4758c9a0, 51'h10e3ec32d3d1b};
        rom[  6] = {51'h000000002a44f, 51'h0000003ca6c44, 51'h000041a0822c3, 51'h002f5701439d1, 51'h111301d0125b6};
        rom[  7] = {51'h000000002abac, 51'h0000003d4fd79, 51'h00004257743b5, 51'h002fdaf8e555f, 51'h11429aaea92df};
        rom[  8] = {51'h000000002b31e, 51'h0000003dfac23, 51'h000043106447b, 51'h00306060683e2, 51'h1172b83c7d518};
        rom[  9] = {51'h000000002baa5, 51'h0000003ea7894, 51'h000043cb57df1, 51'h0030e73bcddb8, 51'h11a35beb6fcb8};
        rom[ 10] = {51'h000000002c240, 51'h0000003f56320, 51'h00004488549e9, 51'h00316f8f22de8, 51'h11d4873168b9b};
        rom[ 11] = {51'h000000002c9f1, 51'h0000004006c1a, 51'h0000454760330, 51'h0031f95e7f41a, 51'h12063b88628ce};
        rom[ 12] = {51'h000000002d1b7, 51'h00000040b93d7, 51'h0000460880591, 51'h003284ae0668a, 51'h12387a6e75624};
        rom[ 13] = {51'h000000002d993, 51'h000000416daac, 51'h000046cbbadd4, 51'h00331181e740b, 51'h126b4565e27cf};
        rom[ 14] = {51'h000000002e185, 51'h00000042240f2, 51'h00004791159c7, 51'h00339fde5c604, 51'h129e9df51fdef};
        rom[ 15] = {51'h000000002e98d, 51'h00000042dc6fe, 51'h000048589683b, 51'h00342fc7ac279, 51'h12d285a6e4032};
        rom[ 16] = {51'h000000002f1ab, 51'h0000004396d2a, 51'h000049224390b, 51'h0034c14228e1c, 51'h1306fe0a31b72};
        rom[ 17] = {51'h000000002f9e0, 51'h00000044533d0, 51'h000049ee22d1d, 51'h0035545230e5e, 51'h133c08b264171};
        rom[ 18] = {51'h000000003022c, 51'h0000004511b49, 51'h00004abc3a665, 51'h0035e8fc2eb88, 51'h1371a7373aa9d};
        rom[ 19] = {51'h0000000030a8f, 51'h00000045d23f1, 51'h00004b8c907e6, 51'h00367f44992db, 51'h13a7db34e5a00};
        rom[ 20] = {51'h0000000031309, 51'h0000004694e26, 51'h00004c5f2b5ba, 51'h0037172ff38b6, 51'h13dea64c12343};
        rom[ 21] = {51'h0000000031b9b, 51'h0000004759a43, 51'h00004d3411510, 51'h0037b0c2cdabf, 51'h14160a21f72e3};
        rom[ 22] = {51'h0000000032445, 51'h00000048208a9, 51'h00004e0b48c33, 51'h00384c01c4217, 51'h144e086061894};
        rom[ 23] = {51'h0000000032d07, 51'h00000048e99b6, 51'h00004ee4d828a, 51'h0038e8f18058d, 51'h1486a2b5c13ce};
        rom[ 24] = {51'h00000000335e2, 51'h00000049b4dcb, 51'h00004fc0c609b, 51'h00398796b8bdf, 51'h14bfdad5362a3};
        rom[ 25] = {51'h0000000033ed5, 51'h0000004a8254a, 51'h0000509f19012, 51'h003a27f630dfc, 51'h14f9b2769d2cb};
        rom[ 26] = {51'h00000000347e1, 51'h0000004b52095, 51'h0000517fd7bbf, 51'h003aca14b994f, 51'h15342b569d4f9};
        rom[ 27] = {51'h0000000035106, 51'h0000004c24010, 51'h0000526308f9e, 51'h003b6df73120f, 51'h156f4736b527f};
        rom[ 28] = {51'h0000000035a45, 51'h0000004cf8421, 51'h00005348b38d7, 51'h003c13a283594, 51'h15ab07dd48544};
        rom[ 29] = {51'h000000003639d, 51'h0000004dced2c, 51'h00005430de5c2, 51'h003cbb1ba9cb7, 51'h15e76f15ad215};
        rom[ 30] = {51'h0000000036d10, 51'h0000004ea7b9a, 51'h0000551b905eb, 51'h003d6467abe34, 51'h16247eb03a559};
        rom[ 31] = {51'h000000003769d, 51'h0000004f82fd2, 51'h00005608d0a14, 51'h003e0f8b9f116, 51'h1662388255223};
        rom[ 32] = {51'h0000000038045, 51'h0000005060a3d, 51'h000056f8a643c, 51'h003ebc8ca6f27, 51'h16a09e667f3be};
        rom[ 33] = {51'h0000000038a07, 51'h0000005140b47, 51'h000057eb1879c, 51'h003f6b6ff5768, 51'h16dfb23c651a4};
        rom[ 34] = {51'h00000000393e5, 51'h000000522335b, 51'h000058e02e8b2, 51'h00401c3acb092, 51'h171f75e8ec5f8};
        rom[ 35] = {51'h0000000039dde, 51'h00000053082e6, 51'h000059d7efd3d, 51'h0040cef276b99, 51'h175feb564267e};
        rom[ 36] = {51'h000000003a7f3, 51'h00000053efa55, 51'h00005ad263c48, 51'h0041839c5663c, 51'h17a11473eb019};
        rom[ 37] = {51'h000000003b224, 51'h00000054d9a18, 51'h00005bcf91e27, 51'h00423a3dd6d96, 51'h17e2f336cf4e7};
        rom[ 38] = {51'h000000003bc72, 51'h00000055c629f, 51'h00005ccf81c7f, 51'h0042f2dc740bc, 51'h182589994cce2};
        rom[ 39] = {51'h000000003c6dc, 51'h00000056b545c, 51'h00005dd23b247, 51'h0043ad7db935d, 51'h1868d99b44930};
        rom[ 40] = {51'h000000003d163, 51'h00000057a6fc3, 51'h00005ed7c5bce, 51'h00446a2741070, 51'h18ace5422aa0f};
        rom[ 41] = {51'h000000003dc08, 51'h000000589b546, 51'h00005fe0296bc, 51'h004528deb5cdf, 51'h18f1ae9915774};
        rom[ 42] = {51'h000000003e6ca, 51'h000000599255b, 51'h000060eb6e218, 51'h0045e9a9d1a47, 51'h193737b0cdc5f};
        rom[ 43] = {51'h000000003f1aa, 51'h0000005a8c07a, 51'h000061f99be4d, 51'h0046ac8e5e9b1, 51'h197d829fde4e6};
        rom[ 44] = {51'h000000003fca9, 51'h0000005b8871a, 51'h0000630abad28, 51'h0047719236e61, 51'h19c49182a3f0a};
        rom[ 45] = {51'h00000000407c6, 51'h0000005c879b4, 51'h0000641ed31e3, 51'h004838bb450a0, 51'h1a0c667b5de57};
        rom[ 46] = {51'h0000000041302, 51'h0000005d898c2, 51'h00006535ed126, 51'h0049020f8409a, 51'h1a5503b23e257};
        rom[ 47] = {51'h0000000041e5e, 51'h0000005e8e4c2, 51'h0000665011108, 51'h0049cd94ff935, 51'h1a9e6b5579fdd};
        rom[ 48] = {51'h00000000429d9, 51'h0000005f95e30, 51'h0000676d47918, 51'h004a9b51d4302, 51'h1ae89f995ad3c};
        rom[ 49] = {51'h0000000043574, 51'h00000060a058a, 51'h0000688d9925f, 51'h004b6b4c2f725, 51'h1b33a2b84f161};
        rom[ 50] = {51'h0000000044130, 51'h00000061adb52, 51'h000069b10e762, 51'h004c3d8a50252, 51'h1b7f76f2fb5e6};
        rom[ 51] = {51'h0000000044d0c, 51'h00000062be007, 51'h00006ad7b042c, 51'h004d1212867cb, 51'h1bcc1e904bc1e};
        rom[ 52] = {51'h000000004590a, 51'h00000063d142e, 51'h00006c0187649, 51'h004de8eb34468, 51'h1c199bdd8552b};
        rom[ 53] = {51'h0000000046528, 51'h00000064e7849, 51'h00006d2e9ccd5, 51'h004ec21acd1a9, 51'h1c67f12e57d16};
        rom[ 54] = {51'h0000000047169, 51'h0000006600ce0, 51'h00006e5ef9877, 51'h004f9da7d68cf, 51'h1cb720dcef908};
        rom[ 55] = {51'h0000000047dcc, 51'h000000671d279, 51'h00006f92a6b6b, 51'h00507b98e85ff, 51'h1d072d4a07899};
        rom[ 56] = {51'h0000000048a51, 51'h000000683c99c, 51'h000070c9ad984, 51'h00515bf4acb6c, 51'h1d5818dcfba4a};
        rom[ 57] = {51'h00000000496f9, 51'h000000695f2d5, 51'h0000720417832, 51'h00523ec1e048c, 51'h1da9e603db32a};
        rom[ 58] = {51'h000000004a3c4, 51'h0000006a84ead, 51'h00007341ede85, 51'h0053240752950, 51'h1dfc97337b9b7};
        rom[ 59] = {51'h000000004b0b3, 51'h0000006baddb4, 51'h000074833a532, 51'h00540bcbe6173, 51'h1e502ee78b401};
        rom[ 60] = {51'h000000004bdc7, 51'h0000006cda076, 51'h000075c806697, 51'h0054f616907be, 51'h1ea4afa2a490f};
        rom[ 61] = {51'h000000004cafe, 51'h0000006e09785, 51'h000077105bec3, 51'h0055e2ee5ad69, 51'h1efa1bee615a4};
        rom[ 62] = {51'h000000004d85b, 51'h0000006f3c372, 51'h0000785c44b74, 51'h0056d25a61d76, 51'h1f50765b6e455};
        rom[ 63] = {51'h000000004e5dc, 51'h00000070724d1, 51'h000079abcac23, 51'h0057c461d601f, 51'h1fa7c1819e90f};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
