/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=24 (degree 3); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m24 #(parameter integer WMAN = 24, parameter integer D = 3, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer RW   = 17;
    localparam integer CW   = 39;
    localparam integer ACCW = 41;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {39'h7ffffe6bc4, 39'h00008ea558, 39'h7fc755c613, 39'h1ffffffff6};
        rom[  1] = {39'h7ffffe7ecc, 39'h000089e8e8, 39'h7fc86e566f, 39'h1fc7e2d725};
        rom[  2] = {39'h7ffffe90ac, 39'h000085658c, 39'h7fc97da6df, 39'h1f90d99549};
        rom[  3] = {39'h7ffffea17a, 39'h00008117cc, 39'h7fca842615, 39'h1f5adb3260};
        rom[  4] = {39'h7ffffeb14a, 39'h00007cfc71, 39'h7fcb823c14, 39'h1f25df11bb};
        rom[  5] = {39'h7ffffec02e, 39'h0000791081, 39'h7fcc784aaf, 39'h1ef1dcfb8a};
        rom[  6] = {39'h7ffffece37, 39'h000075513a, 39'h7fcd66adfc, 39'h1ebecd16e9};
        rom[  7] = {39'h7ffffedb74, 39'h000071bc09, 39'h7fce4dbcbb, 39'h1e8ca7e455};
        rom[  8] = {39'h7ffffee7f3, 39'h00006e4e8e, 39'h7fcf2dc8b9, 39'h1e5b66388d};
        rom[  9] = {39'h7ffffef3c2, 39'h00006b068e, 39'h7fd0071f28, 39'h1e2b0137c7};
        rom[ 10] = {39'h7ffffefeed, 39'h000067e1f9, 39'h7fd0da08f1, 39'h1dfb725140};
        rom[ 11] = {39'h7fffff097d, 39'h000064dee1, 39'h7fd1a6cafb, 39'h1dccb33b17};
        rom[ 12] = {39'h7fffff137e, 39'h000061fb78, 39'h7fd26da675, 39'h1d9ebdee71};
        rom[ 13] = {39'h7fffff1cf9, 39'h00005f3610, 39'h7fd32ed90e, 39'h1d718ca3db};
        rom[ 14] = {39'h7fffff25f6, 39'h00005c8d16, 39'h7fd3ea9d39, 39'h1d4519cff3};
        rom[ 15] = {39'h7fffff2e7d, 39'h000059ff12, 39'h7fd4a12a58, 39'h1d19602037};
        rom[ 16] = {39'h7fffff3696, 39'h0000578aa1, 39'h7fd552b4f6, 39'h1cee5a781e};
        rom[ 17] = {39'h7fffff3e48, 39'h0000552e7a, 39'h7fd5ff6ef1, 39'h1cc403ee4b};
        rom[ 18] = {39'h7fffff4598, 39'h000052e966, 39'h7fd6a787a6, 39'h1c9a57c9fe};
        rom[ 19] = {39'h7fffff4c8c, 39'h000050ba41, 39'h7fd74b2c18, 39'h1c715180a3};
        rom[ 20] = {39'h7fffff532b, 39'h00004e9ff9, 39'h7fd7ea8714, 39'h1c48ecb389};
        rom[ 21] = {39'h7fffff5979, 39'h00004c998d, 39'h7fd885c153, 39'h1c21252dc2};
        rom[ 22] = {39'h7fffff5f7b, 39'h00004aa60a, 39'h7fd91d019a, 39'h1bf9f6e21b};
        rom[ 23] = {39'h7fffff6536, 39'h000048c48c, 39'h7fd9b06cd8, 39'h1bd35de93b};
        rom[ 24] = {39'h7fffff6aac, 39'h000046f43c, 39'h7fda402641, 39'h1bad567fd5};
        rom[ 25] = {39'h7fffff6fe3, 39'h000045344f, 39'h7fdacc4f65, 39'h1b87dd04fe};
        rom[ 26] = {39'h7fffff74de, 39'h0000438406, 39'h7fdb55084d, 39'h1b62edf896};
        rom[ 27] = {39'h7fffff799f, 39'h000041e2ac, 39'h7fdbda6f8b, 39'h1b3e85f9c7};
        rom[ 28] = {39'h7fffff7e2b, 39'h0000404f96, 39'h7fdc5ca253, 39'h1b1aa1c59d};
        rom[ 29] = {39'h7fffff8284, 39'h00003eca23, 39'h7fdcdbbc8b, 39'h1af73e35b1};
        rom[ 30] = {39'h7fffff86ad, 39'h00003d51ba, 39'h7fdd57d8e3, 39'h1ad4583ee4};
        rom[ 31] = {39'h7fffff8aa8, 39'h00003be5cb, 39'h7fddd110de, 39'h1ab1ecf02e};
        rom[ 32] = {39'h7fffff8e78, 39'h00003a85cd, 39'h7fde477ce6, 39'h1a8ff9717f};
        rom[ 33] = {39'h7fffff921f, 39'h000039313e, 39'h7fdebb345d, 39'h1a6e7b02aa};
        rom[ 34] = {39'h7fffff959f, 39'h000037e7a3, 39'h7fdf2c4da6, 39'h1a4d6efa64};
        rom[ 35] = {39'h7fffff98fa, 39'h000036a889, 39'h7fdf9ade35, 39'h1a2cd2c54d};
        rom[ 36] = {39'h7fffff9c32, 39'h000035737f, 39'h7fe006fa9c, 39'h1a0ca3e505};
        rom[ 37] = {39'h7fffff9f49, 39'h000034481d, 39'h7fe070b693, 39'h19ecdfef52};
        rom[ 38] = {39'h7fffffa240, 39'h00003325ff, 39'h7fe0d82508, 39'h19cd848d4c};
        rom[ 39] = {39'h7fffffa519, 39'h0000320cc7, 39'h7fe13d5822, 39'h19ae8f7a93};
        rom[ 40] = {39'h7fffffa7d6, 39'h000030fc19, 39'h7fe1a06153, 39'h198ffe8495};
        rom[ 41] = {39'h7fffffaa77, 39'h00002ff3a1, 39'h7fe201515b, 39'h1971cf89d7};
        rom[ 42] = {39'h7fffffacfe, 39'h00002ef30b, 39'h7fe2603852, 39'h195400794a};
        rom[ 43] = {39'h7fffffaf6d, 39'h00002dfa0c, 39'h7fe2bd25b2, 39'h19368f51a6};
        rom[ 44] = {39'h7fffffb1c4, 39'h00002d0857, 39'h7fe318285a, 39'h19197a20d1};
        rom[ 45] = {39'h7fffffb404, 39'h00002c1da7, 39'h7fe3714e9c, 39'h18fcbf0346};
        rom[ 46] = {39'h7fffffb62f, 39'h00002b39b8, 39'h7fe3c8a63c, 39'h18e05c238d};
        rom[ 47] = {39'h7fffffb846, 39'h00002a5c4b, 39'h7fe41e3c7e, 39'h18c44fb9b1};
        rom[ 48] = {39'h7fffffba49, 39'h0000298520, 39'h7fe4721e24, 39'h18a8980abf};
        rom[ 49] = {39'h7fffffbc39, 39'h000028b3fe, 39'h7fe4c4577c, 39'h188d33684b};
        rom[ 50] = {39'h7fffffbe18, 39'h000027e8ad, 39'h7fe514f45f, 39'h1872202fff};
        rom[ 51] = {39'h7fffffbfe5, 39'h00002722f7, 39'h7fe564003a, 39'h18575ccb23};
        rom[ 52] = {39'h7fffffc1a2, 39'h00002662aa, 39'h7fe5b1860f, 39'h183ce7ae39};
        rom[ 53] = {39'h7fffffc350, 39'h000025a793, 39'h7fe5fd907e, 39'h1822bf5894};
        rom[ 54] = {39'h7fffffc4ee, 39'h000024f185, 39'h7fe64829c7, 39'h1808e253f5};
        rom[ 55] = {39'h7fffffc67e, 39'h0000244053, 39'h7fe6915bce, 39'h17ef4f3430};
        rom[ 56] = {39'h7fffffc801, 39'h00002393d1, 39'h7fe6d9301f, 39'h17d60496cf};
        rom[ 57] = {39'h7fffffc976, 39'h000022ebd7, 39'h7fe71faff3, 39'h17bd0122c0};
        rom[ 58] = {39'h7fffffcadf, 39'h000022483d, 39'h7fe764e430, 39'h17a4438800};
        rom[ 59] = {39'h7fffffcc3c, 39'h000021a8dd, 39'h7fe7a8d573, 39'h178bca7f4c};
        rom[ 60] = {39'h7fffffcd8d, 39'h0000210d94, 39'h7fe7eb8c0c, 39'h177394c9d9};
        rom[ 61] = {39'h7fffffced4, 39'h000020763f, 39'h7fe82d1006, 39'h175ba13107};
        rom[ 62] = {39'h7fffffd00f, 39'h00001fe2bc, 39'h7fe86d6925, 39'h1743ee861f};
        rom[ 63] = {39'h7fffffd140, 39'h00001f52eb, 39'h7fe8ac9ef0, 39'h172c7ba20f};
        rom[ 64] = {39'h7fffffd268, 39'h00001ec6af, 39'h7fe8eab8ad, 39'h171547652b};
        rom[ 65] = {39'h7fffffd386, 39'h00001e3de8, 39'h7fe927bd66, 39'h16fe50b6ee};
        rom[ 66] = {39'h7fffffd49b, 39'h00001db87c, 39'h7fe963b3eb, 39'h16e79685c2};
        rom[ 67] = {39'h7fffffd5a7, 39'h00001d364f, 39'h7fe99ea2d5, 39'h16d117c6c4};
        rom[ 68] = {39'h7fffffd6ab, 39'h00001cb746, 39'h7fe9d89088, 39'h16bad3758e};
        rom[ 69] = {39'h7fffffd7a7, 39'h00001c3b49, 39'h7fea118335, 39'h16a4c89408};
        rom[ 70] = {39'h7fffffd89b, 39'h00001bc240, 39'h7fea4980db, 39'h168ef62a2e};
        rom[ 71] = {39'h7fffffd988, 39'h00001b4c13, 39'h7fea808f4a, 39'h16795b45e4};
        rom[ 72] = {39'h7fffffda6d, 39'h00001ad8ac, 39'h7feab6b424, 39'h1663f6fac9};
        rom[ 73] = {39'h7fffffdb4c, 39'h00001a67f5, 39'h7feaebf4de, 39'h164ec86205};
        rom[ 74] = {39'h7fffffdc24, 39'h000019f9da, 39'h7feb2056c6, 39'h1639ce9a24};
        rom[ 75] = {39'h7fffffdcf5, 39'h0000198e46, 39'h7feb53deff, 39'h162508c6e8};
        rom[ 76] = {39'h7fffffddc1, 39'h0000192527, 39'h7feb869285, 39'h1610761123};
        rom[ 77] = {39'h7fffffde86, 39'h000018be6a, 39'h7febb8762e, 39'h15fc15a690};
        rom[ 78] = {39'h7fffffdf46, 39'h00001859fd, 39'h7febe98eac, 39'h15e7e6b9ae};
        rom[ 79] = {39'h7fffffe000, 39'h000017f7cf, 39'h7fec19e08f, 39'h15d3e8819d};
        rom[ 80] = {39'h7fffffe0b4, 39'h00001797cf, 39'h7fec497043, 39'h15c01a39fb};
        rom[ 81] = {39'h7fffffe164, 39'h00001739ee, 39'h7fec784215, 39'h15ac7b22c2};
        rom[ 82] = {39'h7fffffe20f, 39'h000016de1b, 39'h7feca65a32, 39'h15990a8029};
        rom[ 83] = {39'h7fffffe2b4, 39'h0000168448, 39'h7fecd3bca9, 39'h1585c79a85};
        rom[ 84] = {39'h7fffffe356, 39'h0000162c66, 39'h7fed006d6a, 39'h1572b1be2a};
        rom[ 85] = {39'h7fffffe3f2, 39'h000015d668, 39'h7fed2c704b, 39'h155fc83b50};
        rom[ 86] = {39'h7fffffe48b, 39'h0000158240, 39'h7fed57c906, 39'h154d0a65f6};
        rom[ 87] = {39'h7fffffe51f, 39'h0000152fe2, 39'h7fed827b3a, 39'h153a7795c7};
        rom[ 88] = {39'h7fffffe5af, 39'h000014df40, 39'h7fedac8a6c, 39'h15280f2601};
        rom[ 89] = {39'h7fffffe63b, 39'h000014904e, 39'h7fedd5fa0a, 39'h1515d0755c};
        rom[ 90] = {39'h7fffffe6c4, 39'h0000144301, 39'h7fedfecd6a, 39'h1503bae5f0};
        rom[ 91] = {39'h7fffffe749, 39'h000013f74e, 39'h7fee2707c8, 39'h14f1cddd1e};
        rom[ 92] = {39'h7fffffe7ca, 39'h000013ad29, 39'h7fee4eac4f, 39'h14e008c37d};
        rom[ 93] = {39'h7fffffe848, 39'h0000136488, 39'h7fee75be0f, 39'h14ce6b04bf};
        rom[ 94] = {39'h7fffffe8c3, 39'h0000131d61, 39'h7fee9c4007, 39'h14bcf40f9e};
        rom[ 95] = {39'h7fffffe93a, 39'h000012d7aa, 39'h7feec23520, 39'h14aba355c9};
        rom[ 96] = {39'h7fffffe9ae, 39'h0000129359, 39'h7feee7a030, 39'h149a784bcd};
        rom[ 97] = {39'h7fffffea20, 39'h0000125065, 39'h7fef0c83fb, 39'h1489726904};
        rom[ 98] = {39'h7fffffea8e, 39'h0000120ec4, 39'h7fef30e331, 39'h1478912783};
        rom[ 99] = {39'h7fffffeafa, 39'h000011ce6f, 39'h7fef54c071, 39'h1467d40407};
        rom[100] = {39'h7fffffeb63, 39'h0000118f5d, 39'h7fef781e4a, 39'h14573a7de1};
        rom[101] = {39'h7fffffebc9, 39'h0000115185, 39'h7fef9aff38, 39'h1446c416ea};
        rom[102] = {39'h7fffffec2d, 39'h00001114e0, 39'h7fefbd65aa, 39'h1436705371};
        rom[103] = {39'h7fffffec8e, 39'h000010d967, 39'h7fefdf53fd, 39'h14263eba28};
        rom[104] = {39'h7fffffeced, 39'h0000109f10, 39'h7ff000cc7f, 39'h14162ed419};
        rom[105] = {39'h7fffffed49, 39'h00001065d6, 39'h7ff021d170, 39'h1406402c94};
        rom[106] = {39'h7fffffeda3, 39'h0000102db2, 39'h7ff0426503, 39'h13f6725124};
        rom[107] = {39'h7fffffedfb, 39'h00000ff69c, 39'h7ff062895b, 39'h13e6c4d17c};
        rom[108] = {39'h7fffffee51, 39'h00000fc08e, 39'h7ff0824090, 39'h13d7373f6f};
        rom[109] = {39'h7fffffeea5, 39'h00000f8b82, 39'h7ff0a18ca9, 39'h13c7c92edd};
        rom[110] = {39'h7fffffeef7, 39'h00000f5771, 39'h7ff0c06fa6, 39'h13b87a35ad};
        rom[111] = {39'h7fffffef47, 39'h00000f2456, 39'h7ff0deeb76, 39'h13a949ebbb};
        rom[112] = {39'h7fffffef95, 39'h00000ef22a, 39'h7ff0fd01fe, 39'h139a37eacc};
        rom[113] = {39'h7fffffefe1, 39'h00000ec0e8, 39'h7ff11ab519, 39'h138b43ce89};
        rom[114] = {39'h7ffffff02b, 39'h00000e908b, 39'h7ff1380695, 39'h137c6d346b};
        rom[115] = {39'h7ffffff074, 39'h00000e610c, 39'h7ff154f834, 39'h136db3bbb5};
        rom[116] = {39'h7ffffff0bb, 39'h00000e3268, 39'h7ff1718bb1, 39'h135f170569};
        rom[117] = {39'h7ffffff100, 39'h00000e0498, 39'h7ff18dc2b9, 39'h135096b43c};
        rom[118] = {39'h7ffffff144, 39'h00000dd799, 39'h7ff1a99ef2, 39'h1342326c8e};
        rom[119] = {39'h7ffffff186, 39'h00000dab64, 39'h7ff1c521f7, 39'h1333e9d45c};
        rom[120] = {39'h7ffffff1c7, 39'h00000d7ff7, 39'h7ff1e04d5a, 39'h1325bc933e};
        rom[121] = {39'h7ffffff206, 39'h00000d554b, 39'h7ff1fb22a3, 39'h1317aa5255};
        rom[122] = {39'h7ffffff244, 39'h00000d2b5d, 39'h7ff215a352, 39'h1309b2bc49};
        rom[123] = {39'h7ffffff280, 39'h00000d0228, 39'h7ff22fd0de, 39'h12fbd57d3b};
        rom[124] = {39'h7ffffff2bb, 39'h00000cd9a9, 39'h7ff249acb7, 39'h12ee1242c2};
        rom[125] = {39'h7ffffff2f5, 39'h00000cb1db, 39'h7ff2633842, 39'h12e068bbdd};
        rom[126] = {39'h7ffffff32e, 39'h00000c8aba, 39'h7ff27c74de, 39'h12d2d898ef};
        rom[127] = {39'h7ffffff365, 39'h00000c6443, 39'h7ff29563e3, 39'h12c5618bb5};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
