/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=11 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + 1 (final multiply); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m11_d2 #(parameter integer WMAN = 11, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 4;
    localparam integer D    = 2;
    localparam integer RW   = 6;
    localparam integer CW   = 26;
    localparam integer ACCW = 28;
    localparam integer NSEG = 16;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    (* rom_style = "logic", syn_romstyle = "logic" *)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {26'h0003975, 26'h3fa3c31, 26'h0b8aa26};
        rom[1] = {26'h0003250, 26'h3faaeed, 26'h0b31fa6};
        rom[2] = {26'h0002c5d, 26'h3fb1367, 26'h0ae00c3};
        rom[3] = {26'h000275e, 26'h3fb6c04, 26'h0a9406d};
        rom[4] = {26'h0002321, 26'h3fbbaa8, 26'h0a4d3b8};
        rom[5] = {26'h0001f83, 26'h3fc00d7, 26'h0a0b16e};
        rom[6] = {26'h0001c67, 26'h3fc3fce, 26'h09cd1b7};
        rom[7] = {26'h00019b5, 26'h3fc788e, 26'h0992dde};
        rom[8] = {26'h000175c, 26'h3fcabed, 26'h095c014};
        rom[9] = {26'h000154e, 26'h3fcda9c, 26'h0928352};
        rom[10] = {26'h000137f, 26'h3fd0530, 26'h08f7332};
        rom[11] = {26'h00011e5, 26'h3fd2c27, 26'h08c8bd8};
        rom[12] = {26'h000107a, 26'h3fd4feb, 26'h089c9dc};
        rom[13] = {26'h0000f35, 26'h3fd70da, 26'h0872a3b};
        rom[14] = {26'h0000e13, 26'h3fd8f40, 26'h084aa44};
        rom[15] = {26'h0000d0e, 26'h3fdab63, 26'h0824791};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
