/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=32 (degree 4); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m32 #(parameter integer WMAN = 32, parameter integer D = 4, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 4) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer RW   = 25;
    localparam integer CW   = 47;
    localparam integer ACCW = 49;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {47'h00000004e916, 47'h7ffffe61f056, 47'h00008eab7d11, 47'h7fc755c4d837, 47'h1ffffffffff8};
        rom[  1] = {47'h000000049c1a, 47'h7ffffe7592cc, 47'h000089eeac87, 47'h7fc86e55479a, 47'h1fc7e2d72e9d};
        rom[  2] = {47'h0000000454e0, 47'h7ffffe88017e, 47'h0000856af746, 47'h7fc97da5c95f, 47'h1f90d9955196};
        rom[  3] = {47'h0000000412e6, 47'h7ffffe99536e, 47'h0000811ce462, 47'h7fca84250fd2, 47'h1f5adb32688d};
        rom[  4] = {47'h00000003d5b8, 47'h7ffffea99d99, 47'h00007d013cf2, 47'h7fcb823b1e67, 47'h1f25df11c309};
        rom[  5] = {47'h000000039ceb, 47'h7ffffeb8f327, 47'h000079150649, 47'h7fcc7849c7e2, 47'h1ef1dcfb91a6};
        rom[  6] = {47'h000000036823, 47'h7ffffec765a1, 47'h000075557cc3, 47'h7fcd66ad2187, 47'h1ebecd16efd9};
        rom[  7] = {47'h000000033708, 47'h7ffffed50512, 47'h000071c00f1d, 47'h7fce4dbbec6b, 47'h1e8ca7e45bdc};
        rom[  8] = {47'h00000003094f, 47'h7ffffee1e030, 47'h00006e525a39, 47'h7fcf2dc7f5ee, 47'h1e5b66389375};
        rom[  9] = {47'h00000002deb0, 47'h7ffffeee047d, 47'h00006b0a254f, 47'h7fd0071e701e, 47'h1e2b0137cd12};
        rom[ 10] = {47'h00000002b6ec, 47'h7ffffef97e61, 47'h000067e55e75, 47'h7fd0da0842e5, 47'h1dfb725145a3};
        rom[ 11] = {47'h0000000291ca, 47'h7fffff045947, 47'h000064e21784, 47'h7fd1a6ca5696, 47'h1dccb33b1c42};
        rom[ 12] = {47'h000000026f15, 47'h7fffff0e9fb4, 47'h000061fe833b, 47'h7fd26da5d892, 47'h1d9ebdee7566};
        rom[ 13] = {47'h000000024e9d, 47'h7fffff185b5b, 47'h00005f38f2ae, 47'h7fd32ed87a6e, 47'h1d718ca3dff6};
        rom[ 14] = {47'h000000023036, 47'h7fffff21952e, 47'h00005c8fd2e8, 47'h7fd3ea9cac43, 47'h1d4519cff703};
        rom[ 15] = {47'h0000000213b9, 47'h7fffff2a5572, 47'h00005a01aacd, 47'h7fd4a129d26c, 47'h1d1960203b8c};
        rom[ 16] = {47'h00000001f902, 47'h7fffff32a3cf, 47'h0000578d1922, 47'h7fd552b4773b, 47'h1cee5a7821eb};
        rom[ 17] = {47'h00000001dfef, 47'h7fffff3a8759, 47'h00005530d2c5, 47'h7fd5ff6e78ee, 47'h1cc403ee4f14};
        rom[ 18] = {47'h00000001c862, 47'h7fffff4206a0, 47'h000052eba10e, 47'h7fd6a787343a, 47'h1c9a57ca020b};
        rom[ 19] = {47'h00000001b23f, 47'h7fffff4927bb, 47'h000050bc604e, 47'h7fd74b2babb7, 47'h1c715180a650};
        rom[ 20] = {47'h000000019d6c, 47'h7fffff4ff050, 47'h00004ea1fe73, 47'h7fd7ea86ac78, 47'h1c48ecb38c4a};
        rom[ 21] = {47'h0000000189d1, 47'h7fffff5665a0, 47'h00004c9b79c6, 47'h7fd885c0eff5, 47'h1c21252dc4ec};
        rom[ 22] = {47'h00000001775a, 47'h7fffff5c8c8d, 47'h00004aa7dfc7, 47'h7fd91d013ba1, 47'h1bf9f6e21e15};
        rom[ 23] = {47'h0000000165f2, 47'h7fffff6269a3, 47'h000048c64c19, 47'h7fd9b06c7e39, 47'h1bd35de93d60};
        rom[ 24] = {47'h000000015587, 47'h7fffff68011f, 47'h000046f5e78d, 47'h7fda4025eb18, 47'h1bad567fd743};
        rom[ 25] = {47'h000000014608, 47'h7fffff6d56f3, 47'h00004535e73b, 47'h7fdacc4f13a7, 47'h1b87dd05008b};
        rom[ 26] = {47'h000000013765, 47'h7fffff726ecf, 47'h000043858baf, 47'h7fdb5507ff11, 47'h1b62edf89865};
        rom[ 27] = {47'h00000001298f, 47'h7fffff774c23, 47'h000041e42025, 47'h7fdbda6f406c, 47'h1b3e85f9c956};
        rom[ 28] = {47'h000000011c7b, 47'h7fffff7bf227, 47'h00004050f9d4, 47'h7fdc5ca20b59, 47'h1b1aa1c59f96};
        rom[ 29] = {47'h00000001101a, 47'h7fffff8063db, 47'h00003ecb774b, 47'h7fdcdbbc475e, 47'h1af73e35b363};
        rom[ 30] = {47'h000000010463, 47'h7fffff84a412, 47'h00003d52ffd1, 47'h7fdd57d8a1ec, 47'h1ad4583ee5ff};
        rom[ 31] = {47'h00000000f949, 47'h7fffff88b56c, 47'h00003be702dd, 47'h7fddd1109f4b, 47'h1ab1ecf0302e};
        rom[ 32] = {47'h00000000eec4, 47'h7fffff8c9a63, 47'h00003a86f78d, 47'h7fde477caa6c, 47'h1a8ff9718109};
        rom[ 33] = {47'h00000000e4c9, 47'h7fffff905547, 47'h000039325c2d, 47'h7fdebb3423bb, 47'h1a6e7b02ac27};
        rom[ 34] = {47'h00000000db52, 47'h7fffff93e845, 47'h000037e8b5c5, 47'h7fdf2c4d6f0e, 47'h1a4d6efa661e};
        rom[ 35] = {47'h00000000d255, 47'h7fffff975567, 47'h000036a98faf, 47'h7fdf9ade00ac, 47'h1a2cd2c54e86};
        rom[ 36] = {47'h00000000c9cc, 47'h7fffff9a9e98, 47'h000035747b36, 47'h7fe006fa6991, 47'h1a0ca3e5069c};
        rom[ 37] = {47'h00000000c1af, 47'h7fffff9dc5a5, 47'h000034490f3a, 47'h7fe070b662f1, 47'h19ecdfef53c4};
        rom[ 38] = {47'h00000000b9f8, 47'h7fffffa0cc42, 47'h00003326e7da, 47'h7fe0d824d90e, 47'h19cd848d4d41};
        rom[ 39] = {47'h00000000b2a2, 47'h7fffffa3b406, 47'h0000320da625, 47'h7fe13d57f566, 47'h19ae8f7a9461};
        rom[ 40] = {47'h00000000aba6, 47'h7fffffa67e72, 47'h000030fcefd3, 47'h7fe1a0612847, 47'h198ffe849693};
        rom[ 41] = {47'h00000000a500, 47'h7fffffa92cf2, 47'h00002ff46efc, 47'h7fe2015131dc, 47'h1971cf89d8c4};
        rom[ 42] = {47'h000000009eab, 47'h7fffffabc0db, 47'h00002ef3d1d9, 47'h7fe260382aaa, 47'h195400794b8d};
        rom[ 43] = {47'h0000000098a2, 47'h7fffffae3b71, 47'h00002dfaca8b, 47'h7fe2bd258b99, 47'h19368f51a795};
        rom[ 44] = {47'h0000000092e1, 47'h7fffffb09de3, 47'h00002d090edd, 47'h7fe318283588, 47'h19197a20d1cb};
        rom[ 45] = {47'h000000008d64, 47'h7fffffb2e953, 47'h00002c1e5816, 47'h7fe3714e7870, 47'h18fcbf0346f4};
        rom[ 46] = {47'h000000008827, 47'h7fffffb51ecf, 47'h00002b3a62c2, 47'h7fe3c8a61a22, 47'h18e05c238e2e};
        rom[ 47] = {47'h000000008327, 47'h7fffffb73f59, 47'h00002a5cee89, 47'h7fe41e3c5cae, 47'h18c44fb9b207};
        rom[ 48] = {47'h000000007e61, 47'h7fffffb94be4, 47'h00002985be00, 47'h7fe4721e0465, 47'h18a8980abfbd};
        rom[ 49] = {47'h0000000079d1, 47'h7fffffbb4556, 47'h000028b49683, 47'h7fe4c4575d92, 47'h188d33684c65};
        rom[ 50] = {47'h000000007575, 47'h7fffffbd2c8a, 47'h000027e9400d, 47'h7fe514f441dc, 47'h1872202fffa0};
        rom[ 51] = {47'h000000007149, 47'h7fffffbf024d, 47'h000027238518, 47'h7fe564001d66, 47'h18575ccb2387};
        rom[ 52] = {47'h000000006d4c, 47'h7fffffc0c764, 47'h000026633279, 47'h7fe5b185f3a2, 47'h183ce7ae399b};
        rom[ 53] = {47'h00000000697b, 47'h7fffffc27c88, 47'h000025a8173e, 47'h7fe5fd9063f1, 47'h1822bf589466};
        rom[ 54] = {47'h0000000065d4, 47'h7fffffc42269, 47'h000024f20496, 47'h7fe64829adf1, 47'h1808e253f597};
        rom[ 55] = {47'h000000006255, 47'h7fffffc5b9ae, 47'h00002440cdb3, 47'h7fe6915bb5aa, 47'h17ef4f34305b};
        rom[ 56] = {47'h000000005efb, 47'h7fffffc742f6, 47'h0000239447af, 47'h7fe6d930076e, 47'h17d60496cfbb};
        rom[ 57] = {47'h000000005bc5, 47'h7fffffc8bed7, 47'h000022ec4973, 47'h7fe71fafdb9a, 47'h17bd0122c0c8};
        rom[ 58] = {47'h0000000058b1, 47'h7fffffca2de1, 47'h00002248aba1, 47'h7fe764e41a19, 47'h17a443880071};
        rom[ 59] = {47'h0000000055be, 47'h7fffffcb909c, 47'h000021a94880, 47'h7fe7a8d55dc3, 47'h178bca7f4cbd};
        rom[ 60] = {47'h0000000052e9, 47'h7fffffcce789, 47'h0000210dfbe3, 47'h7fe7eb8bf78d, 47'h177394c9d959};
        rom[ 61] = {47'h000000005031, 47'h7fffffce3323, 47'h00002076a319, 47'h7fe82d0ff18f, 47'h175ba1310739};
        rom[ 62] = {47'h000000004d96, 47'h7fffffcf73e0, 47'h00001fe31cd9, 47'h7fe86d6911ef, 47'h1743ee861f35};
        rom[ 63] = {47'h000000004b15, 47'h7fffffd0aa2f, 47'h00001f534934, 47'h7fe8ac9edd99, 47'h172c7ba20f73};
        rom[ 64] = {47'h0000000048ad, 47'h7fffffd1d67b, 47'h00001ec7097e, 47'h7fe8eab89ae0, 47'h171547652b83};
        rom[ 65] = {47'h00000000465e, 47'h7fffffd2f928, 47'h00001e3e4044, 47'h7fe927bd5400, 47'h16fe50b6ef08};
        rom[ 66] = {47'h000000004425, 47'h7fffffd41298, 47'h00001db8d13e, 47'h7fe963b3d978, 47'h16e79685c2d2};
        rom[ 67] = {47'h000000004203, 47'h7fffffd52327, 47'h00001d36a13c, 47'h7fe99ea2c452, 47'h16d117c6c445};
        rom[ 68] = {47'h000000003ff5, 47'h7fffffd62b2c, 47'h00001cb7961f, 47'h7fe9d890784b, 47'h16bad3758efd};
        rom[ 69] = {47'h000000003dfc, 47'h7fffffd72afc, 47'h00001c3b96c6, 47'h7fea118325e3, 47'h16a4c8940889};
        rom[ 70] = {47'h000000003c16, 47'h7fffffd822e6, 47'h00001bc28b0a, 47'h7fea4980cc53, 47'h168ef62a2e2a};
        rom[ 71] = {47'h000000003a42, 47'h7fffffd91337, 47'h00001b4c5bab, 47'h7fea808f3b6e, 47'h16795b45e482};
        rom[ 72] = {47'h00000000387f, 47'h7fffffd9fc38, 47'h00001ad8f24c, 47'h7feab6b4156e, 47'h1663f6fac913};
        rom[ 73] = {47'h0000000036cd, 47'h7fffffdade2e, 47'h00001a683964, 47'h7feaebf4d0a7, 47'h164ec8620583};
        rom[ 74] = {47'h00000000352b, 47'h7fffffdbb95d, 47'h000019fa1c3a, 47'h7feb2056b92e, 47'h1639ce9a2489};
        rom[ 75] = {47'h000000003398, 47'h7fffffdc8e04, 47'h0000198e86d5, 47'h7feb53def264, 47'h162508c6e878};
        rom[ 76] = {47'h000000003214, 47'h7fffffdd5c61, 47'h0000192565f9, 47'h7feb8692787b, 47'h16107611234d};
        rom[ 77] = {47'h00000000309e, 47'h7fffffde24ad, 47'h000018bea71f, 47'h7febb87621df, 47'h15fc15a69035};
        rom[ 78] = {47'h000000002f35, 47'h7fffffdee720, 47'h0000185a3867, 47'h7febe98ea09a, 47'h15e7e6b9ae7e};
        rom[ 79] = {47'h000000002dd9, 47'h7fffffdfa3f1, 47'h000017f8089a, 47'h7fec19e0839e, 47'h15d3e8819dd4};
        rom[ 80] = {47'h000000002c89, 47'h7fffffe05b52, 47'h00001798071b, 47'h7fec49703809, 47'h15c01a39fbd6};
        rom[ 81] = {47'h000000002b46, 47'h7fffffe10d74, 47'h0000173a23e3, 47'h7fec78420a59, 47'h15ac7b22c2d5};
        rom[ 82] = {47'h000000002a0d, 47'h7fffffe1ba87, 47'h000016de4f7e, 47'h7feca65a2791, 47'h15990a8029ca};
        rom[ 83] = {47'h0000000028df, 47'h7fffffe262b7, 47'h000016847b01, 47'h7fecd3bc9e54, 47'h1585c79a856c};
        rom[ 84] = {47'h0000000027bc, 47'h7fffffe30630, 47'h0000162c9804, 47'h7fed006d5ff6, 47'h1572b1be2a57};
        rom[ 85] = {47'h0000000026a2, 47'h7fffffe3a51b, 47'h000015d698a0, 47'h7fed2c70417a, 47'h155fc83b503b};
        rom[ 86] = {47'h000000002592, 47'h7fffffe43fa0, 47'h000015826f68, 47'h7fed57c8fc93, 47'h154d0a65f612};
        rom[ 87] = {47'h00000000248b, 47'h7fffffe4d5e5, 47'h000015300f62, 47'h7fed827b308a, 47'h153a7795c73f};
        rom[ 88] = {47'h00000000238d, 47'h7fffffe56810, 47'h000014df6c05, 47'h7fedac8a632a, 47'h15280f26019b};
        rom[ 89] = {47'h000000002298, 47'h7fffffe5f642, 47'h000014907937, 47'h7fedd5fa0198, 47'h1515d0755c66};
        rom[ 90] = {47'h0000000021aa, 47'h7fffffe6809e, 47'h000014432b3f, 47'h7fedfecd6129, 47'h1503bae5f00e};
        rom[ 91] = {47'h0000000020c5, 47'h7fffffe70744, 47'h000013f776ce, 47'h7fee2707c02a, 47'h14f1cddd1ebe};
        rom[ 92] = {47'h000000001fe6, 47'h7fffffe78a54, 47'h000013ad50f1, 47'h7fee4eac46a6, 47'h14e008c37dbf};
        rom[ 93] = {47'h000000001f0f, 47'h7fffffe809ec, 47'h00001364af11, 47'h7fee75be071e, 47'h14ce6b04bf90};
        rom[ 94] = {47'h000000001e3f, 47'h7fffffe88627, 47'h0000131d86ef, 47'h7fee9c3fff40, 47'h14bcf40f9eb9};
        rom[ 95] = {47'h000000001d76, 47'h7fffffe8ff23, 47'h000012d7cea3, 47'h7feec2351891, 47'h14aba355c94f};
        rom[ 96] = {47'h000000001cb3, 47'h7fffffe974f9, 47'h000012937c93, 47'h7feee7a02918, 47'h149a784bcd1b};
        rom[ 97] = {47'h000000001bf6, 47'h7fffffe9e7c4, 47'h000012508778, 47'h7fef0c83f3f7, 47'h148972690473};
        rom[ 98] = {47'h000000001b40, 47'h7fffffea579c, 47'h0000120ee652, 47'h7fef30e32a0d, 47'h14789127839d};
        rom[ 99] = {47'h000000001a8f, 47'h7fffffeac499, 47'h000011ce906d, 47'h7fef54c06a84, 47'h1467d40406d7};
        rom[100] = {47'h0000000019e3, 47'h7fffffeb2ed1, 47'h0000118f7d58, 47'h7fef781e4361, 47'h14573a7de0ef};
        rom[101] = {47'h00000000193d, 47'h7fffffeb965b, 47'h00001151a4ea, 47'h7fef9aff3211, 47'h1446c416ea5d};
        rom[102] = {47'h00000000189b, 47'h7fffffebfb4c, 47'h00001114ff35, 47'h7fefbd65a3e9, 47'h1436705370ef};
        rom[103] = {47'h0000000017ff, 47'h7fffffec5db9, 47'h000010d9848e, 47'h7fefdf53f6a5, 47'h14263eba27f5};
        rom[104] = {47'h000000001768, 47'h7fffffecbdb4, 47'h0000109f2d84, 47'h7ff000cc78e7, 47'h14162ed418df};
        rom[105] = {47'h0000000016d5, 47'h7fffffed1b52, 47'h00001065f2e1, 47'h7ff021d16aab, 47'h1406402c9466};
        rom[106] = {47'h000000001646, 47'h7fffffed76a4, 47'h0000102dcda7, 47'h7ff04264fdb5, 47'h13f672512419};
        rom[107] = {47'h0000000015bc, 47'h7fffffedcfbc, 47'h00000ff6b70d, 47'h7ff062895607, 47'h13e6c4d17c5f};
        rom[108] = {47'h000000001536, 47'h7fffffee26ab, 47'h00000fc0a87f, 47'h7ff082408a44, 47'h13d7373f6eeb};
        rom[109] = {47'h0000000014b4, 47'h7fffffee7b81, 47'h00000f8b9b9a, 47'h7ff0a18ca41a, 47'h13c7c92edd8e};
        rom[110] = {47'h000000001435, 47'h7fffffeece4f, 47'h00000f578a2d, 47'h7ff0c06fa0a1, 47'h13b87a35ad77};
        rom[111] = {47'h0000000013bb, 47'h7fffffef1f24, 47'h00000f246e35, 47'h7ff0deeb70bf, 47'h13a949ebbaca};
        rom[112] = {47'h000000001344, 47'h7fffffef6e0e, 47'h00000ef241dc, 47'h7ff0fd01f97f, 47'h139a37eacc9c};
        rom[113] = {47'h0000000012d0, 47'h7fffffefbb1b, 47'h00000ec0ff76, 47'h7ff11ab5146e, 47'h138b43ce8948};
        rom[114] = {47'h000000001260, 47'h7ffffff0065a, 47'h00000e90a185, 47'h7ff138068fec, 47'h137c6d346b18};
        rom[115] = {47'h0000000011f3, 47'h7ffffff04fd8, 47'h00000e6122af, 47'h7ff154f82f83, 47'h136db3bbb543};
        rom[116] = {47'h000000001189, 47'h7ffffff097a1, 47'h00000e327dc5, 47'h7ff1718bac33, 47'h135f1705693f};
        rom[117] = {47'h000000001121, 47'h7ffffff0ddc2, 47'h00000e04adba, 47'h7ff18dc2b4c1, 47'h135096b43c60};
        rom[118] = {47'h0000000010bd, 47'h7ffffff12247, 47'h00000dd7adaa, 47'h7ff1a99eee02, 47'h1342326c8dbf};
        rom[119] = {47'h00000000105c, 47'h7ffffff1653c, 47'h00000dab78d1, 47'h7ff1c521f321, 47'h1333e9d45c70};
        rom[120] = {47'h000000000ffd, 47'h7ffffff1a6ab, 47'h00000d800a8f, 47'h7ff1e04d55e7, 47'h1325bc933dfa};
        rom[121] = {47'h000000000fa1, 47'h7ffffff1e6a0, 47'h00000d555e63, 47'h7ff1fb229efb, 47'h1317aa525517};
        rom[122] = {47'h000000000f48, 47'h7ffffff22525, 47'h00000d2b6fef, 47'h7ff215a34e26, 47'h1309b2bc48b6};
        rom[123] = {47'h000000000ef1, 47'h7ffffff26244, 47'h00000d023af1, 47'h7ff22fd0da91, 47'h12fbd57d3b38};
        rom[124] = {47'h000000000e9c, 47'h7ffffff29e07, 47'h00000cd9bb47, 47'h7ff249acb302, 47'h12ee1242c1ef};
        rom[125] = {47'h000000000e4a, 47'h7ffffff2d877, 47'h00000cb1eceb, 47'h7ff263383e16, 47'h12e068bbdcdb};
        rom[126] = {47'h000000000dfa, 47'h7ffffff3119e, 47'h00000c8acbf2, 47'h7ff27c74da78, 47'h12d2d898ee9d};
        rom[127] = {47'h000000000dac, 47'h7ffffff34985, 47'h00000c64548f, 47'h7ff29563df1d, 47'h12c5618bb49e};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
