/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=16 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + (2+STAGE_PRODUCT) (final multiply: registered inputs + split); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m16_d2 #(parameter integer WMAN = 16, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 6;
    localparam integer D    = 2;
    localparam integer RW   = 9;
    localparam integer CW   = 31;
    localparam integer ACCW = 33;
    localparam integer NSEG = 64;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {31'h000078fa, 31'h7fd1d63d, 31'h1715475a};
        rom[1] = {31'h000074db, 31'h7fd2c82a, 31'h16e7967b};
        rom[2] = {31'h000070ef, 31'h7fd3b1da, 31'h16bad36b};
        rom[3] = {31'h00006d32, 31'h7fd493b2, 31'h168ef620};
        rom[4] = {31'h000069a2, 31'h7fd56e10, 31'h1663f6f1};
        rom[5] = {31'h0000663b, 31'h7fd6414e, 31'h1639ce91};
        rom[6] = {31'h000062fb, 31'h7fd70dbe, 31'h16107609};
        rom[7] = {31'h00005fe1, 31'h7fd7d3b0, 31'h15e7e6b2};
        rom[8] = {31'h00005ce9, 31'h7fd8936d, 31'h15c01a32};
        rom[9] = {31'h00005a12, 31'h7fd94d3a, 31'h15990a79};
        rom[10] = {31'h0000575b, 31'h7fda015b, 31'h1572b1b7};
        rom[11] = {31'h000054c1, 31'h7fdab00d, 31'h154d0a5f};
        rom[12] = {31'h00005242, 31'h7fdb598b, 31'h15280f1f};
        rom[13] = {31'h00004fde, 31'h7fdbfe0c, 31'h1503bae0};
        rom[14] = {31'h00004d93, 31'h7fdc9dc5, 31'h14e008bd};
        rom[15] = {31'h00004b60, 31'h7fdd38e8, 31'h14bcf40a};
        rom[16] = {31'h00004942, 31'h7fddcfa4, 31'h149a7846};
        rom[17] = {31'h0000473b, 31'h7fde6226, 31'h14789122};
        rom[18] = {31'h00004547, 31'h7fdef099, 31'h14573a79};
        rom[19] = {31'h00004366, 31'h7fdf7b24, 31'h1436704f};
        rom[20] = {31'h00004198, 31'h7fe001ee, 31'h14162ecf};
        rom[21] = {31'h00003fdb, 31'h7fe0851c, 31'h13f6724d};
        rom[22] = {31'h00003e2f, 31'h7fe104d0, 31'h13d7373b};
        rom[23] = {31'h00003c92, 31'h7fe1812c, 31'h13b87a31};
        rom[24] = {31'h00003b04, 31'h7fe1fa4e, 31'h139a37e7};
        rom[25] = {31'h00003985, 31'h7fe27054, 31'h137c6d30};
        rom[26] = {31'h00003813, 31'h7fe2e35c, 31'h135f1702};
        rom[27] = {31'h000036ae, 31'h7fe35380, 31'h13423269};
        rom[28] = {31'h00003556, 31'h7fe3c0da, 31'h1325bc90};
        rom[29] = {31'h00003409, 31'h7fe42b84, 31'h1309b2b9};
        rom[30] = {31'h000032c8, 31'h7fe49395, 31'h12ee123f};
        rom[31] = {31'h00003191, 31'h7fe4f923, 31'h12d2d896};
        rom[32] = {31'h00003065, 31'h7fe55c45, 31'h12b80344};
        rom[33] = {31'h00002f43, 31'h7fe5bd0e, 31'h129d8fe8};
        rom[34] = {31'h00002e2b, 31'h7fe61b94, 31'h12837c34};
        rom[35] = {31'h00002d1b, 31'h7fe677e8, 31'h1269c5ed};
        rom[36] = {31'h00002c15, 31'h7fe6d21e, 31'h12506aeb};
        rom[37] = {31'h00002b16, 31'h7fe72a46, 31'h12376918};
        rom[38] = {31'h00002a20, 31'h7fe78071, 31'h121ebe6f};
        rom[39] = {31'h00002931, 31'h7fe7d4af, 31'h120668fa};
        rom[40] = {31'h0000284a, 31'h7fe82710, 31'h11ee66d6};
        rom[41] = {31'h0000276a, 31'h7fe877a3, 31'h11d6b62b};
        rom[42] = {31'h00002690, 31'h7fe8c675, 31'h11bf5533};
        rom[43] = {31'h000025bd, 31'h7fe91395, 31'h11a84234};
        rom[44] = {31'h000024f1, 31'h7fe95f0f, 31'h11917b82};
        rom[45] = {31'h0000242a, 31'h7fe9a8ef, 31'h117aff7d};
        rom[46] = {31'h0000236a, 31'h7fe9f143, 31'h1164cc93};
        rom[47] = {31'h000022af, 31'h7fea3816, 31'h114ee13c};
        rom[48] = {31'h000021f9, 31'h7fea7d72, 31'h11393bfc};
        rom[49] = {31'h00002148, 31'h7feac163, 31'h1123db64};
        rom[50] = {31'h0000209d, 31'h7feb03f4, 31'h110ebe0c};
        rom[51] = {31'h00001ff6, 31'h7feb452d, 31'h10f9e299};
        rom[52] = {31'h00001f54, 31'h7feb8519, 31'h10e547b9};
        rom[53] = {31'h00001eb7, 31'h7febc3c1, 31'h10d0ec23};
        rom[54] = {31'h00001e1e, 31'h7fec012e, 31'h10bcce98};
        rom[55] = {31'h00001d89, 31'h7fec3d69, 31'h10a8ede1};
        rom[56] = {31'h00001cf8, 31'h7fec787a, 31'h109548cf};
        rom[57] = {31'h00001c6b, 31'h7fecb268, 31'h1081de3e};
        rom[58] = {31'h00001be1, 31'h7feceb3d, 31'h106ead0e};
        rom[59] = {31'h00001b5b, 31'h7fed22ff, 31'h105bb429};
        rom[60] = {31'h00001ad9, 31'h7fed59b5, 31'h1048f280};
        rom[61] = {31'h00001a5a, 31'h7fed8f67, 31'h1036670c};
        rom[62] = {31'h000019df, 31'h7fedc41b, 31'h102410cb};
        rom[63] = {31'h00001966, 31'h7fedf7d8, 31'h1011eec3};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
