/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=8 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + 1 (final multiply); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m8_d2 #(parameter integer WMAN = 8, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 3;
    localparam integer D    = 2;
    localparam integer RW   = 4;
    localparam integer CW   = 23;
    localparam integer ACCW = 25;
    localparam integer NSEG = 8;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    (* rom_style = "logic", syn_romstyle = "logic" *)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {23'h001ae4, 23'h7e9015, 23'h171533};
        rom[1] = {23'h0014e6, 23'h7ec593, 23'h15c00c};
        rom[2] = {23'h0010a4, 23'h7eef2f, 23'h149a6e};
        rom[3] = {23'h000d83, 23'h7f1057, 23'h139a30};
        rom[4] = {23'h000b28, 23'h7f2b47, 23'h12b7fe};
        rom[5] = {23'h000957, 23'h7f4187, 23'h11ee62};
        rom[6] = {23'h0007ea, 23'h7f5429, 23'h113939};
        rom[7] = {23'h0006c7, 23'h7f63f5, 23'h109546};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
