/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=53 (degree 6); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m53 #(parameter integer WMAN = 53, parameter integer D = 6, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 6) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 5;
    localparam integer CF   = 65;
    localparam integer RW   = 60;
    localparam integer CW   = 68;
    localparam integer ACCW = 70;
    localparam integer NSEG = 32;
    localparam integer HSBW = WSB;

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {68'h0000000000051a379, 68'h0000000005760c961, 68'h00000004ecaae92a0, 68'h0000038d611adbf1e, 68'h0001ebfbdff82d1eb, 68'h00b17217f7d1cf6d5, 68'h20000000000000002};
        rom[  1] = {68'h00000000000536d1d, 68'h000000000594a996b, 68'h000000050845cc2ab, 68'h000003a14ac90ab89, 68'h0001f6c1c633409f6, 68'h00b554cba92b3e641, 68'h20b361a62b0ae875f};
        rom[  2] = {68'h000000000005540c6, 68'h0000000005b3f232f, 68'h00000005247b6dce0, 68'h000003b5a4172393e, 68'h000201c4104e01902, 68'h00b94d47530aa9532, 68'h216ab0d9f3121ec55};
        rom[  3] = {68'h00000000000571eac, 68'h0000000005d3ea2cd, 68'h00000005414f31869, 68'h000003ca6f76e1a99, 68'h00020d0410cf63788, 68'h00bd5c050e7d81af8, 68'h222603a024b6a14a0};
        rom[  4] = {68'h00000000000590709, 68'h0000000005f4955b6, 68'h000000055ec48dc58, 68'h000003dfaf67b3c3c, 68'h0002188321a805c93, 68'h00c18181a101f217a, 68'h22e57078faa2f5b9e};
        rom[  5] = {68'h000000000005afa19, 68'h000000000615f7ab2, 68'h000000057cdf0c653, 68'h000003f56677091f8, 68'h00022442a45bc1949, 68'h00c5be3c8b839d775, 68'h23a90e62d17354f03};
        rom[  6] = {68'h000000000005cf815, 68'h000000000638151ec, 68'h000000059ba24b15c, 68'h0000040b97409fea0, 68'h00023044022c20369, 68'h00ca12b819ac61b42, 68'h2470f4dceac470cdb};
        rom[  7] = {68'h000000000005f013d, 68'h00000000065af1cf2, 68'h00000005bb11fbcca, 68'h00000422446ed5760, 68'h00023c88ac43c0062, 68'h00ce7f79718af4d79, 68'h253d3bea3fbdc2587};
        rom[  8] = {68'h000000000006115cd, 68'h00000000067e91ec7, 68'h00000005db31e535c, 68'h0000043970baf8327, 68'h000249121be2ac462, 68'h00d30508a3913dfa7, 68'h260dfc14636e2a5c0};
        rom[  9] = {68'h00000000000633608, 68'h0000000006a2f9be2, 68'h00000005fc05e3282, 68'h000004511eed9b6cf, 68'h000255e1d28bada95, 68'h00d7a3f0baec55c00, 68'h26e34e6e7553954e5};
        rom[ 10] = {68'h0000000000065622d, 68'h0000000006c82da39, 68'h000000061d91e71c1, 68'h0000046951deece98, 68'h000262f95a3298db9, 68'h00dc5cbfce3824f2f, 68'h27bd4c982468446b9};
        rom[ 11] = {68'h00000000000679a7f, 68'h0000000006ee3214e, 68'h000000063fd9f8a4b, 68'h000004820c770c5a4, 68'h0002705a456ba09f3, 68'h00e130071090a2d92, 68'h289c10c0c3125a065};
        rom[ 12] = {68'h0000000000069df43, 68'h0000000007150ba31, 68'h0000000662e235ebe, 68'h0000049b51ae64c12, 68'h00027e062f9bb12e3, 68'h00e61e5ae302c010c, 68'h297fb5aa6c544e3ab};
        rom[ 13] = {68'h000000000006c30bf, 68'h00000000073cbef8b, 68'h0000000686aed430c, 68'h000004b5248e07c76, 68'h00028bfebd29daae0, 68'h00eb2852e65f16486, 68'h2a6856ad3a9f03be4};
        rom[ 14] = {68'h000000000006e8f3a, 68'h00000000076550dab, 68'h00000006ab4420492, 68'h000004cf88300b141, 68'h00029a459bb1d0a5f, 68'h00f04e8a0d7080e09, 68'h2b560fba90a852b1c};
        rom[ 15] = {68'h0000000000070fafd, 68'h00000000078ec6288, 68'h00000006d0a67f25a, 68'h000004ea7fbfe7aea, 68'h0002a8dc823784886, 68'h00f5919eaf98ce87f, 68'h2c48fd6074ab09641};
        rom[ 16] = {68'h00000000000737452, 68'h0000000007b923dcf, 68'h00000006f6da6e591, 68'h000005060e7adb77d, 68'h0002b7c5315be181f, 68'h00faf2329bd5c823f, 68'h2d413cccfe7799214};
        rom[ 17] = {68'h0000000000075fb84, 68'h0000000007e46f0ee, 68'h000000071de484a26, 68'h0000052237b04cc4d, 68'h0002c7017392afe41, 68'h010070eb2c30d5e29, 68'h2e3eebd1d8bee7ba7};
        rom[ 18] = {68'h000000000007890e3, 68'h000000000810acf18, 68'h0000000745c97279a, 68'h0000053efec230295, 68'h0002d6931d59a6a47, 68'h01060e71599b981e7, 68'h2f4228e7d6030dafe};
        rom[ 19] = {68'h000000000007b34be, 68'h00000000083de2d56, 68'h000000076e8e02a07, 68'h0000055c6725707b5, 68'h0002e67c0d70b18e0, 68'h010bcb71d03bd6d66, 68'h304b1332999c2515d};
        rom[ 20] = {68'h000000000007de765, 68'h00000000086c16289, 68'h0000000798371ab51, 68'h0000057a7462591f1, 68'h0002f6be2d1372e65, 68'h0111a89d042937d79, 68'h3159ca845541b6b78};
        rom[ 21] = {68'h0000000000080a92b, 68'h00000000089b4c77f, 68'h00000007c2c9bbc96, 68'h000005992a1502a5e, 68'h0003075b703407700, 68'h0117a6a7469f39662, 68'h326e6f619b8bc9e8d};
        rom[ 22] = {68'h00000000000837a66, 68'h0000000008cb8b6f2, 68'h00000007ee4b02fc3, 68'h000005b88bedc1ce6, 68'h00031855d5b713d89, 68'h011dc648dba5fd249, 68'h3389230547e120393};
        rom[ 23] = {68'h00000000000865b6c, 68'h0000000008fcd8d9c, 68'h000000081ac02a171, 68'h000005d89db198f30, 68'h000329af67b122c89, 68'h0124083e10347d430, 68'h34aa07647c4ab916c};
        rom[ 24] = {68'h00000000000894c96, 68'h00000000092f3aa3d, 68'h00000008482e882eb, 68'h000005f9633aabf40, 68'h00033b6a3ba55af5b, 68'h012a6d4750ced4924, 68'h35d13f32b5a75abd4};
        rom[ 25] = {68'h000000000008c4e3d, 68'h000000000962b6dab, 68'h00000008769b92471, 68'h0000061ae078b6aba, 68'h00034d8872c594bdf, 68'h0130f62940a350ff5, 68'h36feede5f6bc8dd58};
        rom[ 26] = {68'h000000000008f60bf, 68'h00000000099753ad8, 68'h00000008a60cdbfb9, 68'h0000063d197185fa0, 68'h0003600c3a33d6ffd, 68'h0137a3acd12917368, 68'h383337bb0aa538448};
        rom[ 27] = {68'h00000000000928479, 68'h0000000009cd176e2, 68'h00000008d688182a2, 68'h0000066012417377c, 68'h000372f7cb45430c8, 68'h013e769f5a432dbd2, 68'h396e41b9df20d22a4};
        rom[ 28] = {68'h0000000000095b9ce, 68'h000000000a040891c, 68'h00000009081319a29, 68'h00000683cf1be3de1, 68'h0003864d6bc677bdf, 68'h01456fd2b2ead5b98, 68'h3ab031b9f7490e4bf};
        rom[ 29] = {68'h0000000000099011e, 68'h000000000a3c2db1f, 68'h000000093ab3d3d9e, 68'h000006a8544bc832f, 68'h00039a0f6e4173e81, 68'h014c901d4a6427df3, 68'h3bf92e66f736bd731};
        rom[ 30] = {68'h000000000009c5acf, 68'h000000000a758d8d1, 68'h000000096e705ba10, 68'h000006cda63421ca4, 68'h0003ae4032450089d, 68'h0153d85a41fffc93f, 68'h3d495f454921b30b6};
        rom[ 31] = {68'h000000000009fc748, 68'h000000000ab02f079, 68'h00000009a34ee7dfb, 68'h000006f3c950892a2, 68'h0003c2e224adab523, 68'h015b4969876e3758d, 68'h3ea0ecb6dc8a80cee};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
