/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=27 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + (2+STAGE_PRODUCT) (final multiply: registered inputs + split); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m27_d3 #(parameter integer WMAN = 27, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 7;
    localparam integer D    = 3;
    localparam integer RW   = 19;
    localparam integer CW   = 42;
    localparam integer ACCW = 44;
    localparam integer NSEG = 128;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {42'h3fffffe933f, 42'h00000f63575, 42'h3ff4755c568, 42'h0b8aa3b2958};
        rom[1] = {42'h3fffffe9c2f, 42'h00000f1ef42, 42'h3ff493deb2d, 42'h0b7f285b774};
        rom[2] = {42'h3fffffea4d7, 42'h00000edc3e0, 42'h3ff4b1d9f54, 42'h0b73cb42e12};
        rom[3] = {42'h3fffffead3a, 42'h00000e9b275, 42'h3ff4cf516a7, 42'h0b688be361e};
        rom[4] = {42'h3fffffeb559, 42'h00000e5ba31, 42'h3ff4ec48442, 42'h0b5d69bac74};
        rom[5] = {42'h3fffffebd38, 42'h00000e1da4a, 42'h3ff508c19ab, 42'h0b52644a040};
        rom[6] = {42'h3fffffec4d9, 42'h00000de11ff, 42'h3ff524c06db, 42'h0b477b1516e};
        rom[7] = {42'h3fffffecc3e, 42'h00000da6097, 42'h3ff54047a50, 42'h0b3cada2f20};
        rom[8] = {42'h3fffffed36a, 42'h00000d6c55d, 42'h3ff55b5a11d, 42'h0b31fb7d645};
        rom[9] = {42'h3fffffeda5e, 42'h00000d33fa7, 42'h3ff575fa6f3, 42'h0b276431029};
        rom[10] = {42'h3fffffee11e, 42'h00000cfcece, 42'h3ff5902b634, 42'h0b1ce74d121};
        rom[11] = {42'h3fffffee7aa, 42'h00000cc7232, 42'h3ff5a9ef7fa, 42'h0b128463741};
        rom[12] = {42'h3fffffeee04, 42'h00000c9293b, 42'h3ff5c349428, 42'h0b083b08917};
        rom[13] = {42'h3fffffef42f, 42'h00000c5f353, 42'h3ff5dc3b170, 42'h0afe0ad347f};
        rom[14] = {42'h3fffffefa2c, 42'h00000c2cfeb, 42'h3ff5f4c7563, 42'h0af3f35cd71};
        rom[15] = {42'h3fffffefffd, 42'h00000bfbe7a, 42'h3ff60cf0479, 42'h0ae9f440cec};
        rom[16] = {42'h3ffffff05a3, 42'h00000bcbe7b, 42'h3ff624b8219, 42'h0ae00d1cfdc};
        rom[17] = {42'h3ffffff0b20, 42'h00000b9cf6e, 42'h3ff63c210a9, 42'h0ad63d91614};
        rom[18] = {42'h3ffffff1075, 42'h00000b6f0d7, 42'h3ff6532d191, 42'h0acc854014c};
        rom[19] = {42'h3ffffff15a4, 42'h00000b4223f, 42'h3ff669de544, 42'h0ac2e3cd429};
        rom[20] = {42'h3ffffff1aad, 42'h00000b16333, 42'h3ff68036b4f, 42'h0ab958df150};
        rom[21] = {42'h3ffffff1f93, 42'h00000aeb343, 42'h3ff69638259, 42'h0aafe41da7f};
        rom[22] = {42'h3ffffff2456, 42'h00000ac1203, 42'h3ff6abe4830, 42'h0aa68532fae};
        rom[23] = {42'h3ffffff28f8, 42'h00000a97f0d, 42'h3ff6c13d9cd, 42'h0a9d3bcae38};
        rom[24] = {42'h3ffffff2d79, 42'h00000a6f9fd, 42'h3ff6d645360, 42'h0a94079300b};
        rom[25] = {42'h3ffffff31dc, 42'h00000a48270, 42'h3ff6eafd052, 42'h0a8ae83aae1};
        rom[26] = {42'h3ffffff3620, 42'h00000a21809, 42'h3ff6ff66b4d, 42'h0a81dd72f7e};
        rom[27] = {42'h3ffffff3a47, 42'h000009fba6f, 42'h3ff71383e43, 42'h0a78e6ee8f4};
        rom[28] = {42'h3ffffff3e51, 42'h000009d6948, 42'h3ff72756275, 42'h0a700461bec};
        rom[29] = {42'h3ffffff4240, 42'h000009b2442, 42'h3ff73adf077, 42'h0a6735825fb};
        rom[30] = {42'h3ffffff4615, 42'h0000098eb09, 42'h3ff74e20037, 42'h0a5e7a07cf4};
        rom[31] = {42'h3ffffff49d1, 42'h0000096bd4e, 42'h3ff7611a900, 42'h0a55d1aae49};
        rom[32] = {42'h3ffffff4d73, 42'h00000949ac5, 42'h3ff773d0182, 42'h0a4d3c25e67};
        rom[33] = {42'h3ffffff50fe, 42'h00000928324, 42'h3ff78641fd8, 42'h0a44b934822};
        rom[34] = {42'h3ffffff5471, 42'h00000907622, 42'h3ff79871987, 42'h0a3c4893c1b};
        rom[35] = {42'h3ffffff57ce, 42'h000008e737a, 42'h3ff7aa60389, 42'h0a33ea02035};
        rom[36] = {42'h3ffffff5b15, 42'h000008c7ae8, 42'h3ff7bc0f24f, 42'h0a2b9d3ef06};
        rom[37] = {42'h3ffffff5e47, 42'h000008a8c2b, 42'h3ff7cd7f9c3, 42'h0a23620b751};
        rom[38] = {42'h3ffffff6164, 42'h0000088a703, 42'h3ff7deb2d51, 42'h0a1b3829b86};
        rom[39] = {42'h3ffffff646e, 42'h0000086cb34, 42'h3ff7efa9fe5, 42'h0a131f5d13e};
        rom[40] = {42'h3ffffff6764, 42'h0000084f882, 42'h3ff800663f6, 42'h0a0b176a0c6};
        rom[41] = {42'h3ffffff6a48, 42'h00000832eb3, 42'h3ff810e8b83, 42'h0a0320164a2};
        rom[42] = {42'h3ffffff6d1a, 42'h00000816d8e, 42'h3ff8213281a, 42'h09fb392891f};
        rom[43] = {42'h3ffffff6fda, 42'h000007fb4df, 42'h3ff83144adc, 42'h09f36268be2};
        rom[44] = {42'h3ffffff7289, 42'h000007e0470, 42'h3ff8412047d, 42'h09eb9b9fb76};
        rom[45] = {42'h3ffffff7527, 42'h000007c5c0e, 42'h3ff850c654a, 42'h09e3e4976eb};
        rom[46] = {42'h3ffffff77b6, 42'h000007abb87, 42'h3ff86037d2d, 42'h09dc3d1ad6a};
        rom[47] = {42'h3ffffff7a35, 42'h000007922ac, 42'h3ff86f75bad, 42'h09d4a4f5dd5};
        rom[48] = {42'h3ffffff7ca5, 42'h0000077914e, 42'h3ff87e80ff3, 42'h09cd1bf5664};
        rom[49] = {42'h3ffffff7f06, 42'h00000760740, 42'h3ff88d5a8c9, 42'h09c5a1e7449};
        rom[50] = {42'h3ffffff8159, 42'h00000748454, 42'h3ff89c034a4, 42'h09be369a358};
        rom[51] = {42'h3ffffff839e, 42'h00000730862, 42'h3ff8aa7c1a0, 42'h09b6d9ddda9};
        rom[52] = {42'h3ffffff85d6, 42'h0000071933f, 42'h3ff8b8c5d85, 42'h09af8b82b49};
        rom[53] = {42'h3ffffff8800, 42'h000007024c2, 42'h3ff8c6e15c8, 42'h09a84b5a1e2};
        rom[54] = {42'h3ffffff8a1e, 42'h000006ebcc6, 42'h3ff8d4cf792, 42'h09a1193646d};
        rom[55] = {42'h3ffffff8c30, 42'h000006d5b23, 42'h3ff8e290fba, 42'h0999f4ea2e2};
        rom[56] = {42'h3ffffff8e35, 42'h000006bffb5, 42'h3ff8f026acf, 42'h0992de499ef};
        rom[57] = {42'h3ffffff902f, 42'h000006aaa57, 42'h3ff8fd91517, 42'h098bd5292a8};
        rom[58] = {42'h3ffffff921e, 42'h00000695ae7, 42'h3ff90ad1a90, 42'h0984d95e245};
        rom[59] = {42'h3ffffff9401, 42'h00000681142, 42'h3ff917e86f2, 42'h097deabe9d9};
        rom[60] = {42'h3ffffff95da, 42'h0000066cd48, 42'h3ff924d65b5, 42'h0977092160f};
        rom[61] = {42'h3ffffff97a8, 42'h00000658ed8, 42'h3ff9319c20d, 42'h0970345dee6};
        rom[62] = {42'h3ffffff996d, 42'h000006455d4, 42'h3ff93e3a6f0, 42'h09696c4c774};
        rom[63] = {42'h3ffffff9b27, 42'h0000063221c, 42'h3ff94ab1f14, 42'h0962b0c5da4};
        rom[64] = {42'h3ffffff9cd8, 42'h0000061f393, 42'h3ff957034f7, 42'h095c01a39fb};
        rom[65] = {42'h3ffffff9e7f, 42'h0000060ca1c, 42'h3ff9632f2d7, 42'h09555ebff5c};
        rom[66] = {42'h3ffffffa01d, 42'h000005fa59a, 42'h3ff96f362bf, 42'h094ec7f5ace};
        rom[67] = {42'h3ffffffa1b3, 42'h000005e85f4, 42'h3ff97b18e7e, 42'h09483d20345};
        rom[68] = {42'h3ffffffa33f, 42'h000005d6b0e, 42'h3ff986d7fb0, 42'h0941be1b96a};
        rom[69] = {42'h3ffffffa4c4, 42'h000005c54ce, 42'h3ff99273fba, 42'h093b4ac4767};
        rom[70] = {42'h3ffffffa640, 42'h000005b431a, 42'h3ff99ded7d0, 42'h0934e2f80b2};
        rom[71] = {42'h3ffffffa7b4, 42'h000005a35db, 42'h3ff9a9450f2, 42'h092e86941db};
        rom[72] = {42'h3ffffffa920, 42'h00000592cf9, 42'h3ff9b47b3f2, 42'h0928357705d};
        rom[73] = {42'h3ffffffaa85, 42'h0000058285b, 42'h3ff9bf90970, 42'h0921ef7fa67};
        rom[74] = {42'h3ffffffabe2, 42'h000005727ec, 42'h3ff9ca859e1, 42'h091bb48d6b8};
        rom[75] = {42'h3ffffffad39, 42'h00000562b95, 42'h3ff9d55ad8b, 42'h09158480468};
        rom[76] = {42'h3ffffffae88, 42'h00000553340, 42'h3ff9e010c88, 42'h090f5f38ac0};
        rom[77] = {42'h3ffffffafd0, 42'h00000543ed9, 42'h3ff9eaa7ec9, 42'h09094497911};
        rom[78] = {42'h3ffffffb112, 42'h00000534e4b, 42'h3ff9f520c14, 42'h0903347e683};
        rom[79] = {42'h3ffffffb24d, 42'h00000526182, 42'h3ff9ff7bc07, 42'h08fd2ecf1f4};
        rom[80] = {42'h3ffffffb382, 42'h0000051786a, 42'h3ffa09b9618, 42'h08f7336c1c9};
        rom[81] = {42'h3ffffffb4b0, 42'h000005092f1, 42'h3ffa13da198, 42'h08f142383cd};
        rom[82] = {42'h3ffffffb5d9, 42'h000004fb104, 42'h3ffa1dde5b0, 42'h08eb5b16d06};
        rom[83] = {42'h3ffffffb6fc, 42'h000004ed290, 42'h3ffa27c6967, 42'h08e57deb993};
        rom[84] = {42'h3ffffffb819, 42'h000004df785, 42'h3ffa319339e, 42'h08dfaa9ac86};
        rom[85] = {42'h3ffffffb930, 42'h000004d1fd0, 42'h3ffa3b44b14, 42'h08d9e108fc1};
        rom[86] = {42'h3ffffffba42, 42'h000004c4b62, 42'h3ffa44db667, 42'h08d4211b3d6};
        rom[87] = {42'h3ffffffbb4f, 42'h000004b7a29, 42'h3ffa4e57c12, 42'h08ce6ab6fe1};
        rom[88] = {42'h3ffffffbc56, 42'h000004aac16, 42'h3ffa57ba271, 42'h08c8bdc216b};
        rom[89] = {42'h3ffffffbd58, 42'h0000049e119, 42'h3ffa6102fbe, 42'h08c31a22c47};
        rom[90] = {42'h3ffffffbe55, 42'h00000491922, 42'h3ffa6a32a18, 42'h08bd7fbfa77};
        rom[91] = {42'h3ffffffbf4e, 42'h00000485424, 42'h3ffa734977c, 42'h08b7ee7fc06};
        rom[92] = {42'h3ffffffc042, 42'h0000047920f, 42'h3ffa7c47dcc, 42'h08b2664a6f4};
        rom[93] = {42'h3ffffffc131, 42'h0000046d2d5, 42'h3ffa852e2cc, 42'h08ace707711};
        rom[94] = {42'h3ffffffc21b, 42'h00000461668, 42'h3ffa8dfcc25, 42'h08a7709ede3};
        rom[95] = {42'h3ffffffc301, 42'h00000455cbb, 42'h3ffa96b3f63, 42'h08a202f928b};
        rom[96] = {42'h3ffffffc3e3, 42'h0000044a5c0, 42'h3ffa9f541f9, 42'h089c9dff1ab};
        rom[97] = {42'h3ffffffc4c1, 42'h0000043f16b, 42'h3ffaa7dd93f, 42'h08974199d47};
        rom[98] = {42'h3ffffffc59a, 42'h00000433fae, 42'h3ffab050a72, 42'h0891edb2cb2};
        rom[99] = {42'h3ffffffc670, 42'h0000042907f, 42'h3ffab8adab9, 42'h088ca233c6d};
        rom[100] = {42'h3ffffffc741, 42'h0000041e3cf, 42'h3ffac0f4f20, 42'h08875f06e14};
        rom[101] = {42'h3ffffffc80f, 42'h00000413995, 42'h3ffac926c9d, 42'h08822416845};
        rom[102] = {42'h3ffffffc8d9, 42'h000004091c3, 42'h3ffad14380d, 42'h087cf14d686};
        rom[103] = {42'h3ffffffc99f, 42'h000003fec4f, 42'h3ffad94b637, 42'h0877c69692f};
        rom[104] = {42'h3ffffffca62, 42'h000003f492e, 42'h3ffae13ebcc, 42'h0872a3dd554};
        rom[105] = {42'h3ffffffcb21, 42'h000003ea855, 42'h3ffae91dd67, 42'h086d890d4b1};
        rom[106] = {42'h3ffffffcbdd, 42'h000003e09ba, 42'h3ffaf0e8f8d, 42'h0868761258e};
        rom[107] = {42'h3ffffffcc95, 42'h000003d6d52, 42'h3ffaf8a06b0, 42'h08636ad8ab2};
        rom[108] = {42'h3ffffffcd4b, 42'h000003cd313, 42'h3ffb004472b, 42'h085e674cb4a};
        rom[109] = {42'h3ffffffcdfc, 42'h000003c3af4, 42'h3ffb07d5547, 42'h08596b5b2d2};
        rom[110] = {42'h3ffffffceab, 42'h000003ba4ea, 42'h3ffb0f5353a, 42'h085476f110a};
        rom[111] = {42'h3ffffffcf57, 42'h000003b10ec, 42'h3ffb16beb24, 42'h084f89fb9d9};
        rom[112] = {42'h3ffffffd000, 42'h000003a7ef1, 42'h3ffb1e17b16, 42'h084aa468540};
        rom[113] = {42'h3ffffffd0a5, 42'h0000039eef1, 42'h3ffb255e90c, 42'h0845c624f47};
        rom[114] = {42'h3ffffffd148, 42'h000003960e1, 42'h3ffb2c938f2, 42'h0840ef1f7e9};
        rom[115] = {42'h3ffffffd1e8, 42'h0000038d4ba, 42'h3ffb33b6ea0, 42'h083c1f46304};
        rom[116] = {42'h3ffffffd285, 42'h00000384a73, 42'h3ffb3ac8de0, 42'h08375687846};
        rom[117] = {42'h3ffffffd320, 42'h0000037c204, 42'h3ffb41c9a6a, 42'h083294d231f};
        rom[118] = {42'h3ffffffd3b8, 42'h00000373b64, 42'h3ffb48b97e5, 42'h082dda152ad};
        rom[119] = {42'h3ffffffd44d, 42'h0000036b68d, 42'h3ffb4f989e8, 42'h0829263f9af};
        rom[120] = {42'h3ffffffd4e0, 42'h00000363375, 42'h3ffb56673fb, 42'h08247940e70};
        rom[121] = {42'h3ffffffd570, 42'h0000035b215, 42'h3ffb5d25997, 42'h081fd308ac0};
        rom[122] = {42'h3ffffffd5fe, 42'h00000353267, 42'h3ffb63d3e24, 42'h081b3386bdd};
        rom[123] = {42'h3ffffffd68a, 42'h0000034b462, 42'h3ffb6a724fd, 42'h08169aab266};
        rom[124] = {42'h3ffffffd713, 42'h000003437ff, 42'h3ffb710116f, 42'h0812086624e};
        rom[125] = {42'h3ffffffd79a, 42'h0000033bd38, 42'h3ffb77806b7, 42'h080d7ca82cf};
        rom[126] = {42'h3ffffffd81e, 42'h00000334406, 42'h3ffb7df0805, 42'h0808f761e58};
        rom[127] = {42'h3ffffffd8a1, 42'h0000032cc61, 42'h3ffb845187c, 42'h08047884281};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
