/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=53): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m53 #(parameter integer MODE = 0, parameter integer UNROLL100 = 100, parameter integer WSB = 1) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 89:0] x0,
    input  wire signed [ 89:0] y0,
    input  wire signed [ 89:0] z0,
    output wire                busy,
    output wire                done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 89:0] xn,
    output wire signed [ 89:0] yn,
    output wire signed [ 89:0] zn,
    output wire        [ 90:0] const2pi    // round(2*pi * 2**XF), CWB = XF + 3 bits
);
    localparam integer N    = 32;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 90;
    localparam integer WZ   = 90;
    localparam integer XF   = 88;   // x/y fractional scale
    localparam integer ZF   = 87;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 91;
    localparam signed [WX-1:0] KINV = 90'sd187935680555264234290519122;   // round(1/gain * 2**XF)

    assign const2pi = 91'd1944551666501805353363452692;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        90'd11468322278445317,   // atan(2^-31)/2pi
        90'd22936644556890635,   // atan(2^-30)/2pi
        90'd45873289113781269,   // atan(2^-29)/2pi
        90'd91746578227562538,   // atan(2^-28)/2pi
        90'd183493156455125073,   // atan(2^-27)/2pi
        90'd366986312910250126,   // atan(2^-26)/2pi
        90'd733972625820500089,   // atan(2^-25)/2pi
        90'd1467945251640998875,   // atan(2^-24)/2pi
        90'd2935890503281987319,   // atan(2^-23)/2pi
        90'd5871781006563891196,   // atan(2^-22)/2pi
        90'd11743562013127114847,   // atan(2^-21)/2pi
        90'd23487124026248889340,   // atan(2^-20)/2pi
        90'd46974248052455055851,   // atan(2^-19)/2pi
        90'd93948496104568329064,   // atan(2^-18)/2pi
        90'd187896992206402397026,   // atan(2^-17)/2pi
        90'd375793984390930705238,   // atan(2^-16)/2pi
        90'd751587968606868700050,   // atan(2^-15)/2pi
        90'd1503175935813795719631,   // atan(2^-14)/2pi
        90'd3006351860428058089382,   // atan(2^-13)/2pi
        90'd6012703631259852383675,   // atan(2^-12)/2pi
        90'd12025406545749690532984,   // atan(2^-11)/2pi
        90'd24050807357342343232029,   // atan(2^-10)/2pi
        90'd48101568841526816840208,   // atan(2^-9)/2pi
        90'd96202770700940500420797,   // atan(2^-8)/2pi
        90'd192402605645765968748931,   // atan(2^-7)/2pi
        90'd384781728467339219987296,   // atan(2^-6)/2pi
        90'd769375697461617340665418,   // atan(2^-5)/2pi
        90'd1537252609958984946836992,   // atan(2^-4)/2pi
        90'd3062619103773773612960043,   // atan(2^-3)/2pi
        90'd6033342982675023321342458,   // atan(2^-2)/2pi
        90'd11418729339503494323455099,   // atan(2^-1)/2pi
        90'd19342813113834066795298816   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(.N(N), .UNROLL100(UNROLL100), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
