/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=24 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m24 #(parameter integer WMAN = 24, parameter integer D = 3, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [SBW-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [SBW-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 5;
    localparam integer CF   = 36;
    localparam integer RW   = 31;
    localparam integer CW   = 39;
    localparam integer ACCW = 41;
    localparam integer NSEG = 32;
    localparam integer HSBW = SBW;

    (* rom_style = "block", syn_romstyle = "EBR" *)  // The table is large, map it to a block ROM (EBR)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {39'h000001cba5, 39'h0000f5fad6, 39'h0058b90c9b, 39'h0ffffffffb};
        rom[  1] = {39'h000001d5b5, 39'h0000fb5db8, 39'h005aaa6677, 39'h1059b0d310};
        rom[  2] = {39'h000001dffe, 39'h000100decb, 39'h005ca6a44f, 39'h10b5586cf4};
        rom[  3] = {39'h000001ea81, 39'h0001067eb9, 39'h005eae0331, 39'h111301d00d};
        rom[  4] = {39'h000001f53f, 39'h00010c3e2f, 39'h0060c0c17e, 39'h1172b83c78};
        rom[  5] = {39'h0000020039, 39'h0001121ddd, 39'h0062df1ef7, 39'h11d4873163};
        rom[  6] = {39'h0000020b70, 39'h0001181e79, 39'h0065095cc2, 39'h12387a6e70};
        rom[  7] = {39'h00000216e6, 39'h00011e40ba, 39'h00673fbd72, 39'h129e9df51a};
        rom[  8] = {39'h000002229d, 39'h000124855e, 39'h006982850f, 39'h1306fe0a2c};
        rom[  9] = {39'h0000022e95, 39'h00012aed24, 39'h006bd1f91f, 39'h1371a73735};
        rom[ 10] = {39'h0000023ad0, 39'h00013178d3, 39'h006e2e60ac, 39'h13dea64c0c};
        rom[ 11] = {39'h0000024750, 39'h0001382933, 39'h0070980452, 39'h144e08605b};
        rom[ 12] = {39'h0000025416, 39'h00013eff12, 39'h00730f2e40, 39'h14bfdad530};
        rom[ 13] = {39'h0000026123, 39'h000145fb42, 39'h0075942a46, 39'h15342b5697};
        rom[ 14] = {39'h0000026e7a, 39'h00014d1e9a, 39'h00782745de, 39'h15ab07dd42};
        rom[ 15] = {39'h0000027c1b, 39'h00015469f6, 39'h007ac8d034, 39'h16247eb033};
        rom[ 16] = {39'h0000028a09, 39'h00015bde36, 39'h007d791a2f, 39'h16a09e6678};
        rom[ 17] = {39'h0000029845, 39'h0001637c3e, 39'h008038767c, 39'h171f75e8e5};
        rom[ 18] = {39'h000002a6d0, 39'h00016b44fa, 39'h0083073998, 39'h17a11473e4};
        rom[ 19] = {39'h000002b5ae, 39'h0001733958, 39'h0085e5b9d8, 39'h1825899945};
        rom[ 20] = {39'h000002c4de, 39'h00017b5a4e, 39'h0088d44f77, 39'h18ace54223};
        rom[ 21] = {39'h000002d464, 39'h000183a8d5, 39'h008bd3549e, 39'h193737b0c6};
        rom[ 22] = {39'h000002e440, 39'h00018c25ec, 39'h008ee3256e, 39'h19c491829c};
        rom[ 23] = {39'h000002f476, 39'h000194d299, 39'h009204200e, 39'h1a5503b236};
        rom[ 24] = {39'h0000030506, 39'h00019dafe6, 39'h009536a4b4, 39'h1ae89f9952};
        rom[ 25] = {39'h00000315f4, 39'h0001a6bee5, 39'h00987b15b1, 39'h1b7f76f2f3};
        rom[ 26] = {39'h0000032740, 39'h0001b000aa, 39'h009bd1d780, 39'h1c199bdd7d};
        rom[ 27] = {39'h00000338ed, 39'h0001b97654, 39'h009f3b50ca, 39'h1cb720dce7};
        rom[ 28] = {39'h0000034afd, 39'h0001c32106, 39'h00a2b7ea7d, 39'h1d5818dcf3};
        rom[ 29] = {39'h0000035d73, 39'h0001cd01e7, 39'h00a6480fcf, 39'h1dfc973372};
        rom[ 30] = {39'h0000037050, 39'h0001d71a28, 39'h00a9ec2e51, 39'h1ea4afa29b};
        rom[ 31] = {39'h0000038397, 39'h0001e16b00, 39'h00ada4b5fb, 39'h1f50765b65};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
