/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=16): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m16 #(parameter integer MODE = 0, parameter integer UNROLL100 = 100, parameter integer WSB = 1) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 33:0] x0,
    input  wire signed [ 33:0] y0,
    input  wire signed [ 36:0] z0,
    output wire                busy,
    output wire                done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 33:0] xn,
    output wire signed [ 33:0] yn,
    output wire signed [ 36:0] zn,
    output wire        [ 34:0] const2pi    // round(2*pi * 2**XF), CWB = XF + 3 bits
);
    localparam integer N    = 13;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 34;
    localparam integer WZ   = 37;
    localparam integer XF   = 32;   // x/y fractional scale
    localparam integer ZF   = 34;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 35;
    localparam signed [WX-1:0] KINV = 34'sd2608131522;   // round(1/gain * 2**XF)

    assign const2pi = 35'd26986075409;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        37'd667544,   // atan(2^-12)/2pi
        37'd1335088,   // atan(2^-11)/2pi
        37'd2670176,   // atan(2^-10)/2pi
        37'd5340347,   // atan(2^-9)/2pi
        37'd10680653,   // atan(2^-8)/2pi
        37'd21360980,   // atan(2^-7)/2pi
        37'd42719353,   // atan(2^-6)/2pi
        37'd85417861,   // atan(2^-5)/2pi
        37'd170669324,   // atan(2^-4)/2pi
        37'd340019024,   // atan(2^-3)/2pi
        37'd669835629,   // atan(2^-2)/2pi
        37'd1267733622,   // atan(2^-1)/2pi
        37'd2147483648   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(.N(N), .UNROLL100(UNROLL100), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
