/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=11): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m11 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 26:0] x0,
    input  wire signed [ 26:0] y0,
    input  wire signed [ 31:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 26:0] xn,
    output wire signed [ 26:0] yn,
    output wire signed [ 31:0] zn,
    output wire        [ 27:0] const2pi    // round(2*pi * 2**XF), CWB = XF + 3 bits
);
    localparam integer N    = 11;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 27;
    localparam integer WZ   = 32;
    localparam integer XF   = 25;   // x/y fractional scale
    localparam integer ZF   = 29;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 28;
    localparam signed [WX-1:0] KINV = 27'sd20376031;   // round(1/gain * 2**XF)

    assign const2pi = 28'd210828714;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        32'd83443,   // atan(2^-10)/2pi
        32'd166886,   // atan(2^-9)/2pi
        32'd333770,   // atan(2^-8)/2pi
        32'd667531,   // atan(2^-7)/2pi
        32'd1334980,   // atan(2^-6)/2pi
        32'd2669308,   // atan(2^-5)/2pi
        32'd5333416,   // atan(2^-4)/2pi
        32'd10625595,   // atan(2^-3)/2pi
        32'd20932363,   // atan(2^-2)/2pi
        32'd39616676,   // atan(2^-1)/2pi
        32'd67108864   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
