/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=16 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m16 #(parameter integer WMAN = 16, parameter integer D = 2, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer RW   = 9;
    localparam integer CW   = 31;
    localparam integer ACCW = 33;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {31'h00008c47, 31'h7fc756aa, 31'h1ffffff3};
        rom[  1] = {31'h000087a7, 31'h7fc86f2f, 31'h1fc7e2cb};
        rom[  2] = {31'h0000833e, 31'h7fc97e76, 31'h1f90d98a};
        rom[  3] = {31'h00007f0a, 31'h7fca84ec, 31'h1f5adb27};
        rom[  4] = {31'h00007b06, 31'h7fcb82f9, 31'h1f25df07};
        rom[  5] = {31'h00007731, 31'h7fcc78ff, 31'h1ef1dcf2};
        rom[  6] = {31'h00007386, 31'h7fcd675a, 31'h1ebecd0d};
        rom[  7] = {31'h00007005, 31'h7fce4e61, 31'h1e8ca7db};
        rom[  8] = {31'h00006caa, 31'h7fcf2e66, 31'h1e5b6630};
        rom[  9] = {31'h00006974, 31'h7fd007b6, 31'h1e2b012f};
        rom[ 10] = {31'h00006660, 31'h7fd0da9a, 31'h1dfb7249};
        rom[ 11] = {31'h0000636d, 31'h7fd1a756, 31'h1dccb333};
        rom[ 12] = {31'h00006099, 31'h7fd26e2c, 31'h1d9ebde7};
        rom[ 13] = {31'h00005de1, 31'h7fd32f59, 31'h1d718c9d};
        rom[ 14] = {31'h00005b46, 31'h7fd3eb18, 31'h1d4519c9};
        rom[ 15] = {31'h000058c5, 31'h7fd4a1a0, 31'h1d19601a};
        rom[ 16] = {31'h0000565c, 31'h7fd55326, 31'h1cee5a72};
        rom[ 17] = {31'h0000540c, 31'h7fd5ffdc, 31'h1cc403e8};
        rom[ 18] = {31'h000051d2, 31'h7fd6a7f1, 31'h1c9a57c4};
        rom[ 19] = {31'h00004fad, 31'h7fd74b91, 31'h1c71517b};
        rom[ 20] = {31'h00004d9d, 31'h7fd7eae8, 31'h1c48ecae};
        rom[ 21] = {31'h00004ba0, 31'h7fd8861f, 31'h1c212529};
        rom[ 22] = {31'h000049b5, 31'h7fd91d5c, 31'h1bf9f6dd};
        rom[ 23] = {31'h000047dc, 31'h7fd9b0c4, 31'h1bd35de4};
        rom[ 24] = {31'h00004614, 31'h7fda407a, 31'h1bad567b};
        rom[ 25] = {31'h0000445c, 31'h7fdacca1, 31'h1b87dd00};
        rom[ 26] = {31'h000042b3, 31'h7fdb5557, 31'h1b62edf4};
        rom[ 27] = {31'h00004119, 31'h7fdbdabb, 31'h1b3e85f6};
        rom[ 28] = {31'h00003f8d, 31'h7fdc5ceb, 31'h1b1aa1c2};
        rom[ 29] = {31'h00003e0e, 31'h7fdcdc03, 31'h1af73e32};
        rom[ 30] = {31'h00003c9c, 31'h7fdd581d, 31'h1ad4583b};
        rom[ 31] = {31'h00003b36, 31'h7fddd153, 31'h1ab1eced};
        rom[ 32] = {31'h000039db, 31'h7fde47bd, 31'h1a8ff96e};
        rom[ 33] = {31'h0000388c, 31'h7fdebb72, 31'h1a6e7aff};
        rom[ 34] = {31'h00003748, 31'h7fdf2c8a, 31'h1a4d6ef7};
        rom[ 35] = {31'h0000360e, 31'h7fdf9b18, 31'h1a2cd2c2};
        rom[ 36] = {31'h000034de, 31'h7fe00733, 31'h1a0ca3e2};
        rom[ 37] = {31'h000033b7, 31'h7fe070ed, 31'h19ecdfec};
        rom[ 38] = {31'h00003299, 31'h7fe0d85a, 31'h19cd848a};
        rom[ 39] = {31'h00003184, 31'h7fe13d8b, 31'h19ae8f78};
        rom[ 40] = {31'h00003078, 31'h7fe1a093, 31'h198ffe82};
        rom[ 41] = {31'h00002f73, 31'h7fe20182, 31'h1971cf87};
        rom[ 42] = {31'h00002e76, 31'h7fe26067, 31'h19540077};
        rom[ 43] = {31'h00002d81, 31'h7fe2bd53, 31'h19368f4f};
        rom[ 44] = {31'h00002c93, 31'h7fe31854, 31'h19197a1e};
        rom[ 45] = {31'h00002bac, 31'h7fe37179, 31'h18fcbf01};
        rom[ 46] = {31'h00002acb, 31'h7fe3c8d0, 31'h18e05c21};
        rom[ 47] = {31'h000029f1, 31'h7fe41e65, 31'h18c44fb7};
        rom[ 48] = {31'h0000291d, 31'h7fe47245, 31'h18a89809};
        rom[ 49] = {31'h0000284e, 31'h7fe4c47e, 31'h188d3366};
        rom[ 50] = {31'h00002786, 31'h7fe51519, 31'h1872202e};
        rom[ 51] = {31'h000026c3, 31'h7fe56424, 31'h18575cc9};
        rom[ 52] = {31'h00002605, 31'h7fe5b1a9, 31'h183ce7ac};
        rom[ 53] = {31'h0000254d, 31'h7fe5fdb3, 31'h1822bf57};
        rom[ 54] = {31'h00002499, 31'h7fe6484b, 31'h1808e252};
        rom[ 55] = {31'h000023ea, 31'h7fe6917c, 31'h17ef4f32};
        rom[ 56] = {31'h00002340, 31'h7fe6d950, 31'h17d60495};
        rom[ 57] = {31'h0000229a, 31'h7fe71fcf, 31'h17bd0121};
        rom[ 58] = {31'h000021f9, 31'h7fe76502, 31'h17a44386};
        rom[ 59] = {31'h0000215b, 31'h7fe7a8f3, 31'h178bca7e};
        rom[ 60] = {31'h000020c2, 31'h7fe7eba8, 31'h177394c8};
        rom[ 61] = {31'h0000202c, 31'h7fe82d2c, 31'h175ba12f};
        rom[ 62] = {31'h00001f9b, 31'h7fe86d84, 31'h1743ee85};
        rom[ 63] = {31'h00001f0d, 31'h7fe8acb9, 31'h172c7ba1};
        rom[ 64] = {31'h00001e82, 31'h7fe8ead2, 31'h17154764};
        rom[ 65] = {31'h00001dfb, 31'h7fe927d6, 31'h16fe50b6};
        rom[ 66] = {31'h00001d77, 31'h7fe963cc, 31'h16e79684};
        rom[ 67] = {31'h00001cf7, 31'h7fe99ebb, 31'h16d117c5};
        rom[ 68] = {31'h00001c79, 31'h7fe9d8a8, 31'h16bad374};
        rom[ 69] = {31'h00001bff, 31'h7fea119a, 31'h16a4c893};
        rom[ 70] = {31'h00001b87, 31'h7fea4997, 31'h168ef629};
        rom[ 71] = {31'h00001b12, 31'h7fea80a5, 31'h16795b45};
        rom[ 72] = {31'h00001aa0, 31'h7feab6c9, 31'h1663f6fa};
        rom[ 73] = {31'h00001a31, 31'h7feaec0a, 31'h164ec861};
        rom[ 74] = {31'h000019c4, 31'h7feb206b, 31'h1639ce99};
        rom[ 75] = {31'h0000195a, 31'h7feb53f3, 31'h162508c6};
        rom[ 76] = {31'h000018f2, 31'h7feb86a6, 31'h16107610};
        rom[ 77] = {31'h0000188c, 31'h7febb889, 31'h15fc15a6};
        rom[ 78] = {31'h00001829, 31'h7febe9a1, 31'h15e7e6b9};
        rom[ 79] = {31'h000017c8, 31'h7fec19f3, 31'h15d3e881};
        rom[ 80] = {31'h00001769, 31'h7fec4982, 31'h15c01a39};
        rom[ 81] = {31'h0000170c, 31'h7fec7853, 31'h15ac7b22};
        rom[ 82] = {31'h000016b1, 31'h7feca66b, 31'h15990a7f};
        rom[ 83] = {31'h00001658, 31'h7fecd3cd, 31'h1585c79a};
        rom[ 84] = {31'h00001601, 31'h7fed007e, 31'h1572b1bd};
        rom[ 85] = {31'h000015ac, 31'h7fed2c80, 31'h155fc83a};
        rom[ 86] = {31'h00001559, 31'h7fed57d8, 31'h154d0a65};
        rom[ 87] = {31'h00001508, 31'h7fed828a, 31'h153a7795};
        rom[ 88] = {31'h000014b8, 31'h7fedac99, 31'h15280f25};
        rom[ 89] = {31'h0000146a, 31'h7fedd609, 31'h1515d075};
        rom[ 90] = {31'h0000141d, 31'h7fedfedc, 31'h1503bae5};
        rom[ 91] = {31'h000013d2, 31'h7fee2716, 31'h14f1cddc};
        rom[ 92] = {31'h00001389, 31'h7fee4eba, 31'h14e008c3};
        rom[ 93] = {31'h00001341, 31'h7fee75cb, 31'h14ce6b04};
        rom[ 94] = {31'h000012fb, 31'h7fee9c4d, 31'h14bcf40f};
        rom[ 95] = {31'h000012b5, 31'h7feec242, 31'h14aba355};
        rom[ 96] = {31'h00001272, 31'h7feee7ad, 31'h149a784b};
        rom[ 97] = {31'h00001230, 31'h7fef0c90, 31'h14897268};
        rom[ 98] = {31'h000011ef, 31'h7fef30ef, 31'h14789127};
        rom[ 99] = {31'h000011af, 31'h7fef54cc, 31'h1467d403};
        rom[100] = {31'h00001170, 31'h7fef782a, 31'h14573a7d};
        rom[101] = {31'h00001133, 31'h7fef9b0b, 31'h1446c416};
        rom[102] = {31'h000010f7, 31'h7fefbd71, 31'h14367053};
        rom[103] = {31'h000010bc, 31'h7fefdf5f, 31'h14263eba};
        rom[104] = {31'h00001082, 31'h7ff000d7, 31'h14162ed3};
        rom[105] = {31'h0000104a, 31'h7ff021dc, 31'h1406402c};
        rom[106] = {31'h00001012, 31'h7ff0426f, 31'h13f67251};
        rom[107] = {31'h00000fdc, 31'h7ff06293, 31'h13e6c4d1};
        rom[108] = {31'h00000fa6, 31'h7ff0824b, 31'h13d7373f};
        rom[109] = {31'h00000f71, 31'h7ff0a196, 31'h13c7c92e};
        rom[110] = {31'h00000f3e, 31'h7ff0c079, 31'h13b87a35};
        rom[111] = {31'h00000f0b, 31'h7ff0def5, 31'h13a949eb};
        rom[112] = {31'h00000eda, 31'h7ff0fd0b, 31'h139a37ea};
        rom[113] = {31'h00000ea9, 31'h7ff11abe, 31'h138b43ce};
        rom[114] = {31'h00000e79, 31'h7ff1380f, 31'h137c6d34};
        rom[115] = {31'h00000e4a, 31'h7ff15501, 31'h136db3bb};
        rom[116] = {31'h00000e1b, 31'h7ff17194, 31'h135f1705};
        rom[117] = {31'h00000dee, 31'h7ff18dcb, 31'h135096b4};
        rom[118] = {31'h00000dc1, 31'h7ff1a9a7, 31'h1342326c};
        rom[119] = {31'h00000d96, 31'h7ff1c52a, 31'h1333e9d4};
        rom[120] = {31'h00000d6b, 31'h7ff1e055, 31'h1325bc93};
        rom[121] = {31'h00000d40, 31'h7ff1fb2b, 31'h1317aa52};
        rom[122] = {31'h00000d17, 31'h7ff215ab, 31'h1309b2bc};
        rom[123] = {31'h00000cee, 31'h7ff22fd8, 31'h12fbd57d};
        rom[124] = {31'h00000cc6, 31'h7ff249b4, 31'h12ee1242};
        rom[125] = {31'h00000c9e, 31'h7ff26340, 31'h12e068bb};
        rom[126] = {31'h00000c77, 31'h7ff27c7c, 31'h12d2d899};
        rom[127] = {31'h00000c51, 31'h7ff2956b, 31'h12c5618b};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
