/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=24 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m24 #(parameter integer WMAN = 24, parameter integer D = 3, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 in_valid,
    input  wire       [SBW-1:0] sb_in,
    input  wire      [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                 out_valid,
    output wire       [SBW-1:0] sb_out,
    output wire [2*WMAN+12-2:0] l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    // verilator coverage_off
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 6;
    localparam integer RW   = 17;
    localparam integer CW   = 39;
    localparam integer ACCW = 41;
    localparam integer NSEG = 64;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    (* rom_style = "block", syn_romstyle = "EBR" *)  // The table is large, map it to a block ROM (EBR)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {39'h7ffffe97be, 39'h00007b1684, 39'h7fd1d57256, 39'h1715476523};
        rom[  1] = {39'h7ffffea90e, 39'h000076ddfd, 39'h7fd2c768c1, 39'h16e79685ba};
        rom[  2] = {39'h7ffffeb94e, 39'h000072d963, 39'h7fd3b121ee, 39'h16bad37587};
        rom[  3] = {39'h7ffffec890, 39'h00006f0584, 39'h7fd4930287, 39'h168ef62a27};
        rom[  4] = {39'h7ffffed6e9, 39'h00006b5f68, 39'h7fd56d690b, 39'h1663f6fac2};
        rom[  5] = {39'h7ffffee468, 39'h000067e452, 39'h7fd640ae45, 39'h1639ce9a1e};
        rom[  6] = {39'h7ffffef11e, 39'h00006491b6, 39'h7fd70d25b8, 39'h161076111d};
        rom[  7] = {39'h7ffffefd19, 39'h0000616538, 39'h7fd7d31dfc, 39'h15e7e6b9a9};
        rom[  8] = {39'h7fffff0865, 39'h00005e5ca8, 39'h7fd892e121, 39'h15c01a39f6};
        rom[  9] = {39'h7fffff1310, 39'h00005b75fb, 39'h7fd94cb4f6, 39'h15990a8025};
        rom[ 10] = {39'h7fffff1d23, 39'h000058af4b, 39'h7fda00db5e, 39'h1572b1be25};
        rom[ 11] = {39'h7fffff26aa, 39'h00005606d3, 39'h7fdaaf928e, 39'h154d0a65f1};
        rom[ 12] = {39'h7fffff2fad, 39'h0000537aee, 39'h7fdb591553, 39'h15280f25fd};
        rom[ 13] = {39'h7fffff3836, 39'h0000510a10, 39'h7fdbfd9b48, 39'h1503bae5ec};
        rom[ 14] = {39'h7fffff404b, 39'h00004eb2ca, 39'h7fdc9d590c, 39'h14e008c37a};
        rom[ 15] = {39'h7fffff47f5, 39'h00004c73c3, 39'h7fdd388077, 39'h14bcf40f9b};
        rom[ 16] = {39'h7fffff4f3a, 39'h00004a4bb8, 39'h7fddcf40c4, 39'h149a784bca};
        rom[ 17] = {39'h7fffff5621, 39'h000048397c, 39'h7fde61c6c0, 39'h1478912780};
        rom[ 18] = {39'h7fffff5cb0, 39'h0000463bf3, 39'h7fdef03cee, 39'h14573a7dde};
        rom[ 19] = {39'h7fffff62eb, 39'h0000445214, 39'h7fdf7acbaa, 39'h143670536e};
        rom[ 20] = {39'h7fffff68d8, 39'h0000427ae5, 39'h7fe001994f, 39'h14162ed416};
        rom[ 21] = {39'h7fffff6e7b, 39'h000040b57c, 39'h7fe084ca54, 39'h13f6725121};
        rom[ 22] = {39'h7fffff73d9, 39'h00003f00fc, 39'h7fe1048169, 39'h13d7373f6c};
        rom[ 23] = {39'h7fffff78f7, 39'h00003d5c97, 39'h7fe180df92, 39'h13b87a35ab};
        rom[ 24] = {39'h7fffff7dd7, 39'h00003bc788, 39'h7fe1fa0440, 39'h139a37eaca};
        rom[ 25] = {39'h7fffff827d, 39'h00003a4119, 39'h7fe2700d69, 39'h137c6d3469};
        rom[ 26] = {39'h7fffff86ec, 39'h000038c89a, 39'h7fe2e3179e, 39'h135f170567};
        rom[ 27] = {39'h7fffff8b28, 39'h0000375d6a, 39'h7fe3533e1f, 39'h1342326c8c};
        rom[ 28] = {39'h7fffff8f33, 39'h000035feec, 39'h7fe3c09aeb, 39'h1325bc933c};
        rom[ 29] = {39'h7fffff9310, 39'h000034ac90, 39'h7fe42b46d9, 39'h1309b2bc47};
        rom[ 30] = {39'h7fffff96c2, 39'h00003365cb, 39'h7fe49359a0, 39'h12ee1242c0};
        rom[ 31] = {39'h7fffff9a4b, 39'h0000322a1a, 39'h7fe4f8e9ec, 39'h12d2d898ed};
        rom[ 32] = {39'h7fffff9dac, 39'h000030f902, 39'h7fe55c0d6c, 39'h12b803473e};
        rom[ 33] = {39'h7fffffa0e9, 39'h00002fd20f, 39'h7fe5bcd8dc, 39'h129d8feb58};
        rom[ 34] = {39'h7fffffa402, 39'h00002eb4d0, 39'h7fe61b6017, 39'h12837c372c};
        rom[ 35] = {39'h7fffffa6fb, 39'h00002da0de, 39'h7fe677b61d, 39'h1269c5f015};
        rom[ 36] = {39'h7fffffa9d3, 39'h00002c95d5, 39'h7fe6d1ed24, 39'h12506aee0a};
        rom[ 37] = {39'h7fffffac8e, 39'h00002b9355, 39'h7fe72a169e, 39'h1237691ad6};
        rom[ 38] = {39'h7fffffaf2d, 39'h00002a9906, 39'h7fe7804346, 39'h121ebe7157};
        rom[ 39] = {39'h7fffffb1b0, 39'h000029a691, 39'h7fe7d48328, 39'h120668fccf};
        rom[ 40] = {39'h7fffffb41a, 39'h000028bba7, 39'h7fe826e5a7, 39'h11ee66d838};
        rom[ 41] = {39'h7fffffb66b, 39'h000027d7f9, 39'h7fe877798c, 39'h11d6b62da0};
        rom[ 42] = {39'h7fffffb8a5, 39'h000026fb3f, 39'h7fe8c64d06, 39'h11bf553590};
        rom[ 43] = {39'h7fffffbac9, 39'h0000262533, 39'h7fe9136db7, 39'h11a842367a};
        rom[ 44] = {39'h7fffffbcd7, 39'h0000255591, 39'h7fe95ee8b9, 39'h11917b842c};
        rom[ 45] = {39'h7fffffbed2, 39'h0000248c1c, 39'h7fe9a8caa1, 39'h117aff7f4e};
        rom[ 46] = {39'h7fffffc0ba, 39'h000023c897, 39'h7fe9f11f8d, 39'h1164cc94de};
        rom[ 47] = {39'h7fffffc28f, 39'h0000230ac8, 39'h7fea37f323, 39'h114ee13dbb};
        rom[ 48] = {39'h7fffffc452, 39'h0000225278, 39'h7fea7d5097, 39'h11393bfe35};
        rom[ 49] = {39'h7fffffc606, 39'h0000219f73, 39'h7feac142b4, 39'h1123db6595};
        rom[ 50] = {39'h7fffffc7a9, 39'h000020f187, 39'h7feb03d3df, 39'h110ebe0dc2};
        rom[ 51] = {39'h7fffffc93d, 39'h0000204884, 39'h7feb450e19, 39'h10f9e29ad0};
        rom[ 52] = {39'h7fffffcac2, 39'h00001fa43d, 39'h7feb84fb08, 39'h10e547baaa};
        rom[ 53] = {39'h7fffffcc3a, 39'h00001f0486, 39'h7febc3a3f7, 39'h10d0ec24b1};
        rom[ 54] = {39'h7fffffcda4, 39'h00001e6936, 39'h7fec0111de, 39'h10bcce9969};
        rom[ 55] = {39'h7fffffcf01, 39'h00001dd224, 39'h7fec3d4d61, 39'h10a8ede221};
        rom[ 56] = {39'h7fffffd053, 39'h00001d3f2b, 39'h7fec785ed8, 39'h109548d0a7};
        rom[ 57] = {39'h7fffffd198, 39'h00001cb025, 39'h7fecb24e4e, 39'h1081de3efd};
        rom[ 58] = {39'h7fffffd2d3, 39'h00001c24f1, 39'h7feceb2389, 39'h106ead0f08};
        rom[ 59] = {39'h7fffffd403, 39'h00001b9d6c, 39'h7fed22e60a, 39'h105bb42a55};
        rom[ 60] = {39'h7fffffd528, 39'h00001b1977, 39'h7fed599d0f, 39'h1048f281ce};
        rom[ 61] = {39'h7fffffd644, 39'h00001a98f2, 39'h7fed8f4f98, 39'h1036670d7b};
        rom[ 62] = {39'h7fffffd756, 39'h00001a1bc0, 39'h7fedc4046b, 39'h102410cc49};
        rom[ 63] = {39'h7fffffd860, 39'h000019a1c6, 39'h7fedf7c210, 39'h1011eec3cb};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
