/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=23 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m23_d3 #(parameter integer WMAN = 23, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire [WMAN+12-1:0]     f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire        [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire                   guard,
    output wire                   round,
    output wire                   sticky
);
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 5;
    localparam integer D    = 3;
    localparam integer CF   = 35;
    localparam integer RW   = 30;
    localparam integer CW   = 38;
    localparam integer ACCW = 40;
    localparam integer NSEG = 32;
    localparam integer HSBW = SBW;

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {38'h000000e5d2, 38'h00007afd6b, 38'h002c5c864d, 38'h07fffffffe};
        rom[1] = {38'h000000eadb, 38'h00007daedc, 38'h002d55333b, 38'h082cd86988};
        rom[2] = {38'h000000efff, 38'h0000806f65, 38'h002e535228, 38'h085aac367a};
        rom[3] = {38'h000000f541, 38'h0000833f5c, 38'h002f570198, 38'h088980e807};
        rom[4] = {38'h000000fa9f, 38'h0000861f17, 38'h00306060bf, 38'h08b95c1e3c};
        rom[5] = {38'h000001001c, 38'h0000890eef, 38'h00316f8f7b, 38'h08ea4398b2};
        rom[6] = {38'h00000105b8, 38'h00008c0f3c, 38'h003284ae61, 38'h091c3d3738};
        rom[7] = {38'h0000010b73, 38'h00008f205d, 38'h00339fdeb9, 38'h094f4efa8d};
        rom[8] = {38'h000001114e, 38'h00009242af, 38'h0034c14287, 38'h09837f0516};
        rom[9] = {38'h000001174a, 38'h0000957692, 38'h0035e8fc8f, 38'h09b8d39b9a};
        rom[10] = {38'h0000011d68, 38'h000098bc69, 38'h0037173056, 38'h09ef532606};
        rom[11] = {38'h00000123a8, 38'h00009c1499, 38'h00384c0229, 38'h0a2704302e};
        rom[12] = {38'h0000012a0b, 38'h00009f7f89, 38'h0039879720, 38'h0a5fed6a98};
        rom[13] = {38'h0000013091, 38'h0000a2fda1, 38'h003aca1523, 38'h0a9a15ab4b};
        rom[14] = {38'h000001373d, 38'h0000a68f4d, 38'h003c13a2ef, 38'h0ad583eea1};
        rom[15] = {38'h0000013e0d, 38'h0000aa34fb, 38'h003d64681a, 38'h0b123f581a};
        rom[16] = {38'h0000014504, 38'h0000adef1b, 38'h003ebc8d17, 38'h0b504f333c};
        rom[17] = {38'h0000014c22, 38'h0000b1be1f, 38'h00401c3b3e, 38'h0b8fbaf473};
        rom[18] = {38'h0000015368, 38'h0000b5a27d, 38'h0041839ccc, 38'h0bd08a39f2};
        rom[19] = {38'h0000015ad7, 38'h0000b99cac, 38'h0042f2dcec, 38'h0c12c4cca3};
        rom[20] = {38'h000001626f, 38'h0000bdad27, 38'h00446a27bc, 38'h0c5672a111};
        rom[21] = {38'h0000016a32, 38'h0000c1d46a, 38'h0045e9aa4f, 38'h0c9b9bd863};
        rom[22] = {38'h0000017220, 38'h0000c612f6, 38'h00477192b7, 38'h0ce248c14e};
        rom[23] = {38'h0000017a3b, 38'h0000ca694c, 38'h0049021007, 38'h0d2a81d91b};
        rom[24] = {38'h0000018283, 38'h0000ced7f3, 38'h004a9b525a, 38'h0d744fcca9};
        rom[25] = {38'h0000018afa, 38'h0000d35f72, 38'h004c3d8ad9, 38'h0dbfbb7979};
        rom[26] = {38'h00000193a0, 38'h0000d80055, 38'h004de8ebc0, 38'h0e0ccdeebe};
        rom[27] = {38'h0000019c77, 38'h0000dcbb2a, 38'h004f9da865, 38'h0e5b906e73};
        rom[28] = {38'h000001a57f, 38'h0000e19083, 38'h00515bf53e, 38'h0eac0c6e79};
        rom[29] = {38'h000001aeb9, 38'h0000e680f3, 38'h00532407e8, 38'h0efe4b99b9};
        rom[30] = {38'h000001b828, 38'h0000eb8d14, 38'h0054f61729, 38'h0f5257d14e};
        rom[31] = {38'h000001c1cb, 38'h0000f0b580, 38'h0056d25afd, 38'h0fa83b2db2};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
