/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=17 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m17_d2 #(parameter integer WMAN = 17, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire [WMAN+12-1:0]     f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire        [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire                   guard,
    output wire                   round,
    output wire                   sticky
);
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer D    = 2;
    localparam integer CF   = 29;
    localparam integer RW   = 23;
    localparam integer CW   = 32;
    localparam integer ACCW = 34;
    localparam integer NSEG = 64;
    localparam integer HSBW = SBW;

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {32'h00007baa, 32'h0058b8cc, 32'h20000004};
        rom[1] = {32'h00007d03, 32'h0059b01f, 32'h20593481};
        rom[2] = {32'h00007e5f, 32'h005aaa24, 32'h20b361aa};
        rom[3] = {32'h00007fbf, 32'h005ba6e2, 32'h210e8a35};
        rom[4] = {32'h00008124, 32'h005ca661, 32'h216ab0de};
        rom[5] = {32'h0000828c, 32'h005da8a7, 32'h21c7d869};
        rom[6] = {32'h000083f8, 32'h005eadbe, 32'h222603a4};
        rom[7] = {32'h00008567, 32'h005fb5ad, 32'h22853561};
        rom[8] = {32'h000086db, 32'h0060c07b, 32'h22e5707d};
        rom[9] = {32'h00008853, 32'h0061ce31, 32'h2346b7db};
        rom[10] = {32'h000089cf, 32'h0062ded7, 32'h23a90e67};
        rom[11] = {32'h00008b4f, 32'h0063f275, 32'h240c7715};
        rom[12] = {32'h00008cd4, 32'h00650913, 32'h2470f4e1};
        rom[13] = {32'h00008e5c, 32'h006622ba, 32'h24d68ad0};
        rom[14] = {32'h00008fe9, 32'h00673f72, 32'h253d3bee};
        rom[15] = {32'h0000917a, 32'h00685f44, 32'h25a50b52};
        rom[16] = {32'h00009310, 32'h00698238, 32'h260dfc19};
        rom[17] = {32'h000094aa, 32'h006aa857, 32'h26781169};
        rom[18] = {32'h00009648, 32'h006bd1aa, 32'h26e34e73};
        rom[19] = {32'h000097eb, 32'h006cfe3a, 32'h274fb66e};
        rom[20] = {32'h00009993, 32'h006e2e10, 32'h27bd4c9d};
        rom[21] = {32'h00009b3f, 32'h006f6135, 32'h282c1448};
        rom[22] = {32'h00009cf0, 32'h007097b2, 32'h289c10c5};
        rom[23] = {32'h00009ea5, 32'h0071d191, 32'h290d4570};
        rom[24] = {32'h0000a05f, 32'h00730eda, 32'h297fb5af};
        rom[25] = {32'h0000a21e, 32'h00744f98, 32'h29f364f2};
        rom[26] = {32'h0000a3e2, 32'h007593d4, 32'h2a6856b2};
        rom[27] = {32'h0000a5ab, 32'h0076db98, 32'h2ade8e72};
        rom[28] = {32'h0000a779, 32'h007826ee, 32'h2b560fbf};
        rom[29] = {32'h0000a94c, 32'h007975df, 32'h2bcede30};
        rom[30] = {32'h0000ab24, 32'h007ac877, 32'h2c48fd65};
        rom[31] = {32'h0000ad01, 32'h007c1ebd, 32'h2cc4710a};
        rom[32] = {32'h0000aee3, 32'h007d78bf, 32'h2d413cd2};
        rom[33] = {32'h0000b0cb, 32'h007ed684, 32'h2dbf647e};
        rom[34] = {32'h0000b2b8, 32'h00803819, 32'h2e3eebd7};
        rom[35] = {32'h0000b4aa, 32'h00819d87, 32'h2ebfd6b2};
        rom[36] = {32'h0000b6a1, 32'h008306da, 32'h2f4228ed};
        rom[37] = {32'h0000b89e, 32'h0084741c, 32'h2fc5e673};
        rom[38] = {32'h0000baa1, 32'h0085e558, 32'h304b1338};
        rom[39] = {32'h0000bca9, 32'h00875a9a, 32'h30d1b33c};
        rom[40] = {32'h0000beb7, 32'h0088d3ec, 32'h3159ca8a};
        rom[41] = {32'h0000c0cb, 32'h008a5159, 32'h31e35d38};
        rom[42] = {32'h0000c2e4, 32'h008bd2ee, 32'h326e6f67};
        rom[43] = {32'h0000c504, 32'h008d58b6, 32'h32fb0545};
        rom[44] = {32'h0000c729, 32'h008ee2bd, 32'h3389230b};
        rom[45] = {32'h0000c954, 32'h0090710e, 32'h3418ccfd};
        rom[46] = {32'h0000cb85, 32'h009203b5, 32'h34aa076a};
        rom[47] = {32'h0000cdbd, 32'h00939abf, 32'h353cd6b1};
        rom[48] = {32'h0000cffa, 32'h00953638, 32'h35d13f39};
        rom[49] = {32'h0000d23e, 32'h0096d62b, 32'h36674577};
        rom[50] = {32'h0000d488, 32'h00987aa6, 32'h36feedec};
        rom[51] = {32'h0000d6d9, 32'h009a23b6, 32'h37983d27};
        rom[52] = {32'h0000d92f, 32'h009bd166, 32'h383337c1};
        rom[53] = {32'h0000db8d, 32'h009d83c4, 32'h38cfe263};
        rom[54] = {32'h0000ddf1, 32'h009f3adc, 32'h396e41c0};
        rom[55] = {32'h0000e05c, 32'h00a0f6bd, 32'h3a0e5a9b};
        rom[56] = {32'h0000e2cd, 32'h00a2b774, 32'h3ab031c1};
        rom[57] = {32'h0000e545, 32'h00a47d0d, 32'h3b53cc0e};
        rom[58] = {32'h0000e7c4, 32'h00a64796, 32'h3bf92e6e};
        rom[59] = {32'h0000ea4a, 32'h00a8171e, 32'h3ca05dd6};
        rom[60] = {32'h0000ecd8, 32'h00a9ebb2, 32'h3d495f4c};
        rom[61] = {32'h0000ef6c, 32'h00abc560, 32'h3df437e4};
        rom[62] = {32'h0000f207, 32'h00ada437, 32'h3ea0ecbe};
        rom[63] = {32'h0000f4aa, 32'h00af8845, 32'h3f4f830a};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
