/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=18 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m18 #(parameter integer WMAN = 18, parameter integer D = 2, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 in_valid,
    input  wire       [WSB-1:0] sb_in,
    input  wire      [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                 out_valid,
    output wire       [WSB-1:0] sb_out,
    output wire [2*WMAN+12-2:0] l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    // verilator coverage_off
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 7;
    localparam integer RW   = 10;
    localparam integer CW   = 33;
    localparam integer ACCW = 35;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WFRAC;  // carry t alongside the sideband to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {33'h000007a09, 33'h1ffa3ab49, 33'h05c551d8f};
        rom[  1] = {33'h0000077ed, 33'h1ffa49f5a, 33'h05bf942d6};
        rom[  2] = {33'h0000075de, 33'h1ffa58f31, 33'h05b9e5a12};
        rom[  3] = {33'h0000073db, 33'h1ffa67aeb, 33'h05b445f16};
        rom[  4] = {33'h0000071e5, 33'h1ffa7629f, 33'h05aeb4dd1};
        rom[  5] = {33'h000006ffb, 33'h1ffa84668, 33'h05a93224b};
        rom[  6] = {33'h000006e1d, 33'h1ffa9265c, 33'h05a3bd8a4};
        rom[  7] = {33'h000006c49, 33'h1ffaa0294, 33'h059e56d13};
        rom[  8] = {33'h000006a81, 33'h1ffaadb25, 33'h0598fdbe6};
        rom[  9] = {33'h0000068c4, 33'h1ffabb026, 33'h0593b2183};
        rom[ 10] = {33'h000006710, 33'h1ffac81ac, 33'h058e73a64};
        rom[ 11] = {33'h000006567, 33'h1ffad4fcb, 33'h058942317};
        rom[ 12] = {33'h0000063c7, 33'h1ffae1a97, 33'h05841d840};
        rom[ 13] = {33'h000006231, 33'h1ffaee224, 33'h057f05696};
        rom[ 14] = {33'h0000060a4, 33'h1ffafa684, 33'h0579f9ae3};
        rom[ 15] = {33'h000005f1f, 33'h1ffb067ca, 33'h0574fa202};
        rom[ 16] = {33'h000005da3, 33'h1ffb12608, 33'h0570068e4};
        rom[ 17] = {33'h000005c30, 33'h1ffb1e14d, 33'h056b1ec87};
        rom[ 18] = {33'h000005ac5, 33'h1ffb299ac, 33'h0566429fd};
        rom[ 19] = {33'h000005961, 33'h1ffb34f35, 33'h056171e66};
        rom[ 20] = {33'h000005806, 33'h1ffb401f6, 33'h055cac6f5};
        rom[ 21] = {33'h0000056b1, 33'h1ffb4b200, 33'h0557f20ea};
        rom[ 22] = {33'h000005564, 33'h1ffb55f62, 33'h055342994};
        rom[ 23] = {33'h00000541e, 33'h1ffb60a29, 33'h054e9de54};
        rom[ 24] = {33'h0000052df, 33'h1ffb6b265, 33'h054a03c95};
        rom[ 25] = {33'h0000051a7, 33'h1ffb75822, 33'h0545741d2};
        rom[ 26] = {33'h000005075, 33'h1ffb7fb6e, 33'h0540eeb95};
        rom[ 27] = {33'h000004f49, 33'h1ffb89c57, 33'h053c73771};
        rom[ 28] = {33'h000004e23, 33'h1ffb93ae8, 33'h05380230b};
        rom[ 29] = {33'h000004d04, 33'h1ffb9d72e, 33'h05339ac10};
        rom[ 30] = {33'h000004bea, 33'h1ffba7134, 33'h052f3d03c};
        rom[ 31] = {33'h000004ad6, 33'h1ffbb0908, 33'h052ae8d54};
        rom[ 32] = {33'h0000049c7, 33'h1ffbb9eb3, 33'h05269e12c};
        rom[ 33] = {33'h0000048be, 33'h1ffbc3241, 33'h05225c9a1};
        rom[ 34] = {33'h0000047ba, 33'h1ffbcc3bd, 33'h051e2449b};
        rom[ 35] = {33'h0000046bc, 33'h1ffbd5331, 33'h0519f500d};
        rom[ 36] = {33'h0000045c2, 33'h1ffbde0a8, 33'h0515ce9f5};
        rom[ 37] = {33'h0000044cd, 33'h1ffbe6c2a, 33'h0511b1059};
        rom[ 38] = {33'h0000043dd, 33'h1ffbef5c3, 33'h050d9c14b};
        rom[ 39] = {33'h0000042f1, 33'h1ffbf7d7c, 33'h05098fae6};
        rom[ 40] = {33'h00000420a, 33'h1ffc0035d, 33'h05058bb4e};
        rom[ 41] = {33'h000004127, 33'h1ffc08770, 33'h0501900b0};
        rom[ 42] = {33'h000004049, 33'h1ffc109bd, 33'h04fd9c942};
        rom[ 43] = {33'h000003f6e, 33'h1ffc18a4e, 33'h04f9b1344};
        rom[ 44] = {33'h000003e98, 33'h1ffc2092a, 33'h04f5cdcfc};
        rom[ 45] = {33'h000003dc6, 33'h1ffc2865a, 33'h04f1f24b9};
        rom[ 46] = {33'h000003cf8, 33'h1ffc301e5, 33'h04ee1e8d5};
        rom[ 47] = {33'h000003c2d, 33'h1ffc37bd3, 33'h04ea527ad};
        rom[ 48] = {33'h000003b66, 33'h1ffc3f42d, 33'h04e68dfa9};
        rom[ 49] = {33'h000003aa3, 33'h1ffc46af9, 33'h04e2d0f38};
        rom[ 50] = {33'h0000039e3, 33'h1ffc4e03e, 33'h04df1b4d0};
        rom[ 51] = {33'h000003927, 33'h1ffc55404, 33'h04db6ceed};
        rom[ 52] = {33'h00000386e, 33'h1ffc5c651, 33'h04d7c5c14};
        rom[ 53] = {33'h0000037b8, 33'h1ffc6372d, 33'h04d425acf};
        rom[ 54] = {33'h000003706, 33'h1ffc6a69d, 33'h04d08c9b0};
        rom[ 55] = {33'h000003657, 33'h1ffc714a8, 33'h04ccfa750};
        rom[ 56] = {33'h0000035aa, 33'h1ffc78155, 33'h04c96f24b};
        rom[ 57] = {33'h000003501, 33'h1ffc7ecaa, 33'h04c5ea948};
        rom[ 58] = {33'h00000345b, 33'h1ffc856ac, 33'h04c26caef};
        rom[ 59] = {33'h0000033b8, 33'h1ffc8bf62, 33'h04bef55f3};
        rom[ 60] = {33'h000003317, 33'h1ffc926d1, 33'h04bb84909};
        rom[ 61] = {33'h000003279, 33'h1ffc98cfe, 33'h04b81a2ee};
        rom[ 62] = {33'h0000031de, 33'h1ffc9f1f0, 33'h04b4b6262};
        rom[ 63] = {33'h000003145, 33'h1ffca55ac, 33'h04b15862d};
        rom[ 64] = {33'h0000030af, 33'h1ffcab836, 33'h04ae00d1b};
        rom[ 65] = {33'h00000301c, 33'h1ffcb1995, 33'h04aaaf5fe};
        rom[ 66] = {33'h000002f8b, 33'h1ffcb79cc, 33'h04a763fac};
        rom[ 67] = {33'h000002efc, 33'h1ffcbd8e2, 33'h04a41e900};
        rom[ 68] = {33'h000002e70, 33'h1ffcc36da, 33'h04a0df0db};
        rom[ 69] = {33'h000002de6, 33'h1ffcc93ba, 33'h049da5622};
        rom[ 70] = {33'h000002d5e, 33'h1ffccef85, 33'h049a717bf};
        rom[ 71] = {33'h000002cd9, 33'h1ffcd4a41, 33'h0497434a0};
        rom[ 72] = {33'h000002c55, 33'h1ffcda3f2, 33'h04941abb7};
        rom[ 73] = {33'h000002bd4, 33'h1ffcdfc9d, 33'h0490f7bfc};
        rom[ 74] = {33'h000002b55, 33'h1ffce5445, 33'h048dda46a};
        rom[ 75] = {33'h000002ad8, 33'h1ffceaaee, 33'h048ac2401};
        rom[ 76] = {33'h000002a5d, 33'h1ffcf009d, 33'h0487af9c4};
        rom[ 77] = {33'h0000029e3, 33'h1ffcf5556, 33'h0484a24bb};
        rom[ 78] = {33'h00000296c, 33'h1ffcfa91c, 33'h04819a3f2};
        rom[ 79] = {33'h0000028f6, 33'h1ffcffbf4, 33'h047e97678};
        rom[ 80] = {33'h000002883, 33'h1ffd04de1, 33'h047b99b60};
        rom[ 81] = {33'h000002811, 33'h1ffd09ee6, 33'h0478a11c1};
        rom[ 82] = {33'h0000027a1, 33'h1ffd0ef08, 33'h0475ad8b5};
        rom[ 83] = {33'h000002733, 33'h1ffd13e49, 33'h0472bef5c};
        rom[ 84] = {33'h0000026c6, 33'h1ffd18cae, 33'h046fd54d5};
        rom[ 85] = {33'h00000265b, 33'h1ffd1da39, 33'h046cf0847};
        rom[ 86] = {33'h0000025f1, 33'h1ffd226ef, 33'h046a108d9};
        rom[ 87] = {33'h00000258a, 33'h1ffd272d1, 33'h0467355b7};
        rom[ 88] = {33'h000002523, 33'h1ffd2bde4, 33'h04645ee10};
        rom[ 89] = {33'h0000024bf, 33'h1ffd3082b, 33'h04618d115};
        rom[ 90] = {33'h00000245b, 33'h1ffd351a8, 33'h045ebfdfc};
        rom[ 91] = {33'h0000023fa, 33'h1ffd39a5e, 33'h045bf73fd};
        rom[ 92] = {33'h000002399, 33'h1ffd3e251, 33'h045933252};
        rom[ 93] = {33'h00000233a, 33'h1ffd42983, 33'h04567383b};
        rom[ 94] = {33'h0000022dd, 33'h1ffd46ff7, 33'h0453b84f6};
        rom[ 95] = {33'h000002281, 33'h1ffd4b5b1, 33'h0451017c8};
        rom[ 96] = {33'h000002226, 33'h1ffd4fab2, 33'h044e4eff8};
        rom[ 97] = {33'h0000021cc, 33'h1ffd53efd, 33'h044ba0cce};
        rom[ 98] = {33'h000002174, 33'h1ffd58296, 33'h0448f6d95};
        rom[ 99] = {33'h00000211d, 33'h1ffd5c57e, 33'h04465119d};
        rom[100] = {33'h0000020c7, 33'h1ffd607b8, 33'h0443af836};
        rom[101] = {33'h000002073, 33'h1ffd64946, 33'h0441120b3};
        rom[102] = {33'h000002020, 33'h1ffd68a2c, 33'h043e78a6a};
        rom[103] = {33'h000001fcd, 33'h1ffd6ca6a, 33'h043be34b4};
        rom[104] = {33'h000001f7c, 33'h1ffd70a05, 33'h043951eea};
        rom[105] = {33'h000001f2d, 33'h1ffd748fe, 33'h0436c486a};
        rom[106] = {33'h000001ede, 33'h1ffd78756, 33'h04343b092};
        rom[107] = {33'h000001e90, 33'h1ffd7c512, 33'h0431b56c5};
        rom[108] = {33'h000001e44, 33'h1ffd80232, 33'h042f33a65};
        rom[109] = {33'h000001df8, 33'h1ffd83eb9, 33'h042cb5ad9};
        rom[110] = {33'h000001dad, 33'h1ffd87aa8, 33'h042a3b788};
        rom[111] = {33'h000001d64, 33'h1ffd8b603, 33'h0427c4fdc};
        rom[112] = {33'h000001d1b, 33'h1ffd8f0cb, 33'h042552342};
        rom[113] = {33'h000001cd4, 33'h1ffd92b02, 33'h0422e3127};
        rom[114] = {33'h000001c8d, 33'h1ffd964aa, 33'h0420778fb};
        rom[115] = {33'h000001c48, 33'h1ffd99dc4, 33'h041e0fa31};
        rom[116] = {33'h000001c03, 33'h1ffd9d654, 33'h041bab43b};
        rom[117] = {33'h000001bbf, 33'h1ffda0e5a, 33'h04194a691};
        rom[118] = {33'h000001b7c, 33'h1ffda45d8, 33'h0416ed0a9};
        rom[119] = {33'h000001b3a, 33'h1ffda7cd1, 33'h0414931fc};
        rom[120] = {33'h000001af9, 33'h1ffdab346, 33'h04123ca07};
        rom[121] = {33'h000001ab9, 33'h1ffdae939, 33'h040fe9845};
        rom[122] = {33'h000001a7a, 33'h1ffdb1eab, 33'h040d99c35};
        rom[123] = {33'h000001a3b, 33'h1ffdb539e, 33'h040b4d559};
        rom[124] = {33'h0000019fd, 33'h1ffdb8814, 33'h040904331};
        rom[125] = {33'h0000019c0, 33'h1ffdbbc0f, 33'h0406be541};
        rom[126] = {33'h000001984, 33'h1ffdbef8f, 33'h04047bb0f};
        rom[127] = {33'h000001949, 33'h1ffdc2297, 33'h04023c421};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [WSB-1:0]   sb_p   = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .WACC(ACCW), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
