/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=11 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m11 #(parameter integer WMAN = 11, parameter integer D = 2, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 4;
    localparam integer CF   = 23;
    localparam integer RW   = 19;
    localparam integer CW   = 26;
    localparam integer ACCW = 28;
    localparam integer NSEG = 16;
    localparam integer HSBW = WSB;

    (* rom_style = "logic" *) // keep a small table in logic
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {26'h0001f6c, 26'h0058b50, 26'h0800004};
        rom[  1] = {26'h00020d1, 26'h005ca26, 26'h085aac7};
        rom[  2] = {26'h0002244, 26'h0060bc5, 26'h08b95c6};
        rom[  3] = {26'h00023c9, 26'h006504c, 26'h091c3d8};
        rom[  4] = {26'h000255e, 26'h00697db, 26'h09837f5};
        rom[  5] = {26'h0002706, 26'h006e295, 26'h09ef537};
        rom[  6] = {26'h00028c0, 26'h007309f, 26'h0a5fedb};
        rom[  7] = {26'h0002a8e, 26'h007821c, 26'h0ad5844};
        rom[  8] = {26'h0002c70, 26'h007d736, 26'h0b504f8};
        rom[  9] = {26'h0002e68, 26'h0083014, 26'h0bd08a9};
        rom[ 10] = {26'h0003076, 26'h0088ce1, 26'h0c56730};
        rom[ 11] = {26'h000329b, 26'h008edca, 26'h0ce2492};
        rom[ 12] = {26'h00034d9, 26'h00952fd, 26'h0d74503};
        rom[ 13] = {26'h0003730, 26'h009bcab, 26'h0e0cce5};
        rom[ 14] = {26'h00039a1, 26'h00a2b07, 26'h0eac0ce};
        rom[ 15] = {26'h0003c2f, 26'h00a9e46, 26'h0f52584};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
