/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=17 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + 1 (final multiply); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m17_d2 #(parameter integer WMAN = 17, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 7;
    localparam integer D    = 2;
    localparam integer RW   = 9;
    localparam integer CW   = 32;
    localparam integer ACCW = 34;
    localparam integer NSEG = 128;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {32'h00003d05, 32'hffd1d5a5, 32'h2e2a8ec7};
        rom[1] = {32'h00003bf6, 32'hffd24fad, 32'h2dfca16b};
        rom[2] = {32'h00003aef, 32'hffd2c799, 32'h2dcf2d09};
        rom[3] = {32'h000039ee, 32'hffd33d75, 32'h2da22f8b};
        rom[4] = {32'h000038f3, 32'hffd3b150, 32'h2d75a6e9};
        rom[5] = {32'h000037fd, 32'hffd42334, 32'h2d499126};
        rom[6] = {32'h0000370e, 32'hffd4932e, 32'h2d1dec52};
        rom[7] = {32'h00003625, 32'hffd5014a, 32'h2cf2b689};
        rom[8] = {32'h00003541, 32'hffd56d93, 32'h2cc7edf3};
        rom[9] = {32'h00003462, 32'hffd5d813, 32'h2c9d90c2};
        rom[10] = {32'h00003388, 32'hffd640d6, 32'h2c739d32};
        rom[11] = {32'h000032b3, 32'hffd6a7e5, 32'h2c4a118c};
        rom[12] = {32'h000031e4, 32'hffd70d4c, 32'h2c20ec20};
        rom[13] = {32'h00003118, 32'hffd77112, 32'h2bf82b4b};
        rom[14] = {32'h00003052, 32'hffd7d342, 32'h2bcfcd71};
        rom[15] = {32'h00002f90, 32'hffd833e5, 32'h2ba7d101};
        rom[16] = {32'h00002ed2, 32'hffd89304, 32'h2b803472};
        rom[17] = {32'h00002e18, 32'hffd8f0a7, 32'h2b58f644};
        rom[18] = {32'h00002d62, 32'hffd94cd6, 32'h2b3214fe};
        rom[19] = {32'h00002cb1, 32'hffd9a79a, 32'h2b0b8f33};
        rom[20] = {32'h00002c03, 32'hffda00fb, 32'h2ae5637b};
        rom[21] = {32'h00002b59, 32'hffda5900, 32'h2abf9075};
        rom[22] = {32'h00002ab2, 32'hffdaafb1, 32'h2a9a14ca};
        rom[23] = {32'h00002a0f, 32'hffdb0515, 32'h2a74ef2a};
        rom[24] = {32'h00002970, 32'hffdb5932, 32'h2a501e4a};
        rom[25] = {32'h000028d3, 32'hffdbac11, 32'h2a2ba0e9};
        rom[26] = {32'h0000283a, 32'hffdbfdb7, 32'h2a0775ca};
        rom[27] = {32'h000027a4, 32'hffdc4e2b, 32'h29e39bb9};
        rom[28] = {32'h00002712, 32'hffdc9d74, 32'h29c01185};
        rom[29] = {32'h00002682, 32'hffdceb97, 32'h299cd608};
        rom[30] = {32'h000025f5, 32'hffdd389a, 32'h2979e81e};
        rom[31] = {32'h0000256b, 32'hffdd8484, 32'h295746aa};
        rom[32] = {32'h000024e4, 32'hffddcf59, 32'h2934f096};
        rom[33] = {32'h0000245f, 32'hffde1921, 32'h2912e4d1};
        rom[34] = {32'h000023dd, 32'hffde61df, 32'h28f1224e};
        rom[35] = {32'h0000235e, 32'hffdea999, 32'h28cfa807};
        rom[36] = {32'h000022e1, 32'hffdef054, 32'h28ae74fa};
        rom[37] = {32'h00002266, 32'hffdf3615, 32'h288d882d};
        rom[38] = {32'h000021ee, 32'hffdf7ae2, 32'h286ce0a6};
        rom[39] = {32'h00002178, 32'hffdfbebe, 32'h284c7d73};
        rom[40] = {32'h00002105, 32'hffe001ae, 32'h282c5da7};
        rom[41] = {32'h00002094, 32'hffe043b8, 32'h280c8058};
        rom[42] = {32'h00002024, 32'hffe084df, 32'h27ece4a1};
        rom[43] = {32'h00001fb7, 32'hffe0c527, 32'h27cd89a2};
        rom[44] = {32'h00001f4c, 32'hffe10495, 32'h27ae6e7e};
        rom[45] = {32'h00001ee3, 32'hffe1432d, 32'h278f925d};
        rom[46] = {32'h00001e7c, 32'hffe180f2, 32'h2770f46a};
        rom[47] = {32'h00001e16, 32'hffe1bdea, 32'h275293d6};
        rom[48] = {32'h00001db3, 32'hffe1fa16, 32'h27346fd5};
        rom[49] = {32'h00001d51, 32'hffe2357c, 32'h2716879c};
        rom[50] = {32'h00001cf2, 32'hffe2701f, 32'h26f8da68};
        rom[51] = {32'h00001c93, 32'hffe2aa02, 32'h26db6776};
        rom[52] = {32'h00001c37, 32'hffe2e329, 32'h26be2e0a};
        rom[53] = {32'h00001bdc, 32'hffe31b96, 32'h26a12d68};
        rom[54] = {32'h00001b83, 32'hffe3534e, 32'h268464d8};
        rom[55] = {32'h00001b2b, 32'hffe38a54, 32'h2667d3a8};
        rom[56] = {32'h00001ad5, 32'hffe3c0ab, 32'h264b7926};
        rom[57] = {32'h00001a81, 32'hffe3f655, 32'h262f54a4};
        rom[58] = {32'h00001a2e, 32'hffe42b56, 32'h26136578};
        rom[59] = {32'h000019dc, 32'hffe45fb1, 32'h25f7aafa};
        rom[60] = {32'h0000198c, 32'hffe49368, 32'h25dc2485};
        rom[61] = {32'h0000193d, 32'hffe4c67f, 32'h25c0d177};
        rom[62] = {32'h000018ef, 32'hffe4f8f8, 32'h25a5b131};
        rom[63] = {32'h000018a3, 32'hffe52ad6, 32'h258ac317};
        rom[64] = {32'h00001858, 32'hffe55c1b, 32'h2570068e};
        rom[65] = {32'h0000180e, 32'hffe58cca, 32'h25557aff};
        rom[66] = {32'h000017c5, 32'hffe5bce6, 32'h253b1fd6};
        rom[67] = {32'h0000177e, 32'hffe5ec71, 32'h2520f480};
        rom[68] = {32'h00001738, 32'hffe61b6d, 32'h2506f86e};
        rom[69] = {32'h000016f3, 32'hffe649dd, 32'h24ed2b11};
        rom[70] = {32'h000016af, 32'hffe677c3, 32'h24d38bdf};
        rom[71] = {32'h0000166c, 32'hffe6a521, 32'h24ba1a50};
        rom[72] = {32'h0000162b, 32'hffe6d1f9, 32'h24a0d5db};
        rom[73] = {32'h000015ea, 32'hffe6fe4e, 32'h2487bdfe};
        rom[74] = {32'h000015aa, 32'hffe72a22, 32'h246ed235};
        rom[75] = {32'h0000156c, 32'hffe75577, 32'h24561200};
        rom[76] = {32'h0000152e, 32'hffe7804f, 32'h243d7ce2};
        rom[77] = {32'h000014f2, 32'hffe7aaab, 32'h2425125e};
        rom[78] = {32'h000014b6, 32'hffe7d48e, 32'h240cd1f9};
        rom[79] = {32'h0000147b, 32'hffe7fdfa, 32'h23f4bb3c};
        rom[80] = {32'h00001441, 32'hffe826f0, 32'h23dccdb0};
        rom[81] = {32'h00001408, 32'hffe84f73, 32'h23c508e0};
        rom[82] = {32'h000013d0, 32'hffe87784, 32'h23ad6c5b};
        rom[83] = {32'h00001399, 32'hffe89f25, 32'h2395f7ae};
        rom[84] = {32'h00001363, 32'hffe8c657, 32'h237eaa6b};
        rom[85] = {32'h0000132d, 32'hffe8ed1d, 32'h23678423};
        rom[86] = {32'h000012f9, 32'hffe91377, 32'h2350846c};
        rom[87] = {32'h000012c5, 32'hffe93969, 32'h2339aadb};
        rom[88] = {32'h00001292, 32'hffe95ef2, 32'h2322f708};
        rom[89] = {32'h0000125f, 32'hffe98415, 32'h230c688b};
        rom[90] = {32'h0000122e, 32'hffe9a8d4, 32'h22f5fefe};
        rom[91] = {32'h000011fd, 32'hffe9cd2f, 32'h22dfb9ff};
        rom[92] = {32'h000011cd, 32'hffe9f128, 32'h22c99929};
        rom[93] = {32'h0000119d, 32'hffea14c2, 32'h22b39c1d};
        rom[94] = {32'h0000116e, 32'hffea37fc, 32'h229dc27b};
        rom[95] = {32'h00001140, 32'hffea5ad8, 32'h22880be4};
        rom[96] = {32'h00001113, 32'hffea7d59, 32'h227277fc};
        rom[97] = {32'h000010e6, 32'hffea9f7f, 32'h225d0667};
        rom[98] = {32'h000010ba, 32'hffeac14b, 32'h2247b6cb};
        rom[99] = {32'h0000108f, 32'hffeae2bf, 32'h223288cf};
        rom[100] = {32'h00001064, 32'hffeb03dc, 32'h221d7c1b};
        rom[101] = {32'h00001039, 32'hffeb24a3, 32'h2208905a};
        rom[102] = {32'h00001010, 32'hffeb4516, 32'h21f3c535};
        rom[103] = {32'h00000fe7, 32'hffeb6535, 32'h21df1a5a};
        rom[104] = {32'h00000fbe, 32'hffeb8502, 32'h21ca8f75};
        rom[105] = {32'h00000f96, 32'hffeba47f, 32'h21b62435};
        rom[106] = {32'h00000f6f, 32'hffebc3ab, 32'h21a1d849};
        rom[107] = {32'h00000f48, 32'hffebe289, 32'h218dab62};
        rom[108] = {32'h00000f22, 32'hffec0119, 32'h21799d32};
        rom[109] = {32'h00000efc, 32'hffec1f5c, 32'h2165ad6c};
        rom[110] = {32'h00000ed7, 32'hffec3d54, 32'h2151dbc4};
        rom[111] = {32'h00000eb2, 32'hffec5b02, 32'h213e27ee};
        rom[112] = {32'h00000e8e, 32'hffec7866, 32'h212a91a1};
        rom[113] = {32'h00000e6a, 32'hffec9581, 32'h21171893};
        rom[114] = {32'h00000e47, 32'hffecb255, 32'h2103bc7e};
        rom[115] = {32'h00000e24, 32'hffeccee2, 32'h20f07d18};
        rom[116] = {32'h00000e02, 32'hffeceb2a, 32'h20dd5a1e};
        rom[117] = {32'h00000de0, 32'hffed072d, 32'h20ca5348};
        rom[118] = {32'h00000dbe, 32'hffed22ec, 32'h20b76854};
        rom[119] = {32'h00000d9d, 32'hffed3e69, 32'h20a498fe};
        rom[120] = {32'h00000d7d, 32'hffed59a3, 32'h2091e503};
        rom[121] = {32'h00000d5d, 32'hffed749c, 32'h207f4c22};
        rom[122] = {32'h00000d3d, 32'hffed8f55, 32'h206cce1b};
        rom[123] = {32'h00000d1e, 32'hffeda9cf, 32'h205a6aac};
        rom[124] = {32'h00000cff, 32'hffedc40a, 32'h20482198};
        rom[125] = {32'h00000ce0, 32'hffedde07, 32'h2035f2a0};
        rom[126] = {32'h00000cc2, 32'hffedf7c8, 32'h2023dd87};
        rom[127] = {32'h00000ca4, 32'hffee114c, 32'h2011e210};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
