/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=11 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m11 #(parameter integer WMAN = 11, parameter integer D = 2, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 5;
    localparam integer RW   = 6;
    localparam integer CW   = 26;
    localparam integer ACCW = 28;
    localparam integer NSEG = 32;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {26'h00042bc, 26'h3f8ec6b, 26'h0ffffe8};
        rom[  1] = {26'h0003ab0, 26'h3f971b0, 26'h0f92ee5};
        rom[  2] = {26'h00033f7, 26'h3f9e6e8, 26'h0f2db21};
        rom[  3] = {26'h0002e4b, 26'h3fa4eb5, 26'h0ecf5e1};
        rom[  4] = {26'h0002979, 26'h3faab31, 26'h0e772c8};
        rom[  5] = {26'h0002556, 26'h3fafe0d, 26'h0e2475b};
        rom[  6] = {26'h00021c5, 26'h3fb48a7, 26'h0dd6aab};
        rom[  7] = {26'h0001eab, 26'h3fb8c22, 26'h0d8d506};
        rom[  8] = {26'h0001bf6, 26'h3fbc96b, 26'h0d47fc5};
        rom[  9] = {26'h0001995, 26'h3fc014c, 26'h0d06519};
        rom[ 10] = {26'h000177b, 26'h3fc346d, 26'h0cc7fef};
        rom[ 11] = {26'h000159e, 26'h3fc635b, 26'h0c8cbcc};
        rom[ 12] = {26'h00013f5, 26'h3fc8e90, 26'h0c544bc};
        rom[ 13] = {26'h000127a, 26'h3fcb675, 26'h0c1e73a};
        rom[ 14] = {26'h0001125, 26'h3fcdb63, 26'h0beb021};
        rom[ 15] = {26'h0000ff2, 26'h3fcfda9, 26'h0bb9ca3};
        rom[ 16] = {26'h0000edd, 26'h3fd1d89, 26'h0b8aa38};
        rom[ 17] = {26'h0000de2, 26'h3fd3b40, 26'h0b5d699};
        rom[ 18] = {26'h0000cfd, 26'h3fd5700, 26'h0b31fb6};
        rom[ 19] = {26'h0000c2d, 26'h3fd70f8, 26'h0b083ae};
        rom[ 20] = {26'h0000b6f, 26'h3fd8951, 26'h0ae00d0};
        rom[ 21] = {26'h0000ac1, 26'h3fda02d, 26'h0ab958c};
        rom[ 22] = {26'h0000a22, 26'h3fdb5ae, 26'h0a94078};
        rom[ 23] = {26'h000098f, 26'h3fdc9f0, 26'h0a70045};
        rom[ 24] = {26'h0000908, 26'h3fddd0d, 26'h0a4d3c1};
        rom[ 25] = {26'h000088b, 26'h3fdef1b, 26'h0a2b9d3};
        rom[ 26] = {26'h0000817, 26'h3fe002f, 26'h0a0b175};
        rom[ 27] = {26'h00007ac, 26'h3fe105c, 26'h09eb9b9};
        rom[ 28] = {26'h0000748, 26'h3fe1fb2, 26'h09cd1be};
        rom[ 29] = {26'h00006ec, 26'h3fe2e42, 26'h09af8b7};
        rom[ 30] = {26'h0000696, 26'h3fe3c19, 26'h0992de4};
        rom[ 31] = {26'h0000645, 26'h3fe4944, 26'h0977091};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
