/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=36 (degree 4); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m36 #(parameter integer WMAN = 36, parameter integer D = 4, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 4) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 8;
    localparam integer RW   = 28;
    localparam integer CW   = 51;
    localparam integer ACCW = 53;
    localparam integer NSEG = 256;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {51'h000000004fd3f, 51'h7fffffcc3abcc, 51'h000023aae204e, 51'h7fe3aae26b5ec, 51'h1fffffffffffc};
        rom[  1] = {51'h000000004d539, 51'h7fffffcd7a049, 51'h00002311706a9, 51'h7fe3f19e1eee0, 51'h1fe3ce59d7f38};
        rom[  2] = {51'h000000004aebe, 51'h7fffffceaf4b5, 51'h0000227badad4, 51'h7fe4372aa31eb, 51'h1fc7e2d72ea3c};
        rom[  3] = {51'h00000000489bc, 51'h7fffffcfdaf3a, 51'h000021e97c5d5, 51'h7fe47b8f380a3, 51'h1fac3c4c79a67};
        rom[  4] = {51'h0000000046621, 51'h7fffffd0fd5bb, 51'h0000215ac02c8, 51'h7fe4bed2e40e4, 51'h1f90d995519cd};
        rom[  5] = {51'h00000000443de, 51'h7fffffd216dd7, 51'h000020cf5de0b, 51'h7fe500fc76024, 51'h1f75b9943994e};
        rom[  6] = {51'h00000000422e4, 51'h7fffffd327cec, 51'h000020473b477, 51'h7fe5421287532, 51'h1f5adb326892c};
        rom[  7] = {51'h0000000040322, 51'h7fffffd43081a, 51'h00001fc23f2a3, 51'h7fe5821b7e06d, 51'h1f403d5f9529e};
        rom[  8] = {51'h000000003e48d, 51'h7fffffd531448, 51'h00001f4051432, 51'h7fe5c11d8ea88, 51'h1f25df11c30e5};
        rom[  9] = {51'h000000003c717, 51'h7fffffd62a625, 51'h00001ec15a324, 51'h7fe5ff1ebe1f4, 51'h1f0bbf451286e};
        rom[ 10] = {51'h000000003aab2, 51'h7fffffd71c22b, 51'h00001e454373b, 51'h7fe63c24e3702, 51'h1ef1dcfb91abd};
        rom[ 11] = {51'h0000000038f54, 51'h7fffffd806ca4, 51'h00001dcbf755e, 51'h7fe67835a96c0, 51'h1ed8373d0f5d2};
        rom[ 12] = {51'h00000000374f2, 51'h7fffffd8ea9a9, 51'h00001d5560f06, 51'h7fe6b356904b6, 51'h1ebecd16efde3};
        rom[ 13] = {51'h0000000035b80, 51'h7fffffd9c7d27, 51'h00001ce16c1b8, 51'h7fe6ed8cef381, 51'h1ea59d9c03035};
        rom[ 14] = {51'h00000000342f4, 51'h7fffffda9eadf, 51'h00001c700567e, 51'h7fe726ddf5c5f, 51'h1e8ca7e45be0f};
        rom[ 15] = {51'h0000000032b45, 51'h7fffffdb6f66b, 51'h00001c011a16c, 51'h7fe75f4ead5c5, 51'h1e73eb0d29ebb};
        rom[ 16] = {51'h000000003146a, 51'h7fffffdc3a33f, 51'h00001b9498127, 51'h7fe796e3fa8ef, 51'h1e5b663893797};
        rom[ 17] = {51'h000000002fe59, 51'h7fffffdcff4a7, 51'h00001b2a6de78, 51'h7fe7cda29e69d, 51'h1e43188d91951};
        rom[ 18] = {51'h000000002e90b, 51'h7fffffddbedcf, 51'h00001ac28abda, 51'h7fe8038f37ae2, 51'h1e2b0137cd161};
        rom[ 19] = {51'h000000002d477, 51'h7fffffde791c1, 51'h00001a5cde51a, 51'h7fe838ae4402c, 51'h1e131f677cef3};
        rom[ 20] = {51'h000000002c096, 51'h7fffffdf2e367, 51'h000019f958ef2, 51'h7fe86d042117d, 51'h1dfb725145a6d};
        rom[ 21] = {51'h000000002ad61, 51'h7fffffdfde58c, 51'h00001997eb6ac, 51'h7fe8a0950dbed, 51'h1de3f92e19ed6};
        rom[ 22] = {51'h0000000029ad1, 51'h7fffffe089adf, 51'h00001938871ca, 51'h7fe8d3652af6b, 51'h1dccb33b1c458};
        rom[ 23] = {51'h00000000288e0, 51'h7fffffe1305f4, 51'h000018db1ddb3, 51'h7fe905787cedf, 51'h1db59fb981b3a};
        rom[ 24] = {51'h0000000027786, 51'h7fffffe1d2943, 51'h0000187fa1f5f, 51'h7fe936d2ebf9c, 51'h1d9ebdee7569c};
        rom[ 25] = {51'h00000000266be, 51'h7fffffe27072e, 51'h000018260630d, 51'h7fe9677845839, 51'h1d880d22fd65c};
        rom[ 26] = {51'h0000000025683, 51'h7fffffe30a1fc, 51'h000017ce3dbfa, 51'h7fe9976c3ced4, 51'h1d718ca3dff8b};
        rom[ 27] = {51'h00000000246cf, 51'h7fffffe39fbde, 51'h000017783c416, 51'h7fe9c6b26c6c4, 51'h1d5b3bc18a2d4};
        rom[ 28] = {51'h000000002379c, 51'h7fffffe4316f2, 51'h00001723f5bcb, 51'h7fe9f54e55dc5, 51'h1d4519cff7058};
        rom[ 29] = {51'h00000000228e7, 51'h7fffffe4bf53d, 51'h000016d15e9b1, 51'h7fea2343638a0, 51'h1d2f262697874};
        rom[ 30] = {51'h0000000021aa9, 51'h7fffffe5498b2, 51'h000016806ba5c, 51'h7fea5094e8f52, 51'h1d1960203b8e5};
        rom[ 31] = {51'h0000000020cdf, 51'h7fffffe5d0333, 51'h000016311201a, 51'h7fea7d46238c4, 51'h1d03c71afb5ec};
        rom[ 32] = {51'h000000001ff84, 51'h7fffffe65368c, 51'h000015e3472c0, 51'h7feaa95a3b60b, 51'h1cee5a7821ed9};
        rom[ 33] = {51'h000000001f294, 51'h7fffffe6d347b, 51'h0000159700f71, 51'h7fead4d443d3d, 51'h1cd9199c17db1};
        rom[ 34] = {51'h000000001e60b, 51'h7fffffe74feab, 51'h0000154c3586e, 51'h7feaffb73c3de, 51'h1cc403ee4f16b};
        rom[ 35] = {51'h000000001d9e5, 51'h7fffffe7c96b9, 51'h00001502db4e6, 51'h7feb2a06108e7, 51'h1caf18d92f26b};
        rom[ 36] = {51'h000000001ce1f, 51'h7fffffe83fe31, 51'h000014bae90c3, 51'h7feb53c399e71, 51'h1c9a57ca020d4};
        rom[ 37] = {51'h000000001c2b5, 51'h7fffffe8b3692, 51'h0000147455c81, 51'h7feb7cf29f306, 51'h1c85c030e1c56};
        rom[ 38] = {51'h000000001b7a4, 51'h7fffffe92414c, 51'h0000142f18d02, 51'h7feba595d5a93, 51'h1c715180a6523};
        rom[ 39] = {51'h000000001ace9, 51'h7fffffe991fc3, 51'h000013eb29b67, 51'h7febcdafe170d, 51'h1c5d0b2ed45a7};
        rom[ 40] = {51'h000000001a280, 51'h7fffffe9fd34d, 51'h000013a8804e4, 51'h7febf543560c5, 51'h1c48ecb38c4c4};
        rom[ 41] = {51'h0000000019866, 51'h7fffffea65d33, 51'h0000136714a9f, 51'h7fec1c52b6e70, 51'h1c34f5897a038};
        rom[ 42] = {51'h0000000018e99, 51'h7fffffeacbeb4, 51'h00001326df18c, 51'h7fec42e077cde, 51'h1c21252dc4ede};
        rom[ 43] = {51'h0000000018517, 51'h7fffffeb2f903, 51'h000012e7d8247, 51'h7fec68eefd675, 51'h1c0d7b2000a92};
        rom[ 44] = {51'h0000000017bdc, 51'h7fffffeb90d48, 51'h000012a9f88f4, 51'h7fec8e809da63, 51'h1bf9f6e21e165};
        rom[ 45] = {51'h00000000172e5, 51'h7fffffebefca0, 51'h0000126d39523, 51'h7fecb397a038f, 51'h1be697f85cdde};
        rom[ 46] = {51'h0000000016a32, 51'h7fffffec4c821, 51'h00001231939ac, 51'h7fecd8363ef4a, 51'h1bd35de93d614};
        rom[ 47] = {51'h00000000161be, 51'h7fffffeca70d4, 51'h000011f700c95, 51'h7fecfc5ea63cb, 51'h1bc0483d7315b};
        rom[ 48] = {51'h0000000015989, 51'h7fffffecff7ba, 51'h000011bd7a6f6, 51'h7fed2012f5669, 51'h1bad567fd744b};
        rom[ 49] = {51'h0000000015190, 51'h7fffffed55dcc, 51'h00001184fa4dc, 51'h7fed43553f1a5, 51'h1b9a883d5c2eb};
        rom[ 50] = {51'h00000000149d0, 51'h7fffffedaa3f9, 51'h0000114d7a532, 51'h7fed662789aff, 51'h1b87dd05008c7};
        rom[ 51] = {51'h0000000014249, 51'h7fffffedfcb29, 51'h00001116f49a4, 51'h7fed888bcf88d, 51'h1b755467c36be};
        rom[ 52] = {51'h0000000013af8, 51'h7fffffee4d43d, 51'h000010e16368d, 51'h7fedaa83ff674, 51'h1b62edf898660};
        rom[ 53] = {51'h00000000133db, 51'h7fffffee9c00c, 51'h000010acc12d9, 51'h7fedcc11fcc22, 51'h1b50a94c5c294};
        rom[ 54] = {51'h0000000012cf1, 51'h7fffffeee8f68, 51'h00001079087f6, 51'h7feded37a0164, 51'h1b3e85f9c9575};
        rom[ 55] = {51'h0000000012637, 51'h7fffffef3431c, 51'h00001046341b9, 51'h7fee0df6b734a, 51'h1b2c83996db26};
        rom[ 56] = {51'h0000000011fad, 51'h7fffffef7dbea, 51'h000010143ee4d, 51'h7fee2e51058ec, 51'h1b1aa1c59f97b};
        rom[ 57] = {51'h0000000011951, 51'h7fffffefc5a91, 51'h00000fe323e1e, 51'h7fee4e48447f8, 51'h1b08e01a73c4a};
        rom[ 58] = {51'h0000000011321, 51'h7ffffff00bfc7, 51'h00000fb2de3c7, 51'h7fee6dde2392a, 51'h1af73e35b3641};
        rom[ 59] = {51'h0000000010d1c, 51'h7ffffff050c3d, 51'h00000f83693ff, 51'h7fee8d1448c8f, 51'h1ae5bbb6d2618};
        rom[ 60] = {51'h0000000010740, 51'h7ffffff09409f, 51'h00000f54c0588, 51'h7feeabec50db2, 51'h1ad4583ee5ffe};
        rom[ 61] = {51'h000000001018d, 51'h7ffffff0d5d93, 51'h00000f26df11d, 51'h7feeca67cf79e, 51'h1ac313709bb16};
        rom[ 62] = {51'h000000000fc00, 51'h7ffffff1163b9, 51'h00000ef9c1165, 51'h7feee8884f8c2, 51'h1ab1ecf0302ef};
        rom[ 63] = {51'h000000000f699, 51'h7ffffff1553ad, 51'h00000ecd622de, 51'h7fef064f536b5, 51'h1aa0e46366ccd};
        rom[ 64] = {51'h000000000f156, 51'h7ffffff192e05, 51'h00000ea1be3d6, 51'h7fef23be551dc, 51'h1a8ff971810a5};
        rom[ 65] = {51'h000000000ec37, 51'h7ffffff1cf354, 51'h00000e76d1452, 51'h7fef40d6c68f0, 51'h1a7f2bc3365b2};
        rom[ 66] = {51'h000000000e73a, 51'h7ffffff20a426, 51'h00000e4c9760b, 51'h7fef5d9a11c6e, 51'h1a6e7b02ac27f};
        rom[ 67] = {51'h000000000e25f, 51'h7ffffff244105, 51'h00000e230cc57, 51'h7fef7a09991e0, 51'h1a5de6db6e057};
        rom[ 68] = {51'h000000000dda3, 51'h7ffffff27ca76, 51'h00000dfa2dc24, 51'h7fef9626b7719, 51'h1a4d6efa661f2};
        rom[ 69] = {51'h000000000d906, 51'h7ffffff2b40f8, 51'h00000dd1f6be5, 51'h7fefb1f2c054d, 51'h1a3d130dd5d46};
        rom[ 70] = {51'h000000000d488, 51'h7ffffff2ea508, 51'h00000daa6438b, 51'h7fefcd6f00417, 51'h1a2cd2c54e875};
        rom[ 71] = {51'h000000000d027, 51'h7ffffff31f720, 51'h00000d8372c75, 51'h7fefe89cbcc65, 51'h1a1cadd1aa9a7};
        rom[ 72] = {51'h000000000cbe3, 51'h7ffffff3537b4, 51'h00000d5d1f16a, 51'h7ff0037d34b4b, 51'h1a0ca3e5069c7};
        rom[ 73] = {51'h000000000c7ba, 51'h7ffffff386736, 51'h00000d3765e88, 51'h7ff01e11a04c4, 51'h19fcb4b2baa12};
        rom[ 74] = {51'h000000000c3ab, 51'h7ffffff3b8614, 51'h00000d124413f, 51'h7ff0385b3165c, 51'h19ecdfef53c4d};
        rom[ 75] = {51'h000000000bfb7, 51'h7ffffff3e94ba, 51'h00000cedb6844, 51'h7ff0525b139c4, 51'h19dd25508dda7};
        rom[ 76] = {51'h000000000bbdc, 51'h7ffffff41938e, 51'h00000cc9ba387, 51'h7ff06c126c756, 51'h19cd848d4d41f};
        rom[ 77] = {51'h000000000b819, 51'h7ffffff4482f7, 51'h00000ca64c42d, 51'h7ff085825b87f, 51'h19bdfd5d98e66};
        rom[ 78] = {51'h000000000b46e, 51'h7ffffff476354, 51'h00000c8369c82, 51'h7ff09eabfaa21, 51'h19ae8f7a94621};
        rom[ 79] = {51'h000000000b0da, 51'h7ffffff4a3505, 51'h00000c610fff4, 51'h7ff0b7905deda, 51'h199f3a9e7a486};
        rom[ 80] = {51'h000000000ad5c, 51'h7ffffff4cf867, 51'h00000c3f3c30a, 51'h7ff0d0309413b, 51'h198ffe8496933};
        rom[ 81] = {51'h000000000a9f4, 51'h7ffffff4fadd2, 51'h00000c1debb58, 51'h7ff0e88da65f4, 51'h1980dae94133a};
        rom[ 82] = {51'h000000000a6a2, 51'h7ffffff52559d, 51'h00000bfd1bf7f, 51'h7ff100a898dec, 51'h1971cf89d8c4c};
        rom[ 83] = {51'h000000000a363, 51'h7ffffff54f01d, 51'h00000bdcca71d, 51'h7ff118826a848, 51'h1962dc24bd5f5};
        rom[ 84] = {51'h000000000a039, 51'h7ffffff577da4, 51'h00000bbcf4aca, 51'h7ff1301c15465, 51'h195400794b8d9};
        rom[ 85] = {51'h0000000009d21, 51'h7ffffff59fe80, 51'h00000b9d98411, 51'h7ff147768e3c5, 51'h19453c47d75e4};
        rom[ 86] = {51'h0000000009a1d, 51'h7ffffff5c7300, 51'h00000b7eb2d67, 51'h7ff15e92c5bec, 51'h19368f51a795a};
        rom[ 87] = {51'h000000000972b, 51'h7ffffff5edb6e, 51'h00000b6042228, 51'h7ff17571a782d, 51'h1927f958f0fca};
        rom[ 88] = {51'h000000000944a, 51'h7ffffff613813, 51'h00000b4243e8a, 51'h7ff18c141ab6f, 51'h19197a20d1cb6};
        rom[ 89] = {51'h000000000917b, 51'h7ffffff638936, 51'h00000b24b5f9f, 51'h7ff1a27b021e5, 51'h190b116d4d30c};
        rom[ 90] = {51'h0000000008ebd, 51'h7ffffff65cf1d, 51'h00000b0796349, 51'h7ff1b8a73c2b2, 51'h18fcbf0346f41};
        rom[ 91] = {51'h0000000008c0e, 51'h7ffffff680a0a, 51'h00000aeae2835, 51'h7ff1ce99a318d, 51'h18ee82a87f315};
        rom[ 92] = {51'h0000000008970, 51'h7ffffff6a3a3f, 51'h00000ace98dd7, 51'h7ff1e4530d04e, 51'h18e05c238e2ef};
        rom[ 93] = {51'h00000000086e1, 51'h7ffffff6c5ffa, 51'h00000ab2b7466, 51'h7ff1f9d44c078, 51'h18d24b3be04c2};
        rom[ 94] = {51'h0000000008461, 51'h7ffffff6e7b79, 51'h00000a973bcd2, 51'h7ff20f1e2e4b6, 51'h18c44fb9b207b};
        rom[ 95] = {51'h00000000081f0, 51'h7ffffff708cfa, 51'h00000a7c248c2, 51'h7ff224317e24b, 51'h18b669660c1dd};
        rom[ 96] = {51'h0000000007f8d, 51'h7ffffff7294b5, 51'h00000a616fa8f, 51'h7ff2390f0227b, 51'h18a8980abfbd3};
        rom[ 97] = {51'h0000000007d37, 51'h7ffffff7492e3, 51'h00000a471b53e, 51'h7ff24db77d3e9, 51'h189adb7262d1d};
        rom[ 98] = {51'h0000000007aef, 51'h7ffffff7687bc, 51'h00000a2d25c7d, 51'h7ff2622baebeb, 51'h188d33684c65e};
        rom[ 99] = {51'h00000000078b5, 51'h7ffffff787376, 51'h00000a138d49c, 51'h7ff2766c527d6, 51'h187f9fb891170};
        rom[100] = {51'h0000000007687, 51'h7ffffff7a5645, 51'h000009fa5028b, 51'h7ff28a7a20e42, 51'h1872202fffa0d};
        rom[101] = {51'h0000000007465, 51'h7ffffff7c305b, 51'h000009e16cbd6, 51'h7ff29e55cf041, 51'h1864b49c1d7a5};
        rom[102] = {51'h000000000724f, 51'h7ffffff7e01eb, 51'h000009c8e169f, 51'h7ff2b2000ea93, 51'h18575ccb2387c};
        rom[103] = {51'h0000000007045, 51'h7ffffff7fcb24, 51'h000009b0ac998, 51'h7ff2c5798e6ce, 51'h184a188bfade8};
        rom[104] = {51'h0000000006e47, 51'h7ffffff818c37, 51'h00000998ccc06, 51'h7ff2d8c2f9c81, 51'h183ce7ae399b7};
        rom[105] = {51'h0000000006c54, 51'h7ffffff83454f, 51'h00000981405b8, 51'h7ff2ebdcf924d, 51'h182fca021fcbc};
        rom[106] = {51'h0000000006a6b, 51'h7ffffff84f69b, 51'h0000096a05f03, 51'h7ff2fec831efa, 51'h1822bf5894664};
        rom[107] = {51'h000000000688d, 51'h7ffffff86a045, 51'h000009531c0c2, 51'h7ff3118546a7d, 51'h1815c78322566};
        rom[108] = {51'h00000000066ba, 51'h7ffffff884278, 51'h0000093c8144f, 51'h7ff32414d6f05, 51'h1808e253f5977};
        rom[109] = {51'h00000000064f0, 51'h7ffffff89dd5c, 51'h0000092634382, 51'h7ff336777f9f2, 51'h17fc0f9dd85fd};
        rom[110] = {51'h0000000006331, 51'h7ffffff8b711b, 51'h00000910338ae, 51'h7ff348addaccd, 51'h17ef4f34305bd};
        rom[111] = {51'h000000000617b, 51'h7ffffff8cfddc, 51'h000008fa7de9c, 51'h7ff35ab87fe3f, 51'h17e2a0eafbf84};
        rom[112] = {51'h0000000005fce, 51'h7ffffff8e83c3, 51'h000008e512088, 51'h7ff36c9803af4, 51'h17d60496cfbb5};
        rom[113] = {51'h0000000005e2a, 51'h7ffffff9002f8, 51'h000008cfeea22, 51'h7ff37e4cf8685, 51'h17c97a0cd3ac1};
        rom[114] = {51'h0000000005c8f, 51'h7ffffff917b9d, 51'h000008bb12784, 51'h7ff38fd7edc57, 51'h17bd0122c0c8a};
        rom[115] = {51'h0000000005afd, 51'h7ffffff92edd6, 51'h000008a67c537, 51'h7ff3a13971072, 51'h17b099aede891};
        rom[116] = {51'h0000000005973, 51'h7ffffff9459c7, 51'h000008922b02c, 51'h7ff3b2720d057, 51'h17a443880070d};
        rom[117] = {51'h00000000057f1, 51'h7ffffff95bf8f, 51'h0000087e1d5b8, 51'h7ff3c3824a3cd, 51'h1797fe8583ac8};
        rom[118] = {51'h0000000005677, 51'h7ffffff971f51, 51'h0000086a52395, 51'h7ff3d46aaedad, 51'h178bca7f4cbcd};
        rom[119] = {51'h0000000005505, 51'h7ffffff98792b, 51'h00000856c87df, 51'h7ff3e52bbeca7, 51'h177fa74dc52d7};
        rom[120] = {51'h000000000539b, 51'h7ffffff99cd3e, 51'h000008437f110, 51'h7ff3f5c5fbbfd, 51'h177394c9d958d};
        rom[121] = {51'h0000000005238, 51'h7ffffff9b1ba8, 51'h0000083074dfe, 51'h7ff40639e5444, 51'h176792ccf6373};
        rom[122] = {51'h00000000050dc, 51'h7ffffff9c6486, 51'h0000081da8dd9, 51'h7ff41687f8c17, 51'h175ba13107395};
        rom[123] = {51'h0000000004f88, 51'h7ffffff9da7f5, 51'h0000080b1a029, 51'h7ff426b0b18ca, 51'h174fbfd0742e6};
        rom[124] = {51'h0000000004e3a, 51'h7ffffff9ee611, 51'h000007f8c74cd, 51'h7ff436b488f19, 51'h1743ee861f355};
        rom[125] = {51'h0000000004cf3, 51'h7ffffffa01ef7, 51'h000007e6afbf6, 51'h7ff44693f63cd, 51'h17382d2d62b86};
        rom[126] = {51'h0000000004bb2, 51'h7ffffffa152c0, 51'h000007d4d2628, 51'h7ff4564f6ec69, 51'h172c7ba20f732};
        rom[127] = {51'h0000000004a78, 51'h7ffffffa28188, 51'h000007c32e436, 51'h7ff465e765fc4, 51'h1720d9c06a836};
        rom[128] = {51'h0000000004945, 51'h7ffffffa3ab68, 51'h000007b1c2741, 51'h7ff4755c4d6aa, 51'h171547652b830};
        rom[129] = {51'h0000000004817, 51'h7ffffffa4d079, 51'h000007a08e0b7, 51'h7ff484ae94c77, 51'h1709c46d7aac7};
        rom[130] = {51'h00000000046ef, 51'h7ffffffa5f0d3, 51'h0000078f9024f, 51'h7ff493dea9fab, 51'h16fe50b6ef085};
        rom[131] = {51'h00000000045cd, 51'h7ffffffa70c8e, 51'h0000077ec7e08, 51'h7ff4a2ecf927e, 51'h16f2ec1f8ca41};
        rom[132] = {51'h00000000044b1, 51'h7ffffffa823c2, 51'h0000076e3462a, 51'h7ff4b1d9ecb6e, 51'h16e79685c2d22};
        rom[133] = {51'h000000000439b, 51'h7ffffffa93685, 51'h0000075dd4d3f, 51'h7ff4c0a5ed5cc, 51'h16dc4fc86a72d};
        rom[134] = {51'h0000000004289, 51'h7ffffffaa44ed, 51'h0000074da8618, 51'h7ff4cf5162242, 51'h16d117c6c4457};
        rom[135] = {51'h000000000417d, 51'h7ffffffab4f11, 51'h0000073dae3c4, 51'h7ff4dddcb075f, 51'h16c5ee6077427};
        rom[136] = {51'h0000000004077, 51'h7ffffffac5505, 51'h0000072de5996, 51'h7ff4ec483c210, 51'h16bad3758efd8};
        rom[137] = {51'h0000000003f75, 51'h7ffffffad56df, 51'h0000071e4db1e, 51'h7ff4fa9467626, 51'h16afc6e67a0fa};
        rom[138] = {51'h0000000003e78, 51'h7ffffffae54b1, 51'h0000070ee5c29, 51'h7ff508c192ed2, 51'h16a4c89408891};
        rom[139] = {51'h0000000003d80, 51'h7ffffffaf4e91, 51'h000006ffad0c2, 51'h7ff516d01df19, 51'h1699d85f6a6b6};
        rom[140] = {51'h0000000003c8d, 51'h7ffffffb04492, 51'h000006f0a2d2c, 51'h7ff524c066252, 51'h168ef62a2e2a2};
        rom[141] = {51'h0000000003b9f, 51'h7ffffffb136c6, 51'h000006e1c65e7, 51'h7ff53292c7c95, 51'h168421d63f340};
        rom[142] = {51'h0000000003ab5, 51'h7ffffffb2253f, 51'h000006d316fa7, 51'h7ff540479db2f, 51'h16795b45e4820};
        rom[143] = {51'h00000000039cf, 51'h7ffffffb31011, 51'h000006c493f5a, 51'h7ff54ddf4150e, 51'h166ea25bbf2ea};
        rom[144] = {51'h00000000038ee, 51'h7ffffffb3f74c, 51'h000006b63ca21, 51'h7ff55b5a0ab30, 51'h1663f6fac9131};
        rom[145] = {51'h0000000003811, 51'h7ffffffb4db02, 51'h000006a810553, 51'h7ff568b85090e, 51'h16595906536bc};
        rom[146] = {51'h0000000003738, 51'h7ffffffb5bb44, 51'h0000069a0e67a, 51'h7ff575fa684fd, 51'h164ec86205830};
        rom[147] = {51'h0000000003663, 51'h7ffffffb69822, 51'h0000068c36352, 51'h7ff58320a609d, 51'h164444f1db623};
        rom[148] = {51'h0000000003592, 51'h7ffffffb771ac, 51'h0000067e871c8, 51'h7ff5902b5c932, 51'h1639ce9a24896};
        rom[149] = {51'h00000000034c5, 51'h7ffffffb847f2, 51'h00000671007f7, 51'h7ff59d1add80d, 51'h162f653f82acd};
        rom[150] = {51'h00000000033fb, 51'h7ffffffb91b04, 51'h00000663a1c2c, 51'h7ff5a9ef792e5, 51'h162508c6e8788};
        rom[151] = {51'h0000000003336, 51'h7ffffffb9eaf1, 51'h000006566a4df, 51'h7ff5b6a97ec36, 51'h161ab91598598};
        rom[152] = {51'h0000000003274, 51'h7ffffffbab7c6, 51'h00000649598b6, 51'h7ff5c3493c39c, 51'h16107611234d3};
        rom[153] = {51'h00000000031b5, 51'h7ffffffbb8194, 51'h0000063c6ee84, 51'h7ff5cfcefe62b, 51'h16063f9f67b60};
        rom[154] = {51'h00000000030fa, 51'h7ffffffbc4867, 51'h0000062fa9d45, 51'h7ff5dc3b10ec4, 51'h15fc15a690358};
        rom[155] = {51'h0000000003042, 51'h7ffffffbd0c4f, 51'h0000062309c1e, 51'h7ff5e88dbe66c, 51'h15f1f80d128c2};
        rom[156] = {51'h0000000002f8e, 51'h7ffffffbdcd57, 51'h000006168e260, 51'h7ff5f4c75049e, 51'h15e7e6b9ae7dd};
        rom[157] = {51'h0000000002edd, 51'h7ffffffbe8b8e, 51'h0000060a36783, 51'h7ff600e80ef9c, 51'h15dde1936cbc0};
        rom[158] = {51'h0000000002e2f, 51'h7ffffffbf4701, 51'h000005fe02324, 51'h7ff60cf041cbf, 51'h15d3e8819dd49};
        rom[159] = {51'h0000000002d84, 51'h7ffffffbfffbb, 51'h000005f1f0d0a, 51'h7ff618e02f0c4, 51'h15c9fb6bd925b};
        rom[160] = {51'h0000000002cdc, 51'h7ffffffc0b5ca, 51'h000005e601d1f, 51'h7ff624b81c019, 51'h15c01a39fbd68};
        rom[161] = {51'h0000000002c37, 51'h7ffffffc1693a, 51'h000005da34b73, 51'h7ff630784cf27, 51'h15b644d427d47};
        rom[162] = {51'h0000000002b95, 51'h7ffffffc21a16, 51'h000005ce8903b, 51'h7ff63c2105299, 51'h15ac7b22c2d53};
        rom[163] = {51'h0000000002af6, 51'h7ffffffc2c86b, 51'h000005c2fe3cc, 51'h7ff647b286fa7, 51'h15a2bd0e755d2};
        rom[164] = {51'h0000000002a5a, 51'h7ffffffc37443, 51'h000005b793ea1, 51'h7ff6532d13c59, 51'h15990a8029ca6};
        rom[165] = {51'h00000000029c0, 51'h7ffffffc41daa, 51'h000005ac49956, 51'h7ff65e90ebfcc, 51'h158f63610b63d};
        rom[166] = {51'h0000000002929, 51'h7ffffffc4c4aa, 51'h000005a11eca6, 51'h7ff669de4f275, 51'h1585c79a856c8};
        rom[167] = {51'h0000000002895, 51'h7ffffffc5694f, 51'h000005961316e, 51'h7ff675157be65, 51'h157c3716423b7};
        rom[168] = {51'h0000000002803, 51'h7ffffffc60ba3, 51'h0000058b260ad, 51'h7ff68036aff83, 51'h1572b1be2a56e};
        rom[169] = {51'h0000000002774, 51'h7ffffffc6abb0, 51'h000005805737d, 51'h7ff68b42283d2, 51'h1569377c63944};
        rom[170] = {51'h00000000026e7, 51'h7ffffffc7497f, 51'h00000575a6318, 51'h7ff6963820bab, 51'h155fc83b503b6};
        rom[171] = {51'h000000000265d, 51'h7ffffffc7e51c, 51'h0000056b128d8, 51'h7ff6a118d49f7, 51'h155663e58e2e0};
        rom[172] = {51'h00000000025d5, 51'h7ffffffc87e90, 51'h000005609be31, 51'h7ff6abe47e470, 51'h154d0a65f6128};
        rom[173] = {51'h000000000254f, 51'h7ffffffc915e4, 51'h0000055641cb6, 51'h7ff6b69b573d6, 51'h1543bba79a82e};
        rom[174] = {51'h00000000024cc, 51'h7ffffffc9ab21, 51'h0000054c03e14, 51'h7ff6c13d9842a, 51'h153a7795c73ed};
        rom[175] = {51'h000000000244b, 51'h7ffffffca3e50, 51'h00000541e1c15, 51'h7ff6cbcb794e4, 51'h15313e1c00617};
        rom[176] = {51'h00000000023cc, 51'h7ffffffcacf7b, 51'h00000537db09f, 51'h7ff6d6453192a, 51'h15280f26019ab};
        rom[177] = {51'h000000000234f, 51'h7ffffffcb5ea9, 51'h0000052def5af, 51'h7ff6e0aaf7806, 51'h151eea9fbd6ba};
        rom[178] = {51'h00000000022d4, 51'h7ffffffcbebe5, 51'h000005241e55e, 51'h7ff6eafd00c9c, 51'h1515d0755c667};
        rom[179] = {51'h000000000225b, 51'h7ffffffcc7735, 51'h0000051a679e0, 51'h7ff6f53b82657, 51'h150cc0933c71a};
        rom[180] = {51'h00000000021e5, 51'h7ffffffcd00a2, 51'h00000510cad7e, 51'h7ff6ff66b0923, 51'h1503bae5f00e2};
        rom[181] = {51'h0000000002170, 51'h7ffffffcd8834, 51'h0000050747a9c, 51'h7ff7097ebed98, 51'h14fabf5a3da0a};
        rom[182] = {51'h00000000020fd, 51'h7ffffffce0df4, 51'h000004fdddbb6, 51'h7ff71383e012e, 51'h14f1cddd1ebe2};
        rom[183] = {51'h000000000208c, 51'h7ffffffce91e8, 51'h000004f48cb5d, 51'h7ff71d764666a, 51'h14e8e65bbf7b7};
        rom[184] = {51'h000000000201d, 51'h7ffffffcf1419, 51'h000004eb5443c, 51'h7ff727562350d, 51'h14e008c37dbf2};
        rom[185] = {51'h0000000001fb0, 51'h7ffffffcf948d, 51'h000004e234113, 51'h7ff73123a7a43, 51'h14d73501e8970};
        rom[186] = {51'h0000000001f44, 51'h7ffffffd0134c, 51'h000004d92bcb7, 51'h7ff73adf038cf, 51'h14ce6b04bf903};
        rom[187] = {51'h0000000001edb, 51'h7ffffffd0905d, 51'h000004d03b215, 51'h7ff7448866932, 51'h14c5aab9f2119};
        rom[188] = {51'h0000000001e73, 51'h7ffffffd10bc8, 51'h000004c761c2d, 51'h7ff74e1fff9df, 51'h14bcf40f9eb98};
        rom[189] = {51'h0000000001e0c, 51'h7ffffffd18592, 51'h000004be9f615, 51'h7ff757a5fcf5a, 51'h14b446f412bde};
        rom[190] = {51'h0000000001da8, 51'h7ffffffd1fdc4, 51'h000004b5f3af7, 51'h7ff7611a8c46d, 51'h14aba355c94ec};
        rom[191] = {51'h0000000001d45, 51'h7ffffffd27462, 51'h000004ad5e612, 51'h7ff76a7ddaa45, 51'h14a309236afbb};
        rom[192] = {51'h0000000001ce3, 51'h7ffffffd2e975, 51'h000004a4df2b6, 51'h7ff773d0148a2, 51'h149a784bcd1b9};
        rom[193] = {51'h0000000001c83, 51'h7ffffffd35d01, 51'h0000049c75c4a, 51'h7ff77d1165dfa, 51'h1491f0bdf1369};
        rom[194] = {51'h0000000001c25, 51'h7ffffffd3cf0e, 51'h0000049421e45, 51'h7ff78641f9fa0, 51'h1489726904732};
        rom[195] = {51'h0000000001bc8, 51'h7ffffffd43fa2, 51'h0000048be3431, 51'h7ff78f61fb9e8, 51'h1480fd3c5f049};
        rom[196] = {51'h0000000001b6d, 51'h7ffffffd4aec2, 51'h00000483b99aa, 51'h7ff798719504f, 51'h14789127839cc};
        rom[197] = {51'h0000000001b13, 51'h7ffffffd51c74, 51'h0000047ba4a60, 51'h7ff7a170efd9c, 51'h14702e1a1edf4};
        rom[198] = {51'h0000000001aba, 51'h7ffffffd588bf, 51'h00000473a4212, 51'h7ff7aa6035405, 51'h1467d40406d77};
        rom[199] = {51'h0000000001a63, 51'h7ffffffd5f3a7, 51'h0000046bb7c91, 51'h7ff7b33f8dd4e, 51'h145f82d53a707};
        rom[200] = {51'h0000000001a0d, 51'h7ffffffd65d33, 51'h00000463df5be, 51'h7ff7bc0f21af2, 51'h14573a7de0ef0};
        rom[201] = {51'h00000000019b9, 51'h7ffffffd6c568, 51'h0000045c1a98d, 51'h7ff7c4cf1863d, 51'h144efaee496e1};
        rom[202] = {51'h0000000001966, 51'h7ffffffd72c4b, 51'h0000045469400, 51'h7ff7cd7f99073, 51'h1446c416ea5cc};
        rom[203] = {51'h0000000001914, 51'h7ffffffd791e1, 51'h0000044ccb129, 51'h7ff7d620ca2ea, 51'h143e95e860fef};
        rom[204] = {51'h00000000018c3, 51'h7ffffffd7f630, 51'h000004453fd2a, 51'h7ff7deb2d1f2f, 51'h1436705370ef7};
        rom[205] = {51'h0000000001874, 51'h7ffffffd8593d, 51'h0000043dc7436, 51'h7ff7e735d5f21, 51'h142e534903a43};
        rom[206] = {51'h0000000001826, 51'h7ffffffd8bb0c, 51'h000004366128b, 51'h7ff7efa9fb512, 51'h14263eba27f4a};
        rom[207] = {51'h00000000017d9, 51'h7ffffffd91ba3, 51'h0000042f0d47b, 51'h7ff7f80f66be4, 51'h141e329811a19};
        rom[208] = {51'h000000000178d, 51'h7ffffffd97b06, 51'h00000427cb661, 51'h7ff800663c726, 51'h14162ed418df4};
        rom[209] = {51'h0000000001743, 51'h7ffffffd9d93a, 51'h000004209b4ac, 51'h7ff808aea0330, 51'h140e335fb9e0e};
        rom[210] = {51'h00000000016f9, 51'h7ffffffda3644, 51'h000004197cbd3, 51'h7ff810e8b5540, 51'h1406402c94666};
        rom[211] = {51'h00000000016b1, 51'h7ffffffda9228, 51'h000004126f861, 51'h7ff819149eb99, 51'h13fe552c6b4b7};
        rom[212] = {51'h000000000166a, 51'h7ffffffdaeceb, 51'h0000040b736e8, 51'h7ff821327ed96, 51'h13f672512418a};
        rom[213] = {51'h0000000001623, 51'h7ffffffdb4691, 51'h000004048840d, 51'h7ff8294277bce, 51'h13ee978cc695d};
        rom[214] = {51'h00000000015de, 51'h7ffffffdb9f1e, 51'h000003fdadc7e, 51'h7ff83144ab027, 51'h13e6c4d17c5ec};
        rom[215] = {51'h000000000159a, 51'h7ffffffdbf696, 51'h000003f6e3cf8, 51'h7ff8393939df5, 51'h13defa119078d};
        rom[216] = {51'h0000000001557, 51'h7ffffffdc4cff, 51'h000003f02a243, 51'h7ff8412045210, 51'h13d7373f6eeaa};
        rom[217] = {51'h0000000001515, 51'h7ffffffdca25b, 51'h000003e980935, 51'h7ff848f9ed2ee, 51'h13cf7c4da4553};
        rom[218] = {51'h00000000014d4, 51'h7ffffffdcf6ae, 51'h000003e2e6eae, 51'h7ff850c6520bc, 51'h13c7c92edd8e6};
        rom[219] = {51'h0000000001494, 51'h7ffffffdd49fe, 51'h000003dc5cf9d, 51'h7ff8588593573, 51'h13c01dd5e73d2};
        rom[220] = {51'h0000000001455, 51'h7ffffffdd9c4d, 51'h000003d5e28f9, 51'h7ff86037d04f5, 51'h13b87a35ad773};
        rom[221] = {51'h0000000001416, 51'h7ffffffdded9f, 51'h000003cf777c7, 51'h7ff867dd27d1f, 51'h13b0de413b602};
        rom[222] = {51'h00000000013d9, 51'h7ffffffde3df8, 51'h000003c91b917, 51'h7ff86f75b85e3, 51'h13a949ebbac9e};
        rom[223] = {51'h000000000139d, 51'h7ffffffde8d5c, 51'h000003c2cea02, 51'h7ff87701a015d, 51'h13a1bd2873d69};
        rom[224] = {51'h0000000001361, 51'h7ffffffdedbce, 51'h000003bc907af, 51'h7ff87e80fcbe8, 51'h139a37eacc9c1};
        rom[225] = {51'h0000000001326, 51'h7ffffffdf2952, 51'h000003b660f4d, 51'h7ff885f3ebc34, 51'h1392ba2648c86};
        rom[226] = {51'h00000000012ed, 51'h7ffffffdf75eb, 51'h000003b03fe18, 51'h7ff88d5a8a35f, 51'h138b43ce89480};
        rom[227] = {51'h00000000012b4, 51'h7ffffffdfc19d, 51'h000003aa2d154, 51'h7ff894b4f4d04, 51'h1383d4d74bed0};
        rom[228] = {51'h000000000127b, 51'h7ffffffe00c6b, 51'h000003a428650, 51'h7ff89c0347f53, 51'h137c6d346b179};
        rom[229] = {51'h0000000001244, 51'h7ffffffe05659, 51'h0000039e31a66, 51'h7ff8a3459fb24, 51'h13750cd9dd603};
        rom[230] = {51'h000000000120d, 51'h7ffffffe09f69, 51'h0000039848af8, 51'h7ff8aa7c17c0a, 51'h136db3bbb5429};
        rom[231] = {51'h00000000011d8, 51'h7ffffffe0e79f, 51'h000003926d572, 51'h7ff8b1a6cb86a, 51'h136661ce20ca2};
        rom[232] = {51'h00000000011a3, 51'h7ffffffe12efd, 51'h0000038c9f74c, 51'h7ff8b8c5d6189, 51'h135f1705693f4};
        rom[233] = {51'h000000000116e, 51'h7ffffffe17588, 51'h00000386dee03, 51'h7ff8bfd9523a3, 51'h1357d355f2d69};
        rom[234] = {51'h000000000113b, 51'h7ffffffe1bb41, 51'h000003812b721, 51'h7ff8c6e15a5fb, 51'h135096b43c606};
        rom[235] = {51'h0000000001108, 51'h7ffffffe2002d, 51'h0000037b85037, 51'h7ff8cdde08aed, 51'h13496114def9e};
        rom[236] = {51'h00000000010d6, 51'h7ffffffe2444d, 51'h00000375eb6df, 51'h7ff8d4cf77002, 51'h1342326c8dbf6};
        rom[237] = {51'h00000000010a5, 51'h7ffffffe287a5, 51'h000003705e8bc, 51'h7ff8dbb5bee00, 51'h133b0ab0157fa};
        rom[238] = {51'h0000000001074, 51'h7ffffffe2ca38, 51'h0000036ade379, 51'h7ff8e290f98fa, 51'h1333e9d45c700};
        rom[239] = {51'h0000000001044, 51'h7ffffffe30c08, 51'h000003656a4cc, 51'h7ff8e96140066, 51'h132ccfce61e20};
        rom[240] = {51'h0000000001015, 51'h7ffffffe34d19, 51'h0000036002a6e, 51'h7ff8f026aaf27, 51'h1325bc933df9e};
        rom[241] = {51'h0000000000fe6, 51'h7ffffffe38d6b, 51'h0000035aa7226, 51'h7ff8f6e152ba0, 51'h131eb01821660};
        rom[242] = {51'h0000000000fb8, 51'h7ffffffe3cd04, 51'h00000355579bf, 51'h7ff8fd914f7c7, 51'h1317aa5255178};
        rom[243] = {51'h0000000000f8b, 51'h7ffffffe40be4, 51'h0000035013f0d, 51'h7ff90436b9130, 51'h1310ab3739fb9};
        rom[244] = {51'h0000000000f5e, 51'h7ffffffe44a0f, 51'h0000034adbfec, 51'h7ff90ad1a7122, 51'h1309b2bc48b66};
        rom[245] = {51'h0000000000f32, 51'h7ffffffe48787, 51'h00000345afa40, 51'h7ff9116230ca1, 51'h1302c0d7115e2};
        rom[246] = {51'h0000000000f06, 51'h7ffffffe4c44f, 51'h000003408ebf4, 51'h7ff917e86d47f, 51'h12fbd57d3b37c};
        rom[247] = {51'h0000000000edc, 51'h7ffffffe50068, 51'h0000033b792fa, 51'h7ff91e647356e, 51'h12f4f0a484745};
        rom[248] = {51'h0000000000eb1, 51'h7ffffffe53bd6, 51'h000003366ed4a, 51'h7ff924d659808, 51'h12ee1242c1ef0};
        rom[249] = {51'h0000000000e87, 51'h7ffffffe5769b, 51'h000003316f8e7, 51'h7ff92b3e360e4, 51'h12e73a4ddeec9};
        rom[250] = {51'h0000000000e5e, 51'h7ffffffe5b0b9, 51'h0000032c7b3d8, 51'h7ff9319c1f0a1, 51'h12e068bbdcdb7};
        rom[251] = {51'h0000000000e36, 51'h7ffffffe5ea31, 51'h0000032791c2a, 51'h7ff937f02a3f3, 51'h12d99d82d3146};
        rom[252] = {51'h0000000000e0e, 51'h7ffffffe62308, 51'h00000322b2ff4, 51'h7ff93e3a6d3b3, 51'h12d2d898ee9cb};
        rom[253] = {51'h0000000000de6, 51'h7ffffffe65b3e, 51'h0000031dded52, 51'h7ff9447afd4ea, 51'h12cc19f471e87};
        rom[254] = {51'h0000000000dbf, 51'h7ffffffe692d6, 51'h0000031915265, 51'h7ff94ab1ef8e0, 51'h12c5618bb49e7};
        rom[255] = {51'h0000000000d99, 51'h7ffffffe6c9d3, 51'h0000031455d57, 51'h7ff950df58d29, 51'h12beaf55235c2};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
