/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=27 (degree 3); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m27 #(parameter integer WMAN = 27, parameter integer D = 3, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 8;
    localparam integer RW   = 19;
    localparam integer CW   = 42;
    localparam integer ACCW = 44;
    localparam integer NSEG = 256;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {42'h3fffffe66d3, 42'h000011d53f1, 42'h3ff1d5713fb, 42'h0fffffffffb};
        rom[  1] = {42'h3fffffe70a6, 42'h0000118887e, 42'h3ff1f8cf192, 42'h0ff1e72cebb};
        rom[  2] = {42'h3fffffe7a29, 42'h0000113da80, 42'h3ff21b955af, 42'h0fe3f16b970};
        rom[  3] = {42'h3fffffe8362, 42'h000010f490c, 42'h3ff23dc7a52, 42'h0fd61e263c9};
        rom[  4] = {42'h3fffffe8c51, 42'h000010ad341, 42'h3ff25f697ad, 42'h0fc86ccaa88};
        rom[  5] = {42'h3fffffe94fb, 42'h00001067844, 42'h3ff2807e439, 42'h0fbadcca1c8};
        rom[  6] = {42'h3fffffe9d62, 42'h00001023744, 42'h3ff2a1094bf, 42'h0fad6d99340};
        rom[  7] = {42'h3fffffea587, 42'h00000fe0f77, 42'h3ff2c10dc71, 42'h0fa01eafca5};
        rom[  8] = {42'h3fffffead6f, 42'h00000fa001b, 42'h3ff2e08ecf2, 42'h0f92ef88e15};
        rom[  9] = {42'h3fffffeb51a, 42'h00000f60875, 42'h3ff2ff8f66a, 42'h0f85dfa2890};
        rom[ 10] = {42'h3fffffebc8c, 42'h00000f227d1, 42'h3ff31e12791, 42'h0f78ee7dc8a};
        rom[ 11] = {42'h3fffffec3c6, 42'h00000ee5d81, 42'h3ff33c1adbd, 42'h0f6c1b9e877};
        rom[ 12] = {42'h3fffffecaca, 42'h00000eaa8de, 42'h3ff359ab4f1, 42'h0f5f668b77b};
        rom[ 13] = {42'h3fffffed19a, 42'h00000e70947, 42'h3ff376c67e5, 42'h0f52cece015};
        rom[ 14] = {42'h3fffffed839, 42'h00000e37e21, 42'h3ff3936f017, 42'h0f4653f22dc};
        rom[ 15] = {42'h3fffffedea7, 42'h00000e006d5, 42'h3ff3afa75d0, 42'h0f39f58694c};
        rom[ 16] = {42'h3fffffee4e6, 42'h00000dca2d4, 42'h3ff3cb72037, 42'h0f2db31c499};
        rom[ 17] = {42'h3fffffeeaf9, 42'h00000d95190, 42'h3ff3e6d1553, 42'h0f218c46c8a};
        rom[ 18] = {42'h3fffffef0e0, 42'h00000d61284, 42'h3ff401c7a1b, 42'h0f15809be66};
        rom[ 19] = {42'h3fffffef69d, 42'h00000d2e52e, 42'h3ff41c5727b, 42'h0f098fb3be5};
        rom[ 20] = {42'h3fffffefc32, 42'h00000cfc90f, 42'h3ff43682161, 42'h0efdb928a2a};
        rom[ 21] = {42'h3ffffff01a0, 42'h00000ccbdaf, 42'h3ff4504a8c4, 42'h0ef1fc970cd};
        rom[ 22] = {42'h3ffffff06e8, 42'h00000c9c298, 42'h3ff469b29ab, 42'h0ee6599d8e0};
        rom[ 23] = {42'h3ffffff0c0c, 42'h00000c6d759, 42'h3ff482bc439, 42'h0edacfdcc0b};
        rom[ 24] = {42'h3ffffff110c, 42'h00000c3fb85, 42'h3ff49b697af, 42'h0ecf5ef73a9};
        rom[ 25] = {42'h3ffffff15ea, 42'h00000c12eb1, 42'h3ff4b3bc279, 42'h0ec406917e9};
        rom[ 26] = {42'h3ffffff1aa8, 42'h00000be7078, 42'h3ff4cbb6232, 42'h0eb8c651efd};
        rom[ 27] = {42'h3ffffff1f45, 42'h00000bbc076, 42'h3ff4e3593ac, 42'h0ead9de0c4f};
        rom[ 28] = {42'h3ffffff23c3, 42'h00000b91e4b, 42'h3ff4faa72f6, 42'h0ea28ce7fb6};
        rom[ 29] = {42'h3ffffff2824, 42'h00000b6899b, 42'h3ff511a1b61, 42'h0e9793134ba};
        rom[ 30] = {42'h3ffffff2c67, 42'h00000b4020c, 42'h3ff5284a78b, 42'h0e8cb0101da};
        rom[ 31] = {42'h3ffffff308f, 42'h00000b18748, 42'h3ff53ea315e, 42'h0e81e38d7d9};
        rom[ 32] = {42'h3ffffff349b, 42'h00000af18fa, 42'h3ff554ad21b, 42'h0e772d3c10d};
        rom[ 33] = {42'h3ffffff388d, 42'h00000acb6d0, 42'h3ff56a6a25d, 42'h0e6c8cce0bd};
        rom[ 34] = {42'h3ffffff3c65, 42'h00000aa607c, 42'h3ff57fdba1f, 42'h0e6201f7277};
        rom[ 35] = {42'h3ffffff4025, 42'h00000a815b2, 42'h3ff595030c0, 42'h0e578c6c977};
        rom[ 36] = {42'h3ffffff43cd, 42'h00000a5d627, 42'h3ff5a9e1d09, 42'h0e4d2be500f};
        rom[ 37] = {42'h3ffffff475e, 42'h00000a3a194, 42'h3ff5be79532, 42'h0e42e01870c};
        rom[ 38] = {42'h3ffffff4ad8, 42'h00000a177b4, 42'h3ff5d2caee4, 42'h0e38a8c0531};
        rom[ 39] = {42'h3ffffff4e3d, 42'h000009f5842, 42'h3ff5e6d7f41, 42'h0e2e85976a1};
        rom[ 40] = {42'h3ffffff518c, 42'h000009d42fd, 42'h3ff5faa1ae5, 42'h0e247659c61};
        rom[ 41] = {42'h3ffffff54c7, 42'h000009b37a6, 42'h3ff60e295ea, 42'h0e1a7ac4bcf};
        rom[ 42] = {42'h3ffffff57ee, 42'h00000993600, 42'h3ff621703f0, 42'h0e109296e26};
        rom[ 43] = {42'h3ffffff5b02, 42'h00000973dce, 42'h3ff6347781c, 42'h0e06bd90004};
        rom[ 44] = {42'h3ffffff5e03, 42'h00000954ed7, 42'h3ff6474051d, 42'h0dfcfb710ef};
        rom[ 45] = {42'h3ffffff60f1, 42'h000009368e3, 42'h3ff659cbd30, 42'h0df34bfc2e5};
        rom[ 46] = {42'h3ffffff63ce, 42'h00000918bba, 42'h3ff66c1b225, 42'h0de9aef49ea};
        rom[ 47] = {42'h3ffffff669a, 42'h000008fb729, 42'h3ff67e2f55e, 42'h0de0241eb97};
        rom[ 48] = {42'h3ffffff6955, 42'h000008deafb, 42'h3ff690097d6, 42'h0dd6ab3feb9};
        rom[ 49] = {42'h3ffffff6c01, 42'h000008c26ff, 42'h3ff6a1aaa23, 42'h0dcd441eae0};
        rom[ 50] = {42'h3ffffff6e9c, 42'h000008a6b04, 42'h3ff6b313c77, 42'h0dc3ee82803};
        rom[ 51] = {42'h3ffffff7128, 42'h0000088b6db, 42'h3ff6c445ea5, 42'h0dbaaa33e1a};
        rom[ 52] = {42'h3ffffff73a5, 42'h00000870a56, 42'h3ff6d542023, 42'h0db176fc4c2};
        rom[ 53] = {42'h3ffffff7614, 42'h00000856549, 42'h3ff6e60900d, 42'h0da854a62e0};
        rom[ 54] = {42'h3ffffff7875, 42'h0000083c788, 42'h3ff6f69bd26, 42'h0d9f42fce4a};
        rom[ 55] = {42'h3ffffff7ac8, 42'h000008230e9, 42'h3ff706fb5de, 42'h0d9641ccb6c};
        rom[ 56] = {42'h3ffffff7d0e, 42'h0000080a143, 42'h3ff71728850, 42'h0d8d50e2cfc};
        rom[ 57] = {42'h3ffffff7f47, 42'h000007f186f, 42'h3ff72724247, 42'h0d84700d39d};
        rom[ 58] = {42'h3ffffff8173, 42'h000007d9646, 42'h3ff736ef13f, 42'h0d7b9f1ad9a};
        rom[ 59] = {42'h3ffffff8393, 42'h000007c1aa2, 42'h3ff7468a268, 42'h0d72dddb692};
        rom[ 60] = {42'h3ffffff85a8, 42'h000007aa55e, 42'h3ff755f62a8, 42'h0d6a2c1f72f};
        rom[ 61] = {42'h3ffffff87b0, 42'h00000793658, 42'h3ff76533e9c, 42'h0d6189b84dd};
        rom[ 62] = {42'h3ffffff89ae, 42'h0000077cd6b, 42'h3ff7744429c, 42'h0d58f678180};
        rom[ 63] = {42'h3ffffff8ba0, 42'h00000766a77, 42'h3ff78327aba, 42'h0d507231b35};
        rom[ 64] = {42'h3ffffff8d88, 42'h00000750d5b, 42'h3ff791df2c7, 42'h0d47fcb8c07};
        rom[ 65] = {42'h3ffffff8f66, 42'h0000073b5f6, 42'h3ff7a06b652, 42'h0d3f95e19b2};
        rom[ 66] = {42'h3ffffff9139, 42'h0000072642a, 42'h3ff7aecd0ab, 42'h0d373d81560};
        rom[ 67] = {42'h3ffffff9303, 42'h000007117d9, 42'h3ff7bd04ce5, 42'h0d2ef36db6f};
        rom[ 68] = {42'h3ffffff94c3, 42'h000006fd0e4, 42'h3ff7cb135d7, 42'h0d26b77d330};
        rom[ 69] = {42'h3ffffff967a, 42'h000006e8f2e, 42'h3ff7d8f961e, 42'h0d1e8986eae};
        rom[ 70] = {42'h3ffffff9827, 42'h000006d529d, 42'h3ff7e6b781d, 42'h0d166962a73};
        rom[ 71] = {42'h3ffffff99cc, 42'h000006c1b14, 42'h3ff7f44e600, 42'h0d0e56e8d54};
        rom[ 72] = {42'h3ffffff9b68, 42'h000006ae879, 42'h3ff801be9bf, 42'h0d0651f2834};
        rom[ 73] = {42'h3ffffff9cfb, 42'h0000069bab2, 42'h3ff80f08d1b, 42'h0cfe5a595d4};
        rom[ 74] = {42'h3ffffff9e87, 42'h000006891a6, 42'h3ff81c2d9a4, 42'h0cf66ff7a9d};
        rom[ 75] = {42'h3ffffffa00a, 42'h00000676d3c, 42'h3ff8292d8b5, 42'h0cee92a846e};
        rom[ 76] = {42'h3ffffffa186, 42'h00000664d5c, 42'h3ff8360937b, 42'h0ce6c246a69};
        rom[ 77] = {42'h3ffffffa2fa, 42'h000006531ef, 42'h3ff842c12f3, 42'h0cdefeaecc6};
        rom[ 78] = {42'h3ffffffa466, 42'h00000641add, 42'h3ff84f55fec, 42'h0cd747bd4a2};
        rom[ 79] = {42'h3ffffffa5cb, 42'h00000630811, 42'h3ff85bc8306, 42'h0ccf9d4f3d2};
        rom[ 80] = {42'h3ffffffa72a, 42'h0000061f975, 42'h3ff868184b6, 42'h0cc7ff424b4};
        rom[ 81] = {42'h3ffffffa881, 42'h0000060eef3, 42'h3ff87446d48, 42'h0cc06d74a09};
        rom[ 82] = {42'h3ffffffa9d1, 42'h000005fe878, 42'h3ff880544dc, 42'h0cb8e7c4ec5};
        rom[ 83] = {42'h3ffffffab1b, 42'h000005ee5ed, 42'h3ff88c41369, 42'h0cb16e125ea};
        rom[ 84] = {42'h3ffffffac5f, 42'h000005de741, 42'h3ff8980e0be, 42'h0caa003ca5c};
        rom[ 85] = {42'h3ffffffad9c, 42'h000005cec60, 42'h3ff8a3bb486, 42'h0ca29e23eba};
        rom[ 86] = {42'h3ffffffaed4, 42'h000005bf536, 42'h3ff8af49641, 42'h0c9b47a8d3c};
        rom[ 87] = {42'h3ffffffb005, 42'h000005b01b3, 42'h3ff8bab8d4f, 42'h0c93fcac787};
        rom[ 88] = {42'h3ffffffb130, 42'h000005a11c3, 42'h3ff8c60a0e8, 42'h0c8cbd1068e};
        rom[ 89] = {42'h3ffffffb256, 42'h00000592555, 42'h3ff8d13d823, 42'h0c8588b6a69};
        rom[ 90] = {42'h3ffffffb376, 42'h00000583c58, 42'h3ff8dc539f3, 42'h0c7e5f81a37};
        rom[ 91] = {42'h3ffffffb491, 42'h000005756bd, 42'h3ff8e74cd2a, 42'h0c7741543f9};
        rom[ 92] = {42'h3ffffffb5a7, 42'h00000567471, 42'h3ff8f229879, 42'h0c702e11c71};
        rom[ 93] = {42'h3ffffffb6b7, 42'h00000559566, 42'h3ff8fcea271, 42'h0c69259df02};
        rom[ 94] = {42'h3ffffffb7c2, 42'h0000054b98c, 42'h3ff9078f183, 42'h0c6227dcd90};
        rom[ 95] = {42'h3ffffffb8c8, 42'h0000053e0d3, 42'h3ff91218c01, 42'h0c5b34b3060};
        rom[ 96] = {42'h3ffffffb9ca, 42'h00000530b2e, 42'h3ff91c87821, 42'h0c544c055fd};
        rom[ 97] = {42'h3ffffffbac7, 42'h0000052388c, 42'h3ff926dbbfa, 42'h0c4d6db9316};
        rom[ 98] = {42'h3ffffffbbbf, 42'h000005168e1, 42'h3ff93115d85, 42'h0c4699b4263};
        rom[ 99] = {42'h3ffffffbcb2, 42'h00000509c1f, 42'h3ff93b362a3, 42'h0c3fcfdc488};
        rom[100] = {42'h3ffffffbda2, 42'h000004fd237, 42'h3ff9453d116, 42'h0c391017ffd};
        rom[101] = {42'h3ffffffbe8d, 42'h000004f0b1d, 42'h3ff94f2ae87, 42'h0c325a4e0eb};
        rom[102] = {42'h3ffffffbf73, 42'h000004e46c4, 42'h3ff95900084, 42'h0c2bae6591c};
        rom[103] = {42'h3ffffffc056, 42'h000004d851f, 42'h3ff962bcc81, 42'h0c250c45fd7};
        rom[104] = {42'h3ffffffc134, 42'h000004cc621, 42'h3ff96c617dc, 42'h0c1e73d71cc};
        rom[105] = {42'h3ffffffc20f, 42'h000004c09bf, 42'h3ff975ee7d7, 42'h0c17e5010fe};
        rom[106] = {42'h3ffffffc2e6, 42'h000004b4fed, 42'h3ff97f6419d, 42'h0c115fac4a3};
        rom[107] = {42'h3ffffffc3b9, 42'h000004a989f, 42'h3ff988c2a42, 42'h0c0ae3c1912};
        rom[108] = {42'h3ffffffc488, 42'h0000049e3ca, 42'h3ff9920a6c4, 42'h0c047129fac};
        rom[109] = {42'h3ffffffc554, 42'h00000493163, 42'h3ff99b3bc0a, 42'h0bfe07ceec3};
        rom[110] = {42'h3ffffffc61c, 42'h0000048815e, 42'h3ff9a456ee3, 42'h0bf7a79a182};
        rom[111] = {42'h3ffffffc6e0, 42'h0000047d3b2, 42'h3ff9ad5c40b, 42'h0bf150757df};
        rom[112] = {42'h3ffffffc7a2, 42'h00000472854, 42'h3ff9b64c029, 42'h0beb024b67d};
        rom[113] = {42'h3ffffffc860, 42'h00000467f3a, 42'h3ff9bf267cf, 42'h0be4bd0669d};
        rom[114] = {42'h3ffffffc91a, 42'h0000045d85a, 42'h3ff9c7ebf7a, 42'h0bde8091606};
        rom[115] = {42'h3ffffffc9d2, 42'h000004533aa, 42'h3ff9d09cb94, 42'h0bd84cd76f4};
        rom[116] = {42'h3ffffffca86, 42'h00000449120, 42'h3ff9d939073, 42'h0bd221c4003};
        rom[117] = {42'h3ffffffcb38, 42'h0000043f0b4, 42'h3ff9e1c125d, 42'h0bcbff42c1d};
        rom[118] = {42'h3ffffffcbe6, 42'h0000043525c, 42'h3ff9ea35582, 42'h0bc5e53fa66};
        rom[119] = {42'h3ffffffcc92, 42'h0000042b60f, 42'h3ff9f295e01, 42'h0bbfd3a6e29};
        rom[120] = {42'h3ffffffcd3a, 42'h00000421bc4, 42'h3ff9fae2fe8, 42'h0bb9ca64eca};
        rom[121] = {42'h3ffffffcde0, 42'h00000418374, 42'h3ffa031cf34, 42'h0bb3c9667b1};
        rom[122] = {42'h3ffffffce83, 42'h0000040ed14, 42'h3ffa0b43fd0, 42'h0badd098839};
        rom[123] = {42'h3ffffffcf24, 42'h0000040589e, 42'h3ffa1358596, 42'h0ba7dfe83a1};
        rom[124] = {42'h3ffffffcfc1, 42'h000003fc609, 42'h3ffa1b5a451, 42'h0ba1f7430f9};
        rom[125] = {42'h3ffffffd05c, 42'h000003f354e, 42'h3ffa2349fbc, 42'h0b9c1696b15};
        rom[126] = {42'h3ffffffd0f5, 42'h000003ea664, 42'h3ffa2b27b80, 42'h0b963dd107b};
        rom[127] = {42'h3ffffffd18b, 42'h000003e1944, 42'h3ffa32f3b39, 42'h0b906ce0354};
        rom[128] = {42'h3ffffffd21f, 42'h000003d8de6, 42'h3ffa3aae274, 42'h0b8aa3b295c};
        rom[129] = {42'h3ffffffd2b0, 42'h000003d0443, 42'h3ffa42574af, 42'h0b84e236bd5};
        rom[130] = {42'h3ffffffd33f, 42'h000003c7c55, 42'h3ffa49ef559, 42'h0b7f285b778};
        rom[131] = {42'h3ffffffd3cc, 42'h000003bf613, 42'h3ffa51767d2, 42'h0b79760fc65};
        rom[132] = {42'h3ffffffd457, 42'h000003b7178, 42'h3ffa58ecf6e, 42'h0b73cb42e16};
        rom[133] = {42'h3ffffffd4df, 42'h000003aee7c, 42'h3ffa6052f73, 42'h0b6e27e4353};
        rom[134] = {42'h3ffffffd565, 42'h000003a6d19, 42'h3ffa67a8b19, 42'h0b688be3622};
        rom[135] = {42'h3ffffffd5e9, 42'h0000039ed49, 42'h3ffa6eee58c, 42'h0b62f7303ba};
        rom[136] = {42'h3ffffffd66b, 42'h00000396f04, 42'h3ffa76241e9, 42'h0b5d69bac78};
        rom[137] = {42'h3ffffffd6eb, 42'h0000038f246, 42'h3ffa7d4a343, 42'h0b57e3733d0};
        rom[138] = {42'h3ffffffd769, 42'h00000387707, 42'h3ffa8460c9f, 42'h0b52644a044};
        rom[139] = {42'h3ffffffd7e5, 42'h0000037fd42, 42'h3ffa8b680f7, 42'h0b4cec2fb53};
        rom[140] = {42'h3ffffffd85f, 42'h000003784f1, 42'h3ffa9260339, 42'h0b477b15171};
        rom[141] = {42'h3ffffffd8d7, 42'h00000370e0e, 42'h3ffa9949646, 42'h0b4210eb1f9};
        rom[142] = {42'h3ffffffd94d, 42'h00000369893, 42'h3ffaa023cf5, 42'h0b3cada2f24};
        rom[143] = {42'h3ffffffd9c2, 42'h0000036247c, 42'h3ffaa6efa12, 42'h0b37512ddf9};
        rom[144] = {42'h3ffffffda35, 42'h0000035b1c1, 42'h3ffaadad05d, 42'h0b31fb7d648};
        rom[145] = {42'h3ffffffdaa6, 42'h00000354060, 42'h3ffab45c28c, 42'h0b2cac8329b};
        rom[146] = {42'h3ffffffdb15, 42'h0000034d051, 42'h3ffabafd349, 42'h0b27643102c};
        rom[147] = {42'h3ffffffdb82, 42'h00000346190, 42'h3ffac190537, 42'h0b222278edb};
        rom[148] = {42'h3ffffffdbee, 42'h0000033f417, 42'h3ffac815aeb, 42'h0b1ce74d124};
        rom[149] = {42'h3ffffffdc59, 42'h000003387e3, 42'h3fface8d6f3, 42'h0b17b29fc15};
        rom[150] = {42'h3ffffffdcc1, 42'h00000331cee, 42'h3ffad4f7bd0, 42'h0b128463744};
        rom[151] = {42'h3ffffffdd29, 42'h0000032b332, 42'h3ffadb54bfd, 42'h0b0d5c8acc3};
        rom[152] = {42'h3ffffffdd8e, 42'h00000324aad, 42'h3ffae1a49e8, 42'h0b083b0891a};
        rom[153] = {42'h3ffffffddf3, 42'h0000031e358, 42'h3ffae7e77f9, 42'h0b031fcfb3d};
        rom[154] = {42'h3ffffffde55, 42'h00000317d30, 42'h3ffaee1d88e, 42'h0afe0ad3481};
        rom[155] = {42'h3ffffffdeb6, 42'h00000311830, 42'h3ffaf446df9, 42'h0af8fc06894};
        rom[156] = {42'h3ffffffdf16, 42'h0000030b453, 42'h3ffafa63a88, 42'h0af3f35cd74};
        rom[157] = {42'h3ffffffdf75, 42'h00000305196, 42'h3ffb007407e, 42'h0aeef0c9b66};
        rom[158] = {42'h3ffffffdfd2, 42'h000002feff5, 42'h3ffb0678214, 42'h0ae9f440cee};
        rom[159] = {42'h3ffffffe02d, 42'h000002f8f6a, 42'h3ffb0c7017e, 42'h0ae4fdb5ec9};
        rom[160] = {42'h3ffffffe088, 42'h000002f2ff3, 42'h3ffb125c0e6, 42'h0ae00d1cfdf};
        rom[161] = {42'h3ffffffe0e1, 42'h000002ed18a, 42'h3ffb183c26d, 42'h0adb226a13e};
        rom[162] = {42'h3ffffffe139, 42'h000002e742d, 42'h3ffb1e1082f, 42'h0ad63d91616};
        rom[163] = {42'h3ffffffe18f, 42'h000002e17d7, 42'h3ffb23d943d, 42'h0ad15e873ab};
        rom[164] = {42'h3ffffffe1e4, 42'h000002dbc85, 42'h3ffb29968a3, 42'h0acc854014e};
        rom[165] = {42'h3ffffffe239, 42'h000002d6233, 42'h3ffb2f48765, 42'h0ac7b1b085b};
        rom[166] = {42'h3ffffffe28b, 42'h000002d08dd, 42'h3ffb34ef27e, 42'h0ac2e3cd42b};
        rom[167] = {42'h3ffffffe2dd, 42'h000002cb07f, 42'h3ffb3a8abe4, 42'h0abe1b8b212};
        rom[168] = {42'h3ffffffe32e, 42'h000002c5917, 42'h3ffb401b585, 42'h0ab958df153};
        rom[169] = {42'h3ffffffe37d, 42'h000002c02a1, 42'h3ffb45a1147, 42'h0ab49bbe31c};
        rom[170] = {42'h3ffffffe3cc, 42'h000002bad19, 42'h3ffb4b1c10b, 42'h0aafe41da82};
        rom[171] = {42'h3ffffffe419, 42'h000002b587c, 42'h3ffb508c6aa, 42'h0aab31f2c71};
        rom[172] = {42'h3ffffffe465, 42'h000002b04c7, 42'h3ffb55f23f7, 42'h0aa68532fb0};
        rom[173] = {42'h3ffffffe4b0, 42'h000002ab1f7, 42'h3ffb5b4dabf, 42'h0aa1ddd3cd4};
        rom[174] = {42'h3ffffffe4fa, 42'h000002a6008, 42'h3ffb609ecc7, 42'h0a9d3bcae3a};
        rom[175] = {42'h3ffffffe543, 42'h000002a0ef7, 42'h3ffb65e5bcf, 42'h0a989f0e003};
        rom[176] = {42'h3ffffffe58c, 42'h0000029bec2, 42'h3ffb6b22991, 42'h0a94079300d};
        rom[177] = {42'h3ffffffe5d3, 42'h00000296f65, 42'h3ffb70557c0, 42'h0a8f754fdeb};
        rom[178] = {42'h3ffffffe619, 42'h000002920dd, 42'h3ffb757e80b, 42'h0a8ae83aae3};
        rom[179] = {42'h3ffffffe65e, 42'h0000028d327, 42'h3ffb7a9dc17, 42'h0a8660499e3};
        rom[180] = {42'h3ffffffe6a2, 42'h00000288642, 42'h3ffb7fb3589, 42'h0a81dd72f80};
        rom[181] = {42'h3ffffffe6e6, 42'h00000283a28, 42'h3ffb84bf5fb, 42'h0a7d5fad1ed};
        rom[182] = {42'h3ffffffe728, 42'h0000027eed9, 42'h3ffb89c1f05, 42'h0a78e6ee8f6};
        rom[183] = {42'h3ffffffe76a, 42'h0000027a451, 42'h3ffb8ebb237, 42'h0a74732ddfc};
        rom[184] = {42'h3ffffffe7aa, 42'h00000275a8e, 42'h3ffb93ab11f, 42'h0a700461bee};
        rom[185] = {42'h3ffffffe7ea, 42'h0000027118d, 42'h3ffb9891d41, 42'h0a6b9a80f45};
        rom[186] = {42'h3ffffffe829, 42'h0000026c94b, 42'h3ffb9d6f820, 42'h0a6735825fc};
        rom[187] = {42'h3ffffffe867, 42'h000002681c6, 42'h3ffba244338, 42'h0a62d55cf90};
        rom[188] = {42'h3ffffffe8a4, 42'h00000263afb, 42'h3ffba710001, 42'h0a5e7a07cf6};
        rom[189] = {42'h3ffffffe8e1, 42'h0000025f4e8, 42'h3ffbabd2feb, 42'h0a5a237a096};
        rom[190] = {42'h3ffffffe91d, 42'h0000025af8b, 42'h3ffbb08d466, 42'h0a55d1aae4a};
        rom[191] = {42'h3ffffffe957, 42'h00000256ae1, 42'h3ffbb53eed9, 42'h0a518491b58};
        rom[192] = {42'h3ffffffe992, 42'h000002526e7, 42'h3ffbb9e80a8, 42'h0a4d3c25e69};
        rom[193] = {42'h3ffffffe9cb, 42'h0000024e39c, 42'h3ffbbe88b33, 42'h0a48f85ef8a};
        rom[194] = {42'h3ffffffea04, 42'h0000024a0fe, 42'h3ffbc320fd3, 42'h0a44b934823};
        rom[195] = {42'h3ffffffea3c, 42'h00000245f09, 42'h3ffbc7b0fe0, 42'h0a407e9e2f8};
        rom[196] = {42'h3ffffffea73, 42'h00000241dbc, 42'h3ffbcc38cac, 42'h0a3c4893c1d};
        rom[197] = {42'h3ffffffeaa9, 42'h0000023dd14, 42'h3ffbd0b8782, 42'h0a38170d0f7};
        rom[198] = {42'h3ffffffeadf, 42'h00000239d10, 42'h3ffbd5301ad, 42'h0a33ea02037};
        rom[199] = {42'h3ffffffeb14, 42'h00000235dae, 42'h3ffbd99fc72, 42'h0a2fc16a9d3};
        rom[200] = {42'h3ffffffeb49, 42'h00000231eeb, 42'h3ffbde07911, 42'h0a2b9d3ef07};
        rom[201] = {42'h3ffffffeb7c, 42'h0000022e0c5, 42'h3ffbe2678c6, 42'h0a277d7724b};
        rom[202] = {42'h3ffffffebb0, 42'h0000022a33a, 42'h3ffbe6bfccb, 42'h0a23620b753};
        rom[203] = {42'h3ffffffebe2, 42'h00000226649, 42'h3ffbeb10655, 42'h0a1f4af4308};
        rom[204] = {42'h3ffffffec14, 42'h000002229ef, 42'h3ffbef59693, 42'h0a1b3829b87};
        rom[205] = {42'h3ffffffec45, 42'h0000021ee2b, 42'h3ffbf39aeb3, 42'h0a1729a481d};
        rom[206] = {42'h3ffffffec76, 42'h0000021b2fa, 42'h3ffbf7d4fde, 42'h0a131f5d140};
        rom[207] = {42'h3ffffffeca6, 42'h0000021785b, 42'h3ffbfc07b39, 42'h0a0f194c08d};
        rom[208] = {42'h3ffffffecd5, 42'h00000213e4c, 42'h3ffc00331e7, 42'h0a0b176a0c7};
        rom[209] = {42'h3ffffffed04, 42'h000002104cc, 42'h3ffc0457505, 42'h0a0719afdcf};
        rom[210] = {42'h3ffffffed32, 42'h0000020cbd8, 42'h3ffc08745ad, 42'h0a0320164a3};
        rom[211] = {42'h3ffffffed60, 42'h0000020936e, 42'h3ffc0c8a4f9, 42'h09ff2a9635a};
        rom[212] = {42'h3ffffffed8d, 42'h00000205b8d, 42'h3ffc10993fa, 42'h09fb3928921};
        rom[213] = {42'h3ffffffedb9, 42'h00000202434, 42'h3ffc14a13c1, 42'h09f74bc6635};
        rom[214] = {42'h3ffffffede5, 42'h000001fed61, 42'h3ffc18a255b, 42'h09f36268be3};
        rom[215] = {42'h3ffffffee11, 42'h000001fb711, 42'h3ffc1c9c9d2, 42'h09ef7d08c84};
        rom[216] = {42'h3ffffffee3c, 42'h000001f8144, 42'h3ffc209022c, 42'h09eb9b9fb77};
        rom[217] = {42'h3ffffffee66, 42'h000001f4bf7, 42'h3ffc247cf6c, 42'h09e7be26d23};
        rom[218] = {42'h3ffffffee90, 42'h000001f172a, 42'h3ffc2863293, 42'h09e3e4976ec};
        rom[219] = {42'h3ffffffeeba, 42'h000001ee2db, 42'h3ffc2c42c9d, 42'h09e00eeaf3a};
        rom[220] = {42'h3ffffffeee2, 42'h000001eaf08, 42'h3ffc301be85, 42'h09dc3d1ad6c};
        rom[221] = {42'h3ffffffef0b, 42'h000001e7baf, 42'h3ffc33ee941, 42'h09d86f209db};
        rom[222] = {42'h3ffffffef33, 42'h000001e48d0, 42'h3ffc37badc5, 42'h09d4a4f5dd6};
        rom[223] = {42'h3ffffffef5a, 42'h000001e1669, 42'h3ffc3b80d03, 42'h09d0de9439f};
        rom[224] = {42'h3ffffffef81, 42'h000001de478, 42'h3ffc3f407e8, 42'h09cd1bf5665};
        rom[225] = {42'h3ffffffefa8, 42'h000001db2fc, 42'h3ffc42f9f60, 42'h09c95d13246};
        rom[226] = {42'h3ffffffefce, 42'h000001d81f3, 42'h3ffc46ad454, 42'h09c5a1e744a};
        rom[227] = {42'h3ffffffeff4, 42'h000001d515d, 42'h3ffc4a5a7a9, 42'h09c1ea6ba5f};
        rom[228] = {42'h3fffffff019, 42'h000001d2138, 42'h3ffc4e01a42, 42'h09be369a359};
        rom[229] = {42'h3fffffff03d, 42'h000001cf182, 42'h3ffc51a2d00, 42'h09ba866ceeb};
        rom[230] = {42'h3fffffff062, 42'h000001cc23a, 42'h3ffc553e0c0, 42'h09b6d9dddaa};
        rom[231] = {42'h3fffffff086, 42'h000001c9360, 42'h3ffc58d365e, 42'h09b330e7106};
        rom[232] = {42'h3fffffff0a9, 42'h000001c64f1, 42'h3ffc5c62eb3, 42'h09af8b82b4a};
        rom[233] = {42'h3fffffff0cc, 42'h000001c36ec, 42'h3ffc5feca94, 42'h09abe9aaf97};
        rom[234] = {42'h3fffffff0ef, 42'h000001c0951, 42'h3ffc6370ad5, 42'h09a84b5a1e3};
        rom[235] = {42'h3fffffff111, 42'h000001bdc1d, 42'h3ffc66ef048, 42'h09a4b08a6f8};
        rom[236] = {42'h3fffffff133, 42'h000001baf51, 42'h3ffc6a67bba, 42'h09a1193646e};
        rom[237] = {42'h3fffffff154, 42'h000001b82ea, 42'h3ffc6ddadf9, 42'h099d85580ac};
        rom[238] = {42'h3fffffff176, 42'h000001b56e7, 42'h3ffc71487cf, 42'h0999f4ea2e3};
        rom[239] = {42'h3fffffff196, 42'h000001b2b48, 42'h3ffc74b0a02, 42'h099667e730f};
        rom[240] = {42'h3fffffff1b7, 42'h000001b000b, 42'h3ffc781355a, 42'h0992de499f0};
        rom[241] = {42'h3fffffff1d7, 42'h000001ad52f, 42'h3ffc7b70a98, 42'h098f580c10b};
        rom[242] = {42'h3fffffff1f6, 42'h000001aaab3, 42'h3ffc7ec8a7e, 42'h098bd5292a9};
        rom[243] = {42'h3fffffff215, 42'h000001a8096, 42'h3ffc821b5cb, 42'h0988559b9d0};
        rom[244] = {42'h3fffffff234, 42'h000001a56d6, 42'h3ffc8568d3a, 42'h0984d95e246};
        rom[245] = {42'h3fffffff253, 42'h000001a2d74, 42'h3ffc88b1188, 42'h0981606b88b};
        rom[246] = {42'h3fffffff271, 42'h000001a046d, 42'h3ffc8bf436c, 42'h097deabe9da};
        rom[247] = {42'h3fffffff28f, 42'h0000019dbc0, 42'h3ffc8f3239d, 42'h097a7852424};
        rom[248] = {42'h3fffffff2ad, 42'h0000019b36d, 42'h3ffc926b2ce, 42'h0977092160f};
        rom[249] = {42'h3fffffff2ca, 42'h00000198b73, 42'h3ffc959f1b2, 42'h09739d26ef7};
        rom[250] = {42'h3fffffff2e7, 42'h000001963d1, 42'h3ffc98ce0fa, 42'h0970345dee7};
        rom[251] = {42'h3fffffff303, 42'h00000193c85, 42'h3ffc9bf8154, 42'h096ccec1699};
        rom[252] = {42'h3fffffff320, 42'h0000019158f, 42'h3ffc9f1d36c, 42'h09696c4c775};
        rom[253] = {42'h3fffffff33c, 42'h0000018eeee, 42'h3ffca23d7ec, 42'h09660cfa38f};
        rom[254] = {42'h3fffffff357, 42'h0000018c8a1, 42'h3ffca558f7e, 42'h0962b0c5da5};
        rom[255] = {42'h3fffffff373, 42'h0000018a2a6, 42'h3ffca86fac8, 42'h095f57aa91b};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
