/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=5 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m5_d2 #(parameter integer WMAN = 5, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire [WMAN+12-1:0]     f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire        [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire                   guard,
    output wire                   round,
    output wire                   sticky
);
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 2;
    localparam integer D    = 2;
    localparam integer CF   = 17;
    localparam integer RW   = 15;
    localparam integer CW   = 20;
    localparam integer ACCW = 22;
    localparam integer NSEG = 4;
    localparam integer HSBW = SBW;

    // verilator coverage_off
    (* rom_style = "logic", syn_romstyle = "logic" *)
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {20'h00863, 20'h05875, 20'h20004};
        rom[1] = {20'h009f9, 20'h06932, 20'h260e4};
        rom[2] = {20'h00bdc, 20'h07d19, 20'h2d419};
        rom[3] = {20'h00e1b, 20'h094c4, 20'h35d1a};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
