/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=48 (degree 6); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m48 #(parameter integer WMAN = 48, parameter integer D = 6, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 in_valid,
    input  wire       [WSB-1:0] sb_in,
    input  wire      [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                 out_valid,
    output wire       [WSB-1:0] sb_out,
    output wire [2*WMAN+12-2:0] l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    // verilator coverage_off
    generate if (D != 6) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 6;
    localparam integer RW   = 41;
    localparam integer CW   = 63;
    localparam integer ACCW = 65;
    localparam integer NSEG = 64;
    localparam integer HSBW = WSB + WFRAC;  // carry t alongside the sideband to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {63'h0000000000324f3b, 63'h7ffffffff09fd1e2, 63'h000000049dd8d016, 63'h7ffffe8eab8a77d1, 63'h00007b1c2770c65b, 63'h7fd1d57135a8fc1f, 63'h171547652b82fe12};
        rom[  1] = {63'h00000000002dc8bf, 63'h7ffffffff1cd6fe0, 63'h0000000453e64f55, 63'h7ffffea08d1a0a48, 63'h000076e34655a638, 63'h7fd2c767b2da253c, 63'h16e79685c2d22986};
        rom[  2] = {63'h000000000029b981, 63'h7ffffffff2dfee1d, 63'h000000040f947326, 63'h7ffffeb1524d4600, 63'h000072de59be8a25, 63'h7fd3b120f082b189, 63'h16bad3758efd872d};
        rom[  3] = {63'h00000000002613b7, 63'h7ffffffff3da171b, 63'h00000003d0628c69, 63'h7ffffec110a0d039, 63'h00006f0a2d52079c, 63'h7fd49301989363db, 63'h168ef62a2e2a2396};
        rom[  4] = {63'h000000000022cb5e, 63'h7ffffffff4be62cf, 63'h0000000395dd137a, 63'h7ffffecfdba96734, 63'h00006b63ca43a389, 63'h7fd56d682acaff11, 63'h1663f6fac9131679};
        rom[  5] = {63'h00000000001fd5f5, 63'h7ffffffff58f012e, 63'h000000035f9c25a5, 63'h7ffffeddc54569dd, 63'h000067e871e7eb25, 63'h7fd640ad724b7bc5, 63'h1639ce9a248961e6};
        rom[  6] = {63'h00000000001d2a4a, 63'h7ffffffff64de342, 63'h000000032d4233b2, 63'h7ffffeeaddc8b9e6, 63'h0000649598d47a5d, 63'h7fd70d24f0e62fc7, 63'h16107611234d2f70};
        rom[  7] = {63'h00000000001ac04c, 63'h7ffffffff6fcc2fd, 63'h00000002fe7adabb, 63'h7ffffef73423ae9c, 63'h00006168e27c175f, 63'h7fd7d31d41268eef, 63'h15e7e6b9ae7dd4b3};
        rom[  8] = {63'h00000000001890e4, 63'h7ffffffff79d29fb, 63'h00000002d2f9e17c, 63'h7fffff02d605b5d3, 63'h00005e601d390758, 63'h7fd892e070058515, 63'h15c01a39fbd6879d};
        rom[  9] = {63'h00000000001695d4, 63'h7ffffffff830775e, 63'h00000002aa7a5531, 63'h7fffff0dcffc2aa3, 63'h00005b793eb97729, 63'h7fd94cb44f15725d, 63'h15990a8029ca6635};
        rom[ 10] = {63'h000000000014c99a, 63'h7ffffffff8b7e4e0, 63'h0000000284bdc1cf, 63'h7fffff182d8dd794, 63'h000058b260c34e23, 63'h7fda00dabfe00d1c, 63'h1572b1be2a56dcbe};
        rom[ 11] = {63'h0000000000132759, 63'h7ffffffff9348b3e, 63'h00000002618b81f2, 63'h7fffff21f9538a2a, 63'h00005609be46099e, 63'h7fdaaf91f91b6947, 63'h154d0a65f6127fd6};
        rom[ 12] = {63'h000000000011aac4, 63'h7ffffffff9a7660e, 63'h0000000240b02377, 63'h7fffff2b3d0e1078, 63'h0000537db0b25d9d, 63'h7fdb5914c649c70a, 63'h15280f26019ab16b};
        rom[ 13] = {63'h000000000010500a, 63'h7ffffffffa11571e, 63'h0000000221fcde13, 63'h7fffff3401b9edd8, 63'h0000510cad904ee7, 63'h7fdbfd9ac248405e, 63'h1503bae5f00e1ad1};
        rom[ 14] = {63'h00000000000f13c7, 63'h7ffffffffa73295b, 63'h00000002054719a5, 63'h7fffff3c4fa10a25, 63'h00004eb5444d5355, 63'h7fdc9d588d42b3c7, 63'h14e008c37dbf1d26};
        rom[ 15] = {63'h00000000000df2f9, 63'h7ffffffffacd9367, 63'h00000001ea680240, 63'h7fffff442e6a9648, 63'h00004c761c3cc210, 63'h7fdd387ffe7724dc, 63'h14bcf40f9eb9852b};
        rom[ 16] = {63'h00000000000ceaf2, 63'h7ffffffffb2139da, 63'h00000001d13c2844, 63'h7fffff4ba5295994, 63'h00004a4df2c5829a, 63'h7fddcf40522807a7, 63'h149a784bcd1b8afd};
        rom[ 17] = {63'h00000000000bf94c, 63'h7ffffffffb6eb136, 63'h00000001b9a32b10, 63'h7fffff52ba689522, 63'h0000483b99b87a65, 63'h7fde61c654135d8e, 63'h14789127839cbbe0};
        rom[ 18] = {63'h00000000000b1be6, 63'h7ffffffffbb67fac, 63'h00000001a37f6cf5, 63'h7fffff597437a4d3, 63'h0000463df5cbb7a5, 63'h7fdef03c86bc0bcf, 63'h14573a7de0eefe86};
        rom[ 19] = {63'h00000000000a50d7, 63'h7ffffffffbf91e9d, 63'h000000018eb5cf5e, 63'h7fffff5fd83480f5, 63'h00004453fd36c7f2, 63'h7fdf7acb47cb431f, 63'h1436705370ef6f52};
        rom[ 20] = {63'h0000000000099669, 63'h7ffffffffc36fbfc, 63'h000000017b2d7633, 63'h7fffff65eb953f32, 63'h0000427cb66d0b8f, 63'h7fe00198f1c91171, 63'h14162ed418df3a29};
        rom[ 21] = {63'h000000000008eb13, 63'h7ffffffffc707b7a, 63'h0000000168cf9196, 63'h7fffff6bb330ae0e, 63'h000040b736f32cf3, 63'h7fe084c9fb65314b, 63'h13f6725124189ef1};
        rom[ 22] = {63'h0000000000084d76, 63'h7ffffffffca5f799, 63'h0000000157872d4c, 63'h7fffff71338622e4, 63'h00003f02a24d30e8, 63'h7fe104811483c784, 63'h13d7373f6eeaa35f};
        rom[ 23] = {63'h000000000007bc55, 63'h7ffffffffcd7c29b, 63'h000000014741051e, 63'h7fffff7670c48faa, 63'h00003d5e2902d751, 63'h7fe180df413ceded, 63'h13b87a35ad773109};
        rom[ 24] = {63'h0000000000073692, 63'h7ffffffffd062758, 63'h0000000137eb5db0, 63'h7fffff7b6ed0f356, 63'h00003bc907b840b8, 63'h7fe1fa03f2f99705, 63'h139a37eacc9c09fe};
        rom[ 25] = {63'h000000000006bb2e, 63'h7ffffffffd3169fb, 63'h000000012975e146, 63'h7fffff80314c359c, 63'h00003a428659021f, 63'h7fe2700d1fd4755b, 63'h137c6d346b1790ab};
        rom[ 26] = {63'h0000000000064940, 63'h7ffffffffd59c8ae, 63'h000000011bd18008, 63'h7fffff84bb987cdd, 63'h000038c9f753ffdb, 63'h7fe2e3175862147d, 63'h135f1705693f4430};
        rom[ 27] = {63'h000000000005dff6, 63'h7ffffffffd7f7c2b, 63'h000000010ef0536b, 63'h7fffff8910de0b9d, 63'h0000375eb6e69263, 63'h7fe3533ddc002dca, 63'h1342326c8dbf6759};
        rom[ 28] = {63'h0000000000057e95, 63'h7ffffffffda2b848, 63'h0000000102c58460, 63'h7fffff8d340fb12c, 63'h000036002a759d83, 63'h7fe3c09aabc96fab, 63'h1325bc933df9e2ae};
        rom[ 29] = {63'h0000000000052471, 63'h7ffffffffdc3ac6c, 63'h00000000f74533fc, 63'h7fffff9127eed82c, 63'h000034adbff363e0, 63'h7fe42b469c486097, 63'h1309b2bc48b65c44};
        rom[ 30] = {63'h000000000004d0ee, 63'h7ffffffffde283fe, 63'h00000000ec646665, 63'h7fffff94ef0f3c48, 63'h00003366ed50fe91, 63'h7fe493596601b98b, 63'h12ee1242c1eefdbf};
        rom[ 31] = {63'h0000000000048380, 63'h7ffffffffdff66bf, 63'h00000000e218efaf, 63'h7fffff988bda4f90, 63'h0000322b2ffa7b64, 63'h7fe4f8e9b4ec7e9f, 63'h12d2d898ee9cad73};
        rom[ 32] = {63'h0000000000043ba7, 63'h7ffffffffe1a7929, 63'h00000000d859628d, 63'h7fffff9c0092570a, 63'h000030fa0c5cbc38, 63'h7fe55c0d36ec398d, 63'h12b803473f7ad0f4};
        rom[ 33] = {63'h000000000003f8f0, 63'h7ffffffffe33dcb3, 63'h00000000cf1d0097, 63'h7fffff9f4f55453c, 63'h00002fd30d744763, 63'h7fe5bcd8a9600505, 63'h129d8feb59ce351f};
        rom[ 34] = {63'h000000000003baf0, 63'h7ffffffffe4bb021, 63'h00000000c65bac01, 63'h7fffffa27a1f58b6, 63'h00002eb5c4644c4a, 63'h7fe61b5fe5d78af8, 63'h12837c372d4c9cfd};
        rom[ 35] = {63'h0000000000038147, 63'h7ffffffffe620fbb, 63'h00000000be0ddaa1, 63'h7fffffa582cd842f, 63'h00002da1c81530a4, 63'h7fe677b5edfdaff6, 63'h1269c5f01652e406};
        rom[ 36] = {63'h0000000000034b9d, 63'h7ffffffffe771587, 63'h00000000b62c8a19, 63'h7fffffa86b1fa4fd, 63'h00002c96b4da0a75, 63'h7fe6d1ecf6c75e99, 63'h12506aee0ba6b470};
        rom[ 37] = {63'h00000000000319a3, 63'h7ffffffffe8ad980, 63'h00000000aeb13517, 63'h7fffffab34ba8c77, 63'h00002b942c1c78c6, 63'h7fe72a1672f3bc32, 63'h1237691ad70eadb9};
        rom[ 38] = {63'h000000000002eb10, 63'h7ffffffffe9d71c0, 63'h00000000a795c97f, 63'h7fffffade129e026, 63'h00002a99d40e59bc, 63'h7fe780431cea00d1, 63'h121ebe7158189761};
        rom[ 39] = {63'h000000000002bfa0, 63'h7ffffffffeaef2aa, 63'h00000000a0d49f74, 63'h7fffffb071e1d477, 63'h000029a75760e836, 63'h7fe7d483000035d5, 63'h120668fcd070f863};
        rom[ 40] = {63'h0000000000029718, 63'h7ffffffffebf6f14, 63'h000000009a68712d, 63'h7fffffb2e840c519, 63'h000028bc6500d52d, 63'h7fe826e581353c8d, 63'h11ee66d8393a3ca4};
        rom[ 41] = {63'h000000000002713d, 63'h7ffffffffecef861, 63'h00000000944c5372, 63'h7fffffb54590ae0e, 63'h000027d8afd6fa99, 63'h7fe877796767b0d4, 63'h11d6b62da0db8acf};
        rom[ 42] = {63'h0000000000024ddf, 63'h7ffffffffedd9ea9, 63'h000000008e7baec3, 63'h7fffffb78b088815, 63'h000026fbee8d4ddf, 63'h7fe8c64ce3127f4b, 63'h11bf553590c8a15a};
        rom[ 43] = {63'h0000000000022ccc, 63'h7ffffffffeeb70ce, 63'h0000000088f23916, 63'h7fffffb9b9cd8acd, 63'h00002625db57bf81, 63'h7fe9136d95975ad6, 63'h11a842367acc91e4};
        rom[ 44] = {63'h0000000000020ddb, 63'h7ffffffffef87c99, 63'h0000000083abf00f, 63'h7fffffbbd2f456da, 63'h0000255633c0bcbb, 63'h7fe95ee8981e9f64, 63'h11917b842d690db7};
        rom[ 45] = {63'h000000000001f0e4, 63'h7fffffffff04ced2, 63'h000000007ea513be, 63'h7fffffbdd78209f2, 63'h0000248cb8790de3, 63'h7fe9a8ca82139fc5, 63'h117aff7f4ee33b33};
        rom[ 46] = {63'h000000000001d5c2, 63'h7fffffffff107350, 63'h0000000079da21c5, 63'h7fffffbfc86d3eb1, 63'h000023c92d2ad241, 63'h7fe9f11f6f43d7ca, 63'h1164cc94de9dc641};
        rom[ 47] = {63'h000000000001bc54, 63'h7fffffffff1b7513, 63'h000000007547d0e1, 63'h7fffffc1a69ef9dc, 63'h0000230b584f5f11, 63'h7fea37f305a70290, 63'h114ee13dbc6619d4};
        rom[ 48] = {63'h000000000001a47b, 63'h7fffffffff25de51, 63'h0000000070eb0cd8, 63'h7fffffc372f38685, 63'h000022530307cc52, 63'h7fea7d507ad5a525, 63'h11393bfe35607799};
        rom[ 49] = {63'h0000000000018e1b, 63'h7fffffffff2fb885, 63'h000000006cc0f2ac, 63'h7fffffc52e3b427f, 63'h0000219ff8f7fe1b, 63'h7feac14299333730, 63'h1123db659643ff3a};
        rom[ 50] = {63'h0000000000017919, 63'h7fffffffff390c84, 63'h0000000068c6cd29, 63'h7fffffc6d93b5c52, 63'h000020f20823fd43, 63'h7feb03d3c4d0b4cf, 63'h110ebe0dc29cb050};
        rom[ 51] = {63'h000000000001655d, 63'h7fffffffff41e280, 63'h0000000064fa11ae, 63'h7fffffc874ae83de, 63'h0000204900cf75b0, 63'h7feb450e000c0e13, 63'h10f9e29ad0ce1178};
        rom[ 52] = {63'h00000000000152d1, 63'h7fffffffff4a4220, 63'h0000000061585d3f, 63'h7fffffca01458eb7, 63'h00001fa4b55f33d3, 63'h7feb84faeff09875, 63'h10e547baaa9572a4};
        rom[ 53] = {63'h0000000000014160, 63'h7fffffffff523281, 63'h000000005ddf71c3, 63'h7fffffcb7fa8111f, 63'h00001f04fa3c7df9, 63'h7febc3a3e05c5cbf, 63'h10d0ec24b1cebfd3};
        rom[ 54] = {63'h00000000000130f8, 63'h7fffffffff59ba46, 63'h000000005a8d3388, 63'h7fffffccf074ec95, 63'h00001e69a5ba28ae, 63'h7fec0111c7edd7e0, 63'h10bcce996942914e};
        rom[ 55] = {63'h0000000000012185, 63'h7fffffffff60dfa0, 63'h00000000575fa6ed, 63'h7fffffce5442d4ab, 63'h00001dd28ffb4806, 63'h7fec3d4d4bbd8648, 63'h10a8ede221479d37};
        rom[ 56] = {63'h00000000000112fa, 63'h7fffffffff67a855, 63'h000000005454ee3d, 63'h7fffffcfaba0caf0, 63'h00001d3f92db61dd, 63'h7fec785ec2e6574a, 63'h109548d0a804e842};
        rom[ 57] = {63'h0000000000010545, 63'h7fffffffff6e19ca, 63'h00000000516b47ad, 63'h7fffffd0f716929b, 63'h00001cb089d8074e, 63'h7fecb24e39dff04b, 63'h1081de3efd2515e4};
        rom[ 58] = {63'h000000000000f859, 63'h7fffffffff743909, 63'h000000004ea10b8b, 63'h7fffffd237251c7a, 63'h00001c2551fbbd64, 63'h7feceb2375ad75f9, 63'h106ead0f08ce06d3};
        rom[ 59] = {63'h000000000000ec2a, 63'h7fffffffff7a0ac8, 63'h000000004bf4aa85, 63'h7fffffd36c46ebe0, 63'h00001b9dc9ca1eff, 63'h7fed22e5f6e363a0, 63'h105bb42a55b29398};
        rom[ 60] = {63'h000000000000e0aa, 63'h7fffffffff7f936f, 63'h000000004964ac14, 63'h7fffffd496f074ed, 63'h00001b19d12d235d, 63'h7fed599cfc86ce35, 63'h1048f281ce16a38e};
        rom[ 61] = {63'h000000000000d5cf, 63'h7fffffffff84d71d, 63'h0000000046efad06, 63'h7fffffd5b79074c4, 63'h00001a994963764f, 63'h7fed8f4f86c8492c, 63'h1036670d7ba02a39};
        rom[ 62] = {63'h000000000000cb8f, 63'h7fffffffff89d9af, 63'h0000000044945e1d, 63'h7fffffd6ce904419, 63'h00001a1c14efd075, 63'h7fedc404599c7e9a, 63'h102410cc49d1b86a};
        rom[ 63] = {63'h000000000000c1df, 63'h7fffffffff8e9ec3, 63'h00000000425182d1, 63'h7fffffd7dc54247a, 63'h000019a217893f1e, 63'h7fedf7c1ff346a08, 63'h1011eec3cb0d4eed};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [WSB-1:0]   sb_p   = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .WACC(ACCW), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
