/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=32 (degree 4); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m32 #(parameter integer WMAN = 32, parameter integer D = 4, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                 clk,
    input  wire                 rst,
    input  wire                 in_valid,
    input  wire       [WSB-1:0] sb_in,
    input  wire      [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                 out_valid,
    output wire       [WSB-1:0] sb_out,
    output wire [2*WMAN+12-2:0] l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    // verilator coverage_off
    generate if (D != 4) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 6;
    localparam integer RW   = 25;
    localparam integer CW   = 47;
    localparam integer ACCW = 49;
    localparam integer NSEG = 64;
    localparam integer HSBW = WSB + WFRAC;  // carry t alongside the sideband to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {47'h000000047835, 47'h7ffffe8ecc41, 47'h00007b1c1bcb, 47'h7fd1d571371d, 47'h171547652b7c};
        rom[  1] = {47'h000000043122, 47'h7ffffea0ab52, 47'h000076e33b93, 47'h7fd2c767b432, 47'h16e79685c2cb};
        rom[  2] = {47'h00000003ef6e, 47'h7ffffeb16e40, 47'h000072de4fcb, 47'h7fd3b120f1c1, 47'h16bad3758ef7};
        rom[  3] = {47'h00000003b29e, 47'h7ffffec12a81, 47'h00006f0a241b, 47'h7fd4930199ba, 47'h168ef62a2e24};
        rom[  4] = {47'h000000037a46, 47'h7ffffecff3a6, 47'h00006b63c1b9, 47'h7fd56d682bdc, 47'h1663f6fac90e};
        rom[  5] = {47'h000000034603, 47'h7ffffedddb87, 47'h000067e869fb, 47'h7fd640ad7349, 47'h1639ce9a2484};
        rom[  6] = {47'h00000003157b, 47'h7ffffeeaf276, 47'h000064959177, 47'h7fd70d24f1d2, 47'h161076112348};
        rom[  7] = {47'h00000002e85f, 47'h7ffffef7475d, 47'h00006168dba3, 47'h7fd7d31d4201, 47'h15e7e6b9ae79};
        rom[  8] = {47'h00000002be67, 47'h7fffff02e7eb, 47'h00005e6016d9, 47'h7fd892e070d1, 47'h15c01a39fbd2};
        rom[  9] = {47'h00000002974f, 47'h7fffff0de0a8, 47'h00005b7938c9, 47'h7fd94cb44fd3, 47'h15990a8029c7};
        rom[ 10] = {47'h0000000272de, 47'h7fffff183d1a, 47'h000058b25b3a, 47'h7fda00dac091, 47'h1572b1be2a53};
        rom[ 11] = {47'h0000000250dd, 47'h7fffff2207d7, 47'h00005609b91b, 47'h7fdaaf91f9c1, 47'h154d0a65f60f};
        rom[ 12] = {47'h00000002311a, 47'h7fffff2b4a9d, 47'h0000537dabde, 47'h7fdb5914c6e4, 47'h15280f260198};
        rom[ 13] = {47'h00000002136a, 47'h7fffff340e68, 47'h0000510ca90c, 47'h7fdbfd9ac2d9, 47'h1503bae5f00b};
        rom[ 14] = {47'h00000001f7a4, 47'h7fffff3c5b7e, 47'h00004eb54013, 47'h7fdc9d588dca, 47'h14e008c37dbc};
        rom[ 15] = {47'h00000001dda3, 47'h7fffff443988, 47'h00004c761847, 47'h7fdd387ffef6, 47'h14bcf40f9eb7};
        rom[ 16] = {47'h00000001c544, 47'h7fffff4baf94, 47'h00004a4def0f, 47'h7fddcf40529f, 47'h149a784bcd19};
        rom[ 17] = {47'h00000001ae69, 47'h7fffff52c42e, 47'h0000483b963d, 47'h7fde61c65483, 47'h14789127839b};
        rom[ 18] = {47'h0000000198f5, 47'h7fffff597d64, 47'h0000463df287, 47'h7fdef03c8725, 47'h14573a7de0ed};
        rom[ 19] = {47'h0000000184cf, 47'h7fffff5fe0d3, 47'h00004453fa25, 47'h7fdf7acb482d, 47'h1436705370ed};
        rom[ 20] = {47'h0000000171de, 47'h7fffff65f3b0, 47'h0000427cb38a, 47'h7fe00198f225, 47'h14162ed418dd};
        rom[ 21] = {47'h00000001600d, 47'h7fffff6bbad1, 47'h000040b7343c, 47'h7fe084c9fbbc, 47'h13f672512417};
        rom[ 22] = {47'h000000014f48, 47'h7fffff713ab4, 47'h00003f029fbe, 47'h7fe1048114d6, 47'h13d7373f6ee9};
        rom[ 23] = {47'h000000013f7c, 47'h7fffff767788, 47'h00003d5e269a, 47'h7fe180df418a, 47'h13b87a35ad76};
        rom[ 24] = {47'h000000013098, 47'h7fffff7b7532, 47'h00003bc90572, 47'h7fe1fa03f342, 47'h139a37eacc9b};
        rom[ 25] = {47'h00000001228d, 47'h7fffff803751, 47'h00003a428434, 47'h7fe2700d2019, 47'h137c6d346b16};
        rom[ 26] = {47'h00000001154b, 47'h7fffff84c147, 47'h000038c9f54e, 47'h7fe2e31758a3, 47'h135f1705693e};
        rom[ 27] = {47'h0000000108c7, 47'h7fffff89163c, 47'h0000375eb4fd, 47'h7fe3533ddc3d, 47'h1342326c8dbe};
        rom[ 28] = {47'h00000000fcf3, 47'h7fffff8d3922, 47'h0000360028a7, 47'h7fe3c09aac03, 47'h1325bc933df9};
        rom[ 29] = {47'h00000000f1c3, 47'h7fffff912cbb, 47'h000034adbe3e, 47'h7fe42b469c7f, 47'h1309b2bc48b5};
        rom[ 30] = {47'h00000000e72e, 47'h7fffff94f399, 47'h00003366ebb3, 47'h7fe493596635, 47'h12ee1242c1ee};
        rom[ 31] = {47'h00000000dd2a, 47'h7fffff989026, 47'h0000322b2e72, 47'h7fe4f8e9b51d, 47'h12d2d898ee9c};
        rom[ 32] = {47'h00000000d3ad, 47'h7fffff9c04a5, 47'h000030fa0ae9, 47'h7fe55c0d371b, 47'h12b803473f7a};
        rom[ 33] = {47'h00000000caaf, 47'h7fffff9f5331, 47'h00002fd30c14, 47'h7fe5bcd8a98c, 47'h129d8feb59cd};
        rom[ 34] = {47'h00000000c228, 47'h7fffffa27dc8, 47'h00002eb5c316, 47'h7fe61b5fe601, 47'h12837c372d4c};
        rom[ 35] = {47'h00000000ba11, 47'h7fffffa58647, 47'h00002da1c6d8, 47'h7fe677b5ee25, 47'h1269c5f01652};
        rom[ 36] = {47'h00000000b264, 47'h7fffffa86e6c, 47'h00002c96b3ad, 47'h7fe6d1ecf6ed, 47'h12506aee0ba6};
        rom[ 37] = {47'h00000000ab19, 47'h7fffffab37dc, 47'h00002b942aff, 47'h7fe72a167317, 47'h1237691ad70e};
        rom[ 38] = {47'h00000000a42b, 47'h7fffffade424, 47'h00002a99d2ff, 47'h7fe780431d0c, 47'h121ebe715818};
        rom[ 39] = {47'h000000009d95, 47'h7fffffb074b6, 47'h000029a7565f, 47'h7fe7d4830020, 47'h120668fcd070};
        rom[ 40] = {47'h000000009752, 47'h7fffffb2eaf2, 47'h000028bc640b, 47'h7fe826e58154, 47'h11ee66d8393a};
        rom[ 41] = {47'h00000000915c, 47'h7fffffb54820, 47'h000027d8aeed, 47'h7fe877796785, 47'h11d6b62da0db};
        rom[ 42] = {47'h000000008baf, 47'h7fffffb78d79, 47'h000026fbedaf, 47'h7fe8c64ce32e, 47'h11bf553590c8};
        rom[ 43] = {47'h000000008648, 47'h7fffffb9bc20, 47'h00002625da84, 47'h7fe9136d95b2, 47'h11a842367acc};
        rom[ 44] = {47'h000000008121, 47'h7fffffbbd52b, 47'h0000255632f7, 47'h7fe95ee89838, 47'h11917b842d69};
        rom[ 45] = {47'h000000007c39, 47'h7fffffbdd99e, 47'h0000248cb7b8, 47'h7fe9a8ca822c, 47'h117aff7f4ee3};
        rom[ 46] = {47'h00000000778b, 47'h7fffffbfca71, 47'h000023c92c73, 47'h7fe9f11f6f5b, 47'h1164cc94de9d};
        rom[ 47] = {47'h000000007314, 47'h7fffffc1a88b, 47'h0000230b57a0, 47'h7fea37f305bd, 47'h114ee13dbc66};
        rom[ 48] = {47'h000000006ed0, 47'h7fffffc374c9, 47'h000022530260, 47'h7fea7d507aeb, 47'h11393bfe3560};
        rom[ 49] = {47'h000000006abf, 47'h7fffffc52ffc, 47'h0000219ff858, 47'h7feac1429947, 47'h1123db659644};
        rom[ 50] = {47'h0000000066db, 47'h7fffffc6dae8, 47'h000020f2078b, 47'h7feb03d3c4e4, 47'h110ebe0dc29c};
        rom[ 51] = {47'h000000006324, 47'h7fffffc87648, 47'h00002049003e, 47'h7feb450e001e, 47'h10f9e29ad0ce};
        rom[ 52] = {47'h000000005f97, 47'h7fffffca02cd, 47'h00001fa4b4d4, 47'h7feb84faf002, 47'h10e547baaa95};
        rom[ 53] = {47'h000000005c32, 47'h7fffffcb811e, 47'h00001f04f9b7, 47'h7febc3a3e06d, 47'h10d0ec24b1ce};
        rom[ 54] = {47'h0000000058f2, 47'h7fffffccf1db, 47'h00001e69a53a, 47'h7fec0111c7fe, 47'h10bcce996942};
        rom[ 55] = {47'h0000000055d6, 47'h7fffffce559a, 47'h00001dd28f81, 47'h7fec3d4d4bcd, 47'h10a8ede22147};
        rom[ 56] = {47'h0000000052dc, 47'h7fffffcface9, 47'h00001d3f9266, 47'h7fec785ec2f5, 47'h109548d0a805};
        rom[ 57] = {47'h000000005003, 47'h7fffffd0f851, 47'h00001cb08968, 47'h7fecb24e39ee, 47'h1081de3efd25};
        rom[ 58] = {47'h000000004d48, 47'h7fffffd23852, 47'h00001c255190, 47'h7feceb2375bb, 47'h106ead0f08ce};
        rom[ 59] = {47'h000000004aaa, 47'h7fffffd36d68, 47'h00001b9dc963, 47'h7fed22e5f6f0, 47'h105bb42a55b2};
        rom[ 60] = {47'h000000004827, 47'h7fffffd49805, 47'h00001b19d0ca, 47'h7fed599cfc93, 47'h1048f281ce16};
        rom[ 61] = {47'h0000000045bf, 47'h7fffffd5b89a, 47'h00001a994905, 47'h7fed8f4f86d4, 47'h1036670d7ba0};
        rom[ 62] = {47'h000000004370, 47'h7fffffd6cf8f, 47'h00001a1c1495, 47'h7fedc40459a8, 47'h102410cc49d1};
        rom[ 63] = {47'h000000004139, 47'h7fffffd7dd49, 47'h000019a21732, 47'h7fedf7c1ff3f, 47'h1011eec3cb0d};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [WSB-1:0]   sb_p   = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .WACC(ACCW), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
