/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=32): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m32 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 57:0] x0,
    input  wire signed [ 57:0] y0,
    input  wire signed [ 58:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 57:0] xn,
    output wire signed [ 57:0] yn,
    output wire signed [ 58:0] zn,
    output wire        [ 58:0] const2pi,   // round(2*pi * 2**XF), CWB = XF + 3 bits (sin/cos small angle)
    output wire        [ 53:0] inv_tau,    // round(2**XF / (2*pi)), XF-2 bits (atan2 turns scaling)
    output wire        [ 57:0] kinv        // round(2**XF / gain), inverse CORDIC-gain (atan2 magnitude)
);
    localparam integer N    = 21;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 58;
    localparam integer WZ   = 59;
    localparam integer XF   = 56;   // x/y fractional scale
    localparam integer ZF   = 56;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 59;
    localparam signed [WX-1:0] KINV = 58'sd43757185469216835;   // round(1/gain * 2**XF) (== 2**XF/gain)

    assign const2pi = 59'd452751216129820178;
    assign inv_tau  = 54'd11468322278445317;
    assign kinv     = KINV[WX-1:0];

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        59'd10937044409,   // atan(2^-20)/2pi
        59'd21874088818,   // atan(2^-19)/2pi
        59'd43748177637,   // atan(2^-18)/2pi
        59'd87496355272,   // atan(2^-17)/2pi
        59'd174992710534,   // atan(2^-16)/2pi
        59'd349985420986,   // atan(2^-15)/2pi
        59'd699970841321,   // atan(2^-14)/2pi
        59'd1399941677427,   // atan(2^-13)/2pi
        59'd2799883313132,   // atan(2^-12)/2pi
        59'd5599766292493,   // atan(2^-11)/2pi
        59'd11199529914810,   // atan(2^-10)/2pi
        59'd22399038468267,   // atan(2^-9)/2pi
        59'd44797906047171,   // atan(2^-8)/2pi
        59'd89594445026371,   // atan(2^-7)/2pi
        59'd179177955010598,   // atan(2^-6)/2pi
        59'd358268477703266,   // atan(2^-5)/2pi
        59'd715839029270683,   // atan(2^-4)/2pi
        59'd1426143154396570,   // atan(2^-3)/2pi
        59'd2809494260081567,   // atan(2^-2)/2pi
        59'd5317260203651848,   // atan(2^-1)/2pi
        59'd9007199254740992   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
