/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=48 (degree 6); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m48 #(parameter integer WMAN = 48, parameter integer D = 6, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 6) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 4;
    localparam integer CF   = 60;
    localparam integer RW   = 56;
    localparam integer CW   = 63;
    localparam integer ACCW = 65;
    localparam integer NSEG = 16;
    localparam integer HSBW = WSB;

    (* rom_style = "logic" *) // keep a small table in logic
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {63'h0000000000a50e92, 63'h00000000575d1d24, 63'h00000027655a3595, 63'h00000e35846a5713, 63'h0003d7f7bff08a99, 63'h00b17217f7d1cc5b, 63'h1000000000000008};
        rom[  1] = {63'h0000000000ac5d57, 63'h000000005b3b4d51, 63'h0000002923de7bd6, 63'h00000ed6905b692d, 63'h00040388209c35a0, 63'h00b94d47530aa61e, 63'h10b5586cf9890f6b};
        rom[  2] = {63'h0000000000b3fef0, 63'h000000005f45545f, 63'h0000002af6279e2a, 63'h00000f7ebd9d9cf2, 63'h000431064350404e, 63'h00c18181a101eebe, 63'h1172b83c7d517ae6};
        rom[  3] = {63'h0000000000bbf707, 63'h00000000637d2330, 63'h0000002cdd15accd, 63'h0000102e5d013ffe, 63'h000460880458777f, 63'h00ca12b819ac5e35, 63'h12387a6e75623870};
        rom[  4] = {63'h0000000000c44970, 63'h0000000067e4c0a4, 63'h0000002ed992a387, 63'h000010e5c2ea92f8, 63'h0004922437c5920e, 63'h00d30508a3913a53, 63'h1306fe0a31b71538};
        rom[  5] = {63'h0000000000ccfa2b, 63'h000000006c7e4a95, 63'h00000030ec92da1f, 63'h000011a5477a570d, 63'h0004c5f2b4656dc4, 63'h00dc5cbfce382122, 63'h13dea64c12342240};
        rom[  6] = {63'h0000000000d60d66, 63'h00000000714bf6da, 63'h00000033171579c2, 63'h0000126d46b826fc, 63'h0004fc0c5f37a112, 63'h00e61e5ae302bc15, 63'h14bfdad5362a2728};
        rom[  7] = {63'h0000000000df877d, 63'h0000000076501458, 63'h000000355a24f7a2, 63'h0000133e20beb02a, 63'h0005348b3763e2c9, 63'h00f04e8a0d707cb8, 63'h15ab07dd48542964};
        rom[  8] = {63'h0000000000e96cfd, 63'h000000007b8d0c1c, 63'h00000037b6d794ff, 63'h0000141839e9e0e5, 63'h00056f8a62b80767, 63'h00faf2329bd5c3cc, 63'h16a09e667f3bcc9c};
        rom[  9] = {63'h0000000000f3c2a8, 63'h0000000081056287, 63'h0000003a2e4fe4de, 63'h000014fbfb072217, 63'h0005ad263ab394b3, 63'h01060e71599b9395, 63'h17a11473eb0186e4};
        rom[ 10] = {63'h0000000000fe8d75, 63'h0000000086bbb87e, 63'h0000003cc1bd57a6, 63'h000015e9d187b394, 63'h0005ed7c5a273060, 63'h0111a89d0429331b, 63'h18ace5422aa0db68};
        rom[ 11] = {63'h000000000109d294, 63'h000000008cb2ccb3, 63'h0000003f725cccf6, 63'h000016e22fb54326, 63'h000630abab6e7592, 63'h011dc648dba5f832, 63'h19c49182a3f0902a};
        rom[ 12] = {63'h0000000001159770, 63'h0000000092ed7cf4, 63'h0000004241792be5, 63'h000017e58ce8d7b9, 63'h000676d4774b073f, 63'h012a6d4750cecf68, 63'h1ae89f995ad3ad6c};
        rom[ 13] = {63'h000000000121e1af, 63'h00000000996ec78d, 63'h00000045306c0203, 63'h000018f465c42aea, 63'h0006c018746802ed, 63'h0137a3acd12911d2, 63'h1c199bdd85529c30};
        rom[ 14] = {63'h00000000012eb73a, 63'h00000000a039ccb4, 63'h00000048409e296a, 63'h00001a0f3c6d8ca7, 63'h00070c9ad78d482c, 63'h01456fd2b2ead017, 63'h1d5818dcfba48735};
        rom[ 15] = {63'h00000000013c1e3c, 63'h00000000a751d011, 63'h0000004b7388761f, 63'h00001b3698ce6d8c, 63'h00075c80648a5db1, 63'h0153d85a41fff6b2, 63'h1ea4afa2a490d995};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
