/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=48 (degree 6); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes the kernel C(f)=log2(1+f)/f by the unsigned coordinate v (WFRAC+1 bits) and
/// returns the SIGNED log2(m') = f*C(f) = F*C(f) at scale 2**-F2, F2 = WFRAC+1+CF (f<0 when m>=sqrt(2)).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + _zkf_log2_final_mul; valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m48 #(parameter integer WMAN = 48, parameter integer D = 6, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0, parameter integer WMULTIPLIER = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire         [WSB-1:0] sb_in,
    input  wire        [WMAN-1:0] v,          // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    input  wire signed [WMAN-1:0] f,          // signed reduced argument F = v - 2**WFRAC, scale 2**-(WFRAC+1)
    output wire                   out_valid,
    output wire         [WSB-1:0] sb_out,
    output wire signed [2*WMAN+12:0] l_fix    // SIGNED log2(m') = f*C(f) at scale 2**-F2, F2 = WFRAC+1+CF
);
    // verilator coverage_off
    generate if (D != 6) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer RW   = 41;
    localparam integer CW   = 63;
    localparam integer ACCW = 65;
    localparam integer NSEG = 128;
    localparam integer HSBW = WSB + WF;  // carry the signed reduced argument f to the final multiply

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {63'h000000000035e37b, 63'h7fffffffef5c10eb, 63'h0000000511d4f6ff, 63'h7ffffe61ccec0508, 63'h00008eab89ad2401, 63'h7fc755c4d6a3ea4c, 63'h1ffffffffffffffa};
        rom[  1] = {63'h0000000000311447, 63'h7ffffffff09f24f8, 63'h00000004c1c51cf1, 63'h7ffffe75720e3d7d, 63'h000089eeb82fb713, 63'h7fc86e554625c6a8, 63'h1fc7e2d72ea3fea9};
        rom[  2] = {63'h00000000002cc305, 63'h7ffffffff1c56550, 63'h0000000477bcf943, 63'h7ffffe87e32fa854, 63'h0000856b02108295, 63'h7fc97da5c8069363, 63'h1f90d995519d1009};
        rom[  3] = {63'h000000000028e138, 63'h7ffffffff2d1c4a5, 63'h000000043333bcf9, 63'h7ffffe993758b08c, 63'h0000811cee627f2b, 63'h7fca84250e92031c, 63'h1f5adb326892efe4};
        rom[  4] = {63'h000000000025623e, 63'h7ffffffff3c6dee8, 63'h00000003f3ae7f12, 63'h7ffffea9838ade91, 63'h00007d014639ae6a, 63'h7fcb823b1d3e2561, 63'h1f25df11c30e8585};
        rom[  5] = {63'h0000000000223b0a, 63'h7ffffffff4a7044f, 63'h00000003b8bea627, 63'h7ffffeb8daf53174, 63'h000079150ee68f0f, 63'h7fcc7849c6cec20c, 63'h1ef1dcfb91abf812};
        rom[  6] = {63'h00000000001f61ec, 63'h7ffffffff57442e0, 63'h0000000382008571, 63'h7ffffec74f2287de, 63'h0000755584c5811c, 63'h7fcd66ad208684cd, 63'h1ebecd16efde601a};
        rom[  7] = {63'h00000000001cce66, 63'h7ffffffff6306e9a, 63'h000000034f1a261a, 63'h7ffffed4f022d7dd, 63'h000071c016916edc, 63'h7fce4dbbeb7cce33, 63'h1e8ca7e45be11818};
        rom[  8] = {63'h00000000001a78fe, 63'h7ffffffff6dd2894, 63'h000000031fba36ce, 63'h7ffffee1ccafda42, 63'h00006e52612b2461, 63'h7fcf2dc7f50fcb3b, 63'h1e5b663893799019};
        rom[  9] = {63'h0000000000185b1f, 63'h7ffffffff77be51c, 63'h00000002f3971c62, 63'h7ffffeedf24db7f1, 63'h00006b0a2bc88b01, 63'h7fd0071e6f4f1ebf, 63'h1e2b0137cd163252};
        rom[ 10] = {63'h0000000000166ef9, 63'h7ffffffff80df10b, 63'h00000002ca6e1f27, 63'h7ffffef96d683484, 63'h000067e564808c10, 63'h7fd0da0842236a4a, 63'h1dfb725145a6f09a};
        rom[ 11] = {63'h000000000014af69, 63'h7ffffffff894766d, 63'h00000002a402b132, 63'h7fffff04496cc13a, 63'h000064e21d29b70e, 63'h7fd1a6ca55e1eb90, 63'h1dccb33b1c459aa0};
        rom[ 12] = {63'h00000000001317e4, 63'h7ffffffff9108083, 63'h00000002801dca4a, 63'h7fffff0e90e1d54b, 63'h000061fe8882f30a, 63'h7fd26da5d7e8ceaf, 63'h1d9ebdee7569d57d};
        rom[ 13] = {63'h000000000011a460, 63'h7ffffffff982ff50, 63'h000000025e8d56c4, 63'h7fffff184d7bdcb0, 63'h00005f38f79e87ca, 63'h7fd32ed879d06fa5, 63'h1d718ca3dff8cf2f};
        rom[ 14] = {63'h0000000000105149, 63'h7ffffffff9eccaa8, 63'h000000023f23b6ef, 63'h7fffff2188300429, 63'h00005c8fd788aea5, 63'h7fd3ea9cabaf471f, 63'h1d4519cff7059dc0};
        rom[ 15] = {63'h00000000000f1b6e, 63'h7ffffffffa4ea4eb, 63'h0000000221b74ce5, 63'h7fffff2a4945205c, 63'h00005a01af23a19e, 63'h7fd4a129d1e16995, 63'h1d1960203b8e6a8b};
        rom[ 16] = {63'h00000000000dfff9, 63'h7ffffffffaa93d5a, 63'h0000000206221719, 63'h7fffff329862e646, 63'h0000578d1d33cd2b, 63'h7fd552b476b91e99, 63'h1cee5a7821eda355};
        rom[ 17] = {63'h00000000000cfc62, 63'h7ffffffffafd3234, 63'h00000001ec415601, 63'h7fffff3a7c9fa488, 63'h00005530d6976178, 63'h7fd5ff6e7873fab3, 63'h1cc403ee4f16c9c9};
        rom[ 18] = {63'h00000000000c0e64, 63'h7ffffffffb4b128a, 63'h00000001d3f53b8d, 63'h7fffff41fc8ca766, 63'h000052eba4a505d2, 63'h7fd6a78733c6e885, 63'h1c9a57ca020d4f10};
        rom[ 19] = {63'h00000000000b33f9, 63'h7ffffffffb935fd9, 63'h00000001bd20a340, 63'h7fffff491e416c3b, 63'h000050bc63ade69c, 63'h7fd74b2bab4b8b93, 63'h1c715180a6524147};
        rom[ 20] = {63'h00000000000a6b51, 63'h7ffffffffbd68f7d, 63'h00000001a7a8d1e6, 63'h7fffff4fe765c4d8, 63'h00004ea2019fbde5, 63'h7fd7ea86ac12418a, 63'h1c48ecb38c4c56c2};
        rom[ 21] = {63'h000000000009b2cb, 63'h7ffffffffc150bee, 63'h0000000193753c04, 63'h7fffff565d3b0781, 63'h00004c9b7cc3d251, 63'h7fd885c0ef95a4c1, 63'h1c21252dc4ede7ba};
        rom[ 22] = {63'h00000000000908f0, 63'h7ffffffffc4f35e8, 63'h00000001806f5243, 63'h7fffff5c84a464cc, 63'h00004aa7e29838d2, 63'h7fd91d013b46bc5a, 63'h1bf9f6e21e166108};
        rom[ 23] = {63'h0000000000086c71, 63'h7ffffffffc85655d, 63'h000000016e82531a, 63'h7fffff62622e79e9, 63'h000048c64ec0ed56, 63'h7fd9b06c7de3e890, 63'h1bd35de93d614c19};
        rom[ 24] = {63'h000000000007dc1e, 63'h7ffffffffcb7ea62, 63'h000000015d9b2131, 63'h7fffff67fa16332c, 63'h000046f5ea0e9603, 63'h7fda4025eac802cd, 63'h1bad567fd744c0ce};
        rom[ 25] = {63'h00000000000756e5, 63'h7ffffffffce70df1, 63'h000000014da81de9, 63'h7fffff6d504f10a0, 63'h00004535e998fcf2, 63'h7fdacc4f135b09b1, 63'h1b87dd05008c7479};
        rom[ 26] = {63'h000000000006dbd1, 63'h7ffffffffd13129e, 63'h000000013e99079e, 63'h7fffff726888dc40, 63'h000043858deb7e63, 63'h7fdb5507fec9fc2a, 63'h1b62edf898660e7a};
        rom[ 27] = {63'h0000000000066a01, 63'h7ffffffffd3c3536, 63'h00000001305edb32, 63'h7fffff774634dff8, 63'h000041e42241d601, 63'h7fdbda6f4028301f, 63'h1b3e85f9c9575b53};
        rom[ 28] = {63'h00000000000600ae, 63'h7ffffffffd62ad50, 63'h0000000122ebb88f, 63'h7fffff7bec8aa7dc, 63'h00004050fbd3dd83, 63'h7fdc5ca20b196ee5, 63'h1b1aa1c59f97bbd4};
        rom[ 29] = {63'h0000000000059f1f, 63'h7ffffffffd86adc8, 63'h000000011632c9cf, 63'h7fffff805e8c5bc3, 63'h00003ecb792ef266, 63'h7fdcdbbc47216a5a, 63'h1af73e35b36416a4};
        rom[ 30] = {63'h00000000000544b0, 63'h7ffffffffda86534, 63'h000000010a282cb7, 63'h7fffff849f0aba45, 63'h00003d53019bd82f, 63'h7fdd57d8a1b2a945, 63'h1ad4583ee5ffe5db};
        rom[ 31] = {63'h000000000004f0ca, 63'h7ffffffffdc7fe4a, 63'h00000000fec0de5a, 63'h7fffff88b0a8be08, 63'h00003be704900905, 63'h7fddd1109f14d16f, 63'h1ab1ecf0302ef82e};
        rom[ 32] = {63'h000000000004a2e5, 63'h7ffffffffde5a03d, 63'h00000000f3f2a898, 63'h7fffff8c95def555, 63'h00003a86f9297fb3, 63'h7fde477caa383326, 63'h1a8ff971810a5e18};
        rom[ 33] = {63'h0000000000045a85, 63'h7ffffffffe016f0b, 63'h00000000e9b41155, 63'h7fffff9050fe9340, 63'h000039325db41d18, 63'h7fdebb34238aa777, 63'h1a6e7b02ac27f1ff};
        rom[ 34] = {63'h0000000000041738, 63'h7ffffffffe1b8bcc, 63'h00000000dffc4b37, 63'h7fffff93e43440b3, 63'h000037e8b737df59, 63'h7fdf2c4d6ee02b0a, 63'h1a4d6efa661f24b1};
        rom[ 35] = {63'h000000000003d899, 63'h7ffffffffe3414f1, 63'h00000000d6c327c5, 63'h7fffff97518ab34c, 63'h000036a9910f3390, 63'h7fdf9ade00801efc, 63'h1a2cd2c54e875e02};
        rom[ 36] = {63'h0000000000039e48, 63'h7ffffffffe4b2686, 63'h00000000ce010ac2, 63'h7fffff9a9aed0f2f, 63'h000035747c84bb44, 63'h7fe006fa6966bb5e, 63'h1a0ca3e5069c7928};
        rom[ 37] = {63'h00000000000367f1, 63'h7ffffffffe60da5f, 63'h00000000c5aedea9, 63'h7fffff9dc2291894, 63'h000034491077eddd, 63'h7fe070b662c900ca, 63'h19ecdfef53c4ce89};
        rom[ 38] = {63'h0000000000033545, 63'h7ffffffffe754852, 63'h00000000bdc60a23, 63'h7fffffa0c8f1394a, 63'h00003326e9080b9e, 63'h7fe0d824d8e85461, 63'h19cd848d4d41f6bc};
        rom[ 39] = {63'h00000000000305fd, 63'h7ffffffffe88865f, 63'h00000000b6406678, 63'h7fffffa3b0de5e06, 63'h0000320da744e400, 63'h7fe13d57f541e943, 63'h19ae8f7a946217c0};
        rom[ 40] = {63'h000000000002d9d7, 63'h7ffffffffe9aa8d7, 63'h00000000af1836be, 63'h7fffffa67b71aef3, 63'h000030fcf0e4fbfd, 63'h7fe1a061282528fb, 63'h198ffe84969335dd};
        rom[ 41] = {63'h000000000002b096, 63'h7ffffffffeabc286, 63'h00000000a8481fd9, 63'h7fffffa92a1626b9, 63'h00002ff47000ab08, 63'h7fe2015131bb7003, 63'h1971cf89d8c4c333};
        rom[ 42] = {63'h0000000000028a05, 63'h7ffffffffebbe4cc, 63'h00000000a1cb211b, 63'h7fffffabbe220abb, 63'h00002ef3d2d1ce36, 63'h7fe260382a8aa9c4, 63'h195400794b8d97ec};
        rom[ 43] = {63'h00000000000265f0, 63'h7ffffffffecb1fc2, 63'h000000009b9c8d8f, 63'h7fffffae38d84734, 63'h00002dfacb77b957, 63'h7fe2bd258b7b9ee8, 63'h19368f51a795aa8c};
        rom[ 44] = {63'h000000000002442a, 63'h7ffffffffed98252, 63'h0000000095b805c5, 63'h7fffffb09b69b182, 63'h00002d090fbf1521, 63'h7fe31828356c1fdb, 63'h19197a20d1cb5d40};
        rom[ 45] = {63'h0000000000022487, 63'h7ffffffffee71a4e, 63'h0000000090197229, 63'h7fffffb2e6f632c7, 63'h00002c1e58ed6031, 63'h7fe3714e78549a4a, 63'h18fcbf0346f40ffe};
        rom[ 46] = {63'h00000000000206e1, 63'h7ffffffffef3f48c, 63'h000000008abcfdce, 63'h7fffffb51c8ddcc5, 63'h00002b3a638fced6, 63'h7fe3c8a61a081a56, 63'h18e05c238e2eee3f};
        rom[ 47] = {63'h000000000001eb13, 63'h7fffffffff001cf4, 63'h00000000859f11a1, 63'h7fffffb73d31eac1, 63'h00002a5cef4d4b10, 63'h7fe41e3c5c953585, 63'h18c44fb9b207ad6a};
        rom[ 48] = {63'h000000000001d0fc, 63'h7fffffffff0b9e97, 63'h0000000080bc5006, 63'h7fffffb949d5b007, 63'h00002985bebb5b49, 63'h7fe4721e044de59e, 63'h18a8980abfbd3266};
        rom[ 49] = {63'h000000000001b87e, 63'h7fffffffff1683c0, 63'h000000007c1190c5, 63'h7fffffbb435f757f, 63'h000028b49735bad6, 63'h7fe4c4575d7beb37, 63'h188d33684c65e2ed};
        rom[ 50] = {63'h000000000001a17c, 63'h7fffffffff20d600, 63'h00000000779bdd50, 63'h7fffffbd2aa947b4, 63'h000027e940b8738f, 63'h7fe514f441c6ea28, 63'h1872202fffa0cb7c};
        rom[ 51] = {63'h0000000000018bdc, 63'h7fffffffff2a9e42, 63'h0000000073586d4d, 63'h7fffffbf0081b677, 63'h0000272385bc4ba3, 63'h7fe564001d51148b, 63'h18575ccb2387c5b3};
        rom[ 52] = {63'h0000000000017787, 63'h7fffffffff33e4d1, 63'h000000006f44a36d, 63'h7fffffc0c5ac8747, 63'h0000266333155e35, 63'h7fe5b185f38ee2de, 63'h183ce7ae399b73c4};
        rom[ 53] = {63'h0000000000016465, 63'h7fffffffff3cb16a, 63'h000000006b5e0a77, 63'h7fffffc27ae35b82, 63'h000025a817d3b89a, 63'h7fe5fd9063de080d, 63'h1822bf5894663be2};
        rom[ 54] = {63'h0000000000015263, 63'h7fffffffff450b43, 63'h0000000067a25294, 63'h7fffffc420d64b41, 63'h000024f20525d8fa, 63'h7fe64829addf8710, 63'h1808e253f5977850};
        rom[ 55] = {63'h000000000001416d, 63'h7fffffffff4cf919, 63'h00000000640f4ece, 63'h7fffffc5b82c75ce, 63'h00002440ce3cedb7, 63'h7fe6915bb5988bb9, 63'h17ef4f34305bd3d5};
        rom[ 56] = {63'h0000000000013172, 63'h7fffffffff548134, 63'h0000000060a2f2b9, 63'h7fffffc74184886b, 63'h000023944832b777, 63'h7fe6d930075d69d5, 63'h17d60496cfbb4c67};
        rom[ 57] = {63'h0000000000012262, 63'h7fffffffff5ba975, 63'h000000005d5b5052, 63'h7fffffc8bd753c2b, 63'h000022ec49f0f1fa, 63'h7fe71fafdb89eb9c, 63'h17bd0122c0c89b7e};
        rom[ 58] = {63'h000000000001142c, 63'h7fffffffff627757, 63'h000000005a3695fd, 63'h7fffffca2c8dcb83, 63'h00002248ac1a29e5, 63'h7fe764e41a09e2e8, 63'h17a443880070d166};
        rom[ 59] = {63'h00000000000106c3, 63'h7fffffffff68effe, 63'h0000000057330cb0, 63'h7fffffcb8f566031, 63'h000021a948f3e79b, 63'h7fe7a8d55db4beea, 63'h178bca7f4cbccb37};
        rom[ 60] = {63'h000000000000fa1b, 63'h7fffffffff6f1837, 63'h00000000544f1638, 63'h7fffffcce6507a04, 63'h0000210dfc5218f9, 63'h7fe7eb8bf77eb9fc, 63'h177394c9d958d55e};
        rom[ 61] = {63'h000000000000ee26, 63'h7fffffffff74f483, 63'h0000000051892ba7, 63'h7fffffce31f74f0c, 63'h00002076a383a569, 63'h7fe82d0ff1820891, 63'h175ba13107394ae1};
        rom[ 62] = {63'h000000000000e2da, 63'h7fffffffff7a8917, 63'h000000004edfdbd5, 63'h7fffffcf72c025a2, 63'h00001fe31d40192b, 63'h7fe86d6911e24a92, 63'h1743ee861f355636};
        rom[ 63] = {63'h000000000000d82c, 63'h7fffffffff7fd9e7, 63'h000000004c51ca07, 63'h7fffffd0a91aa8cc, 63'h00001f5349965625, 63'h7fe8ac9edd8c5bb1, 63'h172c7ba20f73275b};
        rom[ 64] = {63'h000000000000ce12, 63'h7fffffffff84eaa8, 63'h0000000049ddaca2, 63'h7fffffd1d5713747, 63'h00001ec709dc39bf, 63'h7fe8eab89ad47d06, 63'h171547652b82fe17};
        rom[ 65] = {63'h000000000000c483, 63'h7fffffffff89bed2, 63'h0000000047824bff, 63'h7fffffd2f8292daf, 63'h00001e3e409f2874, 63'h7fe927bd53f4b294, 63'h16fe50b6ef085180};
        rom[ 66] = {63'h000000000000bb78, 63'h7fffffffff8e59a8, 63'h00000000453e814e, 63'h7fffffd411a32c0c, 63'h00001db8d19570de, 63'h7fe963b3d96d11b1, 63'h16e79685c2d2298a};
        rom[ 67] = {63'h000000000000b2e7, 63'h7fffffffff92be3c, 63'h0000000043113591, 63'h7fffffd5223b571e, 63'h00001d36a19078f1, 63'h7fe99ea2c447a1dd, 63'h16d117c6c4456e92};
        rom[ 68] = {63'h000000000000aac9, 63'h7fffffffff96ef6e, 63'h0000000040f960a5, 63'h7fffffd62a4995af, 63'h00001cb7966fa919, 63'h7fe9d890784157ef, 63'h16bad3758efd8731};
        rom[ 69] = {63'h000000000000a318, 63'h7fffffffff9aeff1, 63'h000000003ef6085b, 63'h7fffffd72a21ca31, 63'h00001c3b971409a6, 63'h7fea118325d99b9b, 63'h16a4c894088918c4};
        rom[ 70] = {63'h0000000000009bce, 63'h7fffffffff9ec253, 63'h000000003d063fa8, 63'h7fffffd8221408e2, 63'h00001bc28b5487ce, 63'h7fea4980cc49b12d, 63'h168ef62a2e2a239a};
        rom[ 71] = {63'h00000000000094e3, 63'h7fffffffffa268f7, 63'h000000003b2925d6, 63'h7fffffd9126ccac2, 63'h00001b4c5bf2d84c, 63'h7fea808f3b654c7f, 63'h16795b45e4820340};
        rom[ 72] = {63'h0000000000008e53, 63'h7fffffffffa5e61f, 63'h00000000395de5d2, 63'h7fffffd9fb751d76, 63'h00001ad8f290ee33, 63'h7feab6b415657edc, 63'h1663f6fac913167d};
        rom[ 73] = {63'h0000000000008819, 63'h7fffffffffa93bea, 63'h0000000037a3b577, 63'h7fffffdadd72d06c, 63'h00001a6839a6fd43, 63'h7feaebf4d09f1f7b, 63'h164ec8620582fb46};
        rom[ 74] = {63'h000000000000822e, 63'h7fffffffffac6c58, 63'h0000000035f9d4ef, 63'h7fffffdbb8a89f4f, 63'h000019fa1c79ff94, 63'h7feb2056b925bd47, 63'h1639ce9a248961e9};
        rom[ 75] = {63'h0000000000007c90, 63'h7fffffffffaf794b, 63'h00000000345f8e1b, 63'h7fffffdc8d565a13, 63'h0000198e8712b6f7, 63'h7feb53def25c18e8, 63'h162508c6e8788189};
        rom[ 76] = {63'h0000000000007739, 63'h7fffffffffb2648a, 63'h0000000032d43404, 63'h7fffffdd5bb90aa9, 63'h00001925663522ec, 63'h7feb869278731757, 63'h16107611234d2f73};
        rom[ 77] = {63'h0000000000007226, 63'h7fffffffffb52fc3, 63'h0000000031572253, 63'h7fffffde240b1894, 63'h000018bea758647c, 63'h7febb87621d80f45, 63'h15fc15a690358426};
        rom[ 78] = {63'h0000000000006d53, 63'h7fffffffffb7dc8b, 63'h000000002fe7bcda, 63'h7fffffdee6846a73, 63'h0000185a389f09c2, 63'h7febe98ea09346f8, 63'h15e7e6b9ae7dd4b6};
        rom[ 79] = {63'h00000000000068bc, 63'h7fffffffffba6c5f, 63'h000000002e856f1a, 63'h7fffffdfa35a85b3, 63'h000017f808cfbb3a, 63'h7fec19e083976be3, 63'h15d3e8819dd4969b};
        rom[ 80] = {63'h000000000000645d, 63'h7fffffffffbce0a9, 63'h000000002d2fabd8, 63'h7fffffe05ac0ac6d, 63'h00001798074e4562, 63'h7fec49703802c217, 63'h15c01a39fbd687a0};
        rom[ 81] = {63'h0000000000006035, 63'h7fffffffffbf3abf, 63'h000000002be5ecb4, 63'h7fffffe10ce7f9a5, 63'h0000173a2414f98b, 63'h7fec78420a52befc, 63'h15ac7b22c2d52c64};
        rom[ 82] = {63'h0000000000005c3f, 63'h7fffffffffc17be2, 63'h000000002aa7b1cb, 63'h7fffffe1b9ff7bfc, 63'h000016de4fae6102, 63'h7feca65a278ab8c6, 63'h15990a8029ca6637};
        rom[ 83] = {63'h0000000000005879, 63'h7fffffffffc3a545, 63'h000000002974815c, 63'h7fffffe262344ee3, 63'h000016847b2f3e0b, 63'h7fecd3bc9e4e4ad0, 63'h1585c79a856c85e8};
        rom[ 84] = {63'h00000000000054e1, 63'h7fffffffffc5b807, 63'h00000000284be770, 63'h7fffffe305b1b276, 63'h0000162c9830d675, 63'h7fed006d5ff0062f, 63'h1572b1be2a56dcc0};
        rom[ 85] = {63'h0000000000005174, 63'h7fffffffffc7b539, 63'h00000000272d758d, 63'h7fffffe3a4a1220c, 63'h000015d698cb83bc, 63'h7fed2c704174fda3, 63'h155fc83b503b6031};
        rom[ 86] = {63'h0000000000004e30, 63'h7fffffffffc99ddf, 63'h000000002618c26b, 63'h7fffffe43f2a698e, 63'h000015826f91850f, 63'h7fed57c8fc8db44d, 63'h154d0a65f6127fd8};
        rom[ 87] = {63'h0000000000004b12, 63'h7fffffffffcb72ed, 63'h00000000250d69ab, 63'h7fffffe4d573b9ae, 63'h000015300f8a0f99, 63'h7fed827b3084ef3f, 63'h153a7795c73ed13d};
        rom[ 88] = {63'h000000000000481a, 63'h7fffffffffcd354a, 63'h00000000240b0b97, 63'h7fffffe567a1bb09, 63'h000014df6c2c99d2, 63'h7fedac8a6324e336, 63'h15280f26019ab16d};
        rom[ 89] = {63'h0000000000004543, 63'h7fffffffffcee5d3, 63'h0000000023114ce2, 63'h7fffffe5f5d7a049, 63'h00001490795c5eb8, 63'h7fedd5fa0193315f, 63'h1515d0755c66727a};
        rom[ 90] = {63'h000000000000428e, 63'h7fffffffffd08558, 63'h00000000221fd66d, 63'h7fffffe680373754, 63'h000014432b6415ee, 63'h7fedfecd61241fe7, 63'h1503bae5f00e1ad2};
        rom[ 91] = {63'h0000000000003ff8, 63'h7fffffffffd2149f, 63'h0000000021365510, 63'h7fffffe706e0f994, 63'h000013f776f1de1c, 63'h7fee2707c0257581, 63'h14f1cddd1ebe264f};
        rom[ 92] = {63'h0000000000003d80, 63'h7fffffffffd39463, 63'h0000000020547967, 63'h7fffffe789f41b6c, 63'h000013ad511356d8, 63'h7fee4eac46a159a2, 63'h14e008c37dbf1d27};
        rom[ 93] = {63'h0000000000003b24, 63'h7fffffffffd50555, 63'h000000001f79f79e, 63'h7fffffe8098e9ade, 63'h00001364af31e7c0, 63'h7fee75be07199620, 63'h14ce6b04bf903457};
        rom[ 94] = {63'h00000000000038e2, 63'h7fffffffffd66820, 63'h000000001ea68744, 63'h7fffffe885cd4d72, 63'h0000131d870f325a, 63'h7fee9c3fff3b9232, 63'h14bcf40f9eb9852c};
        rom[ 95] = {63'h00000000000036ba, 63'h7fffffffffd7bd62, 63'h000000001dd9e321, 63'h7fffffe8fecbed6b, 63'h000012d7cec1acab, 63'h7feec235188d5a3a, 63'h14aba355c94ebf71};
        rom[ 96] = {63'h00000000000034ab, 63'h7fffffffffd905b5, 63'h000000001d13c909, 63'h7fffffe974a52650, 63'h000012937cb16255, 63'h7feee7a02914039d, 63'h149a784bcd1b8afe};
        rom[ 97] = {63'h00000000000032b2, 63'h7fffffffffda41a9, 63'h000000001c53f9b7, 63'h7fffffe9e772a0d5, 63'h000012508794da6f, 63'h7fef0c83f3f3b7e3, 63'h1489726904731aa9};
        rom[ 98] = {63'h00000000000030ce, 63'h7fffffffffdb71c9, 63'h000000001b9a38a9, 63'h7fffffea574d0e2b, 63'h0000120ee66e2023, 63'h7fef30e32a09ae95, 63'h14789127839cbbe2};
        rom[ 99] = {63'h0000000000002f00, 63'h7fffffffffdc9695, 63'h000000001ae64bfb, 63'h7fffffeac44c32c2, 63'h000011ce9087ec6e, 63'h7fef54c06a8059c2, 63'h1467d40406d77405};
        rom[100] = {63'h0000000000002d45, 63'h7fffffffffddb08c, 63'h000000001a37fc48, 63'h7fffffeb2e86f081, 63'h0000118f7d72ef52, 63'h7fef781e435e05ba, 63'h14573a7de0eefe87};
        rom[101] = {63'h0000000000002b9e, 63'h7fffffffffdec024, 63'h00000000198f1489, 63'h7fffffeb96135085, 63'h00001151a50336f8, 63'h7fef9aff320e295e, 63'h1446c416ea5cbe2d};
        rom[102] = {63'h0000000000002a08, 63'h7fffffffffdfc5cd, 63'h0000000018eb61fb, 63'h7fffffebfb068c5c, 63'h00001114ff4db348, 63'h7fefbd65a3e5a166, 63'h1436705370ef6f53};
        rom[103] = {63'h0000000000002883, 63'h7fffffffffe0c1f2, 63'h00000000184cb3fe, 63'h7fffffec5d7516d9, 63'h000010d984a5d495, 63'h7fefdf53f6a20e20, 63'h14263eba27f4a22b};
        rom[104] = {63'h000000000000270e, 63'h7fffffffffe1b4f9, 63'h0000000017b2dbff, 63'h7fffffecbd72a472, 63'h0000109f2d9b4414, 63'h7ff000cc78e48892, 63'h14162ed418df3a2a};
        rom[105] = {63'h00000000000025a9, 63'h7fffffffffe29f45, 63'h00000000171dad5f, 63'h7fffffed1b12333f, 63'h00001065f2f7b4df, 63'h7ff021d16aa7e13f, 63'h1406402c94666348};
        rom[106] = {63'h0000000000002452, 63'h7fffffffffe38131, 63'h00000000168cfd56, 63'h7fffffed76661295, 63'h0000102dcdbccc55, 63'h7ff04264fdb29882, 63'h13f6725124189ef2};
        rom[107] = {63'h0000000000002309, 63'h7fffffffffe45b16, 63'h000000001600a2e6, 63'h7fffffedcf7fea3f, 63'h00000ff6b72220c0, 63'h7ff062895604be24, 63'h13e6c4d17c5eb937};
        rom[108] = {63'h00000000000021ce, 63'h7fffffffffe52d49, 63'h00000000157876bb, 63'h7fffffee2670c170, 63'h00000fc0a8934d3c, 63'h7ff082408a41e3a2, 63'h13d7373f6eeaa360};
        rom[109] = {63'h00000000000020a0, 63'h7fffffffffe5f818, 63'h0000000014f45321, 63'h7fffffee7b49054f, 63'h00000f8b9bae19cb, 63'h7ff0a18ca4174a97, 63'h13c7c92edd8e5b7f};
        rom[110] = {63'h0000000000001f7e, 63'h7fffffffffe6bbd2, 63'h00000000147413ea, 63'h7fffffeece188f44, 63'h00000f578a40b6c2, 63'h7ff0c06fa09e76d8, 63'h13b87a35ad77310a};
        rom[111] = {63'h0000000000001e67, 63'h7fffffffffe778bf, 63'h0000000013f7965e, 63'h7fffffef1eeeaaf2, 63'h00000f246e480a8c, 63'h7ff0deeb70bc49db, 63'h13a949ebbac9dd22};
        rom[112] = {63'h0000000000001d5c, 63'h7fffffffffe82f25, 63'h00000000137eb92b, 63'h7fffffef6dda1bef, 63'h00000ef241ee1109, 63'h7ff0fd01f97ccb67, 63'h139a37eacc9c09ff};
        rom[113] = {63'h0000000000001c5b, 63'h7fffffffffe8df47, 63'h0000000013095c55, 63'h7fffffefbae92339, 63'h00000ec0ff884b9f, 63'h7ff11ab5146bc1d3, 63'h138b43ce8948080a};
        rom[114] = {63'h0000000000001b64, 63'h7fffffffffe98963, 63'h0000000012976123, 63'h7ffffff006298469, 63'h00000e90a1964152, 63'h7ff138068fea3a94, 63'h137c6d346b1790ac};
        rom[115] = {63'h0000000000001a77, 63'h7fffffffffea2db8, 63'h000000001228aa15, 63'h7ffffff04fa88aaa, 63'h00000e6122c00e13, 63'h7ff154f82f812249, 63'h136db3bbb54296e5};
        rom[116] = {63'h0000000000001993, 63'h7fffffffffeacc7f, 63'h0000000011bd1ad3, 63'h7ffffff097730d7e, 63'h00000e327dd500b1, 63'h7ff1718bac310a27, 63'h135f1705693f4430};
        rom[117] = {63'h00000000000018b8, 63'h7fffffffffeb65ef, 63'h0000000011549822, 63'h7ffffff0dd957540, 63'h00000e04adca46a8, 63'h7ff18dc2b4bf373e, 63'h135096b43c605d6b};
        rom[118] = {63'h00000000000017e6, 63'h7fffffffffebfa3d, 63'h0000000010ef07d3, 63'h7ffffff1221bbf7f, 63'h00000dd7adb9a545, 63'h7ff1a99eee0016cf, 63'h1342326c8dbf675a};
        rom[119] = {63'h000000000000171b, 63'h7fffffffffec899c, 63'h00000000108c50be, 63'h7ffffff165118320, 63'h00000dab78e03f81, 63'h7ff1c521f31f31b5, 63'h1333e9d45c6ffce2};
        rom[120] = {63'h0000000000001659, 63'h7fffffffffed143d, 63'h00000000102c5ab0, 63'h7ffffff1a681f456, 63'h00000d800a9d6800, 63'h7ff1e04d55e4b7c1, 63'h1325bc933df9e2ae};
        rom[121] = {63'h000000000000159d, 63'h7fffffffffed9a4e, 63'h000000000fcf0e66, 63'h7ffffff1e677e869, 63'h00000d555e717eb1, 63'h7ff1fb229ef8bacc, 63'h1317aa5255177c0c};
        rom[122] = {63'h00000000000014e9, 63'h7fffffffffee1bfb, 63'h000000000f74557c, 63'h7ffffff224fdd958, 63'h00000d2b6ffcd98c, 63'h7ff215a34e243039, 63'h1309b2bc48b65c45};
        rom[123] = {63'h000000000000143c, 63'h7fffffffffee996f, 63'h000000000f1c1a6b, 63'h7ffffff2621de950, 63'h00000d023afeb7ef, 63'h7ff22fd0da8fcea9, 63'h12fbd57d3b37c5c2};
        rom[124] = {63'h0000000000001395, 63'h7fffffffffef12d2, 63'h000000000ec64879, 63'h7ffffff29de1e5fb, 63'h00000cd9bb54402d, 63'h7ff249acb300dcb4, 63'h12ee1242c1eefdc0};
        rom[125] = {63'h00000000000012f4, 63'h7fffffffffef884b, 63'h000000000e72cbb4, 63'h7ffffff2d8534bb2, 63'h00000cb1ecf786d8, 63'h7ff263383e14047b, 63'h12e068bbdcdb6f7c};
        rom[126] = {63'h0000000000001259, 63'h7fffffffffeffa00, 63'h000000000e2190e7, 63'h7ffffff3117b4881, 63'h00000c8acbfe9f58, 63'h7ff27c74da763f3f, 63'h12d2d898ee9cad74};
        rom[127] = {63'h00000000000011c4, 63'h7ffffffffff06814, 63'h000000000dd28596, 63'h7ffffff34962bf17, 63'h00000c64549ab57a, 63'h7ff29563df1beb28, 63'h12c5618bb49e71cd};
    end
    wire [K-1:0]  idx = v[WMAN-1 -: K];
    wire [RW-1:0] w   = v[RW-1:0];
    reg  [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, f}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire signed [WF-1:0] f_p   = $signed(esb[WF-1:0]);
    wire        [WSB-1:0] sb_p = esb[HSBW-1 -: WSB];
    _zkf_log2_final_mul #(
        .WF(WF), .WACC(ACCM), .F2(F2), .WSB(WSB), .STAGE_PRODUCT(STAGE_PRODUCT), .WMULTIPLIER(WMULTIPLIER)
    ) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .f(f_p), .acc(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
