/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=36 (degree 4); zero-bubble, see _zkf_horner.
/// Evaluates log2(1+t) = t*P(t) as a fixed-point fraction (scale 2**-F2); P(t)=log2(1+t)/t via the table.
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner) + (2+STAGE_PRODUCT) (final multiply: registered inputs + split); valid/sb_in match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_log2_m36_d4 #(parameter integer WMAN = 36, parameter integer SBW = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire                   in_valid,
    input  wire        [SBW-1:0]  sb_in,
    input  wire        [WMAN-2:0] frac,         // stored fraction t (WFRAC = WMAN-1 bits), in [0,1)
    output wire                   out_valid,
    output wire        [SBW-1:0]  sb_out,
    output wire [2*WMAN+12-2:0]   l_fix         // log2(1+t) at scale 2**-F2, F2 = WFRAC + CF, in [0,1)
);
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + CF;
    localparam integer K    = 7;
    localparam integer D    = 4;
    localparam integer RW   = 28;
    localparam integer CW   = 51;
    localparam integer ACCW = 53;
    localparam integer NSEG = 128;
    localparam integer HSBW = SBW + WFRAC;  // carry t alongside the sideband to the final multiply

    // verilator coverage_off
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[0] = {51'h0000000048ad4, 51'h7fffffd1d67ab, 51'h00001ec7097d9, 51'h7fe8eab89ae05, 51'h171547652b82c};
        rom[1] = {51'h00000000465dc, 51'h7fffffd2f9284, 51'h00001e3e40443, 51'h7fe927bd54001, 51'h16fe50b6ef081};
        rom[2] = {51'h0000000044256, 51'h7fffffd412986, 51'h00001db8d13e0, 51'h7fe963b3d9780, 51'h16e79685c2d1f};
        rom[3] = {51'h000000004202e, 51'h7fffffd523271, 51'h00001d36a13c7, 51'h7fe99ea2c4522, 51'h16d117c6c4454};
        rom[4] = {51'h000000003ff57, 51'h7fffffd62b2c5, 51'h00001cb7961ed, 51'h7fe9d890784b7, 51'h16bad3758efd5};
        rom[5] = {51'h000000003dfbf, 51'h7fffffd72afbe, 51'h00001c3b96c64, 51'h7fea118325e35, 51'h16a4c8940888e};
        rom[6] = {51'h000000003c15a, 51'h7fffffd822e5e, 51'h00001bc28b09b, 51'h7fea4980cc531, 51'h168ef62a2e29f};
        rom[7] = {51'h000000003a419, 51'h7fffffd91336d, 51'h00001b4c5baad, 51'h7fea808f3b6e5, 51'h16795b45e481d};
        rom[8] = {51'h00000000387ee, 51'h7fffffd9fc37a, 51'h00001ad8f24b9, 51'h7feab6b4156e3, 51'h1663f6fac912f};
        rom[9] = {51'h0000000036ccf, 51'h7fffffdade2e2, 51'h00001a6839643, 51'h7feaebf4d0a77, 51'h164ec8620582d};
        rom[10] = {51'h00000000352af, 51'h7fffffdbb95d1, 51'h000019fa1c39a, 51'h7feb2056b92dc, 51'h1639ce9a24894};
        rom[11] = {51'h0000000033983, 51'h7fffffdc8e044, 51'h0000198e86d4b, 51'h7feb53def263d, 51'h162508c6e8786};
        rom[12] = {51'h0000000032141, 51'h7fffffdd5c60a, 51'h0000192565f96, 51'h7feb8692787a9, 51'h16107611234d1};
        rom[13] = {51'h00000000309df, 51'h7fffffde24acb, 51'h000018bea71ec, 51'h7febb87621df4, 51'h15fc15a690356};
        rom[14] = {51'h000000002f352, 51'h7fffffdee7203, 51'h0000185a38678, 51'h7febe98ea09a3, 51'h15e7e6b9ae7db};
        rom[15] = {51'h000000002dd92, 51'h7fffffdfa3f0d, 51'h000017f8089a2, 51'h7fec19e0839e2, 51'h15d3e8819dd47};
        rom[16] = {51'h000000002c897, 51'h7fffffe05b51b, 51'h00001798071a9, 51'h7fec497038093, 51'h15c01a39fbd66};
        rom[17] = {51'h000000002b458, 51'h7fffffe10d73e, 51'h0000173a23e31, 51'h7fec78420a590, 51'h15ac7b22c2d51};
        rom[18] = {51'h000000002a0ce, 51'h7fffffe1ba869, 51'h000016de4f7e3, 51'h7feca65a2790c, 51'h15990a8029ca4};
        rom[19] = {51'h0000000028df0, 51'h7fffffe262b6b, 51'h000016847b00c, 51'h7fecd3bc9e542, 51'h1585c79a856c7};
        rom[20] = {51'h0000000027bb9, 51'h7fffffe3062fa, 51'h0000162c9803f, 51'h7fed006d5ff5a, 51'h1572b1be2a56c};
        rom[21] = {51'h0000000026a20, 51'h7fffffe3a51ac, 51'h000015d698a02, 51'h7fed2c70417a7, 51'h155fc83b503b4};
        rom[22] = {51'h0000000025921, 51'h7fffffe43f9ff, 51'h000015826f67a, 51'h7fed57c8fc92f, 51'h154d0a65f6126};
        rom[23] = {51'h00000000248b4, 51'h7fffffe4d5e55, 51'h000015300f619, 51'h7fed827b308a0, 51'h153a7795c73eb};
        rom[24] = {51'h00000000238d3, 51'h7fffffe5680f8, 51'h000014df6c057, 51'h7fedac8a6329c, 51'h15280f26019aa};
        rom[25] = {51'h000000002297a, 51'h7fffffe5f641c, 51'h0000149079368, 51'h7fedd5fa0197f, 51'h1515d0755c666};
        rom[26] = {51'h0000000021aa3, 51'h7fffffe6809de, 51'h000014432b3f8, 51'h7fedfecd6128b, 51'h1503bae5f00e0};
        rom[27] = {51'h0000000020c49, 51'h7fffffe707444, 51'h000013f776ce7, 51'h7fee2707c029e, 51'h14f1cddd1ebe1};
        rom[28] = {51'h000000001fe66, 51'h7fffffe78a542, 51'h000013ad50f11, 51'h7fee4eac46a5a, 51'h14e008c37dbf0};
        rom[29] = {51'h000000001f0f7, 51'h7fffffe809eb9, 51'h00001364af10c, 51'h7fee75be071dc, 51'h14ce6b04bf902};
        rom[30] = {51'h000000001e3f7, 51'h7fffffe886274, 51'h0000131d86ef2, 51'h7fee9c3fff3f9, 51'h14bcf40f9eb97};
        rom[31] = {51'h000000001d762, 51'h7fffffe8ff230, 51'h000012d7cea2a, 51'h7feec23518914, 51'h14aba355c94eb};
        rom[32] = {51'h000000001cb33, 51'h7fffffe974f97, 51'h000012937c935, 51'h7feee7a02917c, 51'h149a784bcd1b7};
        rom[33] = {51'h000000001bf67, 51'h7fffffe9e7c44, 51'h000012508777c, 51'h7fef0c83f3f76, 51'h1489726904731};
        rom[34] = {51'h000000001b3fa, 51'h7fffffea579c2, 51'h0000120ee651f, 51'h7fef30e32a0d3, 51'h14789127839cb};
        rom[35] = {51'h000000001a8e8, 51'h7fffffeac498d, 51'h000011ce906ca, 51'h7fef54c06a83c, 51'h1467d40406d76};
        rom[36] = {51'h0000000019e2f, 51'h7fffffeb2ed13, 51'h0000118f7d587, 51'h7fef781e43615, 51'h14573a7de0eef};
        rom[37] = {51'h00000000193ca, 51'h7fffffeb965b4, 51'h00001151a4e99, 51'h7fef9aff32116, 51'h1446c416ea5cb};
        rom[38] = {51'h00000000189b8, 51'h7fffffebfb4c4, 51'h00001114ff34d, 51'h7fefbd65a3e8c, 51'h1436705370ef6};
        rom[39] = {51'h0000000017ff4, 51'h7fffffec5db8b, 51'h000010d9848db, 51'h7fefdf53f6a51, 51'h14263eba27f49};
        rom[40] = {51'h000000001767c, 51'h7fffffecbdb43, 51'h0000109f2d83e, 51'h7ff000cc78e77, 51'h14162ed418df3};
        rom[41] = {51'h0000000016d4d, 51'h7fffffed1b51c, 51'h00001065f2e10, 51'h7ff021d16aaab, 51'h1406402c94665};
        rom[42] = {51'h0000000016465, 51'h7fffffed76a3c, 51'h0000102dcda6d, 51'h7ff04264fdb56, 51'h13f6725124189};
        rom[43] = {51'h0000000015bc1, 51'h7fffffedcfbbc, 51'h00000ff6b70cd, 51'h7ff0628956077, 51'h13e6c4d17c5eb};
        rom[44] = {51'h000000001535f, 51'h7fffffee26aad, 51'h00000fc0a87e9, 51'h7ff082408a448, 51'h13d7373f6eea9};
        rom[45] = {51'h0000000014b3c, 51'h7fffffee7b816, 51'h00000f8b9b9a0, 51'h7ff0a18ca419d, 51'h13c7c92edd8e5};
        rom[46] = {51'h0000000014357, 51'h7fffffeece4f4, 51'h00000f578a2d3, 51'h7ff0c06fa0a0e, 51'h13b87a35ad772};
        rom[47] = {51'h0000000013bac, 51'h7fffffef1f23c, 51'h00000f246e352, 51'h7ff0deeb70bea, 51'h13a949ebbac9d};
        rom[48] = {51'h000000001343a, 51'h7fffffef6e0db, 51'h00000ef241dbb, 51'h7ff0fd01f97f1, 51'h139a37eacc9c0};
        rom[49] = {51'h0000000012d00, 51'h7fffffefbb1b3, 51'h00000ec0ff767, 51'h7ff11ab5146e0, 51'h138b43ce89480};
        rom[50] = {51'h00000000125fa, 51'h7ffffff0065a2, 51'h00000e90a184e, 51'h7ff138068fec6, 51'h137c6d346b178};
        rom[51] = {51'h0000000011f28, 51'h7ffffff04fd7d, 51'h00000e6122af3, 51'h7ff154f82f834, 51'h136db3bbb5429};
        rom[52] = {51'h0000000011888, 51'h7ffffff097a0f, 51'h00000e327dc4a, 51'h7ff1718bac331, 51'h135f1705693f4};
        rom[53] = {51'h0000000011218, 51'h7ffffff0ddc21, 51'h00000e04adba6, 51'h7ff18dc2b4c13, 51'h135096b43c605};
        rom[54] = {51'h0000000010bd6, 51'h7ffffff122472, 51'h00000dd7adaa3, 51'h7ff1a99eee020, 51'h1342326c8dbf6};
        rom[55] = {51'h00000000105c0, 51'h7ffffff1653bb, 51'h00000dab78d13, 51'h7ff1c521f3211, 51'h1333e9d45c6ff};
        rom[56] = {51'h000000000ffd7, 51'h7ffffff1a6aaf, 51'h00000d800a8ed, 51'h7ff1e04d55e69, 51'h1325bc933df9e};
        rom[57] = {51'h000000000fa16, 51'h7ffffff1e69fc, 51'h00000d555e634, 51'h7ff1fb229efa8, 51'h1317aa5255177};
        rom[58] = {51'h000000000f47f, 51'h7ffffff22524a, 51'h00000d2b6fef0, 51'h7ff215a34e25f, 51'h1309b2bc48b65};
        rom[59] = {51'h000000000ef0f, 51'h7ffffff26243a, 51'h00000d023af14, 51'h7ff22fd0da918, 51'h12fbd57d3b37c};
        rom[60] = {51'h000000000e9c4, 51'h7ffffff29e069, 51'h00000cd9bb473, 51'h7ff249acb3028, 51'h12ee1242c1eef};
        rom[61] = {51'h000000000e49f, 51'h7ffffff2d8770, 51'h00000cb1ecead, 51'h7ff263383e15a, 51'h12e068bbdcdb6};
        rom[62] = {51'h000000000df9d, 51'h7ffffff3119e0, 51'h00000c8acbf24, 51'h7ff27c74da77d, 51'h12d2d898ee9ca};
        rom[63] = {51'h000000000dabd, 51'h7ffffff349849, 51'h00000c64548ea, 51'h7ff29563df1d7, 51'h12c5618bb49e7};
        rom[64] = {51'h000000000d5ff, 51'h7ffffff380333, 51'h00000c3e830b7, 51'h7ff2ae069b779, 51'h12b803473f7ad};
        rom[65] = {51'h000000000d161, 51'h7ffffff3b5b24, 51'h00000c1953cd7, 51'h7ff2c65e57a7b, 51'h12aabd7feb90e};
        rom[66] = {51'h000000000cce2, 51'h7ffffff3ea09d, 51'h00000bf4c351f, 51'h7ff2de6c54b16, 51'h129d8feb59ce3};
        rom[67] = {51'h000000000c881, 51'h7ffffff41d41b, 51'h00000bd0ce2e4, 51'h7ff2f631ccab3, 51'h12907a4068a97};
        rom[68] = {51'h000000000c43e, 51'h7ffffff44f618, 51'h00000bad710e8, 51'h7ff30daff2ed1, 51'h12837c372d4c9};
        rom[69] = {51'h000000000c017, 51'h7ffffff480707, 51'h00000b8aa8b57, 51'h7ff324e7f43e1, 51'h12769588eced8};
        rom[70] = {51'h000000000bc0c, 51'h7ffffff4b075c, 51'h00000b6871fb5, 51'h7ff33bdaf7001, 51'h1269c5f01652e};
        rom[71] = {51'h000000000b81b, 51'h7ffffff4df783, 51'h00000b46c9cd4, 51'h7ff3528a1b5ad, 51'h125d0d283b84b};
        rom[72] = {51'h000000000b445, 51'h7ffffff50d7e9, 51'h00000b25ad2d0, 51'h7ff368f67b64e, 51'h12506aee0ba6b};
        rom[73] = {51'h000000000b087, 51'h7ffffff53a8f4, 51'h00000b05192fd, 51'h7ff37f212b4bc, 51'h1243deff4cfb6};
        rom[74] = {51'h000000000ace2, 51'h7ffffff566b0a, 51'h00000ae50afe2, 51'h7ff3950b397b0, 51'h1237691ad70ea};
        rom[75] = {51'h000000000a954, 51'h7ffffff591e8a, 51'h00000ac57fd2e, 51'h7ff3aab5aec17, 51'h122b09008d067};
        rom[76] = {51'h000000000a5de, 51'h7ffffff5bc3d4, 51'h00000aa674fb0, 51'h7ff3c0218e761, 51'h121ebe7158189};
        rom[77] = {51'h000000000a27d, 51'h7ffffff5e5b44, 51'h00000a87e7d50, 51'h7ff3d54fd69b4, 51'h1212892f2224c};
        rom[78] = {51'h0000000009f32, 51'h7ffffff60e531, 51'h00000a69d5d01, 51'h7ff3ea4180012, 51'h120668fcd070f};
        rom[79] = {51'h0000000009bfc, 51'h7ffffff6361f3, 51'h00000a4c3c6c0, 51'h7ff3fef77e670, 51'h11fa5d9e3e885};
        rom[80] = {51'h00000000098da, 51'h7ffffff65d1dd, 51'h00000a2f19387, 51'h7ff41372c09b9, 51'h11ee66d8393a3};
        rom[81] = {51'h00000000095cc, 51'h7ffffff683541, 51'h00000a1269d48, 51'h7ff427b4309c9, 51'h11e2847079b9b};
        rom[82] = {51'h00000000092d2, 51'h7ffffff6a8c6c, 51'h000009f62bee6, 51'h7ff43bbcb3b4c, 51'h11d6b62da0db8};
        rom[83] = {51'h0000000008fe9, 51'h7ffffff6cd7ac, 51'h000009da5d42b, 51'h7ff44f8d2a9a2, 51'h11cafbd732728};
        rom[84] = {51'h0000000008d13, 51'h7ffffff6f174c, 51'h000009befb9c5, 51'h7ff46326718a2, 51'h11bf553590c8a};
        rom[85] = {51'h0000000008a4e, 51'h7ffffff714b93, 51'h000009a404d3e, 51'h7ff476896065c, 51'h11b3c211f834f};
        rom[86] = {51'h000000000879b, 51'h7ffffff7374c7, 51'h0000098976cf4, 51'h7ff489b6cacc8, 51'h11a842367acc9};
        rom[87] = {51'h00000000084f8, 51'h7ffffff75932d, 51'h0000096f4f816, 51'h7ff49caf80370, 51'h119cd56dfc2e6};
        rom[88] = {51'h0000000008265, 51'h7ffffff77a706, 51'h000009558ce9d, 51'h7ff4af744c102, 51'h11917b842d691};
        rom[89] = {51'h0000000007fe1, 51'h7ffffff79b094, 51'h0000093c2d143, 51'h7ff4c205f5ce1, 51'h1186344588f9a};
        rom[90] = {51'h0000000007d6d, 51'h7ffffff7bb015, 51'h000009232e183, 51'h7ff4d465410a9, 51'h117aff7f4ee33};
        rom[91] = {51'h0000000007b08, 51'h7ffffff7da5c4, 51'h0000090a8e18f, 51'h7ff4e692ed9a1, 51'h116fdcff80de1};
        rom[92] = {51'h00000000078b1, 51'h7ffffff7f91de, 51'h000008f24b44f, 51'h7ff4f88fb7a2a, 51'h1164cc94de9dc};
        rom[93] = {51'h0000000007667, 51'h7ffffff81749c, 51'h000008da63d56, 51'h7ff50a5c57b25, 51'h1159ce0ee22e3};
        rom[94] = {51'h000000000742c, 51'h7ffffff834e36, 51'h000008c2d60e5, 51'h7ff51bf982d43, 51'h114ee13dbc661};
        rom[95] = {51'h00000000071fe, 51'h7ffffff851ee1, 51'h000008aba03e0, 51'h7ff52d67eaa5e, 51'h114405f2516eb};
        rom[96] = {51'h0000000006fdc, 51'h7ffffff86e6d4, 51'h00000894c0bcb, 51'h7ff53ea83d6b8, 51'h11393bfe35607};
        rom[97] = {51'h0000000006dc7, 51'h7ffffff88a640, 51'h0000087e35ec8, 51'h7ff54fbb26238, 51'h112e8333a8f39};
        rom[98] = {51'h0000000006bbe, 51'h7ffffff8a5d58, 51'h00000867fe38f, 51'h7ff560a14c9a4, 51'h1123db6596440};
        rom[99] = {51'h00000000069c1, 51'h7ffffff8c0c4e, 51'h000008521816f, 51'h7ff5715b557c4, 51'h111944678da89};
        rom[100] = {51'h00000000067d0, 51'h7ffffff8db34f, 51'h0000083c82043, 51'h7ff581e9e268f, 51'h110ebe0dc29cb};
        rom[101] = {51'h00000000065e9, 51'h7ffffff8f528a, 51'h000008273a874, 51'h7ff5924d9203f, 51'h1104482d08bbb};
        rom[102] = {51'h000000000640e, 51'h7ffffff90ea2b, 51'h00000812402f4, 51'h7ff5a2870006a, 51'h10f9e29ad0ce1};
        rom[103] = {51'h000000000623d, 51'h7ffffff927a5f, 51'h000007fd91938, 51'h7ff5b296c550b, 51'h10ef8d2d25e78};
        rom[104] = {51'h0000000006077, 51'h7ffffff940350, 51'h000007e92d536, 51'h7ff5c27d77f8e, 51'h10e547baaa957};
        rom[105] = {51'h0000000005eba, 51'h7ffffff958527, 51'h000007d512164, 51'h7ff5d23bab5c5, 51'h10db121a961e2};
        rom[106] = {51'h0000000005d07, 51'h7ffffff97000d, 51'h000007c13e8af, 51'h7ff5e1d1f02eb, 51'h10d0ec24b1cec};
        rom[107] = {51'h0000000005b5e, 51'h7ffffff987428, 51'h000007adb167d, 51'h7ff5f140d488d, 51'h10c6d5b15659a};
        rom[108] = {51'h00000000059bf, 51'h7ffffff99e19e, 51'h0000079a696a8, 51'h7ff60088e3f77, 51'h10bcce9969429};
        rom[109] = {51'h0000000005828, 51'h7ffffff9b4896, 51'h000007876557b, 51'h7ff60faaa789c, 51'h10b2d6b65a5a5};
        rom[110] = {51'h000000000569a, 51'h7ffffff9ca932, 51'h00000774a3faf, 51'h7ff61ea6a5df4, 51'h10a8ede22147a};
        rom[111] = {51'h0000000005515, 51'h7ffffff9e0397, 51'h0000076224268, 51'h7ff62d7d63351, 51'h109f13f73b1e9};
        rom[112] = {51'h0000000005398, 51'h7ffffff9f57e7, 51'h0000074fe4b33, 51'h7ff63c2f6173a, 51'h109548d0a804e};
        rom[113] = {51'h0000000005223, 51'h7ffffffa0a643, 51'h0000073de4800, 51'h7ff64abd203b2, 51'h108b8c49e8e39};
        rom[114] = {51'h00000000050b6, 51'h7ffffffa1eecc, 51'h0000072c22728, 51'h7ff659271cf07, 51'h1081de3efd251};
        rom[115] = {51'h0000000004f51, 51'h7ffffffa331a1, 51'h0000071a9d75e, 51'h7ff6676dd2c90, 51'h10783e8c60801};
        rom[116] = {51'h0000000004df3, 51'h7ffffffa46ee2, 51'h00000709547b9, 51'h7ff67591bad72, 51'h106ead0f08ce0};
        rom[117] = {51'h0000000004c9d, 51'h7ffffffa5a6ad, 51'h000006f8467a8, 51'h7ff683934c157, 51'h106529a463ee1};
        rom[118] = {51'h0000000004b4e, 51'h7ffffffa6d91f, 51'h000006e7726f5, 51'h7ff69172fb722, 51'h105bb42a55b29};
        rom[119] = {51'h0000000004a06, 51'h7ffffffa80656, 51'h000006d6d75c1, 51'h7ff69f313bda1, 51'h10524c7f35dac};
        rom[120] = {51'h00000000048c5, 51'h7ffffffa92e6c, 51'h000006c674483, 51'h7ff6acce7e43d, 51'h1048f281ce16a};
        rom[121] = {51'h000000000478b, 51'h7ffffffaa517e, 51'h000006b648404, 51'h7ff6ba4b31b9b, 51'h103fa6115815b};
        rom[122] = {51'h0000000004657, 51'h7ffffffab6fa7, 51'h000006a65255e, 51'h7ff6c7a7c3648, 51'h1036670d7ba03};
        rom[123] = {51'h0000000004529, 51'h7ffffffac88ff, 51'h00000696919fb, 51'h7ff6d4e49e953, 51'h102d35564cba6};
        rom[124] = {51'h0000000004401, 51'h7ffffffad9da1, 51'h0000068705391, 51'h7ff6e2022ccea, 51'h102410cc49d1b};
        rom[125] = {51'h00000000042e0, 51'h7ffffffaeada5, 51'h00000677ac422, 51'h7ff6ef00d5cf5, 51'h101af95059f39};
        rom[126] = {51'h00000000041c5, 51'h7ffffffafb923, 51'h0000066885df9, 51'h7ff6fbe0ff9a9, 51'h1011eec3cb0d5};
        rom[127] = {51'h00000000040af, 51'h7ffffffb0c034, 51'h00000659913a8, 51'h7ff708a30e817, 51'h1008f1085035e};
    end
    wire [K-1:0]  idx = frac[WFRAC-1 -: K];
    wire [RW-1:0] w   = frac[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= {sb_in, frac}; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    // verilator coverage_on
    _zkf_horner #(.D(D), .CW(CW), .RW(RW), .ACCW(ACCW), .SBW(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    wire [WFRAC-1:0] frac_p = esb[WFRAC-1:0];
    wire [SBW-1:0]   sb_p   = esb[HSBW-1 -: SBW];
    // verilator coverage_on
    _zkf_log2_final_mul #(.WFRAC(WFRAC), .ACCW(ACCW), .F2(F2), .SBW(SBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_tp (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in(sb_p), .frac(frac_p), .acc(acc),
        .out_valid(out_valid), .sb_out(sb_out), .l_fix(l_fix));
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
