/// GENERATED by float/zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=32 (degree 4); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: 2 (ROM read) + D*(2+STAGE_PRODUCT) (Horner); valid and sb_in are delayed to match.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

module _zkf_exp2_m32 #(parameter integer WMAN = 32, parameter integer D = 4, parameter integer WSB = 1, parameter integer STAGE_PRODUCT = 0) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire [WMAN+12-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire    [WMAN-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire               guard,
    output wire               round,
    output wire               sticky
);
    // verilator coverage_off
    generate if (D != 4) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 5;
    localparam integer CF   = 44;
    localparam integer RW   = 39;
    localparam integer CW   = 47;
    localparam integer ACCW = 49;
    localparam integer NSEG = 32;
    localparam integer HSBW = WSB;

    (* rom_style = "block" *)  // map a large table to block RAM
    reg [(D+1)*CW-1:0] rom [0:NSEG-1];
    initial begin
        rom[  0] = {47'h000000027d33, 47'h000001c6aa88, 47'h0000f5fdf223, 47'h0058b90bfba4, 47'h100000000001};
        rom[  1] = {47'h000000028b27, 47'h000001d09f3e, 47'h0000fb60e54d, 47'h005aaa65d44f, 47'h1059b0d31587};
        rom[  2] = {47'h000000029969, 47'h000001dacbc2, 47'h000100e20a66, 47'h005ca6a3a93d, 47'h10b5586cf98a};
        rom[  3] = {47'h00000002a7fc, 47'h000001e5314f, 47'h000106820ab4, 47'h005eae0286f5, 47'h111301d0125d};
        rom[  4] = {47'h00000002b6df, 47'h000001efd123, 47'h00010c41932d, 47'h0060c0c0d036, 47'h1172b83c7d53};
        rom[  5] = {47'h00000002c617, 47'h000001faac86, 47'h000112215494, 47'h0062df1e4575, 47'h11d4873168bb};
        rom[  6] = {47'h00000002d5a3, 47'h00000205c4c5, 47'h000118220389, 47'h0065095c0c88, 47'h12387a6e7564};
        rom[  7] = {47'h00000002e587, 47'h000002111b36, 47'h00011e4458a3, 47'h00673fbcb875, 47'h129e9df51fe0};
        rom[  8] = {47'h00000002f5c3, 47'h0000021cb135, 47'h000124891080, 47'h006982845177, 47'h1306fe0a31b9};
        rom[  9] = {47'h00000003065b, 47'h000002288826, 47'h00012af0ebe3, 47'h006bd1f85d22, 47'h1371a7373aab};
        rom[ 10] = {47'h000000031750, 47'h00000234a176, 47'h0001317cafc5, 47'h006e2e5fe6c7, 47'h13dea64c1236};
        rom[ 11] = {47'h0000000328a4, 47'h00000240fe98, 47'h0001382d2571, 47'h0070980387f1, 47'h144e0860618b};
        rom[ 12] = {47'h000000033a59, 47'h0000024da109, 47'h00013f031a98, 47'h00730f2d7128, 47'h14bfdad5362c};
        rom[ 13] = {47'h000000034c71, 47'h0000025a8a4d, 47'h000145ff616f, 47'h0075942972d4, 47'h15342b569d51};
        rom[ 14] = {47'h000000035eef, 47'h00000267bbf1, 47'h00014d22d0c3, 47'h00782745065b, 47'h15ab07dd4856};
        rom[ 15] = {47'h0000000371d4, 47'h00000275378b, 47'h0001546e4416, 47'h007ac8cf576d, 47'h16247eb03a57};
        rom[ 16] = {47'h000000038523, 47'h00000282feba, 47'h00015be29bb9, 47'h007d79194d89, 47'h16a09e667f3e};
        rom[ 17] = {47'h0000000398df, 47'h000002911325, 47'h00016380bce5, 47'h0080387595b5, 47'h171f75e8ec61};
        rom[ 18] = {47'h00000003ad09, 47'h0000029f767d, 47'h00016b4991da, 47'h00830738ac68, 47'h17a11473eb04};
        rom[ 19] = {47'h00000003c1a4, 47'h000002ae2a7d, 47'h0001733e09f8, 47'h0085e5b8e7b6, 47'h182589994cd0};
        rom[ 20] = {47'h00000003d6b3, 47'h000002bd30e9, 47'h00017b5f19db, 47'h0088d44e81aa, 47'h18ace5422aa3};
        rom[ 21] = {47'h00000003ec37, 47'h000002cc8b8e, 47'h000183adbb7e, 47'h008bd353a2e3, 47'h193737b0cdc8};
        rom[ 22] = {47'h000000040235, 47'h000002dc3c45, 47'h00018c2aee53, 47'h008ee3246d64, 47'h19c49182a3f3};
        rom[ 23] = {47'h0000000418ad, 47'h000002ec44f1, 47'h000194d7b763, 47'h0092041f07a9, 47'h1a5503b23e28};
        rom[ 24] = {47'h000000042fa4, 47'h000002fca77e, 47'h00019db52171, 47'h009536a3a7f4, 47'h1ae89f995ad6};
        rom[ 25] = {47'h00000004471b, 47'h0000030d65e4, 47'h0001a6c43d15, 47'h00987b149fdb, 47'h1b7f76f2fb61};
        rom[ 26] = {47'h000000045f16, 47'h0000031e8226, 47'h0001b00620e1, 47'h009bd1d6681c, 47'h1c199bdd8555};
        rom[ 27] = {47'h000000047797, 47'h0000032ffe53, 47'h0001b97be97f, 47'h009f3b4faca6, 47'h1cb720dcef93};
        rom[ 28] = {47'h0000000490a2, 47'h00000341dc84, 47'h0001c326b9d5, 47'h00a2b7e958f7, 47'h1d5818dcfba7};
        rom[ 29] = {47'h00000004aa39, 47'h000003541ede, 47'h0001cd07bb29, 47'h00a6480ea4b1, 47'h1dfc97337b9e};
        rom[ 30] = {47'h00000004c45f, 47'h00000366c793, 47'h0001d7201d41, 47'h00a9ec2d207c, 47'h1ea4afa2a493};
        rom[ 31] = {47'h00000004df18, 47'h00000379d8e0, 47'h0001e171168d, 47'h00ada4b4c330, 47'h1f50765b6e48};
    end
    wire [K-1:0]  idx = f[FF-1 -: K];
    wire [RW-1:0] w   = f[RW-1:0];
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg        [RW-1:0] r_w1, r_w2;
    reg                 r_rv1, r_rv2;
    reg      [HSBW-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else     begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx]; r_co2  <= r_co1;
        r_w1   <= w;        r_w2   <= r_w1;
        r_rsb1 <= sb_in; r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire      [HSBW-1:0]   esb;
    _zkf_horner #(.D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(HSBW), .STAGE_PRODUCT(STAGE_PRODUCT)) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .acc(acc));
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
    assign sb_out      = esb;
    // verilator coverage_on
endmodule

// verilog_lint: waive-stop line-length
`default_nettype wire
