/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=36): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// 2*pi constant for the sin/cos small-angle path (a constant output; atan2 leaves it unconnected).

`default_nettype none

module _zkf_cordic_m36 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 63:0] x0,
    input  wire signed [ 63:0] y0,
    input  wire signed [ 64:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 63:0] xn,
    output wire signed [ 63:0] yn,
    output wire signed [ 64:0] zn,
    output wire        [ 64:0] const2pi    // round(2*pi * 2**XF), CWB = XF + 3 bits
);
    localparam integer N    = 23;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 64;
    localparam integer WZ   = 65;
    localparam integer XF   = 62;   // x/y fractional scale
    localparam integer ZF   = 62;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 65;
    localparam signed [WX-1:0] KINV = 64'sd2800459870029479485;   // round(1/gain * 2**XF)

    assign const2pi = 65'd28976077832308491370;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        65'd174992710548,   // atan(2^-22)/2pi
        65'd349985421095,   // atan(2^-21)/2pi
        65'd699970842190,   // atan(2^-20)/2pi
        65'd1399941684379,   // atan(2^-19)/2pi
        65'd2799883368747,   // atan(2^-18)/2pi
        65'd5599766737413,   // atan(2^-17)/2pi
        65'd11199533474175,   // atan(2^-16)/2pi
        65'd22399066943135,   // atan(2^-15)/2pi
        65'd44798133844548,   // atan(2^-14)/2pi
        65'd89596267355325,   // atan(2^-13)/2pi
        65'd179192532040472,   // atan(2^-12)/2pi
        65'd358385042719534,   // atan(2^-11)/2pi
        65'd716769914547871,   // atan(2^-10)/2pi
        65'd1433538461969102,   // atan(2^-9)/2pi
        65'd2867065987018958,   // atan(2^-8)/2pi
        65'd5734044481687724,   // atan(2^-7)/2pi
        65'd11467389120678282,   // atan(2^-6)/2pi
        65'd22929182573009054,   // atan(2^-5)/2pi
        65'd45813697873323707,   // atan(2^-4)/2pi
        65'd91273161881380487,   // atan(2^-3)/2pi
        65'd179807632645220259,   // atan(2^-2)/2pi
        65'd340304653033718298,   // atan(2^-1)/2pi
        65'd576460752303423488   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
