#!/usr/bin/env python3
"""Regenerate float/tb/zkf_const_wrap.v from zkf_const_cases.py.

Run manually after editing the case list:

    python3 float/tb/gen_zkf_const_wrap.py

The generated file is committed to keep the FuseSoC build self-contained.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from zkf_const_cases import FINITE_VALUES, INF_SIGNS  # noqa: E402

WRAP_PATH = HERE / "zkf_const_wrap.v"


def fmt_real(value: float) -> str:
    """Verilog literal for `value`. repr() returns the shortest round-trip representation,
    which Verilog real parsers (Icarus, Verilator, commercial tools) accept verbatim and
    decode back to the same IEEE 754 double Python started with."""
    if value == 0.0:
        # repr distinguishes 0.0 from -0.0; keep that distinction.
        return "-0.0" if str(value) == "-0.0" else "0.0"
    return repr(value)


def fmt_signed_int(value: int) -> str:
    """Always-signed integer literal (e.g. +1, -1000)."""
    return f"{value:+d}"


def generate() -> str:
    n_finite = len(FINITE_VALUES)
    n_inf = len(INF_SIGNS)
    idx_width = max(3, len(str(max(n_finite, n_inf) - 1)))
    inst_name_w = idx_width
    bus_idx_w = len(str(max(n_finite, n_inf) - 1))

    lines: list[str] = []
    lines.append(
        "/// Testbench harness for zkf_const. AUTO-GENERATED by float/tb/gen_zkf_const_wrap.py from"
    )
    lines.append(
        "/// float/tb/zkf_const_cases.py -- do not edit by hand. Each instance pushes its packed value into one of"
    )
    lines.append(
        "/// the two output buses (y_finite for VALUE-driven instances, y_inf for INF-driven instances); the"
    )
    lines.append(
        "/// Python test_const.py iterates the same case list and compares each slice against the reference packer."
    )
    lines.append("")
    lines.append("`default_nettype none")
    lines.append("")
    lines.append("module zkf_const_wrap #(")
    lines.append("    parameter WEXP = 6,")
    lines.append("    parameter WMAN = 18")
    lines.append(") (")
    lines.append(f"    output wire [{n_finite}*(WEXP+WMAN)-1:0] y_finite,")
    lines.append(f"    output wire [{n_inf}*(WEXP+WMAN)-1:0]   y_inf,")
    lines.append("    output wire [(WEXP+WMAN)-1:0]    y_zero,")
    lines.append("    output wire [(WEXP+WMAN)-1:0]    y_neg_zero")
    lines.append(");")
    lines.append("    localparam WFULL = WEXP + WMAN;")
    lines.append("")
    lines.append("    zkf_const #(.WEXP(WEXP), .WMAN(WMAN), .VALUE( 0.0)) u_zero     (.y(y_zero));")
    lines.append("    zkf_const #(.WEXP(WEXP), .WMAN(WMAN), .VALUE(-0.0)) u_neg_zero (.y(y_neg_zero));")
    lines.append("")
    lines.append(f"    // VALUE-driven instances ({n_finite}).")
    value_strs = [fmt_real(v) for v in FINITE_VALUES]
    value_col = max(len(s) for s in value_strs)
    for i, (v, s) in enumerate(zip(FINITE_VALUES, value_strs)):
        name = f"u_f{i:0{inst_name_w}d}"
        bus = f"y_finite[{i:>{bus_idx_w}d}*WFULL +: WFULL]"
        lines.append(
            f"    zkf_const #(.WEXP(WEXP), .WMAN(WMAN), .VALUE({s:>{value_col}})) "
            f"{name} (.y({bus}));"
        )
    lines.append("")
    lines.append(f"    // INF-driven instances ({n_inf}).")
    inf_strs = [fmt_signed_int(s) for s in INF_SIGNS]
    inf_col = max(len(s) for s in inf_strs)
    for i, (sign, s) in enumerate(zip(INF_SIGNS, inf_strs)):
        name = f"u_i{i:0{inst_name_w}d}"
        bus = f"y_inf[{i:>{bus_idx_w}d}*WFULL +: WFULL]"
        lines.append(
            f"    zkf_const #(.WEXP(WEXP), .WMAN(WMAN), .INF({s:>{inf_col}}))   "
            f"{name} (.y({bus}));"
        )
    lines.append("endmodule")
    lines.append("")
    lines.append("`default_nettype wire")
    return "\n".join(lines) + "\n"


def main() -> int:
    WRAP_PATH.write_text(generate())
    print(f"Wrote {WRAP_PATH} ({len(FINITE_VALUES)} finite, {len(INF_SIGNS)} inf cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
